C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/Gimpact/btClipPolygon.h File Reference
#include `LinearMath/btTransform.h`
#include `LinearMath/btGeometryUtil.h`
Functions
SIMD_FORCE_INLINE void bt_vec_blend (btVector3 &vr, const btVector3 &va, const btVector3 &vb, btScalar blend_factor)
SIMD_FORCE_INLINE void bt_plane_clip_polygon_collect (const btVector3 &point0, const btVector3 &point1, btScalar dist0, btScalar dist1, btVector3 *clipped, int &clipped_count)
This function calcs the distance from a 3D plane.
SIMD_FORCE_INLINE int bt_plane_clip_polygon (const btVector4 &plane, const btVector3 *polygon_points, int polygon_point_count, btVector3 *clipped)
Clips a polygon by a plane.
SIMD_FORCE_INLINE int bt_plane_clip_triangle (const btVector4 &plane, const btVector3 &point0, const btVector3 &point1, const btVector3 &point2, btVector3 *clipped)
Clips a polygon by a plane.
Detailed Description
Author: Francisco Leon Najera
Definition in file btClipPolygon.h.
Function Documentation
SIMD_FORCE_INLINE int bt_plane_clip_polygon (const btVector4 & plane, const btVector3 * polygon_points, int polygon_point_count, btVector3 * clipped)
Clips a polygon by a plane.
Returns: The count of the clipped counts
Definition at line 72 of file btClipPolygon.h.
References bt_plane_clip_polygon_collect().
77 {
78     int clipped_count = 0;
79 
80 
81     //clip first point
82         btScalar firstdist = bt_distance_point_plane(plane,polygon_points[0]);;
83         if(!(firstdist>SIMD_EPSILON))
84         {
85                 clipped[clipped_count] = polygon_points[0];
86                 clipped_count++;
87         }
88 
89         btScalar olddist = firstdist;
90         for(int i=1;i<polygon_point_count;i++)
91         {
92                 btScalar dist = bt_distance_point_plane(plane,polygon_points[i]);
93 
94                 bt_plane_clip_polygon_collect(
95                                                 polygon_points[i-1],polygon_points[i],
96                                                 olddist,
97                                                 dist,
98                                                 clipped,
99                                                 clipped_count);
100 
101 
102                 olddist = dist;
103         }
104 
105         //RETURN TO FIRST  point
106 
107         bt_plane_clip_polygon_collect(
108                                         polygon_points[polygon_point_count-1],polygon_points[0],
109                                         olddist,
110                                         firstdist,
111                                         clipped,
112                                         clipped_count);
113 
114         return clipped_count;
115 }
SIMD_FORCE_INLINE int bt_plane_clip_triangle (const btVector4 & plane, const btVector3 & point0, const btVector3 & point1, const btVector3 & point2, btVector3 * clipped)
Clips a polygon by a plane.
Parameters:
clipped must be an array of 16 points.
Returns: The count of the clipped counts
Definition at line 122 of file btClipPolygon.h.
References bt_plane_clip_polygon_collect().
129 {
130     int clipped_count = 0;
131 
132     //clip first point0
133         btScalar firstdist = bt_distance_point_plane(plane,point0);;
134         if(!(firstdist>SIMD_EPSILON))
135         {
136                 clipped[clipped_count] = point0;
137                 clipped_count++;
138         }
139 
140         // point 1
141         btScalar olddist = firstdist;
142         btScalar dist = bt_distance_point_plane(plane,point1);
143 
144         bt_plane_clip_polygon_collect(
145                                         point0,point1,
146                                         olddist,
147                                         dist,
148                                         clipped,
149                                         clipped_count);
150 
151         olddist = dist;
152 
153 
154         // point 2
155         dist = bt_distance_point_plane(plane,point2);
156 
157         bt_plane_clip_polygon_collect(
158                                         point1,point2,
159                                         olddist,
160                                         dist,
161                                         clipped,
162                                         clipped_count);
163         olddist = dist;
164 
165 
166 
167         //RETURN TO FIRST  point0
168         bt_plane_clip_polygon_collect(
169                                         point2,point0,
170                                         olddist,
171                                         firstdist,
172                                         clipped,
173                                         clipped_count);
174 
175         return clipped_count;
176 }
SIMD_FORCE_INLINE void bt_vec_blend (btVector3 & vr, const btVector3 & va, const btVector3 & vb, btScalar blend_factor)
Vector blending Takes two vectors a, b, blends them together
Definition at line 38 of file btClipPolygon.h.
Referenced by bt_plane_clip_polygon_collect().
39 {
40         vr = (1-blend_factor)*va + blend_factor*vb;
41 }