Assimp::Logger Class Reference
CPP-API: Abstract interface for logger implementations. Assimp provides a default implementation and uses it for almost all logging stuff ('DefaultLogger'). This class defines just basic logging behaviour and is not of interest for you. Instead, take a look at DefaultLogger.
#include <Logger.hpp>
Public Types
enum LogSeverity { NORMAL,
VERBOSE
 }
Log severity to describe the granularity of logging.
enum ErrorSeverity { Debugging = 1,
Info = 2,
Warn = 4,
Err = 8
 }
Description for severity of a log message.
Public Member Functions
virtual ~Logger ()
Virtual destructor.
void debug (const char *message)
Writes a debug message.
void info (const char *message)
Writes a info message.
void warn (const char *message)
Writes a warning message.
void error (const char *message)
Writes an error message.
void setLogSeverity (LogSeverity log_severity)
Set a new log severity.
LogSeverity getLogSeverity () const
Get the current log severity.
virtual bool attachStream (LogStream *pStream, unsigned int severity=Debugging|Err|Warn|Info)=0
Attach a new log-stream.
virtual bool detatchStream (LogStream *pStream, unsigned int severity=Debugging|Err|Warn|Info)=0
Detach a still attached stream from the logger (or modify the filter flags bits).
Protected Member Functions
Logger ()
Logger (LogSeverity severity)
virtual void OnDebug (const char *message)=0
Called as a request to write a specific debug message.
virtual void OnInfo (const char *message)=0
Called as a request to write a specific info message.
virtual void OnWarn (const char *essage)=0
Called as a request to write a specific warn message.
virtual void OnError (const char *message)=0
Called as a request to write a specific error message.
Protected Attributes
LogSeverity m_Severity
Logger severity.
Detailed Description
CPP-API: Abstract interface for logger implementations. Assimp provides a default implementation and uses it for almost all logging stuff ('DefaultLogger'). This class defines just basic logging behaviour and is not of interest for you. Instead, take a look at DefaultLogger.
Definition at line 62 of file Logger.hpp.
Member Enumeration Documentation
enum Assimp::Logger::LogSeverity
Log severity to describe the granularity of logging.
Enumerator:
NORMAL
 Normal granularity of logging.
VERBOSE
 Debug infos will be logged, too.
Definition at line 73 of file Logger.hpp.
74     {
75         NORMAL,     
76         VERBOSE     
77     };
enum Assimp::Logger::ErrorSeverity
Description for severity of a log message.
Every LogStream has a bitwise combination of these flags. A LogStream doesn't receive any messages of a specific type if it doesn't specify the corresponding ErrorSeverity flag.
Enumerator:
Debugging
 Debug log message.
Info
 Info log message.
Warn
 Warn log message.
Err
 Error log message.
Definition at line 87 of file Logger.hpp.
88     {
89         Debugging   = 1,    
90         Info        = 2,    
91         Warn        = 4,    
92         Err         = 8     
93     };
Constructor & Destructor Documentation
Assimp::Logger::Logger () [inline, protected]
Default constructor
Definition at line 212 of file Logger.hpp.
References NORMAL, and setLogSeverity().
212                       {
213     setLogSeverity(NORMAL);
214 }
Assimp::Logger::Logger (LogSeverity severity) [inline, explicit, protected]
Construction with a given log severity
Definition at line 224 of file Logger.hpp.
References setLogSeverity().
224                                           {
225     setLogSeverity(severity);
226 }
Member Function Documentation
void Assimp::Logger::debug (const char * message)
Writes a debug message.
Parameters:
message Debug message
void Assimp::Logger::info (const char * message)
Writes a info message.
Parameters:
message Info message
void Assimp::Logger::warn (const char * message)
Writes a warning message.
Parameters:
message Warn message
void Assimp::Logger::error (const char * message)
Writes an error message.
Parameters:
message Error message
void Assimp::Logger::setLogSeverity (LogSeverity log_severity) [inline]
Set a new log severity.
Parameters:
log_severity New severity for logging
Definition at line 230 of file Logger.hpp.
References m_Severity.
Referenced by Logger().
230                                                           {
231     m_Severity = log_severity;
232 }
virtual bool Assimp::Logger::attachStream (LogStream * pStream, unsigned int severity = Debugging|Err|Warn|Info) [pure virtual]
Attach a new log-stream.
The logger takes ownership of the stream and is responsible for its destruction (which is done using delete when the logger itself is destroyed). Call detachStream to detach a stream and to gain ownership of it again.
Parameters:
pStream Log-stream to attach
severity Message filter, specified which types of log messages are dispatched to the stream. Provide a bitwise combination of the ErrorSeverity flags.
Returns: true if the stream has been attached, false otherwise.
Implemented in Assimp::DefaultLogger, and Assimp::NullLogger.
virtual bool Assimp::Logger::detatchStream (LogStream * pStream, unsigned int severity = Debugging|Err|Warn|Info) [pure virtual]
Detach a still attached stream from the logger (or modify the filter flags bits).
Parameters:
pStream Log-stream instance for detaching
severity Provide a bitwise combination of the ErrorSeverity flags. This value is &~ed with the current flags of the stream, if the result is 0 the stream is detached from the Logger and the caller retakes the possession of the stream.
Returns: true if the stream has been detached, false otherwise.
Implemented in Assimp::DefaultLogger, and Assimp::NullLogger.
virtual void Assimp::Logger::OnDebug (const char * message) [protected, pure virtual]
Called as a request to write a specific debug message.
Parameters:
message Debug message. Never longer than MAX_LOG_MESSAGE_LENGTH characters (excluding the '0').
Note: The message string is only valid until the scope of the function is left.
Implemented in Assimp::NullLogger.
virtual void Assimp::Logger::OnInfo (const char * message) [protected, pure virtual]
Called as a request to write a specific info message.
Parameters:
message Info message. Never longer than MAX_LOG_MESSAGE_LENGTH characters (ecxluding the '0').
Note: The message string is only valid until the scope of the function is left.
Implemented in Assimp::NullLogger.
virtual void Assimp::Logger::OnWarn (const char * essage) [protected, pure virtual]
Called as a request to write a specific warn message.
Parameters:
message Warn message. Never longer than MAX_LOG_MESSAGE_LENGTH characters (exluding the '0').
Note: The message string is only valid until the scope of the function is left.
Implemented in Assimp::NullLogger.
virtual void Assimp::Logger::OnError (const char * message) [protected, pure virtual]
Called as a request to write a specific error message.
Parameters:
message Error message. Never longer than MAX_LOG_MESSAGE_LENGTH characters (exluding the '0').
Note: The message string is only valid until the scope of the function is left.
Implemented in Assimp::NullLogger.
The documentation for this class was generated from the following file:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/assimp-4.1.0/include/assimp/Logger.hpp