btUnionFind Class Reference
UnionFind calculates connected subsets.
#include <btUnionFind.h>
Public Member Functions
void sortIslands ()
Detailed Description
UnionFind calculates connected subsets.
Definition at line 35 of file btUnionFind.h.
Member Function Documentation
void btUnionFind::sortIslands ()
this is a special operation, destroying the content of btUnionFind. it sorts the elements, based on island id, in order to make it easy to iterate over islands
Definition at line 64 of file btUnionFind.cpp.
References btAlignedObjectArray< T >::quickSort(), and btAlignedObjectArray< T >::size().
Referenced by btSimulationIslandManager::buildIslands().
65 {
66 
67         //first store the original body index, and islandId
68         int numElements = m_elements.size();
69         
70         for (int i=0;i<numElements;i++)
71         {
72                 m_elements[i].m_id = find(i);
73 #ifndef STATIC_SIMULATION_ISLAND_OPTIMIZATION
74                 m_elements[i].m_sz = i;
75 #endif //STATIC_SIMULATION_ISLAND_OPTIMIZATION
76         }
77         
78          // Sort the vector using predicate and std::sort
79           //std::sort(m_elements.begin(), m_elements.end(), btUnionFindElementSortPredicate);
80           m_elements.quickSort(btUnionFindElementSortPredicate());
81 
82 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/CollisionDispatch/btUnionFind.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/CollisionDispatch/btUnionFind.cpp