GIM_TRIANGLE Class Reference
Class for colliding triangles.
#include <gim_tri_collision.h>
Public Member Functions
SIMD_FORCE_INLINE void get_triangle_transform (btTransform &triangle_transform) const
Gets the relative transformation of this triangle.
bool collide_triangle_hard_test (const GIM_TRIANGLE &other, GIM_TRIANGLE_CONTACT_DATA &contact_data) const
Test triangles by finding separating axis.
SIMD_FORCE_INLINE bool collide_triangle (const GIM_TRIANGLE &other, GIM_TRIANGLE_CONTACT_DATA &contact_data) const
Test boxes before doing hard test.
SIMD_FORCE_INLINE bool get_uv_parameters (const btVector3 &point, const btVector3 &tri_plane, GREAL &u, GREAL &v) const
SIMD_FORCE_INLINE bool is_point_inside (const btVector3 &point, const btVector3 &tri_normal) const
is point in triangle beam?
SIMD_FORCE_INLINE bool ray_collision (const btVector3 &vPoint, const btVector3 &vDir, btVector3 &pout, btVector3 &triangle_normal, GREAL &tparam, GREAL tmax=G_REAL_INFINITY)
Bidireccional ray collision.
SIMD_FORCE_INLINE bool ray_collision_front_side (const btVector3 &vPoint, const btVector3 &vDir, btVector3 &pout, btVector3 &triangle_normal, GREAL &tparam, GREAL tmax=G_REAL_INFINITY)
one direccion ray collision
Detailed Description
Class for colliding triangles.
Definition at line 126 of file gim_tri_collision.h.
Member Function Documentation
SIMD_FORCE_INLINE void GIM_TRIANGLE::get_triangle_transform (btTransform & triangle_transform) const [inline]
Gets the relative transformation of this triangle.
The transformation is oriented to the triangle normal , and aligned to the 1st edge of this triangle. The position corresponds to vertice 0:
triangle normal corresponds to Z axis.
1st normalized edge corresponds to X axis,
Definition at line 172 of file gim_tri_collision.h.
References MAT_SET_X, MAT_SET_Y, MAT_SET_Z, and VEC_NORMALIZE.
173     {
174         btMatrix3x3 & matrix = triangle_transform.getBasis();
175 
176         btVector3 zaxis;
177         get_normal(zaxis);
178         MAT_SET_Z(matrix,zaxis);
179 
180         btVector3 xaxis = m_vertices[1] - m_vertices[0];
181         VEC_NORMALIZE(xaxis);
182         MAT_SET_X(matrix,xaxis);
183 
184         //y axis
185         xaxis = zaxis.cross(xaxis);
186         MAT_SET_Y(matrix,xaxis);
187 
188         triangle_transform.setOrigin(m_vertices[0]);
189     }
bool GIM_TRIANGLE::collide_triangle_hard_test (const GIM_TRIANGLE & other, GIM_TRIANGLE_CONTACT_DATA & contact_data) const
Test triangles by finding separating axis.
Parameters:
other Triangle for collide
contact_data Structure for holding contact points, normal and penetration depth; The normal is pointing toward this triangle from the other triangle
Definition at line 626 of file gim_tri_collision.cpp.
References m_margin, and m_vertices.
Referenced by collide_triangle().
629 {
630         GIM_TRIANGLE_CALCULATION_CACHE calc_cache;      
631         return calc_cache.triangle_collision(
632                                         m_vertices[0],m_vertices[1],m_vertices[2],m_margin,
633                                         other.m_vertices[0],other.m_vertices[1],other.m_vertices[2],other.m_margin,
634                                         contact_data);
635 
636 }
SIMD_FORCE_INLINE bool GIM_TRIANGLE::collide_triangle (const GIM_TRIANGLE & other, GIM_TRIANGLE_CONTACT_DATA & contact_data) const [inline]
Test boxes before doing hard test.
Parameters:
other Triangle for collide
contact_data Structure for holding contact points, normal and penetration depth; The normal is pointing toward this triangle from the other triangle \
Definition at line 207 of file gim_tri_collision.h.
References collide_triangle_hard_test(), GIM_AABB::has_collision(), m_margin, and m_vertices.
210         {
211                 //test box collisioin
212                 GIM_AABB boxu(m_vertices[0],m_vertices[1],m_vertices[2],m_margin);
213                 GIM_AABB boxv(other.m_vertices[0],other.m_vertices[1],other.m_vertices[2],other.m_margin);
214                 if(!boxu.has_collision(boxv)) return false;
215 
216                 //do hard test
217                 return collide_triangle_hard_test(other,contact_data);
218         }
SIMD_FORCE_INLINE bool GIM_TRIANGLE::get_uv_parameters (const btVector3 & point, const btVector3 & tri_plane, GREAL & u, GREAL & v) const [inline]
Solve the System for u,v parameters:
u*axe1[i1] + v*axe2[i1] = vecproj[i1] u*axe1[i2] + v*axe2[i2] = vecproj[i2]
sustitute: v = (vecproj[i2] - u*axe1[i2])/axe2[i2]
then the first equation in terms of 'u':
--> u*axe1[i1] + ((vecproj[i2] - u*axe1[i2])/axe2[i2])*axe2[i1] = vecproj[i1]
--> u*axe1[i1] + vecproj[i2]*axe2[i1]/axe2[i2] - u*axe1[i2]*axe2[i1]/axe2[i2] = vecproj[i1]
--> u*(axe1[i1] - axe1[i2]*axe2[i1]/axe2[i2]) = vecproj[i1] - vecproj[i2]*axe2[i1]/axe2[i2]
--> u*((axe1[i1]*axe2[i2] - axe1[i2]*axe2[i1])/axe2[i2]) = (vecproj[i1]*axe2[i2] - vecproj[i2]*axe2[i1])/axe2[i2]
--> u*(axe1[i1]*axe2[i2] - axe1[i2]*axe2[i1]) = vecproj[i1]*axe2[i2] - vecproj[i2]*axe2[i1]
--> u = (vecproj[i1]*axe2[i2] - vecproj[i2]*axe2[i1]) /(axe1[i1]*axe2[i2] - axe1[i2]*axe2[i1])
if 0.0<= u+v <=1.0 then they are inside of triangle
Returns: false if the point is outside of triangle.This function doesn't take the margin
Definition at line 248 of file gim_tri_collision.h.
252         {
253                 btVector3 _axe1 = m_vertices[1]-m_vertices[0];
254                 btVector3 _axe2 = m_vertices[2]-m_vertices[0];
255                 btVector3 _vecproj = point - m_vertices[0];
256                 GUINT _i1 = (tri_plane.closestAxis()+1)%3;
257                 GUINT _i2 = (_i1+1)%3;
258                 if(btFabs(_axe2[_i2])<G_EPSILON)
259                 {
260                         u = (_vecproj[_i2]*_axe2[_i1] - _vecproj[_i1]*_axe2[_i2]) /(_axe1[_i2]*_axe2[_i1]  - _axe1[_i1]*_axe2[_i2]);
261                         v = (_vecproj[_i1] - u*_axe1[_i1])/_axe2[_i1];
262                 }
263                 else
264                 {
265                         u = (_vecproj[_i1]*_axe2[_i2] - _vecproj[_i2]*_axe2[_i1]) /(_axe1[_i1]*_axe2[_i2]  - _axe1[_i2]*_axe2[_i1]);
266                         v = (_vecproj[_i2] - u*_axe1[_i2])/_axe2[_i2];
267                 }
268 
269                 if(u<-G_EPSILON)
270                 {
271                         return false;
272                 }
273                 else if(v<-G_EPSILON)
274                 {
275                         return false;
276                 }
277                 else
278                 {
279                         btScalar sumuv;
280                         sumuv = u+v;
281                         if(sumuv<-G_EPSILON)
282                         {
283                                 return false;
284                         }
285                         else if(sumuv-1.0f>G_EPSILON)
286                         {
287                                 return false;
288                         }
289                 }
290                 return true;
291         }
SIMD_FORCE_INLINE bool GIM_TRIANGLE::is_point_inside (const btVector3 & point, const btVector3 & tri_normal) const [inline]
is point in triangle beam?
Test if point is in triangle, with m_margin tolerance
Definition at line 297 of file gim_tri_collision.h.
Referenced by ray_collision(), and ray_collision_front_side().
298         {
299                 //Test with edge 0
300                 btVector4 edge_plane;
301                 this->get_edge_plane(0,tri_normal,edge_plane);
302                 GREAL dist = DISTANCE_PLANE_POINT(edge_plane,point);
303                 if(dist-m_margin>0.0f) return false; // outside plane
304 
305                 this->get_edge_plane(1,tri_normal,edge_plane);
306                 dist = DISTANCE_PLANE_POINT(edge_plane,point);
307                 if(dist-m_margin>0.0f) return false; // outside plane
308 
309                 this->get_edge_plane(2,tri_normal,edge_plane);
310                 dist = DISTANCE_PLANE_POINT(edge_plane,point);
311                 if(dist-m_margin>0.0f) return false; // outside plane
312                 return true;
313         }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/Gimpact/gim_tri_collision.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/Gimpact/gim_tri_collision.cpp