btSphereBoxCollisionAlgorithm Class Reference
#include <btSphereBoxCollisionAlgorithm.h>
Public Member Functions
virtual void processCollision (const btCollisionObjectWrapper *body0Wrap, const btCollisionObjectWrapper *body1Wrap, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
Detailed Description
btSphereBoxCollisionAlgorithm provides sphere-box collision detection. Other features are frame-coherency (persistent data) and collision response.
Definition at line 29 of file btSphereBoxCollisionAlgorithm.h.
Member Function Documentation
void btSphereBoxCollisionAlgorithm::processCollision (const btCollisionObjectWrapper * body0Wrap, const btCollisionObjectWrapper * body1Wrap, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
report a contact. internally this will be kept persistent, and contact reduction is done
Implements btCollisionAlgorithm.
Definition at line 52 of file btSphereBoxCollisionAlgorithm.cpp.
References btManifoldResult::addContactPoint(), btManifoldResult::refreshContactPoints(), and btManifoldResult::setPersistentManifold().
53 {
54         (void)dispatchInfo;
55         (void)resultOut;
56         if (!m_manifoldPtr)
57                 return;
58 
59         const btCollisionObjectWrapper* sphereObjWrap = m_isSwapped? body1Wrap : body0Wrap;
60         const btCollisionObjectWrapper* boxObjWrap = m_isSwapped? body0Wrap : body1Wrap;
61 
62         btVector3 pOnBox;
63 
64         btVector3 normalOnSurfaceB;
65         btScalar penetrationDepth;
66         btVector3 sphereCenter = sphereObjWrap->getWorldTransform().getOrigin();
67         const btSphereShape* sphere0 = (const btSphereShape*)sphereObjWrap->getCollisionShape();
68         btScalar radius = sphere0->getRadius();
69         btScalar maxContactDistance = m_manifoldPtr->getContactBreakingThreshold();
70 
71         resultOut->setPersistentManifold(m_manifoldPtr);
72 
73         if (getSphereDistance(boxObjWrap, pOnBox, normalOnSurfaceB, penetrationDepth, sphereCenter, radius, maxContactDistance))
74         {
76                 resultOut->addContactPoint(normalOnSurfaceB, pOnBox, penetrationDepth);
77         }
78 
79         if (m_ownManifold)
80         {
81                 if (m_manifoldPtr->getNumContacts())
82                 {
83                         resultOut->refreshContactPoints();
84                 }
85         }
86 
87 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp