btInverseDynamics::MultiBodyTree::InitCache Class Reference
#include <MultiBodyTreeInitCache.hpp>
Public Member Functions
InitCache ()
constructor
int addBody (const int body_index, const int parent_index, const JointType joint_type, const vec3 &parent_r_parent_body_ref, const mat33 &body_T_parent_ref, const vec3 &body_axis_of_motion, idScalar mass, const vec3 &body_r_body_com, const mat33 &body_I_body, const int user_int, void *user_ptr)
int buildIndexSets ()
int numDoFs () const
int numBodies () const
int getInertiaData (const int index, InertiaData *inertia) const
int getJointData (const int index, JointData *joint) const
void getParentIndexArray (idArray< int >::type *parent_index)
int getUserInt (const int index, int *user_int) const
int getUserPtr (const int index, void **user_ptr) const
Detailed Description
Data structure to store data passed by the user. This is used in MultiBodyTree::finalize to build internal data structures.
Definition at line 51 of file MultiBodyTreeInitCache.hpp.
Member Function Documentation
int btInverseDynamics::MultiBodyTree::InitCache::addBody (const int body_index, const int parent_index, const JointType joint_type, const vec3 & parent_r_parent_body_ref, const mat33 & body_T_parent_ref, const vec3 & body_axis_of_motion, idScalar mass, const vec3 & body_r_body_com, const mat33 & body_I_body, const int user_int, void * user_ptr)
Add body to the system. this allocates memory and not real-time safe. This only adds the data to an initial cache. After all bodies have been added, the system is setup using the buildSystem call
Parameters:
body_index index of the body to be added. Must >=0, <number of bodies, and index of parent must be < index of body
parent_index index of the parent body The root of the tree has index 0 and its parent (the world frame) is assigned index -1 the rotation and translation relative to the parent are taken as pose of the root body relative to the world frame. Other parameters are ignored
JointType type of joint connecting the body to the parent
mass the mass of the body
body_r_body_com the center of mass of the body relative to and described in the body fixed frame, which is located in the joint axis connecting the body to its parent
body_I_body the moment of inertia of the body w.r.t the body-fixed frame (ie, the reference point is the origin of the body-fixed frame and the matrix is written w.r.t. those unit vectors)
parent_r_parent_body_ref position of joint relative to the parent body's reference frame for q=0, written in the parent bodies reference frame
body_axis_of_motion translation/rotation axis in body-fixed frame. Ignored for joints that are not revolute or prismatic. must be a unit vector.
body_T_parent_ref transform matrix from parent to body reference frame for q=0. This is the matrix transforming a vector represented in the parent's reference frame into one represented in this body's reference frame. ie, if parent_vec is a vector in R^3 whose components are w.r.t to the parent's reference frame, then the same vector written w.r.t. this body's frame (for q=0) is given by body_vec = parent_R_body_ref * parent_vec
user_ptr pointer to user data
user_int pointer to user integer
Returns: 0 on success, -1 on error
Definition at line 12 of file MultiBodyTreeInitCache.cpp.
References btInverseDynamics::InertiaData::m_body_I_body, btInverseDynamics::InertiaData::m_body_pos_body_com, btInverseDynamics::JointData::m_child, btInverseDynamics::JointData::m_child_axis_of_motion, btInverseDynamics::JointData::m_child_T_parent_ref, btInverseDynamics::InertiaData::m_mass, btInverseDynamics::JointData::m_parent, btInverseDynamics::JointData::m_parent_pos_parent_child_ref, and btInverseDynamics::JointData::m_type.
Referenced by btInverseDynamics::MultiBodyTree::addBody().
18                                                                                                               {
19         switch (joint_type) {
20                 case REVOLUTE:
21                 case PRISMATIC:
22                         m_num_dofs += 1;
23                         break;
24                 case FIXED:
25                         // does not add a degree of freedom
26                         // m_num_dofs+=0;
27                         break;
28                 case FLOATING:
29                         m_num_dofs += 6;
30                         break;
31                 default:
32                         error_message("unknown joint type %d\n", joint_type);
33                         return -1;
34         }
35 
36         if(-1 == parent_index) {
37                 if(m_root_index>=0) {
38                         error_message("trying to add body %d as root, but already added %d as root body\n",
39                                                   body_index, m_root_index);
40                         return -1;
41                 }
42                 m_root_index=body_index;
43         }
44 
45         JointData joint;
46         joint.m_child = body_index;
47         joint.m_parent = parent_index;
48         joint.m_type = joint_type;
49         joint.m_parent_pos_parent_child_ref = parent_r_parent_body_ref;
50         joint.m_child_T_parent_ref = body_T_parent_ref;
51         joint.m_child_axis_of_motion = body_axis_of_motion;
52 
53         InertiaData body;
54         body.m_mass = mass;
55         body.m_body_pos_body_com = body_r_body_com;
56         body.m_body_I_body = body_I_body;
57 
58         m_inertias.push_back(body);
59         m_joints.push_back(joint);
60         m_user_int.push_back(user_int);
61         m_user_ptr.push_back(user_ptr);
62         return 0;
63 }
int btInverseDynamics::MultiBodyTree::InitCache::buildIndexSets ()
build index arrays
Returns: 0 on success, -1 on failure
Definition at line 101 of file MultiBodyTreeInitCache.cpp.
References btInverseDynamics::JointData::m_child, btInverseDynamics::JointData::m_parent, and numBodies().
Referenced by btInverseDynamics::MultiBodyTree::finalize().
101                                            {
102         // NOTE: This function assumes that proper indices were provided
103         //         User2InternalIndex from utils can be used to facilitate this.
104 
105         m_parent_index.resize(numBodies());
106         for (idArrayIdx j = 0; j < m_joints.size(); j++) {
107                 const JointData& joint = m_joints[j];
108                 m_parent_index[joint.m_child] = joint.m_parent;
109         }
110 
111         return 0;
112 }
int btInverseDynamics::MultiBodyTree::InitCache::numDoFs () const [inline]
Returns: number of degrees of freedom
Definition at line 65 of file MultiBodyTreeInitCache.hpp.
Referenced by btInverseDynamics::MultiBodyTree::finalize().
65 { return m_num_dofs; }
int btInverseDynamics::MultiBodyTree::InitCache::numBodies () const [inline]
Returns: number of bodies
Definition at line 67 of file MultiBodyTreeInitCache.hpp.
Referenced by buildIndexSets(), and btInverseDynamics::MultiBodyTree::finalize().
67 { return m_inertias.size(); }
int btInverseDynamics::MultiBodyTree::InitCache::getInertiaData (const int index, InertiaData * inertia) const
get inertia data for index
Parameters:
index of the body
inertia pointer for return data
Returns: 0 on success, -1 on failure
Definition at line 64 of file MultiBodyTreeInitCache.cpp.
Referenced by btInverseDynamics::MultiBodyTree::finalize().
64                                                                                       {
65         if (index < 0 || index > static_cast<int>(m_inertias.size())) {
66                 error_message("index out of range\n");
67                 return -1;
68         }
69 
70         *inertia = m_inertias[index];
71         return 0;
72 }
int btInverseDynamics::MultiBodyTree::InitCache::getJointData (const int index, JointData * joint) const
get joint data for index
Parameters:
index of the body
joint pointer for return data
Returns: 0 on success, -1 on failure
Definition at line 92 of file MultiBodyTreeInitCache.cpp.
Referenced by btInverseDynamics::MultiBodyTree::finalize().
92                                                                                 {
93         if (index < 0 || index > static_cast<int>(m_joints.size())) {
94                 error_message("index out of range\n");
95                 return -1;
96         }
97         *joint = m_joints[index];
98         return 0;
99 }
void btInverseDynamics::MultiBodyTree::InitCache::getParentIndexArray (idArray< int >::type * parent_index) [inline]
get parent index array (paren_index[i] is the index of the parent of i)
Parameters:
parent_index pointer for return data
Definition at line 80 of file MultiBodyTreeInitCache.hpp.
Referenced by btInverseDynamics::MultiBodyTree::finalize().
80 { *parent_index = m_parent_index; }
int btInverseDynamics::MultiBodyTree::InitCache::getUserInt (const int index, int * user_int) const
get user integer
Parameters:
index body index
user_int user integer
Returns: 0 on success, -1 on failure
Definition at line 74 of file MultiBodyTreeInitCache.cpp.
74                                                                            {
75         if (index < 0 || index > static_cast<int>(m_user_int.size())) {
76                 error_message("index out of range\n");
77                 return -1;
78         }
79         *user_int = m_user_int[index];
80         return 0;
81 }
int btInverseDynamics::MultiBodyTree::InitCache::getUserPtr (const int index, void ** user_ptr) const
get user pointer
Parameters:
index body index
user_int user pointer
Returns: 0 on success, -1 on failure
Definition at line 83 of file MultiBodyTreeInitCache.cpp.
83                                                                              {
84         if (index < 0 || index > static_cast<int>(m_user_ptr.size())) {
85                 error_message("index out of range\n");
86                 return -1;
87         }
88         *user_ptr = m_user_ptr[index];
89         return 0;
90 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletInverseDynamics/details/MultiBodyTreeInitCache.hpp
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletInverseDynamics/details/MultiBodyTreeInitCache.cpp