Terrain Class Reference
Terrain Interface class.
#include <Terrain.h>
Public Member Functions
Terrain ()
Constructor.
~Terrain ()
Destructor.
Terrain (float scaleX, float scaleY, float scaleZ)
Constructor.
virtual void GenerateTerrain (GLuint textureId, std::string textureFilePath)=0
Generates the terrain.
void SetCamera (Camera *camera)
Sets the camera object.
void SetPosition (glm::vec3 position)
Sets the terrains position.
void SetScale (glm::vec3 scale)
Sets the terrains scale.
Model * GetModel ()
Gets the camera Model object.
Detailed Description
Terrain Interface class.
This terrain class is used as a base class for other methods of terrain generation classes to inherit from. It contains all the core member variables and functionalities that a terrain may have.
Author: Cordell Smith
Version: 01
Date: 31/05/2018
Definition at line 23 of file Terrain.h.
Constructor & Destructor Documentation
Terrain::Terrain ()
Constructor.
This constructor sets the initial scales of the x, y, z components of the terrain to 1.0 and heightfield size to 0. It also initializes the terrains model.
Returns: null
Definition at line 3 of file Terrain.cpp.
4         : m_scaleX(1.0), m_scaleY(1.0), m_scaleZ(1.0), m_heightfieldSize(0)
5 {
6         m_terrainModel = new Model();
7 }
Terrain::~Terrain () [inline]
Destructor.
Empty default destructor.
Returns: null
Definition at line 44 of file Terrain.h.
44 { }
Terrain::Terrain (float scaleX, float scaleY, float scaleZ)
Constructor.
This constructor takes an x, y, z scale and sets the member variables of the terrain to these parsed in.
Returns: null
Definition at line 9 of file Terrain.cpp.
10         : m_scaleX(scaleX), m_scaleY(scaleY), m_scaleZ(scaleZ), m_heightfieldSize(0)
11 {
12         m_terrainModel = new Model();
13 }
Member Function Documentation
virtual void Terrain::GenerateTerrain (GLuint textureId, std::string textureFilePath) [pure virtual]
Generates the terrain.
This virtual method is used to generate a terrain. It is overridden by the inherited class.
Parameters:
GLuint textureId
std::string textureFilePath
Returns: void
Implemented in Bruteforce.
void Terrain::SetCamera (Camera * camera) [inline]
Sets the camera object.
Parses the parameter given Camera* object to the terrains model. This is to be able to access the view and projection matrices when rendering.
Parameters:
Camera* camera
Returns: void
Definition at line 77 of file Terrain.h.
References Model::SetCamera().
77 { m_terrainModel->SetCamera(camera); }
void Terrain::SetPosition (glm::vec3 position) [inline]
Sets the terrains position.
Sets the position of the terrain using the parameter given.
Parameters:
glm::vec3 position
Returns: void
Definition at line 87 of file Terrain.h.
References Model::SetPosition().
87 { m_terrainModel->SetPosition(position); }
void Terrain::SetScale (glm::vec3 scale) [inline]
Sets the terrains scale.
Sets the scale of the terrain using the parameter given.
Parameters:
glm::vec3 scale
Returns: void
Definition at line 97 of file Terrain.h.
References Model::SetScale().
97 { m_terrainModel->SetScale(scale); }
Model* Terrain::GetModel () [inline]
Gets the camera Model object.
Returns a pointer to the terrains model object.
Returns: Model*
Definition at line 106 of file Terrain.h.
106 { return m_terrainModel; }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/AssetFactory/Terrain.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/AssetFactory/Terrain.cpp