btRigidBody Class Reference
#include <btRigidBody.h>
Public Member Functions
btRigidBody (const btRigidBodyConstructionInfo &constructionInfo)
btRigidBody constructor using construction info
btRigidBody (btScalar mass, btMotionState *motionState, btCollisionShape *collisionShape, const btVector3 &localInertia=btVector3(0, 0, 0))
void predictIntegratedTransform (btScalar step, btTransform &predictedTransform)
continuous collision detection needs prediction
void applyDamping (btScalar timeStep)
applyDamping damps the velocity, using the given m_linearDamping and m_angularDamping
void integrateVelocities (btScalar step)
void addConstraintRef (btTypedConstraint *c)
btVector3 computeGyroscopicImpulseImplicit_World (btScalar dt) const
perform implicit force computation in world space
btVector3 computeGyroscopicImpulseImplicit_Body (btScalar step) const
perform implicit force computation in body space (inertial frame)
btVector3 computeGyroscopicForceExplicit (btScalar maxGyroscopicForce) const
explicit version is best avoided, it gains energy
virtual const char * serialize (void *dataBuffer, class btSerializer *serializer) const
fills the dataBuffer and returns the struct name (and 0 on failure)
Static Public Member Functions
static const btRigidBody * upcast (const btCollisionObject *colObj)
Protected Member Functions
void setupRigidBody (const btRigidBodyConstructionInfo &constructionInfo)
setupRigidBody is only used internally by the constructor
Classes
struct btRigidBodyConstructionInfo
Detailed Description
The btRigidBody is the main class for rigid body objects. It is derived from btCollisionObject, so it keeps a pointer to a btCollisionShape. It is recommended for performance and memory use to share btCollisionShape objects whenever possible. There are 3 types of rigid bodies:
A) Dynamic rigid bodies, with positive mass. Motion is controlled by rigid body dynamics.
B) Fixed objects with zero mass. They are not moving (basically collision objects)
C) Kinematic objects, which are objects without mass, but the user can move them. There is on-way interaction, and Bullet calculates a velocity based on the timestep and previous and current world transform. Bullet automatically deactivates dynamic rigid bodies, when the velocity is below a threshold for a given time. Deactivated (sleeping) rigid bodies don't take any processing time, except a minor broadphase collision detection impact (to allow active objects to activate/wake up sleeping objects)
Definition at line 62 of file btRigidBody.h.
Constructor & Destructor Documentation
btRigidBody::btRigidBody (btScalar mass, btMotionState * motionState, btCollisionShape * collisionShape, const btVector3 & localInertia = btVector3(0,0,0))
btRigidBody constructor for backwards compatibility. To specify friction (etc) during rigid body construction, please use the other constructor (using btRigidBodyConstructionInfo)
Definition at line 35 of file btRigidBody.cpp.
References setupRigidBody().
36 {
37         btRigidBodyConstructionInfo cinfo(mass,motionState,collisionShape,localInertia);
38         setupRigidBody(cinfo);
39 }
Member Function Documentation
static const btRigidBody* btRigidBody::upcast (const btCollisionObject * colObj) [inline, static]
to keep collision detection and dynamics separate we don't store a rigidbody pointer but a rigidbody is derived from btCollisionObject, so we can safely perform an upcast
Definition at line 203 of file btRigidBody.h.
Referenced by btSimpleDynamicsWorld::clearForces(), btSimpleDynamicsWorld::removeCollisionObject(), PhysicsEngine::Simulate(), and btSimpleDynamicsWorld::synchronizeMotionStates().
204         {
205                 if (colObj->getInternalType()&btCollisionObject::CO_RIGID_BODY)
206                         return (const btRigidBody*)colObj;
207                 return 0;
208         }
void btRigidBody::integrateVelocities (btScalar step)
clamp angular velocity. collision calculations will fail on higher angular velocities
Definition at line 387 of file btRigidBody.cpp.
388 {
389         if (isStaticOrKinematicObject())
390                 return;
391 
392         m_linearVelocity += m_totalForce * (m_inverseMass * step);
393         m_angularVelocity += m_invInertiaTensorWorld * m_totalTorque * step;
394 
395 #define MAX_ANGVEL SIMD_HALF_PI
397         btScalar angvel = m_angularVelocity.length();
398         if (angvel*step > MAX_ANGVEL)
399         {
400                 m_angularVelocity *= (MAX_ANGVEL/step) /angvel;
401         }
402 
403 }
void btRigidBody::addConstraintRef (btTypedConstraint * c)
disable collision with the 'other' body
Definition at line 433 of file btRigidBody.cpp.
References btAlignedObjectArray< T >::findLinearSearch(), btAlignedObjectArray< T >::push_back(), and btAlignedObjectArray< T >::size().
434 {
436 
437         int index = m_constraintRefs.findLinearSearch(c);
438         //don't add constraints that are already referenced
439         //btAssert(index == m_constraintRefs.size());
440         if (index == m_constraintRefs.size())
441         {
442                 m_constraintRefs.push_back(c);
443                 btCollisionObject* colObjA = &c->getRigidBodyA();
444                 btCollisionObject* colObjB = &c->getRigidBodyB();
445                 if (colObjA == this)
446                 {
447                         colObjA->setIgnoreCollisionCheck(colObjB, true);
448                 }
449                 else
450                 {
451                         colObjB->setIgnoreCollisionCheck(colObjA, true);
452                 }
453         } 
454 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletDynamics/Dynamics/btRigidBody.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletDynamics/Dynamics/btRigidBody.cpp