btGImpactMeshShapePart Class Reference
This class manages a sub part of a mesh supplied by the btStridingMeshInterface interface.
#include <btGImpactShape.h>
Public Member Functions
virtual bool childrenHasTransform () const
if true, then its children must get transforms.
virtual void lockChildShapes () const
call when reading child shapes
virtual int getNumChildShapes () const
Gets the number of children.
virtual btCollisionShape * getChildShape (int index)
Gets the children.
virtual const btCollisionShape * getChildShape (int index) const
Gets the child.
virtual btTransform getChildTransform (int index) const
Gets the children transform.
virtual void setChildTransform (int index, const btTransform &transform)
Sets the children transform.
virtual const btPrimitiveManagerBase * getPrimitiveManager () const
Obtains the primitive manager.
virtual eGIMPACT_SHAPE_TYPE getGImpactShapeType () const
Base method for determinig which kind of GIMPACT shape we get.
virtual bool needsRetrieveTriangles () const
Determines if this shape has triangles.
virtual bool needsRetrieveTetrahedrons () const
Determines if this shape has tetrahedrons.
virtual void setLocalScaling (const btVector3 &scaling)
virtual void processAllTriangles (btTriangleCallback *callback, const btVector3 &aabbMin, const btVector3 &aabbMax) const
Function for retrieve triangles.
virtual void processAllTrianglesRay (btTriangleCallback *callback, const btVector3 &rayFrom, const btVector3 &rayTo) const
Function for retrieve triangles.
Classes
class TrimeshPrimitiveManager
Trimesh primitive manager.
Detailed Description
This class manages a sub part of a mesh supplied by the btStridingMeshInterface interface.
Simply create this shape by passing the btStridingMeshInterface to the constructor btGImpactMeshShapePart, then you must call updateBound() after creating the mesh
When making operations with this shape, you must call lock before accessing to the trimesh primitives, and then call unlock
You can handle deformable meshes with this shape, by calling postUpdate() every time when changing the mesh vertices.
Definition at line 531 of file btGImpactShape.h.
Member Function Documentation
virtual void btGImpactMeshShapePart::setChildTransform (int index, const btTransform & transform) [inline, virtual]
Sets the children transform.
Postcondition: You must call updateBound() for update the box set.
Implements btGImpactShapeInterface.
Definition at line 776 of file btGImpactShape.h.
777         {
778         (void) index;
779         (void) transform;
780                 btAssert(0);
781         }
virtual eGIMPACT_SHAPE_TYPE btGImpactMeshShapePart::getGImpactShapeType () const [inline, virtual]
Base method for determinig which kind of GIMPACT shape we get.
Subshape member functions
Implements btGImpactShapeInterface.
Definition at line 809 of file btGImpactShape.h.
810         {
811                 return CONST_GIMPACT_TRIMESH_SHAPE_PART;
812         }
virtual void btGImpactMeshShapePart::setLocalScaling (const btVector3 & scaling) [inline, virtual]
Postcondition: You must call updateBound() for update the box set.
Reimplemented from btGImpactShapeInterface.
Definition at line 861 of file btGImpactShape.h.
References btGImpactMeshShapePart::TrimeshPrimitiveManager::m_scale, and btGImpactShapeInterface::postUpdate().
Referenced by btGImpactMeshShape::setLocalScaling().
862     {
863         m_primitive_manager.m_scale = scaling;
864         postUpdate();
865     }
void btGImpactMeshShapePart::processAllTriangles (btTriangleCallback * callback, const btVector3 & aabbMin, const btVector3 & aabbMax) const [virtual]
Function for retrieve triangles.
It gives the triangles in local space
Reimplemented from btGImpactShapeInterface.
Definition at line 227 of file btGImpactShape.cpp.
References btGImpactQuantizedBvh::boxQuery(), btGImpactShapeInterface::getPrimitiveTriangle(), lockChildShapes(), btTriangleCallback::processTriangle(), and btAlignedObjectArray< T >::size().
228 {
229         lockChildShapes();
230         btAABB box;
231         box.m_min = aabbMin;
232         box.m_max = aabbMax;
233 
234         btAlignedObjectArray<int> collided;
235         m_box_set.boxQuery(box,collided);
236 
237         if(collided.size()==0)
238         {
239                 unlockChildShapes();
240                 return;
241         }
242 
243         int part = (int)getPart();
244         btPrimitiveTriangle triangle;
245         int i = collided.size();
246         while(i--)
247         {
248                 this->getPrimitiveTriangle(collided[i],triangle);
249                 callback->processTriangle(triangle.m_vertices,part,collided[i]);
250         }
251         unlockChildShapes();
252 
253 }
void btGImpactMeshShapePart::processAllTrianglesRay (btTriangleCallback *, const btVector3 &, const btVector3 &) const [virtual]
Function for retrieve triangles.
It gives the triangles in local space
Reimplemented from btGImpactShapeInterface.
Definition at line 201 of file btGImpactShape.cpp.
References btGImpactShapeInterface::getPrimitiveTriangle(), lockChildShapes(), btTriangleCallback::processTriangle(), btGImpactQuantizedBvh::rayQuery(), and btAlignedObjectArray< T >::size().
202 {
203         lockChildShapes();
204 
205         btAlignedObjectArray<int> collided;
206         btVector3 rayDir(rayTo - rayFrom);
207         rayDir.normalize();
208         m_box_set.rayQuery(rayDir, rayFrom, collided);
209 
210         if(collided.size()==0)
211         {
212                 unlockChildShapes();
213                 return;
214         }
215 
216         int part = (int)getPart();
217         btPrimitiveTriangle triangle;
218         int i = collided.size();
219         while(i--)
220         {
221                 getPrimitiveTriangle(collided[i],triangle);
222                 callback->processTriangle(triangle.m_vertices,part,collided[i]);
223         }
224         unlockChildShapes();
225 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/Gimpact/btGImpactShape.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/Gimpact/btGImpactShape.cpp