btSimpleDynamicsWorld Class Reference
#include <btSimpleDynamicsWorld.h>
Public Member Functions
btSimpleDynamicsWorld (btDispatcher *dispatcher, btBroadphaseInterface *pairCache, btConstraintSolver *constraintSolver, btCollisionConfiguration *collisionConfiguration)
this btSimpleDynamicsWorld constructor creates dispatcher, broadphase pairCache and constraintSolver
virtual int stepSimulation (btScalar timeStep, int maxSubSteps=1, btScalar fixedTimeStep=btScalar(1.)/btScalar(60.))
maxSubSteps/fixedTimeStep for interpolation is currently ignored for btSimpleDynamicsWorld, use btDiscreteDynamicsWorld instead
virtual void removeCollisionObject (btCollisionObject *collisionObject)
removeCollisionObject will first check if it is a rigid body, if so call removeRigidBody otherwise call btCollisionWorld::removeCollisionObject
virtual void synchronizeMotionStates ()
virtual void clearForces ()
Detailed Description
The btSimpleDynamicsWorld serves as unit-test and to verify more complicated and optimized dynamics worlds. Please use btDiscreteDynamicsWorld instead
Definition at line 27 of file btSimpleDynamicsWorld.h.
Member Function Documentation
int btSimpleDynamicsWorld::stepSimulation (btScalar timeStep, int maxSubSteps = 1, btScalar fixedTimeStep = btScalar(1.)/btScalar(60.)) [virtual]
maxSubSteps/fixedTimeStep for interpolation is currently ignored for btSimpleDynamicsWorld, use btDiscreteDynamicsWorld instead
apply gravity, predict motion
perform collision detection
solve contact constraints
integrate transforms
Implements btDynamicsWorld.
Definition at line 55 of file btSimpleDynamicsWorld.cpp.
References clearForces(), btDispatcher::getNumManifolds(), and synchronizeMotionStates().
56 {
57         (void)fixedTimeStep;
58         (void)maxSubSteps;
59 
60 
62         predictUnconstraintMotion(timeStep);
63 
64         btDispatcherInfo&       dispatchInfo = getDispatchInfo();
65         dispatchInfo.m_timeStep = timeStep;
66         dispatchInfo.m_stepCount = 0;
67         dispatchInfo.m_debugDraw = getDebugDrawer();
68 
70         performDiscreteCollisionDetection();
71 
73         int numManifolds = m_dispatcher1->getNumManifolds();
74         if (numManifolds)
75         {
76                 btPersistentManifold** manifoldPtr = ((btCollisionDispatcher*)m_dispatcher1)->getInternalManifoldPointer();
77                 
78                 btContactSolverInfo infoGlobal;
79                 infoGlobal.m_timeStep = timeStep;
80                 m_constraintSolver->prepareSolve(0,numManifolds);
81                 m_constraintSolver->solveGroup(&getCollisionObjectArray()[0],getNumCollisionObjects(),manifoldPtr, numManifolds,0,0,infoGlobal,m_debugDrawer, m_dispatcher1);
82                 m_constraintSolver->allSolved(infoGlobal,m_debugDrawer);
83         }
84 
86         integrateTransforms(timeStep);
87                 
88         updateAabbs();
89 
90         synchronizeMotionStates();
91 
92         clearForces();
93 
94         return 1;
95 
96 }
void btSimpleDynamicsWorld::synchronizeMotionStates () [virtual]
Todo : iterate over awake simulation islands!
Implements btDynamicsWorld.
Definition at line 248 of file btSimpleDynamicsWorld.cpp.
References btRigidBody::getMotionState(), btMotionState::setWorldTransform(), btAlignedObjectArray< T >::size(), and btRigidBody::upcast().
Referenced by stepSimulation().
249 {
251         for ( int i=0;i<m_collisionObjects.size();i++)
252         {
253                 btCollisionObject* colObj = m_collisionObjects[i];
254                 btRigidBody* body = btRigidBody::upcast(colObj);
255                 if (body && body->getMotionState())
256                 {
257                         if (body->getActivationState() != ISLAND_SLEEPING)
258                         {
259                                 body->getMotionState()->setWorldTransform(body->getWorldTransform());
260                         }
261                 }
262         }
263 
264 }
void btSimpleDynamicsWorld::clearForces () [virtual]
Todo : iterate over awake simulation islands!
Implements btDynamicsWorld.
Definition at line 98 of file btSimpleDynamicsWorld.cpp.
References btRigidBody::clearForces(), btAlignedObjectArray< T >::size(), and btRigidBody::upcast().
Referenced by stepSimulation().
99 {
101         for ( int i=0;i<m_collisionObjects.size();i++)
102         {
103                 btCollisionObject* colObj = m_collisionObjects[i];
104                 
105                 btRigidBody* body = btRigidBody::upcast(colObj);
106                 if (body)
107                 {
108                         body->clearForces();
109                 }
110         }
111 }       
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletDynamics/Dynamics/btSimpleDynamicsWorld.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp