btInverseDynamics::MultiBodyTree Class Reference
#include <MultiBodyTree.hpp>
Public Member Functions
MultiBodyTree ()
~MultiBodyTree ()
the destructor. This also deallocates all memory
int addBody (int body_index, int parent_index, JointType joint_type, const vec3 &parent_r_parent_body_ref, const mat33 &body_T_parent_ref, const vec3 &body_axis_of_motion, idScalar mass, const vec3 &body_r_body_com, const mat33 &body_I_body, const int user_int, void *user_ptr)
void setAcceptInvalidMassParameters (bool flag)
bool getAcceptInvalidMassProperties () const
int finalize ()
void printTree ()
pretty print ascii description of tree to stdout
void printTreeData ()
print tree data to stdout
int calculateInverseDynamics (const vecx &q, const vecx &u, const vecx &dot_u, vecx *joint_forces)
int calculateMassMatrix (const vecx &q, const bool update_kinematics, const bool initialize_matrix, const bool set_lower_triangular_matrix, matxx *mass_matrix)
int calculateMassMatrix (const vecx &q, matxx *mass_matrix)
int calculateKinematics (const vecx &q, const vecx &u, const vecx &dot_u)
int calculatePositionKinematics (const vecx &q)
Calculate position kinematics.
int calculatePositionAndVelocityKinematics (const vecx &q, const vecx &u)
Calculate position and velocity kinematics.
int calculateJacobians (const vecx &q, const vecx &u)
int calculateJacobians (const vecx &q)
int setGravityInWorldFrame (const vec3 &gravity)
int numBodies () const
returns number of bodies in tree
int numDoFs () const
returns number of mechanical degrees of freedom (dimension of q-vector)
int getBodyOrigin (const int body_index, vec3 *world_origin) const
int getBodyCoM (const int body_index, vec3 *world_com) const
int getBodyTransform (const int body_index, mat33 *world_T_body) const
int getBodyAngularVelocity (const int body_index, vec3 *world_omega) const
int getBodyLinearVelocity (const int body_index, vec3 *world_velocity) const
int getBodyLinearVelocityCoM (const int body_index, vec3 *world_velocity) const
int getBodyAngularAcceleration (const int body_index, vec3 *world_dot_omega) const
int getBodyLinearAcceleration (const int body_index, vec3 *world_acceleration) const
int getParentIndex (const int body_index, int *parent_index) const
int getJointType (const int body_index, JointType *joint_type) const
int getJointTypeStr (const int body_index, const char **joint_type) const
int getParentRParentBodyRef (const int body_index, vec3 *r) const
int getBodyTParentRef (const int body_index, mat33 *T) const
int getBodyAxisOfMotion (const int body_index, vec3 *axis) const
int getDoFOffset (const int body_index, int *q_offset) const
int getUserInt (const int body_index, int *user_int) const
int getUserPtr (const int body_index, void **user_ptr) const
int setUserInt (const int body_index, const int user_int)
int setUserPtr (const int body_index, void *const user_ptr)
int setBodyMass (const int body_index, const idScalar mass)
int setBodyFirstMassMoment (const int body_index, const vec3 &first_mass_moment)
int setBodySecondMassMoment (const int body_index, const mat33 &second_mass_moment)
int getBodyMass (const int body_index, idScalar *mass) const
int getBodyFirstMassMoment (const int body_index, vec3 *first_mass_moment) const
int getBodySecondMassMoment (const int body_index, mat33 *second_mass_moment) const
void clearAllUserForcesAndMoments ()
set all user forces and moments to zero
int addUserForce (const int body_index, const vec3 &body_force)
int addUserMoment (const int body_index, const vec3 &body_moment)
Classes
class InitCache
class MultiBodyImpl
The MBS implements a tree structured multibody system.
Detailed Description
Interface class for calculating inverse dynamics for tree structured multibody systems
Note on degrees of freedom The q vector contains the generalized coordinate set defining the tree's configuration. Every joint adds elements that define the corresponding link's frame pose relative to its parent. For the joint types that is:
FIXED: none
REVOLUTE: angle of rotation [rad]
PRISMATIC: displacement [m]
FLOATING: Euler x-y-z angles [rad] and displacement in body-fixed frame of parent [m] (in that order) The u vector contains the generalized speeds, which are
FIXED: none
REVOLUTE: time derivative of angle of rotation [rad/s]
PRISMATIC: time derivative of displacement [m/s]
FLOATING: angular velocity [rad/s] (*not* time derivative of rpy angles) and time derivative of displacement in parent frame [m/s]
The q and u vectors are obtained by stacking contributions of all bodies in one vector in the order of body indices.
Note on generalized forces: analogous to u, i.e.,
FIXED: none
REVOLUTE: moment [Nm], about joint axis
PRISMATIC: force [N], along joint axis
FLOATING: moment vector [Nm] and force vector [N], both in body-fixed frame (in that order)
TODO - force element interface (friction, springs, dampers, etc)
gears and motor inertia
Definition at line 52 of file MultiBodyTree.hpp.
Constructor & Destructor Documentation
btInverseDynamics::MultiBodyTree::MultiBodyTree ()
The contructor. Initialization & allocation is via addBody and buildSystem calls.
Definition at line 13 of file MultiBodyTree.cpp.
14         : m_is_finalized(false),
15           m_mass_parameters_are_valid(true),
16           m_accept_invalid_mass_parameters(false),
17           m_impl(0x0),
18           m_init_cache(0x0) {
19         m_init_cache = new InitCache();
20 }
Member Function Documentation
int btInverseDynamics::MultiBodyTree::addBody (int body_index, int parent_index, JointType joint_type, const vec3 & parent_r_parent_body_ref, const mat33 & body_T_parent_ref, const vec3 & body_axis_of_motion, idScalar mass, const vec3 & body_r_body_com, const mat33 & body_I_body, const int user_int, void * user_ptr)
Add body to the system. this allocates memory and not real-time safe. This only adds the data to an initial cache. After all bodies have been added, the system is setup using the buildSystem call
Parameters:
body_index index of the body to be added. Must >=0, <number of bodies, and index of parent must be < index of body
parent_index index of the parent body The root of the tree has index 0 and its parent (the world frame) is assigned index -1 the rotation and translation relative to the parent are taken as pose of the root body relative to the world frame. Other parameters are ignored
JointType type of joint connecting the body to the parent
mass the mass of the body
body_r_body_com the center of mass of the body relative to and described in the body fixed frame, which is located in the joint axis connecting the body to its parent
body_I_body the moment of inertia of the body w.r.t the body-fixed frame (ie, the reference point is the origin of the body-fixed frame and the matrix is written w.r.t. those unit vectors)
parent_r_parent_body_ref position of joint relative to the parent body's reference frame for q=0, written in the parent bodies reference frame
body_axis_of_motion translation/rotation axis in body-fixed frame. Ignored for joints that are not revolute or prismatic. must be a unit vector.
body_T_parent_ref transform matrix from parent to body reference frame for q=0. This is the matrix transforming a vector represented in the parent's reference frame into one represented in this body's reference frame. ie, if parent_vec is a vector in R^3 whose components are w.r.t to the parent's reference frame, then the same vector written w.r.t. this body's frame (for q=0) is given by body_vec = parent_R_body_ref * parent_vec
user_ptr pointer to user data
user_int pointer to user integer
Returns: 0 on success, -1 on error
Definition at line 211 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::InitCache::addBody(), glm::length(), and glm::min().
215                                                                                        {
216         if (body_index < 0) {
217                 error_message("body index must be positive (got %d)\n", body_index);
218                 return -1;
219         }
220         vec3 body_axis_of_motion(body_axis_of_motion_);
221         switch (joint_type) {
222                 case REVOLUTE:
223                 case PRISMATIC:
224                         // check if axis is unit vector
225                         if (!isUnitVector(body_axis_of_motion)) {
226                                 warning_message(
227                                         "axis of motion not a unit axis ([%f %f %f]), will use normalized vector\n",
228                                         body_axis_of_motion(0), body_axis_of_motion(1), body_axis_of_motion(2));
229                                 idScalar length = BT_ID_SQRT(BT_ID_POW(body_axis_of_motion(0), 2) +
230                                                                            BT_ID_POW(body_axis_of_motion(1), 2) +
231                                                                            BT_ID_POW(body_axis_of_motion(2), 2));
232                                 if (length < BT_ID_SQRT(std::numeric_limits<idScalar>::min())) {
233                                         error_message("axis of motion vector too short (%e)\n", length);
234                                         return -1;
235                                 }
236                                 body_axis_of_motion = (1.0 / length) * body_axis_of_motion;
237                         }
238                         break;
239                 case FIXED:
240                         break;
241                 case FLOATING:
242                         break;
243                 default:
244                         error_message("unknown joint type %d\n", joint_type);
245                         return -1;
246         }
247 
248         // sanity check for mass properties. Zero mass is OK.
249         if (mass < 0) {
250                 m_mass_parameters_are_valid = false;
251                 error_message("Body %d has invalid mass %e\n", body_index, mass);
252                 if (!m_accept_invalid_mass_parameters) {
253                         return -1;
254                 }
255         }
256 
257         if (!isValidInertiaMatrix(body_I_body, body_index, FIXED == joint_type)) {
258                 m_mass_parameters_are_valid = false;
259                 // error message printed in function call
260                 if (!m_accept_invalid_mass_parameters) {
261                         return -1;
262                 }
263         }
264 
265         if (!isValidTransformMatrix(body_T_parent_ref)) {
266                 return -1;
267         }
268 
269         return m_init_cache->addBody(body_index, parent_index, joint_type, parent_r_parent_body_ref,
270                                                                  body_T_parent_ref, body_axis_of_motion, mass, body_r_body_com,
271                                                                  body_I_body, user_int, user_ptr);
272 }
void btInverseDynamics::MultiBodyTree::setAcceptInvalidMassParameters (bool flag)
set policy for invalid mass properties
Parameters:
flag if true, invalid mass properties are accepted, the default is false
Definition at line 27 of file MultiBodyTree.cpp.
27                                                             {
28         m_accept_invalid_mass_parameters = flag;
29 }
bool btInverseDynamics::MultiBodyTree::getAcceptInvalidMassProperties () const
Returns: the mass properties policy flag
Definition at line 31 of file MultiBodyTree.cpp.
31                                                          {
32         return m_accept_invalid_mass_parameters;
33 }
int btInverseDynamics::MultiBodyTree::finalize ()
build internal data structures call this after all bodies have been added via addBody
Returns: 0 on success, -1 on error
Definition at line 294 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::InitCache::buildIndexSets(), btInverseDynamics::MultiBodyTree::MultiBodyImpl::calculateStaticData(), btInverseDynamics::MultiBodyTree::MultiBodyImpl::clearAllUserForcesAndMoments(), btInverseDynamics::MultiBodyTree::MultiBodyImpl::generateIndexSets(), btInverseDynamics::MultiBodyTree::InitCache::getInertiaData(), btInverseDynamics::MultiBodyTree::InitCache::getJointData(), btInverseDynamics::MultiBodyTree::InitCache::getParentIndexArray(), btInverseDynamics::InertiaData::m_body_I_body, btInverseDynamics::RigidBody::m_body_I_body, btInverseDynamics::MultiBodyTree::MultiBodyImpl::m_body_list, btInverseDynamics::RigidBody::m_body_mass_com, btInverseDynamics::InertiaData::m_body_pos_body_com, btInverseDynamics::RigidBody::m_body_T_parent_ref, btInverseDynamics::JointData::m_child_axis_of_motion, btInverseDynamics::JointData::m_child_T_parent_ref, btInverseDynamics::RigidBody::m_Jac_JR, btInverseDynamics::RigidBody::m_Jac_JT, btInverseDynamics::RigidBody::m_joint_type, btInverseDynamics::InertiaData::m_mass, btInverseDynamics::RigidBody::m_mass, btInverseDynamics::MultiBodyTree::MultiBodyImpl::m_parent_index, btInverseDynamics::RigidBody::m_parent_pos_parent_body_ref, btInverseDynamics::JointData::m_parent_pos_parent_child_ref, btInverseDynamics::JointData::m_type, btInverseDynamics::MultiBodyTree::InitCache::numBodies(), and btInverseDynamics::MultiBodyTree::InitCache::numDoFs().
294                             {
295         const int &num_bodies = m_init_cache->numBodies();
296         const int &num_dofs = m_init_cache->numDoFs();
297 
298         if(num_dofs<=0) {
299             error_message("Need num_dofs>=1, but num_dofs= %d\n", num_dofs);
300             //return -1;
301         }
302 
303         // 1 allocate internal MultiBody structure
304         m_impl = new MultiBodyImpl(num_bodies, num_dofs);
305 
306         // 2 build new index set assuring index(parent) < index(child)
307         if (-1 == m_init_cache->buildIndexSets()) {
308                 return -1;
309         }
310         m_init_cache->getParentIndexArray(&m_impl->m_parent_index);
311 
312         // 3 setup internal kinematic and dynamic data
313         for (int index = 0; index < num_bodies; index++) {
314                 InertiaData inertia;
315                 JointData joint;
316                 if (-1 == m_init_cache->getInertiaData(index, &inertia)) {
317                         return -1;
318                 }
319                 if (-1 == m_init_cache->getJointData(index, &joint)) {
320                         return -1;
321                 }
322 
323                 RigidBody &rigid_body = m_impl->m_body_list[index];
324 
325                 rigid_body.m_mass = inertia.m_mass;
326                 rigid_body.m_body_mass_com = inertia.m_mass * inertia.m_body_pos_body_com;
327                 rigid_body.m_body_I_body = inertia.m_body_I_body;
328                 rigid_body.m_joint_type = joint.m_type;
329                 rigid_body.m_parent_pos_parent_body_ref = joint.m_parent_pos_parent_child_ref;
330                 rigid_body.m_body_T_parent_ref = joint.m_child_T_parent_ref;
331                 rigid_body.m_parent_pos_parent_body_ref = joint.m_parent_pos_parent_child_ref;
332                 rigid_body.m_joint_type = joint.m_type;
333 
334                 // Set joint Jacobians. Note that the dimension is always 3x1 here to avoid variable sized
335                 // matrices.
336                 switch (rigid_body.m_joint_type) {
337                         case REVOLUTE:
338                                 rigid_body.m_Jac_JR(0) = joint.m_child_axis_of_motion(0);
339                                 rigid_body.m_Jac_JR(1) = joint.m_child_axis_of_motion(1);
340                                 rigid_body.m_Jac_JR(2) = joint.m_child_axis_of_motion(2);
341                                 rigid_body.m_Jac_JT(0) = 0.0;
342                                 rigid_body.m_Jac_JT(1) = 0.0;
343                                 rigid_body.m_Jac_JT(2) = 0.0;
344                                 break;
345                         case PRISMATIC:
346                                 rigid_body.m_Jac_JR(0) = 0.0;
347                                 rigid_body.m_Jac_JR(1) = 0.0;
348                                 rigid_body.m_Jac_JR(2) = 0.0;
349                                 rigid_body.m_Jac_JT(0) = joint.m_child_axis_of_motion(0);
350                                 rigid_body.m_Jac_JT(1) = joint.m_child_axis_of_motion(1);
351                                 rigid_body.m_Jac_JT(2) = joint.m_child_axis_of_motion(2);
352                                 break;
353                         case FIXED:
354                                 // NOTE/TODO: dimension really should be zero ..
355                                 rigid_body.m_Jac_JR(0) = 0.0;
356                                 rigid_body.m_Jac_JR(1) = 0.0;
357                                 rigid_body.m_Jac_JR(2) = 0.0;
358                                 rigid_body.m_Jac_JT(0) = 0.0;
359                                 rigid_body.m_Jac_JT(1) = 0.0;
360                                 rigid_body.m_Jac_JT(2) = 0.0;
361                                 break;
362                         case FLOATING:
363                                 // NOTE/TODO: this is not really correct.
364                                 // the Jacobians should be 3x3 matrices here !
365                                 rigid_body.m_Jac_JR(0) = 0.0;
366                                 rigid_body.m_Jac_JR(1) = 0.0;
367                                 rigid_body.m_Jac_JR(2) = 0.0;
368                                 rigid_body.m_Jac_JT(0) = 0.0;
369                                 rigid_body.m_Jac_JT(1) = 0.0;
370                                 rigid_body.m_Jac_JT(2) = 0.0;
371                                 break;
372                         default:
373                                 error_message("unsupported joint type %d\n", rigid_body.m_joint_type);
374                                 return -1;
375                 }
376         }
377 
378         // 4 assign degree of freedom indices & build per-joint-type index arrays
379         if (-1 == m_impl->generateIndexSets()) {
380                 error_message("generating index sets\n");
381                 return -1;
382         }
383 
384         // 5 do some pre-computations ..
385         m_impl->calculateStaticData();
386 
387         // 6. make sure all user forces are set to zero, as this might not happen
388         //      in the vector ctors.
389         m_impl->clearAllUserForcesAndMoments();
390 
391         m_is_finalized = true;
392         return 0;
393 }
int btInverseDynamics::MultiBodyTree::calculateInverseDynamics (const vecx & q, const vecx & u, const vecx & dot_u, vecx * joint_forces)
Calculate joint forces for given generalized state & derivatives. This also updates kinematic terms computed in calculateKinematics. If gravity is not set to zero, acceleration terms will contain gravitational acceleration.
Parameters:
q generalized coordinates
u generalized velocities. In the general case, u=T(q)*dot(q) and dim(q)>=dim(u)
dot_u time derivative of u
joint_forces this is where the resulting joint forces will be stored. dim(joint_forces) = dim(u)
Returns: 0 on success, -1 on error
Definition at line 83 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::calculateInverseDynamics().
84                                                                                                             {
85         if (false == m_is_finalized) {
86                 error_message("system has not been initialized\n");
87                 return -1;
88         }
89         if (-1 == m_impl->calculateInverseDynamics(q, u, dot_u, joint_forces)) {
90                 error_message("error in inverse dynamics calculation\n");
91                 return -1;
92         }
93         return 0;
94 }
int btInverseDynamics::MultiBodyTree::calculateMassMatrix (const vecx & q, const bool update_kinematics, const bool initialize_matrix, const bool set_lower_triangular_matrix, matxx * mass_matrix)
Calculate joint space mass matrix
Parameters:
q generalized coordinates
initialize_matrix if true, initialize mass matrix with zero. If mass_matrix is initialized to zero externally and only used for mass matrix computations for the same system, it is safe to set this to false.
set_lower_triangular_matrix if true, the lower triangular section of mass_matrix is also populated, otherwise not.
mass_matrix matrix for storing the output (should be dim(q)xdim(q))
Returns: -1 on error, 0 on success
Definition at line 96 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::calculateMassMatrix().
Referenced by calculateMassMatrix().
98                                                                                                                                        {
99         if (false == m_is_finalized) {
100                 error_message("system has not been initialized\n");
101                 return -1;
102         }
103         if (-1 ==
104                 m_impl->calculateMassMatrix(q, update_kinematics, initialize_matrix,
105                                                                         set_lower_triangular_matrix, mass_matrix)) {
106                 error_message("error in mass matrix calculation\n");
107                 return -1;
108         }
109         return 0;
110 }
int btInverseDynamics::MultiBodyTree::calculateMassMatrix (const vecx & q, matxx * mass_matrix)
Calculate joint space mass matrix. This version will update kinematics, initialize all mass_matrix elements to zero and populate all mass matrix entries.
Parameters:
q generalized coordinates
mass_matrix matrix for storing the output (should be dim(q)xdim(q))
Returns: -1 on error, 0 on success
Definition at line 112 of file MultiBodyTree.cpp.
References calculateMassMatrix().
112                                                                         {
113         return calculateMassMatrix(q, true, true, true, mass_matrix);
114 }
int btInverseDynamics::MultiBodyTree::calculateKinematics (const vecx & q, const vecx & u, const vecx & dot_u)
Calculates kinematics also calculated in calculateInverseDynamics, but not dynamics. This function ensures that correct accelerations are computed that do not contain gravitational acceleration terms. Does not calculate Jacobians, but only vector quantities (positions, velocities & accelerations)
Definition at line 118 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::calculateKinematics(), and btInverseDynamics::MultiBodyTree::MultiBodyImpl::m_world_gravity.
118                                                                                       {
119     vec3 world_gravity(m_impl->m_world_gravity);
120     // temporarily set gravity to zero, to ensure we get the actual accelerations
121     setZero(m_impl->m_world_gravity);
122 
123     if (false == m_is_finalized) {
124         error_message("system has not been initialized\n");
125         return -1;
126     }
127     if (-1 == m_impl->calculateKinematics(q, u, dot_u,
128                                           MultiBodyTree::MultiBodyImpl::POSITION_VELOCITY_ACCELERATION)) {
129         error_message("error in kinematics calculation\n");
130         return -1;
131     }
132 
133     m_impl->m_world_gravity=world_gravity;
134     return 0;
135 }
int btInverseDynamics::MultiBodyTree::calculateJacobians (const vecx & q, const vecx & u)
Calculate Jacobians (dvel/du), as well as velocity-dependent accelearation components d(Jacobian)/dt*u This function assumes that calculateInverseDynamics was called, or calculateKinematics, or calculatePositionAndVelocityKinematics
Definition at line 166 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::calculateJacobians().
166                                                                   {
167     if (false == m_is_finalized) {
168         error_message("system has not been initialized\n");
169         return -1;
170     }
171     if (-1 == m_impl->calculateJacobians(q, u,
172                                          MultiBodyTree::MultiBodyImpl::POSITION_VELOCITY)) {
173         error_message("error in jacobian calculation\n");
174         return -1;
175     }
176     return 0;
177 }
int btInverseDynamics::MultiBodyTree::calculateJacobians (const vecx & q)
Calculate Jacobians (dvel/du) This function assumes that calculateInverseDynamics was called, or one of the calculateKineamtics functions
Definition at line 179 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::calculateJacobians().
179                                                   {
180     if (false == m_is_finalized) {
181         error_message("system has not been initialized\n");
182         return -1;
183     }
184     if (-1 == m_impl->calculateJacobians(q, q,
185                                          MultiBodyTree::MultiBodyImpl::POSITION_ONLY)) {
186         error_message("error in jacobian calculation\n");
187         return -1;
188     }
189     return 0;
190 }
int btInverseDynamics::MultiBodyTree::setGravityInWorldFrame (const vec3 & gravity)
set gravitational acceleration the default is [0;0;-9.8] in the world frame
Parameters:
gravity the gravitational acceleration in world frame
Returns: 0 on success, -1 on error
Definition at line 395 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::setGravityInWorldFrame().
395                                                              {
396         return m_impl->setGravityInWorldFrame(gravity);
397 }
int btInverseDynamics::MultiBodyTree::getBodyOrigin (const int body_index, vec3 * world_origin) const
get origin of a body-fixed frame, represented in world frame
Parameters:
body_index index for frame/body
world_origin pointer for return data
Returns: 0 on success, -1 on error
Definition at line 35 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getBodyOrigin().
35                                                                                {
36         return m_impl->getBodyOrigin(body_index, world_origin);
37 }
int btInverseDynamics::MultiBodyTree::getBodyCoM (const int body_index, vec3 * world_com) const
get center of mass of a body, represented in world frame
Parameters:
body_index index for frame/body
world_com pointer for return data
Returns: 0 on success, -1 on error
Definition at line 39 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getBodyCoM().
39                                                                          {
40         return m_impl->getBodyCoM(body_index, world_com);
41 }
int btInverseDynamics::MultiBodyTree::getBodyTransform (const int body_index, mat33 * world_T_body) const
get transform from of a body-fixed frame to the world frame
Parameters:
body_index index for frame/body
world_T_body pointer for return data
Returns: 0 on success, -1 on error
Definition at line 43 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getBodyTransform().
43                                                                                    {
44         return m_impl->getBodyTransform(body_index, world_T_body);
45 }
int btInverseDynamics::MultiBodyTree::getBodyAngularVelocity (const int body_index, vec3 * world_omega) const
get absolute angular velocity for a body, represented in the world frame
Parameters:
body_index index for frame/body
world_omega pointer for return data
Returns: 0 on success, -1 on error
Definition at line 46 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getBodyAngularVelocity().
46                                                                                        {
47         return m_impl->getBodyAngularVelocity(body_index, world_omega);
48 }
int btInverseDynamics::MultiBodyTree::getBodyLinearVelocity (const int body_index, vec3 * world_velocity) const
get linear velocity of a body, represented in world frame
Parameters:
body_index index for frame/body
world_velocity pointer for return data
Returns: 0 on success, -1 on error
Definition at line 49 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getBodyLinearVelocity().
49                                                                                          {
50         return m_impl->getBodyLinearVelocity(body_index, world_velocity);
51 }
int btInverseDynamics::MultiBodyTree::getBodyLinearVelocityCoM (const int body_index, vec3 * world_velocity) const
get linear velocity of a body's CoM, represented in world frame (not required for inverse dynamics, provided for convenience)
Parameters:
body_index index for frame/body
world_vel_com pointer for return data
Returns: 0 on success, -1 on error
Definition at line 53 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getBodyLinearVelocityCoM().
53                                                                                             {
54         return m_impl->getBodyLinearVelocityCoM(body_index, world_velocity);
55 }
int btInverseDynamics::MultiBodyTree::getBodyAngularAcceleration (const int body_index, vec3 * world_dot_omega) const
get origin of a body-fixed frame, represented in world frame
Parameters:
body_index index for frame/body
world_origin pointer for return data
Returns: 0 on success, -1 on error
Definition at line 57 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getBodyAngularAcceleration().
57                                                                                                {
58         return m_impl->getBodyAngularAcceleration(body_index, world_dot_omega);
59 }
int btInverseDynamics::MultiBodyTree::getBodyLinearAcceleration (const int body_index, vec3 * world_acceleration) const
get origin of a body-fixed frame, represented in world frame NOTE: this will include the gravitational acceleration, so the actual acceleration is obtainened by setting gravitational acceleration to zero, or subtracting it.
Parameters:
body_index index for frame/body
world_origin pointer for return data
Returns: 0 on success, -1 on error
Definition at line 60 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getBodyLinearAcceleration().
60                                                                                                  {
61         return m_impl->getBodyLinearAcceleration(body_index, world_acceleration);
62 }
int btInverseDynamics::MultiBodyTree::getParentIndex (const int body_index, int * parent_index) const
returns the (internal) index of body
Parameters:
body_index is the index of a body
parent_index pointer to where parent index will be stored
Returns: 0 on success, -1 on error
Definition at line 274 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getParentIndex().
274                                                                                {
275         return m_impl->getParentIndex(body_index, parent_index);
276 }
int btInverseDynamics::MultiBodyTree::getJointType (const int body_index, JointType * joint_type) const
get joint type
Parameters:
body_index index of the body
joint_type the corresponding joint type
Returns: 0 on success, -1 on failure
Definition at line 399 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getJointType().
399                                                                                  {
400         return m_impl->getJointType(body_index, joint_type);
401 }
int btInverseDynamics::MultiBodyTree::getJointTypeStr (const int body_index, const char ** joint_type) const
get joint type as string
Parameters:
body_index index of the body
joint_type string naming the corresponding joint type
Returns: 0 on success, -1 on failure
Definition at line 403 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getJointTypeStr().
403                                                                                       {
404         return m_impl->getJointTypeStr(body_index, joint_type);
405 }
int btInverseDynamics::MultiBodyTree::getParentRParentBodyRef (const int body_index, vec3 * r) const
get offset translation to parent body (see addBody)
Parameters:
body_index index of the body
r the offset translation (see above)
Returns: 0 on success, -1 on failure
Definition at line 64 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getParentRParentBodyRef().
64                                                                               {
65     return m_impl->getParentRParentBodyRef(body_index, r);
66 }
int btInverseDynamics::MultiBodyTree::getBodyTParentRef (const int body_index, mat33 * T) const
get offset rotation to parent body (see addBody)
Parameters:
body_index index of the body
T the transform (see above)
Returns: 0 on success, -1 on failure
Definition at line 68 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getBodyTParentRef().
68                                                                          {
69     return m_impl->getBodyTParentRef(body_index, T);
70 }
int btInverseDynamics::MultiBodyTree::getBodyAxisOfMotion (const int body_index, vec3 * axis) const
get axis of motion (see addBody)
Parameters:
body_index index of the body
axis the axis (see above)
Returns: 0 on success, -1 on failure
Definition at line 72 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getBodyAxisOfMotion().
72                                                                              {
73     return m_impl->getBodyAxisOfMotion(body_index, axis);
74 }
int btInverseDynamics::MultiBodyTree::getDoFOffset (const int body_index, int * q_offset) const
get offset for degrees of freedom of this body into the q-vector
Parameters:
body_index index of the body
q_offset offset the q vector
Returns: -1 on error, 0 on success
Definition at line 407 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getDoFOffset().
407                                                                          {
408         return m_impl->getDoFOffset(body_index, q_offset);
409 }
int btInverseDynamics::MultiBodyTree::getUserInt (const int body_index, int * user_int) const
get user integer. not used by the library.
Parameters:
body_index index of the body
user_int the user integer
Returns: 0 on success, -1 on error
Definition at line 278 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getUserInt().
278                                                                        {
279         return m_impl->getUserInt(body_index, user_int);
280 }
int btInverseDynamics::MultiBodyTree::getUserPtr (const int body_index, void ** user_ptr) const
get user pointer. not used by the library.
Parameters:
body_index index of the body
user_ptr the user pointer
Returns: 0 on success, -1 on error
Definition at line 282 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getUserPtr().
282                                                                          {
283         return m_impl->getUserPtr(body_index, user_ptr);
284 }
int btInverseDynamics::MultiBodyTree::setUserInt (const int body_index, const int user_int)
set user integer. not used by the library.
Parameters:
body_index index of the body
user_int the user integer
Returns: 0 on success, -1 on error
Definition at line 286 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::setUserInt().
286                                                                       {
287         return m_impl->setUserInt(body_index, user_int);
288 }
int btInverseDynamics::MultiBodyTree::setUserPtr (const int body_index, void *const user_ptr)
set user pointer. not used by the library.
Parameters:
body_index index of the body
user_ptr the user pointer
Returns: 0 on success, -1 on error
Definition at line 290 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::setUserPtr().
290                                                                         {
291         return m_impl->setUserPtr(body_index, user_ptr);
292 }
int btInverseDynamics::MultiBodyTree::setBodyMass (const int body_index, const idScalar mass)
set mass for a body
Parameters:
body_index index of the body
mass the mass to set
Returns: 0 on success, -1 on failure
Definition at line 411 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::setBodyMass().
411                                                                   {
412         return m_impl->setBodyMass(body_index, mass);
413 }
int btInverseDynamics::MultiBodyTree::setBodyFirstMassMoment (const int body_index, const vec3 & first_mass_moment)
set first moment of mass for a body (mass * center of mass, in body fixed frame, relative to joint)
Parameters:
body_index index of the body
first_mass_moment the vector to set
Returns: 0 on success, -1 on failure
Definition at line 415 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::setBodyFirstMassMoment().
415                                                                                              {
416         return m_impl->setBodyFirstMassMoment(body_index, first_mass_moment);
417 }
int btInverseDynamics::MultiBodyTree::setBodySecondMassMoment (const int body_index, const mat33 & second_mass_moment)
set second moment of mass for a body (moment of inertia, in body fixed frame, relative to joint)
Parameters:
body_index index of the body
second_mass_moment the inertia matrix
Returns: 0 on success, -1 on failure
Definition at line 419 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::setBodySecondMassMoment().
419                                                                                                 {
420         return m_impl->setBodySecondMassMoment(body_index, second_mass_moment);
421 }
int btInverseDynamics::MultiBodyTree::getBodyMass (const int body_index, idScalar * mass) const
get mass for a body
Parameters:
body_index index of the body
mass the mass
Returns: 0 on success, -1 on failure
Definition at line 423 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getBodyMass().
423                                                                          {
424         return m_impl->getBodyMass(body_index, mass);
425 }
int btInverseDynamics::MultiBodyTree::getBodyFirstMassMoment (const int body_index, vec3 * first_mass_moment) const
get first moment of mass for a body (mass * center of mass, in body fixed frame, relative to joint)
Parameters:
body_index index of the body
first_moment the vector
Returns: 0 on success, -1 on failure
Definition at line 427 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getBodyFirstMassMoment().
427                                                                                              {
428         return m_impl->getBodyFirstMassMoment(body_index, first_mass_moment);
429 }
int btInverseDynamics::MultiBodyTree::getBodySecondMassMoment (const int body_index, mat33 * second_mass_moment) const
get second moment of mass for a body (moment of inertia, in body fixed frame, relative to joint)
Parameters:
body_index index of the body
second_mass_moment the inertia matrix
Returns: 0 on success, -1 on failure
Definition at line 431 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::getBodySecondMassMoment().
431                                                                                                 {
432         return m_impl->getBodySecondMassMoment(body_index, second_mass_moment);
433 }
int btInverseDynamics::MultiBodyTree::addUserForce (const int body_index, const vec3 & body_force)
Add an external force to a body, acting at the origin of the body-fixed frame. Calls to addUserForce are cumulative. Set the user force and moment to zero via clearAllUserForcesAndMoments()
Parameters:
body_force the force represented in the body-fixed frame of reference
Returns: 0 on success, -1 on error
Definition at line 437 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::addUserForce().
437                                                                             {
438         return m_impl->addUserForce(body_index, body_force);
439 }
int btInverseDynamics::MultiBodyTree::addUserMoment (const int body_index, const vec3 & body_moment)
Add an external moment to a body. Calls to addUserMoment are cumulative. Set the user force and moment to zero via clearAllUserForcesAndMoments()
Parameters:
body_moment the moment represented in the body-fixed frame of reference
Returns: 0 on success, -1 on error
Definition at line 441 of file MultiBodyTree.cpp.
References btInverseDynamics::MultiBodyTree::MultiBodyImpl::addUserMoment().
441                                                                               {
442         return m_impl->addUserMoment(body_index, body_moment);
443 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletInverseDynamics/MultiBodyTree.hpp
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletInverseDynamics/MultiBodyTree.cpp