btBoxBoxCollisionAlgorithm Class Reference
box-box collision detection
#include <btBoxBoxCollisionAlgorithm.h>
Public Member Functions
virtual void processCollision (const btCollisionObjectWrapper *body0Wrap, const btCollisionObjectWrapper *body1Wrap, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
Detailed Description
box-box collision detection
Definition at line 27 of file btBoxBoxCollisionAlgorithm.h.
Member Function Documentation
void btBoxBoxCollisionAlgorithm::processCollision (const btCollisionObjectWrapper * body0Wrap, const btCollisionObjectWrapper * body1Wrap, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
report a contact. internally this will be kept persistent, and contact reduction is done
Implements btCollisionAlgorithm.
Definition at line 45 of file btBoxBoxCollisionAlgorithm.cpp.
References btBoxBoxDetector::getClosestPoints(), btManifoldResult::refreshContactPoints(), and btManifoldResult::setPersistentManifold().
46 {
47         if (!m_manifoldPtr)
48                 return;
49 
50         
51         const btBoxShape* box0 = (btBoxShape*)body0Wrap->getCollisionShape();
52         const btBoxShape* box1 = (btBoxShape*)body1Wrap->getCollisionShape();
53 
54 
55 
57         resultOut->setPersistentManifold(m_manifoldPtr);
58 #ifndef USE_PERSISTENT_CONTACTS 
59         m_manifoldPtr->clearManifold();
60 #endif //USE_PERSISTENT_CONTACTS
61 
62         btDiscreteCollisionDetectorInterface::ClosestPointInput input;
63         input.m_maximumDistanceSquared = BT_LARGE_FLOAT;
64         input.m_transformA = body0Wrap->getWorldTransform();
65         input.m_transformB = body1Wrap->getWorldTransform();
66 
67         btBoxBoxDetector detector(box0,box1);
68         detector.getClosestPoints(input,*resultOut,dispatchInfo.m_debugDraw);
69 
70 #ifdef USE_PERSISTENT_CONTACTS
71         //  refreshContactPoints is only necessary when using persistent contact points. otherwise all points are newly added
72         if (m_ownManifold)
73         {
74                 resultOut->refreshContactPoints();
75         }
76 #endif //USE_PERSISTENT_CONTACTS
77 
78 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp