gim_hash_table< T > Class Template Reference
A compact hash table implementation.
#include <gim_hash_table.h>
Public Member Functions
gim_hash_table (GUINT reserve_size=GIM_DEFAULT_HASH_TABLE_SIZE, GUINT node_size=GIM_DEFAULT_HASH_TABLE_NODE_SIZE, GUINT min_hash_table_size=GIM_INVALID_HASH)
bool check_for_switching_to_hashtable ()
If the container reaches the.
GUINT size () const
Retrieves the amount of keys.
GUINT get_key (GUINT index) const
Retrieves the hash key.
T * get_value_by_index (GUINT index)
Retrieves the value by index.
GUINT find (GUINT hashkey)
Finds the index of the element with the key.
T * get_value (GUINT hashkey)
Retrieves the value associated with the index.
GUINT insert (GUINT hashkey, const T &element)
Insert an element into the hash.
GUINT insert_override (GUINT hashkey, const T &element)
Insert an element into the hash, and could overrite an existing object with the same hash.
GUINT insert_unsorted (GUINT hashkey, const T &element)
Insert an element into the hash,But if this container is a sorted array, this inserts it unsorted.
Protected Member Functions
GUINT _find_cell (GUINT hashkey)
Returns the cell index.
GUINT _find_avaliable_cell (GUINT hashkey)
Find the avaliable cell for the hashkey, and return an existing cell if it has the same hash key.
void _reserve_table_memory (GUINT newtablesize)
reserves the memory for the hash table.
void _clear_table_memory ()
Clear all memory for the hash table.
void _rehash ()
Invalidates the keys (Assigning GIM_INVALID_HASH to all) Reorders the hash keys.
void _resize_table (GUINT newsize)
Resize hash table indices.
void _destroy ()
Destroy hash table memory.
GUINT _assign_hash_table_cell (GUINT hashkey)
Finds an avaliable hash table cell, and resizes the table if there isn't space.
bool _erase_by_index_hash_table (GUINT index)
erase by index in hash table
bool _erase_hash_table (GUINT hashkey)
erase by key in hash table
GUINT _insert_hash_table (GUINT hashkey, const T &value)
insert an element in hash table
GUINT _insert_hash_table_replace (GUINT hashkey, const T &value)
insert an element in hash table.
bool _erase_sorted (GUINT index)
Sorted array data management. The hash table has the indices to the corresponding m_nodes array.
bool _erase_unsorted (GUINT index)
faster, but unsorted
void _insert_in_pos (GUINT hashkey, const T &value, GUINT pos)
Insert in position ordered.
GUINT _insert_sorted (GUINT hashkey, const T &value)
Insert an element in an ordered array.
GUINT _insert_unsorted (GUINT hashkey, const T &value)
Fast insertion in m_nodes array.
Protected Attributes
gim_array< _node_type > m_nodes
The nodes.
GUINT * m_hash_table
Hash table data management. The hash table has the indices to the corresponding m_nodes array.
Detailed Description
template<class T> class gim_hash_table< T >
A compact hash table implementation.
A memory aligned compact hash table that coud be treated as an array. It could be a simple sorted array without the overhead of the hash key bucked, or could be a formely hash table with an array of keys. You can use switch_to_hashtable() and switch_to_sorted_array for saving space or increase speed.
if node_size = 0, then this container becomes a simple sorted array allocator. reserve_size is used for reserve memory in m_nodes. When the array size reaches the size equivalent to 'min_hash_table_size', then it becomes a hash table by calling check_for_switching_to_hashtable.
If node_size != 0, then this container becomes a hash table for ever
Definition at line 191 of file gim_hash_table.h.
Constructor & Destructor Documentation
template<class T> gim_hash_table< T >::gim_hash_table (GUINT reserve_size = GIM_DEFAULT_HASH_TABLE_SIZE, GUINT node_size = GIM_DEFAULT_HASH_TABLE_NODE_SIZE, GUINT min_hash_table_size = GIM_INVALID_HASH) [inline]
if node_size = 0, then this container becomes a simple sorted array allocator. reserve_size is used for reserve memory in m_nodes. When the array size reaches the size equivalent to 'min_hash_table_size', then it becomes a hash table by calling check_for_switching_to_hashtable. If node_size != 0, then this container becomes a hash table for ever
Definition at line 573 of file gim_hash_table.h.
References gim_hash_table< T >::_reserve_table_memory(), gim_hash_table< T >::m_hash_table, and gim_hash_table< T >::m_nodes.
576     {
577         m_hash_table = NULL;
578         m_table_size = 0;
579         m_sorted = false;
580         m_node_size = node_size;
581         m_min_hash_table_size = min_hash_table_size;
582 
583         if(m_node_size!=0)
584         {
585             if(reserve_size!=0)
586             {
587                 m_nodes.reserve(reserve_size);
588                 _reserve_table_memory(reserve_size);
589                 _invalidate_keys();
590             }
591             else
592             {
593                 m_nodes.reserve(GIM_DEFAULT_HASH_TABLE_SIZE);
594                 _reserve_table_memory(GIM_DEFAULT_HASH_TABLE_SIZE);
595                 _invalidate_keys();
596             }
597         }
598         else if(reserve_size!=0)
599         {
600             m_nodes.reserve(reserve_size);
601         }
602 
603     }
Member Function Documentation
template<class T> void gim_hash_table< T >::_reserve_table_memory (GUINT newtablesize) [inline, protected]
reserves the memory for the hash table.
Precondition: hash table must be empty
Postcondition: reserves the memory for the hash table, an initializes all elements to GIM_INVALID_HASH.
Definition at line 263 of file gim_hash_table.h.
References gim_hash_table< T >::m_hash_table.
Referenced by gim_hash_table< T >::_resize_table(), and gim_hash_table< T >::gim_hash_table().
264     {
265         if(newtablesize==0) return;
266         if(m_node_size==0) return;
267 
268         //Get a Prime size
269 
270         m_table_size = gim_next_prime(newtablesize);
271 
272         GUINT datasize = m_table_size*m_node_size;
273         //Alloc the data buffer
274         m_hash_table =  (GUINT *)gim_alloc(datasize*sizeof(GUINT));
275     }
template<class T> GUINT gim_hash_table< T >::_insert_hash_table (GUINT hashkey, const T & value) [inline, protected]
insert an element in hash table
If the element exists, this won't insert the element
Returns: the index in the array of the existing element,or GIM_INVALID_HASH if the element has been inserted If so, the element has been inserted at the last position of the array.
Definition at line 399 of file gim_hash_table.h.
References gim_hash_table< T >::_assign_hash_table_cell(), gim_hash_table< T >::_insert_unsorted(), gim_hash_table< T >::m_hash_table, and gim_hash_table< T >::m_nodes.
Referenced by gim_hash_table< T >::insert(), and gim_hash_table< T >::insert_unsorted().
400     {
401         if(hashkey==GIM_INVALID_HASH)
402         {
403             //Insert anyway
404             _insert_unsorted(hashkey,value);
405             return GIM_INVALID_HASH;
406         }
407 
408         GUINT cell_index = _assign_hash_table_cell(hashkey);
409 
410         GUINT value_key = m_hash_table[cell_index];
411 
412         if(value_key!= GIM_INVALID_HASH) return value_key;// Not overrited
413 
414         m_hash_table[cell_index] = m_nodes.size();
415 
416         _insert_unsorted(hashkey,value);
417         return GIM_INVALID_HASH;
418     }
template<class T> GUINT gim_hash_table< T >::_insert_hash_table_replace (GUINT hashkey, const T & value) [inline, protected]
insert an element in hash table.
If the element exists, this replaces the element.
Returns: the index in the array of the existing element,or GIM_INVALID_HASH if the element has been inserted If so, the element has been inserted at the last position of the array.
Definition at line 426 of file gim_hash_table.h.
References gim_hash_table< T >::_assign_hash_table_cell(), gim_hash_table< T >::_insert_unsorted(), gim_hash_table< T >::m_hash_table, and gim_hash_table< T >::m_nodes.
Referenced by gim_hash_table< T >::insert_override().
427     {
428         if(hashkey==GIM_INVALID_HASH)
429         {
430             //Insert anyway
431             _insert_unsorted(hashkey,value);
432             return GIM_INVALID_HASH;
433         }
434 
435         GUINT cell_index = _assign_hash_table_cell(hashkey);
436 
437         GUINT value_key = m_hash_table[cell_index];
438 
439         if(value_key!= GIM_INVALID_HASH)
440         {//replaces the existing
441             m_nodes[value_key] = _node_type(hashkey,value);
442             return value_key;// index of the replaced element
443         }
444 
445         m_hash_table[cell_index] = m_nodes.size();
446 
447         _insert_unsorted(hashkey,value);
448         return GIM_INVALID_HASH;
449 
450     }
template<class T> void gim_hash_table< T >::_insert_in_pos (GUINT hashkey, const T & value, GUINT pos) [inline, protected]
Insert in position ordered.
Also checks if it is needed to transform this container to a hash table, by calling check_for_switching_to_hashtable
Definition at line 489 of file gim_hash_table.h.
References gim_hash_table< T >::check_for_switching_to_hashtable(), and gim_hash_table< T >::m_nodes.
Referenced by gim_hash_table< T >::_insert_sorted().
490     {
491         m_nodes.insert(_node_type(hashkey,value),pos);
492         this->check_for_switching_to_hashtable();
493     }
template<class T> GUINT gim_hash_table< T >::find (GUINT hashkey) [inline]
Finds the index of the element with the key.
Returns: the index in the array of the existing element,or GIM_INVALID_HASH if the element has been inserted If so, the element has been inserted at the last position of the array.
Definition at line 723 of file gim_hash_table.h.
References gim_hash_table< T >::_find_cell(), gim_binary_search_ex(), gim_hash_table< T >::m_hash_table, and gim_hash_table< T >::m_nodes.
Referenced by gim_hash_table< T >::get_value().
724     {
725         if(m_hash_table)
726         {
727             GUINT cell_index = _find_cell(hashkey);
728             if(cell_index==GIM_INVALID_HASH) return GIM_INVALID_HASH;
729             return m_hash_table[cell_index];
730         }
731                 GUINT last_index = m_nodes.size();
732         if(last_index<2)
733         {
734                         if(last_index==0) return GIM_INVALID_HASH;
735             if(m_nodes[0].m_key == hashkey) return 0;
736             return GIM_INVALID_HASH;
737         }
738         else if(m_sorted)
739         {
740             //Binary search
741             GUINT result_ind = 0;
742                         last_index--;
743             _node_type *  ptr =  m_nodes.pointer();
744 
745             bool found = gim_binary_search_ex(ptr,0,last_index,result_ind,hashkey,GIM_HASH_NODE_CMP_KEY_MACRO());
746 
747 
748             if(found) return result_ind;
749         }
750         return GIM_INVALID_HASH;
751     }
template<class T> T* gim_hash_table< T >::get_value (GUINT hashkey) [inline]
Retrieves the value associated with the index.
Returns: the found element, or null
Definition at line 757 of file gim_hash_table.h.
References gim_hash_table< T >::find(), and gim_hash_table< T >::m_nodes.
758     {
759         GUINT index = find(hashkey);
760         if(index == GIM_INVALID_HASH) return NULL;
761         return &m_nodes[index].m_data;
762     }
template<class T> GUINT gim_hash_table< T >::insert (GUINT hashkey, const T & element) [inline]
Insert an element into the hash.
Returns: If GIM_INVALID_HASH, the object has been inserted succesfully. Else it returns the position of the existing element.
Definition at line 851 of file gim_hash_table.h.
References gim_hash_table< T >::_insert_hash_table(), gim_hash_table< T >::_insert_sorted(), gim_hash_table< T >::_insert_unsorted(), and gim_hash_table< T >::m_hash_table.
852     {
853         if(m_hash_table)
854         {
855             return this->_insert_hash_table(hashkey,element);
856         }
857         if(this->is_sorted())
858         {
859             return this->_insert_sorted(hashkey,element);
860         }
861         return this->_insert_unsorted(hashkey,element);
862     }
template<class T> GUINT gim_hash_table< T >::insert_override (GUINT hashkey, const T & element) [inline]
Insert an element into the hash, and could overrite an existing object with the same hash.
Returns: If GIM_INVALID_HASH, the object has been inserted succesfully. Else it returns the position of the replaced element.
Definition at line 869 of file gim_hash_table.h.
References gim_hash_table< T >::_insert_hash_table_replace(), gim_hash_table< T >::_insert_unsorted(), gim_hash_table< T >::m_hash_table, and gim_hash_table< T >::m_nodes.
870     {
871         if(m_hash_table)
872         {
873             return this->_insert_hash_table_replace(hashkey,element);
874         }
875         if(this->is_sorted())
876         {
877             return this->_insert_sorted_replace(hashkey,element);
878         }
879         this->_insert_unsorted(hashkey,element);
880         return m_nodes.size();
881     }
The documentation for this class was generated from the following file:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/Gimpact/gim_hash_table.h