Shader Class Reference
Basic shader class.
#include <Shader.h>
Public Member Functions
Shader ()
Default constructor.
~Shader ()
Destructor.
std::string LoadShaderFile (std::string filePath)
Loads the shader from file.
void Initialize (std::string vertShader, std::string fragShader)
Initializes the shader program.
GLint GetVariable (std::string variable)
Gets the uniform variable.
void SetInt (GLint id, int newValue)
Sets uniform value to int.
void SetFloat (GLint id, GLfloat newValue)
Sets uniform value to float.
void SetFloat2 (GLint id, GLfloat v0, GLfloat v1)
Selects uniform value to be changed.
void SetFloat3 (GLint id, GLfloat v0, GLfloat v1, GLfloat v2)
Selects uniform value to be changed.
void SetFloat4 (GLint id, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3)
Selects uniform value to be changed.
void SetMatrix4 (GLint id, GLsizei count, GLboolean transpose, const GLfloat *value)
Selects uniform value to be changed.
void TurnOn ()
Turns shader on.
void TurnOff ()
Turns shader off.
void Destroy ()
Destroys any linked shaders.
Protected Attributes
GLuint m_vertexShaderId
Stores vertex shader information.
GLuint m_fragmentShaderId
Stores fragment shader information.
GLuint m_shaderProgramId
Stores the program information.
Detailed Description
Basic shader class.
This shader class is used to load and store our shader information as well as initialize the shaders with OpenGL.
Version: 01
Date: 29/03/2018
Version: 02
Date: 31/05/2018
Definition at line 29 of file Shader.h.
Constructor & Destructor Documentation
Shader::Shader () [inline]
Default constructor.
This is the default constuctor that is empyty.
Returns: null
Definition at line 39 of file Shader.h.
39 { }
Shader::~Shader () [inline]
Destructor.
The destructor calls destroy that will free up any used memory.
Returns: null
Definition at line 48 of file Shader.h.
References Destroy().
48 { Destroy(); }
Member Function Documentation
std::string Shader::LoadShaderFile (std::string filePath)
Loads the shader from file.
The function takes the file path given as a string parameter, opens up a file stream to read the file and stores the file as a string in a local variable that is then returned. It is used to read int and store the Vertex and Fragment shaders.
Parameters:
std::string filePath
Returns: std::string
Definition at line 3 of file Shader.cpp.
4 {
5         std::ifstream fin(filePath.c_str());
6 
7         if ( !fin )
8                 return "";
9 
10         std::string strLine = "";
11         std::string strText = "";
12 
13         while ( getline(fin, strLine) )
14         {
15                 strText = strText + "\n" + strLine;
16         }
17         fin.close();
18 
19         return strText;
20 }
void Shader::Initialize (std::string vertShader, std::string fragShader)
Initializes the shader program.
This function takes the vertex and fragment shaders given as string parameters and creates both shdaders using glCreateShader(). The shader source is then set and assiged to their respected ids. The shader program is created and assigned to the m_shaderProgramId member variable and the two shaders are attached to this program. The program is then linked and it runs a check for any GL errors.
Returns: void
Definition at line 22 of file Shader.cpp.
References Destroy(), m_fragmentShaderId, m_shaderProgramId, and m_vertexShaderId.
Referenced by OpenGl::Prepare().
23 {
24         std::string vShaderStr, fShaderStr;
25 
26         if ( !strVertexFile.length() || !strFragmentFile.length() )
27                 return;
28 
29         if ( m_vertexShaderId || m_fragmentShaderId || m_shaderProgramId )
30                 Destroy();
31 
32         GLenum ErrorCheckValue = glGetError();
33 
34         // Assign VS and FS ids
35         m_vertexShaderId = glCreateShader(GL_VERTEX_SHADER);
36         m_fragmentShaderId = glCreateShader(GL_FRAGMENT_SHADER);
37 
38         vShaderStr = strVertexFile.c_str();
39         fShaderStr = strFragmentFile.c_str();
40 
41         const char *szVShader = vShaderStr.c_str();
42         const char *szFShader = fShaderStr.c_str();
43 
44         glShaderSource(m_vertexShaderId, 1, &szVShader, nullptr);
45         glShaderSource(m_fragmentShaderId, 1, &szFShader, nullptr);
46         
47         // Compile shaders
48         glCompileShader(m_vertexShaderId);
49         glCompileShader(m_fragmentShaderId);
50 
51         // Create shader program
52         m_shaderProgramId = glCreateProgram();
53 
54         // Attach shdaers to program
55         glAttachShader(m_shaderProgramId, m_vertexShaderId);
56         glAttachShader(m_shaderProgramId, m_fragmentShaderId);
57 
58         // Link our program with OpenGL
59         glLinkProgram(m_shaderProgramId);
60 
61         ErrorCheckValue = glGetError();
62 
63         if ( ErrorCheckValue != GL_NO_ERROR )
64         {
65                 std::cout << "ERROR: Could not create the shader program with error Id: " << ErrorCheckValue << std::endl;
66                 exit(-1);
67         }
68 }
GLint Shader::GetVariable (std::string variable)
Gets the uniform variable.
Returns an ID with the same name as the string parameter in the shader.
Parameters:
std::string variable
Returns: GLint
Definition at line 70 of file Shader.cpp.
References m_shaderProgramId.
Referenced by OpenGl::Render().
71 {
72         if(!m_shaderProgramId)
73                 return -1;
74 
75         return glGetUniformLocation(m_shaderProgramId, strVariable.c_str());
76 }
void Shader::SetInt (GLint id, int newValue) [inline]
Sets uniform value to int.
Calls glUniform1i() taking the id associated to the shader variable and changing it to the new value set by the second parameter given.
Parameters:
GLint id
int newValue
Returns: void
Definition at line 97 of file Shader.h.
97 { glUniform1i(id, newValue); }
void Shader::SetFloat (GLint id, GLfloat newValue) [inline]
Sets uniform value to float.
Calls glUniform1f() taking the id associated to the shader variable and changing it to the new value set by the second parameter given.
Parameters:
GLint id
GLfloat newValue
Returns: void
Definition at line 109 of file Shader.h.
Referenced by OpenGl::Render().
109 { glUniform1f(id, newValue); }
void Shader::SetFloat2 (GLint id, GLfloat v0, GLfloat v1) [inline]
Selects uniform value to be changed.
Calls glUniform2f() taking the id associated to the shader variable and changing the value according to the GLfloat parameters specified.
Parameters:
GLint id
GLfloat v0
GLfloat v1
Returns: void
Definition at line 122 of file Shader.h.
122 { glUniform2f(id, v0, v1); }
void Shader::SetFloat3 (GLint id, GLfloat v0, GLfloat v1, GLfloat v2) [inline]
Selects uniform value to be changed.
Calls glUniform3f() taking the id associated to the shader variable and changing the value according to the GLfloat parameters specified.
Parameters:
GLint id
GLfloat v0
GLfloat v1
GLfloat v2
Returns: void
Definition at line 136 of file Shader.h.
136 { glUniform3f(id, v0, v1, v2);  }
void Shader::SetFloat4 (GLint id, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) [inline]
Selects uniform value to be changed.
Calls glUniform4f() taking the id associated to the shader variable and changing the value according to the GLfloat parameters specified.
Parameters:
GLint id
GLfloat v0
GLfloat v1
GLfloat v2
GLfloat v3
Returns: void
Definition at line 151 of file Shader.h.
151 { glUniform4f(id, v0, v1, v2, v3); }
void Shader::SetMatrix4 (GLint id, GLsizei count, GLboolean transpose, const GLfloat * value) [inline]
Selects uniform value to be changed.
Calls glUniformMatrix4fv() taking the id associated to the shader variable and passing a 4x4 matrix of size 16 bytes (4 floats).
Parameters:
GLint id
GLsizei count
GLboolean transpose
const GLfloat* value
Returns: void
Definition at line 165 of file Shader.h.
Referenced by OpenGl::Render().
165 { glUniformMatrix4fv(id, count, transpose, value); }
void Shader::TurnOn () [inline]
Turns shader on.
Calls glUseProgram() turning the shader on.
Returns: void
Definition at line 174 of file Shader.h.
References m_shaderProgramId.
Referenced by OpenGl::Render().
174 {       glUseProgram(m_shaderProgramId); }
void Shader::TurnOff () [inline]
Turns shader off.
Calls glUseProgram(0) turning the shader off.
Returns: void
Definition at line 183 of file Shader.h.
Referenced by OpenGl::Render().
183 { glUseProgram(0); }
void Shader::Destroy ()
Destroys any linked shaders.
Detatches and deletes the shader information. Sets the m_vertexShaderId, m_fragmentShaderId and m_shaderProgramId to 0.
Returns: void
Definition at line 78 of file Shader.cpp.
References m_fragmentShaderId, m_shaderProgramId, and m_vertexShaderId.
Referenced by Initialize(), and ~Shader().
79 {
80         if(m_vertexShaderId)
81         {
82                 glDetachShader(m_shaderProgramId, m_vertexShaderId);
83                 glDeleteShader(m_vertexShaderId);
84                 m_vertexShaderId = 0;
85         }
86 
87         if(m_fragmentShaderId)
88         {
89                 glDetachShader(m_shaderProgramId, m_fragmentShaderId);
90                 glDeleteShader(m_fragmentShaderId);
91                 m_fragmentShaderId = 0;
92         }
93 
94         if(m_shaderProgramId)
95         {
96                 glDeleteShader(m_shaderProgramId);
97                 m_shaderProgramId = 0;
98         }
99 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/headers/Shader.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/src/Shader.cpp