TextureManager Class Reference
Texture manager class that handles the loading, storing, and managing of all textures.
#include <TextureManager.h>
Public Member Functions
bool SetActiveTexture (unsigned int texID)
Activate a texture.
int LoadTexture (std::string filename)
Load a texture.
void AddTextureToMap (std::string filename, int texID)
Add a texture to the map.
int GetTextureID (std::string filename)
Return a texture.
void ReleaseAllTextures ()
Release all textures.
int TexLoaded (std::string filePath)
Find out if texture is loaded.
Static Public Member Functions
static TextureManager & Instance ()
Singleton instance.
Protected Attributes
int m_width
Width of texture loaded.
int m_height
Height of texture loaded.
Detailed Description
Texture manager class that handles the loading, storing, and managing of all textures.
Author: Jack Matters
Date: 03/07/2018
Version: 1.0 Initial start. Created the layout of the class, using a singleton and the SOIL API.
Date: 07/07/2018
Version: 1.1 Changed from SOIL to SOIL2, as SOIL was deprecated. Got file loading and storing in map working. Next to work on is a better system for loading files (from lua), and using the loaded in textures.
Date: 10/07/2018
Version: 1.2 Added a few more useful functions, and some tidy up.
Date: 17/07/2018
Version: 1.3 Altered LoadTexture to check to see if texture is already in map before loading the texture. Also added an function to help with that check.
Date: 31/05/2018
Version: 2.0 Final version for submission.
Definition at line 45 of file TextureManager.h.
Member Function Documentation
static TextureManager& TextureManager::Instance () [inline, static]
Singleton instance.
This function returns a singleton instance of the texture manager class so that there is only one instance of a texture manager.
Returns: static TextureManager&
Definition at line 57 of file TextureManager.h.
Referenced by ScriptManager::LoadTexturesInitLua().
58                 {
59                         static TextureManager instance;
60 
61                         return instance;
62                 }
bool TextureManager::SetActiveTexture (unsigned int texID)
Activate a texture.
Sets the given texture to be active
Parameters:
texID - Texture to set active
Returns: bool - True
Definition at line 23 of file TextureManager.cpp.
24 {
25         // Enable and bind the passed in texture
26         glEnable(GL_TEXTURE_2D);
27         glBindTexture(GL_TEXTURE_2D, texID);
28 
29         return true;
30 }
int TextureManager::LoadTexture (std::string filename)
Load a texture.
Load a texture from file using the SOIL API
Parameters:
filename - Name of file to load
Returns: int - texID (given ID of loaded texture)
Definition at line 33 of file TextureManager.cpp.
References AddTextureToMap(), m_height, m_width, and TexLoaded().
Referenced by GetTextureID(), and ScriptManager::LoadTexturesInitLua().
34 {
35         // Check to see if texture is already loaded and in map, and return texID if true
36         if (TexLoaded(filePath) != 0)
37         {
38                 std::cout << "File already loaded: " << filePath << std::endl;
39                 return TexLoaded(filePath);
40         }
41 
42         // Load in the file
43         //GLuint newTex = SOIL_load_OGL_texture
44         //(
45         //      file,
46         //      SOIL_LOAD_AUTO,
47         //      SOIL_CREATE_NEW_ID,
48         //      SOIL_FLAG_INVERT_Y | SOIL_FLAG_COMPRESS_TO_DXT | SOIL_FLAG_DDS_LOAD_DIRECT
49         //);
50 
52         //if (newTex == 0)
53         //{
54         //      std::cout << "SOIL loading error: " << filename << " - " << SOIL_last_result() << std::endl;
55         //      return -1;
56         //}
57 
58         // Generate a new texID
59         GLuint newTex;
60         glGenTextures(1, &newTex);
61 
62         int width, height, nrComponents;
63         unsigned char* data = stbi_load(filePath.c_str(), &width, &height, &nrComponents, 0);
64         if (data)
65         {
66                 GLenum format;
67                 if (nrComponents == 1)
68                         format = GL_RED;
69                 else if (nrComponents == 3)
70                         format = GL_RGB;
71                 else if (nrComponents == 4)
72                         format = GL_RGBA;
73 
74                 m_width = width;
75                 m_height = height;
76 
77                 // Bind the texture
78                 glBindTexture(GL_TEXTURE_2D, newTex);
79                 glTexImage2D(GL_TEXTURE_2D, 0, format, width, height, 0, format, GL_UNSIGNED_BYTE, data);
80                 glGenerateMipmap(GL_TEXTURE_2D);
81 
82                 glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
83                 glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
84                 glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
85                 glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
86 
87                 stbi_image_free(data);
88 
89                 // Increment number of textures and return ID
90                 m_numTextures++;
91                 std::cout << "Successfully added Texture. Texture Count = " << m_numTextures << std::endl;
92         }
93         else
94         {
95                 std::cout << "Texture failed to load: " << filePath << std::endl;
96                 stbi_image_free(data);
97         }
98 
99         // Add new texture to make
100         AddTextureToMap(filePath, newTex);
101 
102         return newTex;
103 }
void TextureManager::AddTextureToMap (std::string filename, int texID)
Add a texture to the map.
Adds a texture that is loaded into the map for storing and later access
Parameters:
filename - Name of file loaded
texID - ID of texture
Returns: void
Definition at line 106 of file TextureManager.cpp.
Referenced by LoadTexture().
107 {
108         // If loaded texture is not already in map, load it
109         if (!m_textureMap[filename])
110         {
111                 m_textureMap[filename] = texID;
112         }
113 }
int TextureManager::GetTextureID (std::string filename)
Return a texture.
Returns a texture ID to be used
Parameters:
filename - Name of texture file to be returned
Returns: int - texID (given ID and requested texture)
Definition at line 116 of file TextureManager.cpp.
References LoadTexture().
117 {
118         // Get iterator to start of map
119         std::unordered_map<std::string, unsigned int>::iterator it = m_textureMap.begin();
120 
121         // Search map for texture
122         while (it != m_textureMap.end())
123         {
124                 // If texture found, return the given ID
125                 if ((*it).first == filename)
126                 {
127                         return (*it).second;
128                 }
129 
130                 // Increment iterator
131                 it++;
132         }
133 
134         // If texture is not in map, load it in and add to map
135         int texID = LoadTexture(filename);
136 
137         // Return texture ID
138         return texID;
139 }
void TextureManager::ReleaseAllTextures ()
Release all textures.
Releases all textures from memory (called in de-constructor
Returns: void
Definition at line 142 of file TextureManager.cpp.
143 {
144         // Get iterator to start of map
145         std::unordered_map<std::string, unsigned int>::iterator it = m_textureMap.begin();
146 
147         // Loop through map, unloading all textures from map
148         while (it != m_textureMap.end())
149         {
150                 std::cout << "unloading Texture: " << (*it).first << ", ID: " << (*it).second;
151                 glDeleteTextures(1, &(*it).second);
152                 std::cout << " ... done" << std::endl;
153                 ++it;
154         }
155 
156         // Clear the map
157         m_textureMap.clear();
158 }
int TextureManager::TexLoaded (std::string filePath)
Find out if texture is loaded.
Checks map to see if a texture is already loaded, prior to loading it
Parameters:
filePath - File path of texture
Returns: int - texID of loaded texture, or 0 if not in map
Definition at line 161 of file TextureManager.cpp.
Referenced by LoadTexture().
162 {
163         // Get iterator to start of map
164         std::unordered_map<std::string, unsigned int>::iterator it = m_textureMap.begin();
165 
166         // Search map for texture
167         while (it != m_textureMap.end())
168         {
169                 // If texture found, return true
170                 if ((*it).first == filePath)
171                 {
172                         return (*it).second;;
173                 }
174 
175                 // Increment iterator
176                 it++;
177         }
178 
179         // If texture not found, return 0
180         return 0;
181 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/headers/TextureManager.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/src/TextureManager.cpp