btQuaternion Class Reference
The btQuaternion implements quaternion to perform linear algebra rotations in combination with btMatrix3x3, btVector3 and btTransform.
#include <btQuaternion.h>
Public Member Functions
btQuaternion ()
No initialization constructor.
btQuaternion (const btScalar &_x, const btScalar &_y, const btScalar &_z, const btScalar &_w)
Constructor from scalars.
btQuaternion (const btVector3 &_axis, const btScalar &_angle)
Axis angle Constructor.
btQuaternion (const btScalar &yaw, const btScalar &pitch, const btScalar &roll)
Constructor from Euler angles.
void setRotation (const btVector3 &axis, const btScalar &_angle)
Set the rotation using axis angle notation.
void setEuler (const btScalar &yaw, const btScalar &pitch, const btScalar &roll)
Set the quaternion using Euler angles.
void setEulerZYX (const btScalar &yawZ, const btScalar &pitchY, const btScalar &rollX)
Set the quaternion using euler angles.
void getEulerZYX (btScalar &yawZ, btScalar &pitchY, btScalar &rollX) const
Get the euler angles from this quaternion.
SIMD_FORCE_INLINE btQuaternion & operator+= (const btQuaternion &q)
Add two quaternions.
btQuaternion & operator-= (const btQuaternion &q)
Subtract out a quaternion.
btQuaternion & operator*= (const btScalar &s)
Scale this quaternion.
btQuaternion & operator*= (const btQuaternion &q)
Multiply this quaternion by q on the right.
btScalar dot (const btQuaternion &q) const
Return the dot product between this quaternion and another.
btScalar length2 () const
Return the length squared of the quaternion.
btScalar length () const
Return the length of the quaternion.
btQuaternion & normalize ()
Normalize the quaternion Such that x^2 + y^2 + z^2 +w^2 = 1.
SIMD_FORCE_INLINE btQuaternion operator* (const btScalar &s) const
Return a scaled version of this quaternion.
btQuaternion operator/ (const btScalar &s) const
Return an inversely scaled versionof this quaternion.
btQuaternion & operator/= (const btScalar &s)
Inversely scale this quaternion.
btQuaternion normalized () const
Return a normalized version of this quaternion.
btScalar angle (const btQuaternion &q) const
Return the ***half*** angle between this quaternion and the other.
btScalar angleShortestPath (const btQuaternion &q) const
Return the angle between this quaternion and the other along the shortest path.
btScalar getAngle () const
Return the angle [0, 2Pi] of rotation represented by this quaternion.
btScalar getAngleShortestPath () const
Return the angle [0, Pi] of rotation represented by this quaternion along the shortest path.
btVector3 getAxis () const
Return the axis of the rotation represented by this quaternion.
btQuaternion inverse () const
Return the inverse of this quaternion.
SIMD_FORCE_INLINE btQuaternion operator+ (const btQuaternion &q2) const
Return the sum of this quaternion and the other.
SIMD_FORCE_INLINE btQuaternion operator- (const btQuaternion &q2) const
Return the difference between this quaternion and the other.
SIMD_FORCE_INLINE btQuaternion operator- () const
Return the negative of this quaternion This simply negates each element.
SIMD_FORCE_INLINE btQuaternion farthest (const btQuaternion &qd) const
SIMD_FORCE_INLINE btQuaternion nearest (const btQuaternion &qd) const
btQuaternion slerp (const btQuaternion &q, const btScalar &t) const
Return the quaternion which is the result of Spherical Linear Interpolation between this and the other quaternion.
SIMD_FORCE_INLINE void serialize (struct btQuaternionData &dataOut) const
SIMD_FORCE_INLINE void serializeFloat (struct btQuaternionFloatData &dataOut) const
SIMD_FORCE_INLINE void serializeDouble (struct btQuaternionDoubleData &dataOut) const
Detailed Description
The btQuaternion implements quaternion to perform linear algebra rotations in combination with btMatrix3x3, btVector3 and btTransform.
Definition at line 55 of file btQuaternion.h.
Constructor & Destructor Documentation
btQuaternion::btQuaternion (const btVector3 & _axis, const btScalar & _angle) [inline]
Axis angle Constructor.
Parameters:
axis The axis which the rotation is around
angle The magnitude of the rotation around the angle (Radians)
Definition at line 93 of file btQuaternion.h.
References setRotation().
94         { 
95                 setRotation(_axis, _angle); 
96         }
btQuaternion::btQuaternion (const btScalar & yaw, const btScalar & pitch, const btScalar & roll) [inline]
Constructor from Euler angles.
Parameters:
yaw Angle around Y unless BT_EULER_DEFAULT_ZYX defined then Z
pitch Angle around X unless BT_EULER_DEFAULT_ZYX defined then Y
roll Angle around Z unless BT_EULER_DEFAULT_ZYX defined then X
Definition at line 101 of file btQuaternion.h.
References setEuler(), and setEulerZYX().
102         { 
103 #ifndef BT_EULER_DEFAULT_ZYX
104                 setEuler(yaw, pitch, roll); 
105 #else
106                 setEulerZYX(yaw, pitch, roll); 
107 #endif 
108         }
Member Function Documentation
void btQuaternion::setRotation (const btVector3 & axis, const btScalar & _angle) [inline]
Set the rotation using axis angle notation.
Parameters:
axis The axis around which to rotate
angle The magnitude of the rotation in Radians
Definition at line 112 of file btQuaternion.h.
Referenced by btQuaternion().
113         {
114                 btScalar d = axis.length();
115                 btAssert(d != btScalar(0.0));
116                 btScalar s = btSin(_angle * btScalar(0.5)) / d;
117                 setValue(axis.x() * s, axis.y() * s, axis.z() * s, 
118                         btCos(_angle * btScalar(0.5)));
119         }
void btQuaternion::setEuler (const btScalar & yaw, const btScalar & pitch, const btScalar & roll) [inline]
Set the quaternion using Euler angles.
Parameters:
yaw Angle around Y
pitch Angle around X
roll Angle around Z
Definition at line 124 of file btQuaternion.h.
Referenced by btQuaternion().
125         {
126                 btScalar halfYaw = btScalar(yaw) * btScalar(0.5);  
127                 btScalar halfPitch = btScalar(pitch) * btScalar(0.5);  
128                 btScalar halfRoll = btScalar(roll) * btScalar(0.5);  
129                 btScalar cosYaw = btCos(halfYaw);
130                 btScalar sinYaw = btSin(halfYaw);
131                 btScalar cosPitch = btCos(halfPitch);
132                 btScalar sinPitch = btSin(halfPitch);
133                 btScalar cosRoll = btCos(halfRoll);
134                 btScalar sinRoll = btSin(halfRoll);
135                 setValue(cosRoll * sinPitch * cosYaw + sinRoll * cosPitch * sinYaw,
136                         cosRoll * cosPitch * sinYaw - sinRoll * sinPitch * cosYaw,
137                         sinRoll * cosPitch * cosYaw - cosRoll * sinPitch * sinYaw,
138                         cosRoll * cosPitch * cosYaw + sinRoll * sinPitch * sinYaw);
139         }
void btQuaternion::setEulerZYX (const btScalar & yawZ, const btScalar & pitchY, const btScalar & rollX) [inline]
Set the quaternion using euler angles.
Parameters:
yaw Angle around Z
pitch Angle around Y
roll Angle around X
Definition at line 144 of file btQuaternion.h.
Referenced by btQuaternion().
145         {
146                 btScalar halfYaw = btScalar(yawZ) * btScalar(0.5);  
147                 btScalar halfPitch = btScalar(pitchY) * btScalar(0.5);  
148                 btScalar halfRoll = btScalar(rollX) * btScalar(0.5);  
149                 btScalar cosYaw = btCos(halfYaw);
150                 btScalar sinYaw = btSin(halfYaw);
151                 btScalar cosPitch = btCos(halfPitch);
152                 btScalar sinPitch = btSin(halfPitch);
153                 btScalar cosRoll = btCos(halfRoll);
154                 btScalar sinRoll = btSin(halfRoll);
155                 setValue(sinRoll * cosPitch * cosYaw - cosRoll * sinPitch * sinYaw, //x
156                          cosRoll * sinPitch * cosYaw + sinRoll * cosPitch * sinYaw, //y
157                          cosRoll * cosPitch * sinYaw - sinRoll * sinPitch * cosYaw, //z
158                          cosRoll * cosPitch * cosYaw + sinRoll * sinPitch * sinYaw); //formerly yzx
159         }
void btQuaternion::getEulerZYX (btScalar & yawZ, btScalar & pitchY, btScalar & rollX) const [inline]
Get the euler angles from this quaternion.
Parameters:
yaw Angle around Z
pitch Angle around Y
roll Angle around X
Definition at line 165 of file btQuaternion.h.
166         {
167                 btScalar squ;
168                 btScalar sqx;
169                 btScalar sqy;
170                 btScalar sqz;
171                 btScalar sarg;
172                 sqx = m_floats[0] * m_floats[0];
173                 sqy = m_floats[1] * m_floats[1];
174                 sqz = m_floats[2] * m_floats[2];
175                 squ = m_floats[3] * m_floats[3];
176                 rollX = btAtan2(2 * (m_floats[1] * m_floats[2] + m_floats[3] * m_floats[0]), squ - sqx - sqy + sqz);
177                 sarg = btScalar(-2.) * (m_floats[0] * m_floats[2] - m_floats[3] * m_floats[1]);
178                 pitchY = sarg <= btScalar(-1.0) ? btScalar(-0.5) * SIMD_PI: (sarg >= btScalar(1.0) ? btScalar(0.5) * SIMD_PI : btAsin(sarg));
179                 yawZ = btAtan2(2 * (m_floats[0] * m_floats[1] + m_floats[3] * m_floats[2]), squ + sqx - sqy - sqz);
180         }
SIMD_FORCE_INLINE btQuaternion& btQuaternion::operator+= (const btQuaternion & q) [inline]
Add two quaternions.
Parameters:
q The quaternion to add to this one
Definition at line 184 of file btQuaternion.h.
185         {
186 #if defined (BT_USE_SSE_IN_API) && defined (BT_USE_SSE)
187                 mVec128 = _mm_add_ps(mVec128, q.mVec128);
188 #elif defined(BT_USE_NEON)
189                 mVec128 = vaddq_f32(mVec128, q.mVec128);
190 #else   
191                 m_floats[0] += q.x(); 
192         m_floats[1] += q.y(); 
193         m_floats[2] += q.z(); 
194         m_floats[3] += q.m_floats[3];
195 #endif
196                 return *this;
197         }
btQuaternion& btQuaternion::operator-= (const btQuaternion & q) [inline]
Subtract out a quaternion.
Parameters:
q The quaternion to subtract from this one
Definition at line 201 of file btQuaternion.h.
202         {
203 #if defined (BT_USE_SSE_IN_API) && defined (BT_USE_SSE)
204                 mVec128 = _mm_sub_ps(mVec128, q.mVec128);
205 #elif defined(BT_USE_NEON)
206                 mVec128 = vsubq_f32(mVec128, q.mVec128);
207 #else   
208                 m_floats[0] -= q.x(); 
209         m_floats[1] -= q.y(); 
210         m_floats[2] -= q.z(); 
211         m_floats[3] -= q.m_floats[3];
212 #endif
213         return *this;
214         }
btQuaternion& btQuaternion::operator*= (const btScalar & s) [inline]
Scale this quaternion.
Parameters:
s The scalar to scale by
Definition at line 218 of file btQuaternion.h.
219         {
220 #if defined (BT_USE_SSE_IN_API) && defined (BT_USE_SSE)
221                 __m128  vs = _mm_load_ss(&s);   //      (S 0 0 0)
222                 vs = bt_pshufd_ps(vs, 0);       //      (S S S S)
223                 mVec128 = _mm_mul_ps(mVec128, vs);
224 #elif defined(BT_USE_NEON)
225                 mVec128 = vmulq_n_f32(mVec128, s);
226 #else
227                 m_floats[0] *= s; 
228         m_floats[1] *= s; 
229         m_floats[2] *= s; 
230         m_floats[3] *= s;
231 #endif
232                 return *this;
233         }
btQuaternion& btQuaternion::operator*= (const btQuaternion & q) [inline]
Multiply this quaternion by q on the right.
Parameters:
q The other quaternion Equivilant to this = this * q
Definition at line 238 of file btQuaternion.h.
239         {
240 #if defined (BT_USE_SSE_IN_API) && defined (BT_USE_SSE)
241                 __m128 vQ2 = q.get128();
242                 
243                 __m128 A1 = bt_pshufd_ps(mVec128, BT_SHUFFLE(0,1,2,0));
244                 __m128 B1 = bt_pshufd_ps(vQ2, BT_SHUFFLE(3,3,3,0));
245                 
246                 A1 = A1 * B1;
247                 
248                 __m128 A2 = bt_pshufd_ps(mVec128, BT_SHUFFLE(1,2,0,1));
249                 __m128 B2 = bt_pshufd_ps(vQ2, BT_SHUFFLE(2,0,1,1));
250                 
251                 A2 = A2 * B2;
252                 
253                 B1 = bt_pshufd_ps(mVec128, BT_SHUFFLE(2,0,1,2));
254                 B2 = bt_pshufd_ps(vQ2, BT_SHUFFLE(1,2,0,2));
255                 
256                 B1 = B1 * B2;   //      A3 *= B3
257                 
258                 mVec128 = bt_splat_ps(mVec128, 3);      //      A0
259                 mVec128 = mVec128 * vQ2;        //      A0 * B0
260                 
261                 A1 = A1 + A2;   //      AB12
262                 mVec128 = mVec128 - B1; //      AB03 = AB0 - AB3 
263                 A1 = _mm_xor_ps(A1, vPPPM);     //      change sign of the last element
264                 mVec128 = mVec128+ A1;  //      AB03 + AB12
265 
266 #elif defined(BT_USE_NEON)     
267 
268         float32x4_t vQ1 = mVec128;
269         float32x4_t vQ2 = q.get128();
270         float32x4_t A0, A1, B1, A2, B2, A3, B3;
271         float32x2_t vQ1zx, vQ2wx, vQ1yz, vQ2zx, vQ2yz, vQ2xz;
272         
273         {
274         float32x2x2_t tmp;
275         tmp = vtrn_f32( vget_high_f32(vQ1), vget_low_f32(vQ1) );       // {z x}, {w y}
276         vQ1zx = tmp.val[0];
277 
278         tmp = vtrn_f32( vget_high_f32(vQ2), vget_low_f32(vQ2) );       // {z x}, {w y}
279         vQ2zx = tmp.val[0];
280         }
281         vQ2wx = vext_f32(vget_high_f32(vQ2), vget_low_f32(vQ2), 1); 
282 
283         vQ1yz = vext_f32(vget_low_f32(vQ1), vget_high_f32(vQ1), 1);
284 
285         vQ2yz = vext_f32(vget_low_f32(vQ2), vget_high_f32(vQ2), 1);
286         vQ2xz = vext_f32(vQ2zx, vQ2zx, 1);
287 
288         A1 = vcombine_f32(vget_low_f32(vQ1), vQ1zx);                    // X Y  z x 
289         B1 = vcombine_f32(vdup_lane_f32(vget_high_f32(vQ2), 1), vQ2wx); // W W  W X 
290 
291         A2 = vcombine_f32(vQ1yz, vget_low_f32(vQ1));
292         B2 = vcombine_f32(vQ2zx, vdup_lane_f32(vget_low_f32(vQ2), 1));
293 
294         A3 = vcombine_f32(vQ1zx, vQ1yz);        // Z X Y Z
295         B3 = vcombine_f32(vQ2yz, vQ2xz);        // Y Z x z
296 
297         A1 = vmulq_f32(A1, B1);
298         A2 = vmulq_f32(A2, B2);
299         A3 = vmulq_f32(A3, B3); //      A3 *= B3
300         A0 = vmulq_lane_f32(vQ2, vget_high_f32(vQ1), 1); //     A0 * B0
301 
302         A1 = vaddq_f32(A1, A2); //      AB12 = AB1 + AB2
303         A0 = vsubq_f32(A0, A3); //      AB03 = AB0 - AB3 
304         
305         //      change the sign of the last element
306         A1 = (btSimdFloat4)veorq_s32((int32x4_t)A1, (int32x4_t)vPPPM);  
307         A0 = vaddq_f32(A0, A1); //      AB03 + AB12
308         
309         mVec128 = A0;
310 #else
311                 setValue(
312             m_floats[3] * q.x() + m_floats[0] * q.m_floats[3] + m_floats[1] * q.z() - m_floats[2] * q.y(),
313                         m_floats[3] * q.y() + m_floats[1] * q.m_floats[3] + m_floats[2] * q.x() - m_floats[0] * q.z(),
314                         m_floats[3] * q.z() + m_floats[2] * q.m_floats[3] + m_floats[0] * q.y() - m_floats[1] * q.x(),
315                         m_floats[3] * q.m_floats[3] - m_floats[0] * q.x() - m_floats[1] * q.y() - m_floats[2] * q.z());
316 #endif
317                 return *this;
318         }
btScalar btQuaternion::dot (const btQuaternion & q) const [inline]
Return the dot product between this quaternion and another.
Parameters:
q The other quaternion
Definition at line 321 of file btQuaternion.h.
Referenced by angle(), angleShortestPath(), farthest(), length2(), nearest(), and slerp().
322         {
323 #if defined BT_USE_SIMD_VECTOR3 && defined (BT_USE_SSE_IN_API) && defined (BT_USE_SSE)
324                 __m128  vd;
325                 
326                 vd = _mm_mul_ps(mVec128, q.mVec128);
327                 
328         __m128 t = _mm_movehl_ps(vd, vd);
329                 vd = _mm_add_ps(vd, t);
330                 t = _mm_shuffle_ps(vd, vd, 0x55);
331                 vd = _mm_add_ss(vd, t);
332                 
333         return _mm_cvtss_f32(vd);
334 #elif defined(BT_USE_NEON)
335                 float32x4_t vd = vmulq_f32(mVec128, q.mVec128);
336                 float32x2_t x = vpadd_f32(vget_low_f32(vd), vget_high_f32(vd));  
337                 x = vpadd_f32(x, x);
338                 return vget_lane_f32(x, 0);
339 #else    
340                 return  m_floats[0] * q.x() + 
341                 m_floats[1] * q.y() + 
342                 m_floats[2] * q.z() + 
343                 m_floats[3] * q.m_floats[3];
344 #endif
345         }
SIMD_FORCE_INLINE btQuaternion btQuaternion::operator* (const btScalar & s) const [inline]
Return a scaled version of this quaternion.
Parameters:
s The scale factor
Definition at line 395 of file btQuaternion.h.
References btQuaternion().
396         {
397 #if defined (BT_USE_SSE_IN_API) && defined (BT_USE_SSE)
398                 __m128  vs = _mm_load_ss(&s);   //      (S 0 0 0)
399                 vs = bt_pshufd_ps(vs, 0x00);    //      (S S S S)
400                 
401                 return btQuaternion(_mm_mul_ps(mVec128, vs));
402 #elif defined(BT_USE_NEON)
403                 return btQuaternion(vmulq_n_f32(mVec128, s));
404 #else
405                 return btQuaternion(x() * s, y() * s, z() * s, m_floats[3] * s);
406 #endif
407         }
btQuaternion btQuaternion::operator/ (const btScalar & s) const [inline]
Return an inversely scaled versionof this quaternion.
Parameters:
s The inverse scale factor
Definition at line 411 of file btQuaternion.h.
412         {
413                 btAssert(s != btScalar(0.0));
414                 return *this * (btScalar(1.0) / s);
415         }
btQuaternion& btQuaternion::operator/= (const btScalar & s) [inline]
Inversely scale this quaternion.
Parameters:
s The scale factor
Definition at line 419 of file btQuaternion.h.
420         {
421                 btAssert(s != btScalar(0.0));
422                 return *this *= btScalar(1.0) / s;
423         }
btScalar btQuaternion::angle (const btQuaternion & q) const [inline]
Return the ***half*** angle between this quaternion and the other.
Parameters:
q The other quaternion
Definition at line 432 of file btQuaternion.h.
References dot(), and length2().
433         {
434                 btScalar s = btSqrt(length2() * q.length2());
435                 btAssert(s != btScalar(0.0));
436                 return btAcos(dot(q) / s);
437         }
btScalar btQuaternion::angleShortestPath (const btQuaternion & q) const [inline]
Return the angle between this quaternion and the other along the shortest path.
Parameters:
q The other quaternion
Definition at line 441 of file btQuaternion.h.
References dot(), and length2().
442         {
443                 btScalar s = btSqrt(length2() * q.length2());
444                 btAssert(s != btScalar(0.0));
445                 if (dot(q) < 0) // Take care of long angle case see http://en.wikipedia.org/wiki/Slerp
446                         return btAcos(dot(-q) / s) * btScalar(2.0);
447                 else 
448                         return btAcos(dot(q) / s) * btScalar(2.0);
449         }
SIMD_FORCE_INLINE btQuaternion btQuaternion::operator+ (const btQuaternion & q2) const [inline]
Return the sum of this quaternion and the other.
Parameters:
q2 The other quaternion
Definition at line 496 of file btQuaternion.h.
References btQuaternion().
497         {
498 #if defined (BT_USE_SSE_IN_API) && defined (BT_USE_SSE)
499                 return btQuaternion(_mm_add_ps(mVec128, q2.mVec128));
500 #elif defined(BT_USE_NEON)
501         return btQuaternion(vaddq_f32(mVec128, q2.mVec128));
502 #else   
503                 const btQuaternion& q1 = *this;
504                 return btQuaternion(q1.x() + q2.x(), q1.y() + q2.y(), q1.z() + q2.z(), q1.m_floats[3] + q2.m_floats[3]);
505 #endif
506         }
SIMD_FORCE_INLINE btQuaternion btQuaternion::operator- (const btQuaternion & q2) const [inline]
Return the difference between this quaternion and the other.
Parameters:
q2 The other quaternion
Definition at line 511 of file btQuaternion.h.
References btQuaternion().
512         {
513 #if defined (BT_USE_SSE_IN_API) && defined (BT_USE_SSE)
514                 return btQuaternion(_mm_sub_ps(mVec128, q2.mVec128));
515 #elif defined(BT_USE_NEON)
516         return btQuaternion(vsubq_f32(mVec128, q2.mVec128));
517 #else   
518                 const btQuaternion& q1 = *this;
519                 return btQuaternion(q1.x() - q2.x(), q1.y() - q2.y(), q1.z() - q2.z(), q1.m_floats[3] - q2.m_floats[3]);
520 #endif
521         }
SIMD_FORCE_INLINE btQuaternion btQuaternion::farthest (const btQuaternion & qd) const [inline]
Todo document this and it's use
Definition at line 537 of file btQuaternion.h.
References dot().
538         {
539                 btQuaternion diff,sum;
540                 diff = *this - qd;
541                 sum = *this + qd;
542                 if( diff.dot(diff) > sum.dot(sum) )
543                         return qd;
544                 return (-qd);
545         }
SIMD_FORCE_INLINE btQuaternion btQuaternion::nearest (const btQuaternion & qd) const [inline]
Todo document this and it's use
Definition at line 548 of file btQuaternion.h.
References dot().
549         {
550                 btQuaternion diff,sum;
551                 diff = *this - qd;
552                 sum = *this + qd;
553                 if( diff.dot(diff) < sum.dot(sum) )
554                         return qd;
555                 return (-qd);
556         }
btQuaternion btQuaternion::slerp (const btQuaternion & q, const btScalar & t) const [inline]
Return the quaternion which is the result of Spherical Linear Interpolation between this and the other quaternion.
Parameters:
q The other quaternion to interpolate with
t The ratio between this and q to interpolate. If t = 0 the result is this, if t=1 the result is q. Slerp interpolates assuming constant velocity.
Definition at line 563 of file btQuaternion.h.
References btQuaternion(), dot(), length2(), and glm::sign().
564         {
565 
566                 const btScalar magnitude = btSqrt(length2() * q.length2());
567                 btAssert(magnitude > btScalar(0));
568                 
569                 const btScalar product = dot(q) / magnitude;
570                 const btScalar absproduct = btFabs(product);
571                 
572                 if(absproduct < btScalar(1.0 - SIMD_EPSILON))
573                 {
574                         // Take care of long angle case see http://en.wikipedia.org/wiki/Slerp
575                         const btScalar theta = btAcos(absproduct);
576                         const btScalar d = btSin(theta);
577                         btAssert(d > btScalar(0));
578                         
579                         const btScalar sign = (product < 0) ? btScalar(-1) : btScalar(1);
580                         const btScalar s0 = btSin((btScalar(1.0) - t) * theta) / d;
581                         const btScalar s1 = btSin(sign * t * theta) / d;
582                         
583                         return btQuaternion(
584                                 (m_floats[0] * s0 + q.x() * s1),
585                                 (m_floats[1] * s0 + q.y() * s1),
586                                 (m_floats[2] * s0 + q.z() * s1),
587                                 (m_floats[3] * s0 + q.w() * s1));
588                 }
589                 else
590                 {
591                         return *this;
592                 }
593         }
SIMD_FORCE_INLINE void btQuaternion::serialize (struct btQuaternionData & dataOut) const
could also do a memcpy, check if it is worth it
Definition at line 999 of file btQuaternion.h.
1000 {
1002         for (int i=0;i<4;i++)
1003                 dataOut.m_floats[i] = m_floats[i];
1004 }
SIMD_FORCE_INLINE void btQuaternion::serializeFloat (struct btQuaternionFloatData & dataOut) const
could also do a memcpy, check if it is worth it
Definition at line 971 of file btQuaternion.h.
972 {
974         for (int i=0;i<4;i++)
975                 dataOut.m_floats[i] = float(m_floats[i]);
976 }
SIMD_FORCE_INLINE void btQuaternion::serializeDouble (struct btQuaternionDoubleData & dataOut) const
could also do a memcpy, check if it is worth it
Definition at line 985 of file btQuaternion.h.
986 {
988         for (int i=0;i<4;i++)
989                 dataOut.m_floats[i] = double(m_floats[i]);
990 }
The documentation for this class was generated from the following file:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/LinearMath/btQuaternion.h