Bruteforce Class Reference
Bruteforce terrain generation class.
#include <Bruteforce.h>
Public Member Functions
Bruteforce (float scaleX, float scaleY, float scaleZ)
Constructor.
~Bruteforce ()
Destructor.
virtual void GenerateTerrain (GLuint textureId, std::string textureFilePath) override
Generates the terrain.
bool LoadHeightfield (std::string fileName, const int size)
Loads the heightfield data.
Texture AddTexture (GLuint textureId, std::string filePath)
Adds texture to mesh.
bool Inbounds (int xpos, int zpos)
Checks if inbounds.
float GetHeight (int xpos, int zpos)
Gets the height of the terrain.
unsigned char GetHeightColour (int xpos, int zpos)
Gets the colour at a specific height.
float GetAverageHeight (int xpos, int zpos)
Gets the average height.
Detailed Description
Bruteforce terrain generation class.
This class inherits from the base Terrain class. It procedurally generates a terrain using the bruteforce method.
Author: Cordell Smith
Version: 01
Date: 31/05/2018
Definition at line 17 of file Bruteforce.h.
Constructor & Destructor Documentation
Bruteforce::Bruteforce (float scaleX, float scaleY, float scaleZ)
Constructor.
Parameterised constructor that takes the desired scale of the terrain to be generated. This is how large you want it to be in the X, Y and Z directions.
Parameters:
float scaleX
float scaleY
float scaleZ
Returns: null
Definition at line 3 of file Bruteforce.cpp.
4 {
5         m_scaleX = scaleX;
6         m_scaleY = scaleY;
7         m_scaleZ = scaleZ;
8 }
Bruteforce::~Bruteforce () [inline]
Destructor.
Empty destructor.
Returns: null
Definition at line 40 of file Bruteforce.h.
40 { }
Member Function Documentation
void Bruteforce::GenerateTerrain (GLuint textureId, std::string textureFilePath) [override, virtual]
Generates the terrain.
Takes the heightfield data of the terrain and generates a mesh for it. The two parameters are the textures to be assigned to the terrain for rendering.
Parameters:
GLuint textureId
std::string textureFilePath
Returns: void
Implements Terrain.
Definition at line 10 of file Bruteforce.cpp.
References AddTexture(), GetHeight(), GetHeightColour(), Model::GetMeshBatch(), Model::GetTextures(), Mesh::GetTextures(), Mesh::GetVertices(), and Model::SetScale().
11 {
12         Mesh tempMesh;
13         float colour;
14         float texLeft, texBottom, texTop;
15 
16         for (int z = 0; z < m_heightfieldSize - 1; z++)
17         {
18                 for (int x = 0; x < m_heightfieldSize - 1; x++)
19                 {
20                         Vertex3 vertex;
21 
22                         float tex00 = (float)x / (m_heightfieldSize); // U
23                         float tex01 = (float)z / (m_heightfieldSize); // V
24                         float tex10 = (float)(x + 1) / (m_heightfieldSize);
25                         float tex11 = (float)(z + 1) / (m_heightfieldSize);
26 
27                         // Colour of triangle
28                         colour = (float)GetHeightColour(x, z) / 255;
29                         vertex.m_colour = glm::vec4(colour, colour, colour, 1.0);
30 
31                         // Vertices
32                         vertex.m_position.x = (float)x * m_scaleX;
33                         vertex.m_position.y = GetHeight(x, z);
34                         vertex.m_position.z = (float)z * m_scaleZ;
35 
36                         vertex.m_texCoords.x = tex00;
37                         vertex.m_texCoords.y = tex11;
38                         
39                         tempMesh.GetVertices().push_back(vertex); // 0.0, 1.0, 0.0
40 
41                         vertex.m_position.x = (float)(x + 1) * m_scaleX;
42                         vertex.m_position.y = GetHeight(x + 1, z);
43                         vertex.m_position.z = (float)z * m_scaleZ;
44 
45                         vertex.m_texCoords.x = tex10;
46                         vertex.m_texCoords.y = tex01;
47 
48                         tempMesh.GetVertices().push_back(vertex); // 1.0, 1.0, 0.0
49 
50                         vertex.m_position.x = (float)(x + 1) * m_scaleX;
51                         vertex.m_position.y = GetHeight(x + 1, z + 1);
52                         vertex.m_position.z = (float)(z + 1) * m_scaleZ;
53 
54                         vertex.m_texCoords.x = tex10;
55                         vertex.m_texCoords.y = tex11;
56 
57                         tempMesh.GetVertices().push_back(vertex); // 1.0, 1.0, 1.0
58                         
59                         vertex.m_position.x = (float)x * m_scaleX;
60                         vertex.m_position.y = GetHeight(x, z);
61                         vertex.m_position.z = (float)z * m_scaleZ;
62 
63                         vertex.m_texCoords.x = tex00;
64                         vertex.m_texCoords.y = tex01;
65 
66                         tempMesh.GetVertices().push_back(vertex); // 0.0, 1.0, 0.0
67 
68                         vertex.m_position.x = (float)(x + 1) * m_scaleX;
69                         vertex.m_position.y = GetHeight(x + 1, z + 1);
70                         vertex.m_position.z = (float)(z + 1) * m_scaleZ;
71 
72                         vertex.m_texCoords.x = tex10;
73                         vertex.m_texCoords.y = tex11;
74 
75                         tempMesh.GetVertices().push_back(vertex); // 1.0, 1.0, 1.0
76 
77                         vertex.m_position.x = (float)x * m_scaleX;
78                         vertex.m_position.y = GetHeight(x, z + 1);
79                         vertex.m_position.z = (float)(z + 1) * m_scaleZ;
80 
81                         vertex.m_texCoords.x = tex00;
82                         vertex.m_texCoords.y = tex11;
83                         
84                         tempMesh.GetVertices().push_back(vertex); // 0.0, 1.0, 1.0
85                 }
86         }
87         //tempMesh.SetupMesh();
88         tempMesh.GetTextures().push_back(AddTexture(textureId, textureFilePath));
89         m_terrainModel->GetTextures().push_back(AddTexture(textureId, textureFilePath));
90         m_terrainModel->GetMeshBatch().push_back(tempMesh);
91         m_terrainModel->SetScale(glm::vec3(1.0, 1.0, 1.0));
92 }
bool Bruteforce::LoadHeightfield (std::string fileName, const int size)
Loads the heightfield data.
Takes the relative path to the file that is the .raw image that is to be used for the heightfield data. It also takes the images size which should be a power of 2 (eg. 128x128 or 32x32). Returns true if created successfully, false if not.
Parameters:
std::string fileName
const int size
Returns: bool
Definition at line 105 of file Bruteforce.cpp.
References glm::length().
106 {
107         // Open for binary read, print error if error found
108         std::ifstream infile(fileName.c_str(), std::ios::binary);
109         if (!infile)
110         {
111                 std::cout << "Cannot open file: " << fileName << std::endl;
112                 return false;
113         }
114 
115         // Allocate memory, return false if no size = 0
116         if (m_terrainData)
117                 delete[] m_terrainData;
118         if (size > 0)
119                 m_terrainData = new unsigned char[size * size];
120 
121         // Read in heightfield and get length of file
122         infile.seekg(0, std::ios::end);
123         int length = infile.tellg();
124 
125         // Read data in as a block, cast to char*, set size, and close file
126         infile.seekg(0, std::ios::beg);
127         infile.read(reinterpret_cast<char*>(m_terrainData), length);
128         infile.close();
129         m_heightfieldSize = size;
130         
131         std::cout << "Heightfield Load Successful!" << std::endl;
132         
133         return true;
134 }
Texture Bruteforce::AddTexture (GLuint textureId, std::string filePath)
Adds texture to mesh.
Creates a temporary texture and returns it.
Parameters:
GLuint textureId
std::string filePath
Returns: Texture
Definition at line 94 of file Bruteforce.cpp.
Referenced by GenerateTerrain().
95 {
96         Texture temp;
97 
98         temp.m_id = textureId;
99         temp.m_path = textureFilePath;
100         temp.m_type = "texture_diffuse";
101 
102         return temp;
103 }
bool Bruteforce::Inbounds (int xpos, int zpos)
Checks if inbounds.
Checks if the parameter positions given are within that of the terrain. Returns true if it is, false if not.
Parameters:
int xpos
int ypos
Returns: bool
Definition at line 136 of file Bruteforce.cpp.
Referenced by GetAverageHeight(), GetHeight(), and GetHeightColour().
137 {
138         if ((xpos >= 0 && xpos < m_heightfieldSize * m_scaleX) && (zpos >= 0 && zpos < m_heightfieldSize * m_scaleZ))
139                 return true;
140         else
141                 return false;
142 }
float Bruteforce::GetHeight (int xpos, int zpos)
Gets the height of the terrain.
Returns the height value y of the terrain at the corresponding parameters given x and z values.
Parameters:
int xpos
int ypos
Returns: float
Definition at line 144 of file Bruteforce.cpp.
References Inbounds().
Referenced by GenerateTerrain().
145 {
146         if (Inbounds(xpos, zpos))
147                 return ((float)(m_terrainData[(zpos * m_heightfieldSize) + xpos]) * m_scaleY);
148         else
149                 return ((float)(m_terrainData[(zpos - 1 * m_heightfieldSize) + xpos]) * m_scaleY);
150 }
unsigned char Bruteforce::GetHeightColour (int xpos, int zpos)
Gets the colour at a specific height.
Returns the height value y of the terrain at the corresponding parameters given x and z values to be used in determining the colour of the vertex.
Parameters:
int xpos
int ypos
Returns: unsigned char
Definition at line 152 of file Bruteforce.cpp.
References Inbounds().
Referenced by GenerateTerrain().
153 {
154         if (Inbounds(xpos, zpos))
155         {
156                 return m_terrainData[zpos * m_heightfieldSize + xpos];
157         }
158         return 1;
159 }
float Bruteforce::GetAverageHeight (int xpos, int zpos)
Gets the average height.
Returns the y value of the x and z position parsed in as parameters. This function is used for terrain collision.
Parameters:
int xpos
int ypos
Returns: float
Definition at line 161 of file Bruteforce.cpp.
References Inbounds().
162 {
163         if (Inbounds(xpos, zpos))
164         {
165                 return (float)(m_terrainData[((int)(zpos / m_scaleZ) * m_heightfieldSize + (int)(xpos / m_scaleX))]) * m_scaleY;
166         }
167         return 1;
168 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/AssetFactory/Bruteforce.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/AssetFactory/Bruteforce.cpp