Player Class Reference
Player class data and functionality.
#include <Player.h>
Public Member Functions
Player (std::string assetName)
Constructor.
~Player ()
Destructor.
void LoadFromFilePath (std::string filePath)
Load object from file path.
const void Destroy ()
Destroys the player object.
void MoveForward (float time)
Moves the player forward.
void MoveBackward (float time)
Moves the player backward.
void TurnClock (float time)
Turns the player clockwise.
void TurnAntiClock (float time)
Turns the player anti-clockwise.
const std::string & GetFilePath () const
Gets the file path of the player.
void SetFilePath (const std::string &filePath)
Sets the file path of the player.
void SetCamera (Camera *camera)
Sets the camera object.
glm::vec3 GetPosition () const
Gets the position.
void SetPosition (glm::vec3 position)
Sets the position.
glm::vec3 GetRotation () const
Gets the rotation.
void SetRotation (glm::vec3 rotation)
Sets the rotation.
void SetScale (glm::vec3 scale)
Sets the scale.
float GetMoveSpeed ()
Gets the movement speed.
Model * GetModel ()
Gets the model of the player.
Detailed Description
Player class data and functionality.
The player class represents any character in the game that you can control. It requires its own special class because it may contain attributes that other assets or objects may not such as health or statistics.
Author: Cordell Smith
Version: 01
Date: 31/05/2018
Definition at line 20 of file Player.h.
Constructor & Destructor Documentation
Player::Player (std::string assetName)
Constructor.
This constructor takes the a string as the key to reference the player and sets it to the name member variable. It initializes the model, sets the current move speed to 0, current turn speed to 0, move speed to 30 and turn speed to 0.1.
Returns: null
Definition at line 3 of file Player.cpp.
4 {
5         m_name = playerName;
6         m_playerModel = new Model();
7 
8         m_currentMoveSpeed = 0;
9         m_currentTurnSpeed = 0;
10         m_moveSpeed = 30;
11         m_turnSpeed = 0.1;
12 }
Player::~Player () [inline]
Destructor.
This the empty default destructor.
Returns: null
Definition at line 41 of file Player.h.
41 { }
Member Function Documentation
void Player::LoadFromFilePath (std::string filePath)
Load object from file path.
This function takes a file path as a string parameter to load a file.
Parameters:
std::string filePath
Returns: void
Definition at line 14 of file Player.cpp.
References Model::LoadModel().
15 {
16         m_playerModel->LoadModel(filePath);
17 }
const void Player::Destroy ()
Destroys the player object.
This function deallocates any memory that the player class has used. Used for memory management.
Returns: const void
Definition at line 19 of file Player.cpp.
20 {
21         return void();
22 }
void Player::MoveForward (float time)
Moves the player forward.
Takes the delta time as a parameter (glfwGetTime()) and uses it to calculate the speed at which the player will move. It then adjusts the position of the player in a forward direction for movement.
Returns: void
Definition at line 24 of file Player.cpp.
References glm::cos(), Model::GetPosition(), Model::GetRotation(), Model::SetPosition(), and glm::sin().
25 {
26         m_currentMoveSpeed = m_moveSpeed * time * 15;
27         float dx = m_currentMoveSpeed * glm::sin(m_playerModel->GetRotation().y);
28         float dz = m_currentMoveSpeed * glm::cos(m_playerModel->GetRotation().y);
29 
30         glm::vec3 temp = m_playerModel->GetPosition() + glm::vec3(dx, 0, dz);
31         m_playerModel->SetPosition(temp);
32 }
void Player::MoveBackward (float time)
Moves the player backward.
Takes the delta time as a parameter (glfwGetTime()) and uses it to calculate the speed at which the player will move. It then adjusts the position of the player in a backward direction for movement.
Returns: void
Definition at line 34 of file Player.cpp.
References glm::cos(), Model::GetPosition(), Model::GetRotation(), Model::SetPosition(), and glm::sin().
35 {
36         m_currentMoveSpeed = -m_moveSpeed * time * 15;
37         float dx = m_currentMoveSpeed * glm::sin(m_playerModel->GetRotation().y);
38         float dz = m_currentMoveSpeed * glm::cos(m_playerModel->GetRotation().y);
39 
40         glm::vec3 temp = m_playerModel->GetPosition() + glm::vec3(dx, 0, dz);
41         m_playerModel->SetPosition(temp);
42 }
void Player::TurnClock (float time)
Turns the player clockwise.
Takes the delta time as a parameter (glfwGetTime()) and uses it to calculate the speed at which the player will turn. It then adjusts the rotation of the player in a clockwise direction for movement.
Returns: void
Definition at line 44 of file Player.cpp.
References Model::GetRotation(), and Model::SetRotation().
45 {
46         m_currentTurnSpeed = -m_turnSpeed * time * 10;
47         m_playerModel->SetRotation(glm::vec3(0, m_playerModel->GetRotation().y + m_currentTurnSpeed, 0));
48 }
void Player::TurnAntiClock (float time)
Turns the player anti-clockwise.
Takes the delta time as a parameter (glfwGetTime()) and uses it to calculate the speed at which the player will turn. It then adjusts the rotation of the player in a anti-clockwise direction for movement.
Returns: void
Definition at line 50 of file Player.cpp.
References Model::GetRotation(), and Model::SetRotation().
51 {
52         m_currentTurnSpeed = m_turnSpeed * time * 10;
53         m_playerModel->SetRotation(glm::vec3(0, m_playerModel->GetRotation().y + m_currentTurnSpeed, 0));
54 }
const std::string& Player::GetFilePath () const [inline]
Gets the file path of the player.
Returns the file path that the players data was read in from as a string.
Returns: const std::string&
Definition at line 114 of file Player.h.
114 { return m_filePath; }
void Player::SetFilePath (const std::string & filePath) [inline]
Sets the file path of the player.
Sets the file path to which the data was read in from to the string parameter parsed in.
Parameters:
const std::string& filePath
Returns: void
Definition at line 125 of file Player.h.
125 { m_filePath = filePath; }
void Player::SetCamera (Camera * camera) [inline]
Sets the camera object.
Parses the parameter given Camera* object to the players model. This is to be able to access the view and projection matrices when rendering.
Parameters:
Camera* camera
Returns: void
Definition at line 136 of file Player.h.
References Model::SetCamera().
136 { m_playerModel->SetCamera(camera); }
glm::vec3 Player::GetPosition () const [inline]
Gets the position.
Returns the position of the player in a 3 component glm::vec3.
Returns: glm::vec3
Definition at line 145 of file Player.h.
References Model::GetPosition().
145 { return m_playerModel->GetPosition(); }
void Player::SetPosition (glm::vec3 position) [inline]
Sets the position.
Sets the position of the player to the 3 component vector parsed in.
Parameters:
glm::vec3 position
Returns: void
Definition at line 155 of file Player.h.
References Model::SetPosition().
155 { m_playerModel->SetPosition(position); }
glm::vec3 Player::GetRotation () const [inline]
Gets the rotation.
Returns the rotation of the player in a 3 component glm::vec3.
Returns: glm::vec3
Definition at line 164 of file Player.h.
References Model::GetRotation().
164 { return m_playerModel->GetRotation(); }
void Player::SetRotation (glm::vec3 rotation) [inline]
Sets the rotation.
Sets the rotation of the player to the 3 component vector parsed in.
Parameters:
glm::vec3 rotation
Returns: void
Definition at line 174 of file Player.h.
References Model::SetRotation().
174 { m_playerModel->SetRotation(rotation); }
void Player::SetScale (glm::vec3 scale) [inline]
Sets the scale.
Sets the scale of the player to the 3 component vector parsed in.
Parameters:
glm::vec3 scale
Returns: void
Definition at line 184 of file Player.h.
References Model::SetScale().
184 { m_playerModel->SetScale(scale); }
float Player::GetMoveSpeed () [inline]
Gets the movement speed.
Returns the movement speed of the player as float.
Returns: float
Definition at line 193 of file Player.h.
193 { return m_moveSpeed; }
Model* Player::GetModel () [inline]
Gets the model of the player.
Returns a pointer to the model of the player.
Returns: Model*
Definition at line 202 of file Player.h.
202 { return m_playerModel; }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/AssetFactory/Player.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/AssetFactory/Player.cpp