Assimp::IOSystem Class Reference
CPP-API: Interface to the file system.
#include <IOSystem.hpp>
Public Member Functions
IOSystem ()
Default constructor.
virtual ~IOSystem ()
Virtual destructor.
AI_FORCE_INLINE bool Exists (const std::string &pFile) const
For backward compatibility.
virtual bool Exists (const char *pFile) const =0
Tests for the existence of a file at the given path.
virtual char getOsSeparator () const =0
Returns the system specific directory separator.
virtual IOStream * Open (const char *pFile, const char *pMode=`rb`)=0
Open a new file with a given path.
IOStream * Open (const std::string &pFile, const std::string &pMode=std::string(`rb`))
For backward compatibility.
virtual void Close (IOStream *pFile)=0
Closes the given file and releases all resources associated with it.
virtual bool ComparePaths (const char *one, const char *second) const
Compares two paths and check whether the point to identical files.
bool ComparePaths (const std::string &one, const std::string &second) const
For backward compatibility.
virtual bool PushDirectory (const std::string &path)
Pushes a new directory onto the directory stack.
virtual const std::string & CurrentDirectory () const
Returns the top directory from the stack.
virtual size_t StackSize () const
Returns the number of directories stored on the stack.
virtual bool PopDirectory ()
Pops the top directory from the stack.
virtual bool CreateDirectory (const std::string &path)
CReates an new directory at the given path.
virtual bool ChangeDirectory (const std::string &path)
Will change the current directory to the given path.
Detailed Description
CPP-API: Interface to the file system.
Derive an own implementation from this interface to supply custom file handling to the importer library. If you implement this interface, you also want to supply a custom implementation for IOStream.
See also: Importer::SetIOHandler()
Definition at line 84 of file IOSystem.hpp.
Constructor & Destructor Documentation
AI_FORCE_INLINE Assimp::IOSystem::IOSystem ()
Default constructor.
Create an instance of your derived class and assign it to an Assimp::Importer instance by calling Importer::SetIOHandler().
Definition at line 235 of file IOSystem.hpp.
236 : m_pathStack() {
237     // empty
238 }
AI_FORCE_INLINE Assimp::IOSystem::~IOSystem () [virtual]
Virtual destructor.
It is safe to be called from within DLL Assimp, we're constructed on Assimp's heap.
Definition at line 242 of file IOSystem.hpp.
242                     {
243     // empty
244 }
Member Function Documentation
AI_FORCE_INLINE bool Assimp::IOSystem::Exists (const std::string & pFile) const
For backward compatibility.
See also: Exists(const char*)
Definition at line 263 of file IOSystem.hpp.
263                                                    {
264     // NOTE:
265     // For compatibility, interface was changed to const char* to
266     // avoid crashes between binary incompatible STL versions
267     return Exists(pFile.c_str());
268 }
virtual bool Assimp::IOSystem::Exists (const char * pFile) const [pure virtual]
Tests for the existence of a file at the given path.
Parameters:
pFile Path to the file
Returns: true if there is a file with this path, else false.
Implemented in Assimp::DefaultIOSystem.
virtual char Assimp::IOSystem::getOsSeparator () const [pure virtual]
Returns the system specific directory separator.
Returns: System specific directory separator
Implemented in Assimp::DefaultIOSystem.
virtual IOStream* Assimp::IOSystem::Open (const char * pFile, const char * pMode = `rb`) [pure virtual]
Open a new file with a given path.
When the access to the file is finished, call Close() to release all associated resources (or the virtual dtor of the IOStream).
Parameters:
pFile Path to the file
pMode Desired file I/O mode. Required are: `wb`, `w`, `wt`, `rb`, `r`, `rt`.
Returns: New IOStream interface allowing the lib to access the underlying file.
Note: When implementing this class to provide custom IO handling, you probably have to supply an own implementation of IOStream as well.
Implemented in Assimp::DefaultIOSystem.
Referenced by Open().
AI_FORCE_INLINE IOStream * Assimp::IOSystem::Open (const std::string & pFile, const std::string & pMode = std::string(`rb`)) [inline]
For backward compatibility.
See also: Open(const char*, const char*)
Definition at line 254 of file IOSystem.hpp.
References Open().
254                                                                        {
255     // NOTE:
256     // For compatibility, interface was changed to const char* to
257     // avoid crashes between binary incompatible STL versions
258     return Open(pFile.c_str(),pMode.c_str());
259 }
virtual void Assimp::IOSystem::Close (IOStream * pFile) [pure virtual]
Closes the given file and releases all resources associated with it.
Parameters:
pFile The file instance previously created by Open().
Implemented in Assimp::DefaultIOSystem.
virtual bool Assimp::IOSystem::ComparePaths (const char * one, const char * second) const [virtual]
Compares two paths and check whether the point to identical files.
The dummy implementation of this virtual member performs a case-insensitive comparison of the given strings. The default IO system implementation uses OS mechanisms to convert relative into absolute paths, so the result can be trusted.
Parameters:
one First file
second Second file
Returns: true if the paths point to the same file. The file needn't be existing, however.
Reimplemented in Assimp::DefaultIOSystem.
Referenced by ComparePaths().
AI_FORCE_INLINE bool Assimp::IOSystem::ComparePaths (const std::string & one, const std::string & second) const [inline]
For backward compatibility.
See also: ComparePaths(const char*, const char*)
Definition at line 272 of file IOSystem.hpp.
References ComparePaths().
272                                                                                 {
273     // NOTE:
274     // For compatibility, interface was changed to const char* to
275     // avoid crashes between binary incompatible STL versions
276     return ComparePaths(one.c_str(),second.c_str());
277 }
AI_FORCE_INLINE bool Assimp::IOSystem::PushDirectory (const std::string & path) [virtual]
Pushes a new directory onto the directory stack.
Parameters:
path Path to push onto the stack.
Returns: True, when push was successful, false if path is empty.
Definition at line 281 of file IOSystem.hpp.
281                                                     {
282     if ( path.empty() ) {
283         return false;
284     }
285 
286     m_pathStack.push_back( path );
287 
288     return true;
289 }
AI_FORCE_INLINE const std::string & Assimp::IOSystem::CurrentDirectory () const [virtual]
Returns the top directory from the stack.
Returns: The directory on the top of the stack. Returns empty when no directory was pushed to the stack.
Definition at line 293 of file IOSystem.hpp.
293                                                   {
294     if ( m_pathStack.empty() ) {
295         static const std::string Dummy("");
296         return Dummy;
297     }
298     return m_pathStack[ m_pathStack.size()-1 ];
299 }
AI_FORCE_INLINE size_t Assimp::IOSystem::StackSize () const [virtual]
Returns the number of directories stored on the stack.
Returns: The number of directories of the stack.
Definition at line 303 of file IOSystem.hpp.
303                                  {
304     return m_pathStack.size();
305 }
AI_FORCE_INLINE bool Assimp::IOSystem::PopDirectory () [virtual]
Pops the top directory from the stack.
Returns: True, when a directory was on the stack. False if no directory was on the stack.
Definition at line 309 of file IOSystem.hpp.
309                             {
310     if ( m_pathStack.empty() ) {
311         return false;
312     }
313 
314     m_pathStack.pop_back();
315 
316     return true;
317 }
AI_FORCE_INLINE bool Assimp::IOSystem::CreateDirectory (const std::string & path) [virtual]
CReates an new directory at the given path.
Parameters:
path [in] The path to create.
Returns: True, when a directory was created. False if the directory cannot be created.
Definition at line 321 of file IOSystem.hpp.
321                                                       {
322     if ( path.empty() ) {
323         return false;
324     }
325 
326 #ifdef _WIN32
327     return 0 != ::_mkdir( path.c_str() );
328 #else
329     return 0 != ::mkdir( path.c_str(), 0777 );
330 #endif // _WIN32
331 }
AI_FORCE_INLINE bool Assimp::IOSystem::ChangeDirectory (const std::string & path) [virtual]
Will change the current directory to the given path.
Parameters:
path [in] The path to change to.
Returns: True, when the directory has changed successfully.
Definition at line 335 of file IOSystem.hpp.
335                                                       {
336     if ( path.empty() ) {
337         return false;
338     }
339 
340 #ifdef _WIN32
341     return 0 != ::_chdir( path.c_str() );
342 #else
343     return 0 != ::chdir( path.c_str() );
344 #endif // _WIN32
345 }
The documentation for this class was generated from the following file:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/assimp-4.1.0/include/assimp/IOSystem.hpp