OpenGl Class Reference
OpenGl renderer class.
#include <OpenGl.h>
Public Member Functions
OpenGl ()
Default constructor.
~OpenGl ()
Destructor.
void Prepare (Model *model, std::string vertShader, std::string fragShader)
Prepare.
void Render (Model *model)
Render.
Detailed Description
OpenGl renderer class.
This class is the facade class that implements all the necessary functionalities of the OpenGl API into the game engine. It handles creating VAOs, VBOs and EBOs for model data as well as the 3D rendering and uniform calculations to be correctly rendered.
Author: Cordell Smith
Version: 01
Date: 31/05/2018
Definition at line 24 of file OpenGl.h.
Constructor & Destructor Documentation
OpenGl::OpenGl () [inline]
Default constructor.
Empty default constructor.
Returns: null
Definition at line 34 of file OpenGl.h.
34 { }
OpenGl::~OpenGl () [inline]
Destructor.
Empty destructor.
Returns: null
Definition at line 43 of file OpenGl.h.
43 { }
Member Function Documentation
void OpenGl::Prepare (Model * model, std::string vertShader, std::string fragShader)
Prepare.
Takes model data, vertex shader string and fragment shader string and prepares the VAO, VBO and EBO attribute data. It stored the correct data in each attribute of the models VAO, VBO and EBO to be used in the rendering process later on.
Parameters:
Model* model
std::string vertShader
std::string fragShader
Returns: void
Definition at line 3 of file OpenGl.cpp.
References Model::GetMeshBatch(), Model::GetShader(), and Shader::Initialize().
4 {
5         model->GetShader()->Initialize(vertShader, fragShader);
6 
7         int meshBatchSize = model->GetMeshBatch().size();
8         for (int i = 0; i < meshBatchSize; i++)
9         {
10                 glGenVertexArrays(1, &model->GetMeshBatch()[i].VAO);
11                 glGenBuffers(1, &model->GetMeshBatch()[i].VBO);
12                 glGenBuffers(1, &model->GetMeshBatch()[i].EBO);
13 
14                 glBindVertexArray(model->GetMeshBatch()[i].VAO);
15                 glBindBuffer(GL_ARRAY_BUFFER, model->GetMeshBatch()[i].VBO);
16 
17                 glBufferData(GL_ARRAY_BUFFER, sizeof(model->GetMeshBatch()[i].GetVertices()[0]) * model->GetMeshBatch()[i].GetVertices().size(), &model->GetMeshBatch()[i].GetVertices()[0], GL_STATIC_DRAW);
18 
19                 glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, model->GetMeshBatch()[i].EBO);
20                 glBufferData(GL_ELEMENT_ARRAY_BUFFER, model->GetMeshBatch()[i].GetIndices().size() * sizeof(unsigned int), &model->GetMeshBatch()[i].GetIndices()[0], GL_STATIC_DRAW);
21 
22                 // vertex positions
23                 glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(model->GetMeshBatch()[i].GetVertices()[0]), 0);
24                 // vertex texture coords
25                 glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, sizeof(model->GetMeshBatch()[i].GetVertices()[0]), (GLvoid*)sizeof(model->GetMeshBatch()[i].GetVertices()[0].m_position));
26                 // vertex normals
27                 glVertexAttribPointer(2, 3, GL_FLOAT, GL_FALSE, sizeof(model->GetMeshBatch()[i].GetVertices()[0]), (GLvoid*)sizeof(model->GetMeshBatch()[i].GetVertices()[0].m_texCoords));
28                 // vertex colours
29                 glVertexAttribPointer(3, 4, GL_FLOAT, GL_FALSE, sizeof(model->GetMeshBatch()[i].GetVertices()[0]), (GLvoid*)sizeof(model->GetMeshBatch()[i].GetVertices()[0].m_normal));
30 
31                 glBindVertexArray(0);
32         }
33 }
void OpenGl::Render (Model * model)
Render.
Takes model data that is parsed in as a parameter and accesses the necessary opneGl components to render the model to the screen. This includes the textures associated with the model data and its respective mesh data.
Parameters:
Model* model
Returns: void
Definition at line 35 of file OpenGl.cpp.
References Model::GetCamera(), Model::GetMeshBatch(), Model::GetPosition(), Camera::GetProjectionMatrix(), Model::GetRotation(), Model::GetScale(), Model::GetShader(), Shader::GetVariable(), Shader::SetFloat(), Shader::SetMatrix4(), glm::to_string(), Shader::TurnOff(), and Shader::TurnOn().
36 {
37         model->GetShader()->TurnOn();
38 
39         int meshBatchSize = model->GetMeshBatch().size();
40         for (int i = 0; i < meshBatchSize; i++)
41         {
42                 unsigned int diffuseNr = 1;
43                 unsigned int specularNr = 1;
44                 unsigned int normalNr = 1;
45                 unsigned int heightNr = 1;
46 
47                 int textureListSize = meshBatchSize;
48                 for (int j = 0; j < textureListSize; j++)
49                 {
50                         glActiveTexture(GL_TEXTURE0 + j); // activate proper texture unit before binding
51                                                                                                 // retrieve texture number (the N in diffuse_textureN)
52                         std::string number;
53                         std::string name = model->GetMeshBatch()[i].GetTextures()[0].m_type;
54 
55                         if (name == "texture_diffuse")
56                                 number = std::to_string(diffuseNr++);
57                         else if (name == "texture_specular")
58                                 number = std::to_string(specularNr++);
59                         else if (name == "texture_normal")
60                                 number = std::to_string(normalNr++);
61                         else if (name == "texture_height")
62                                 number = std::to_string(heightNr++);
63                         else
64                                 std::cout << "Incorrect texture Id in OpenGl renderer" << std::endl;
65 
66                         GLuint textureUniformId = model->GetShader()->GetVariable((name + number).c_str());
67                         model->GetShader()->SetFloat(textureUniformId, j);
68                         glBindTexture(GL_TEXTURE_2D, model->GetMeshBatch()[i].GetTextures()[0].m_id);
69 
70                         if (meshBatchSize == 1)
71                                 break;
72                 }
73                 glActiveTexture(GL_TEXTURE0);
74 
75                 glm::mat4 projectionMatrix = model->GetCamera()->GetProjectionMatrix();
76                 glm::mat4 modelMatrix = CreateTransformationMatrix(model->GetPosition(), model->GetRotation(), model->GetScale());
77                 glm::mat4 viewMatrix = CreateViewMatrix(model->GetCamera());
78 
79                 GLint modelMatrixId = model->GetShader()->GetVariable("model");
80                 GLint viewMatrixId = model->GetShader()->GetVariable("view");
81                 GLint projectionMatrixId = model->GetShader()->GetVariable("projection");
82 
83                 model->GetShader()->SetMatrix4(modelMatrixId, 1, false, &modelMatrix[0][0]);
84                 model->GetShader()->SetMatrix4(viewMatrixId, 1, false, &viewMatrix[0][0]);
85                 model->GetShader()->SetMatrix4(projectionMatrixId, 1, false, &projectionMatrix[0][0]);
86 
87                 glBindVertexArray(model->GetMeshBatch()[i].VAO);
88 
89                 glEnableVertexAttribArray(0);
90                 glEnableVertexAttribArray(1);
91                 glEnableVertexAttribArray(2);
92                 glEnableVertexAttribArray(3);
93 
94                 glDrawArrays(GL_TRIANGLES, 0, model->GetMeshBatch()[i].GetVertices().size());
95                 //glDrawElements(GL_TRIANGLES, model->GetMeshBatch()[i].GetIndices().size(), GL_UNSIGNED_INT, 0);
96 
97                 glDisableVertexAttribArray(0);
98                 glDisableVertexAttribArray(1);
99                 glDisableVertexAttribArray(2);
100                 glDisableVertexAttribArray(3);
101 
102                 glBindVertexArray(0);
103 
104         }
105         model->GetShader()->TurnOff();
106 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/Renderer/OpenGl.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/Renderer/OpenGl.cpp