Model Class Reference
Model class to store model data.
#include <Model.h>
Public Member Functions
Model ()
Constructor.
~Model ()
Destructor.
void LoadModel (std::string filePath)
Loads the model data.
void ProcessNode (aiNode *node, const aiScene *scene)
Processes the node of an aiScene.
Mesh ProcessMesh (aiMesh *mesh, const aiScene *scene)
Processes the mesh.
std::vector< Texture > LoadMaterialTextures (aiMaterial *mat, aiTextureType type, std::string typeName)
Loads the material textures.
void Destroy ()
Destroys the model.
glm::vec3 & GetPosition ()
Gets the models position.
void SetPosition (glm::vec3 position)
Sets the models position.
glm::vec3 & GetRotation ()
Gets the models rotation.
void SetRotation (glm::vec3 rotation)
Sets the models rotation.
glm::vec3 & GetScale ()
Gets the models scale.
void SetScale (glm::vec3 scale)
Sets the models scale.
Camera * GetCamera ()
Gets the camera object.
const void SetCamera (Camera *camera)
Sets the camera object.
std::vector< Mesh > & GetMeshBatch ()
Gets the mesh batch.
std::vector< Texture > & GetTextures ()
Gets the textures.
Shader * GetShader ()
Gets the shader.
void SetShader (Shader *shader)
Sets the shader.
void SetAI (ComputerAI *compAI)
Sets the AI of the model.
ComputerAI * GetAI ()
Gets the AI of the model.
Detailed Description
Model class to store model data.
The model class is used to read in and store model data that is read in using the assimp import asset library. It contains all the functionality to load in a model of many different file types and store the information in various data structures to be accessed later.
Author: Cordell Smith
Version: 01
Date: 31/05/2018
Definition at line 32 of file Model.h.
Constructor & Destructor Documentation
Model::Model ()
Constructor.
This is the default constuctor that sets the scale value of the model to 1, initializes the models shader as well as setting the AI of the model to NULL.
Returns: null
Definition at line 7 of file Model.cpp.
References SetScale().
8 {
9         SetScale(glm::vec3(1.0, 1.0, 1.0));
10         m_shader = new Shader();
11         m_compAI = NULL;
12 }
Model::~Model () [inline]
Destructor.
This is the default destructor that calls the Destroy() function to free up any resources used by the model, incorporating memory management.
Returns: null
Definition at line 53 of file Model.h.
References Destroy().
53 { Destroy(); }
Member Function Documentation
void Model::LoadModel (std::string filePath)
Loads the model data.
This function loads the model data taking in a relative string file path. The function then uses the assimp import asset library to read the file and with other helper functions, store the data in the correct member variable data structures.
Parameters:
std::string filePath
Returns: void
Definition at line 14 of file Model.cpp.
References AI_SCENE_FLAGS_INCOMPLETE, aiProcess_CalcTangentSpace, aiProcess_FlipUVs, aiProcess_JoinIdenticalVertices, aiProcess_SortByPType, aiProcess_Triangulate, aiScene::mFlags, aiScene::mRootNode, and ProcessNode().
Referenced by Player::LoadFromFilePath().
15 {
16         Assimp::Importer import;
17         const aiScene *scene = import.ReadFile(filePath, aiProcess_FlipUVs 
18                 | aiProcess_CalcTangentSpace
19                 | aiProcess_Triangulate 
20                 | aiProcess_JoinIdenticalVertices 
21                 | aiProcess_SortByPType);
22 
23         m_directory = filePath.substr(0, filePath.find_last_of('/'));
24 
25         if (!scene || scene->mFlags & AI_SCENE_FLAGS_INCOMPLETE || !scene->mRootNode)
26         {
27                 std::cout << "ERROR::ASSIMP::" << import.GetErrorString() << std::endl;
28         }
29         else
30                 ProcessNode(scene->mRootNode, scene);
31 }
void Model::ProcessNode (aiNode * node, const aiScene * scene)
Processes the node of an aiScene.
Assimp reads the loaded file as a scene that contains many nodes. The nodes are stored in a linked list data structure. This function processes the specific node that is being examined.
Parameters:
aiNode* node
const aiScene* scene
Returns: void
Definition at line 33 of file Model.cpp.
References aiNode::mChildren, aiNode::mMeshes, aiScene::mMeshes, aiNode::mNumChildren, aiNode::mNumMeshes, and ProcessMesh().
Referenced by LoadModel().
34 {
35         // process all the node's meshes (if any)
36         for (unsigned int i = 0; i < node->mNumMeshes; i++)
37         {
38                 aiMesh *mesh = scene->mMeshes[node->mMeshes[i]];
39                 m_meshBatch.push_back(ProcessMesh(mesh, scene));
40         }
41         // then do the same for each of its children
42         for (unsigned int i = 0; i < node->mNumChildren; i++)
43         {
44                 ProcessNode(node->mChildren[i], scene);
45         }
46 }
Mesh Model::ProcessMesh (aiMesh * mesh, const aiScene * scene)
Processes the mesh.
For each node that is contained in a scene, if it contains a mesh, then this function processes it. It reads the vertex data in the aiNode object and stores them in the correct member data structures.
Parameters:
aiMesh* mesh
const aiScene* scene
Returns: void
Definition at line 48 of file Model.cpp.
References aiTextureType_AMBIENT, aiTextureType_DIFFUSE, aiTextureType_HEIGHT, aiTextureType_SPECULAR, LoadMaterialTextures(), aiMesh::mFaces, aiFace::mIndices, aiMesh::mMaterialIndex, aiScene::mMaterials, aiMesh::mNormals, aiMesh::mNumFaces, aiMesh::mTextureCoords, and aiMesh::mVertices.
Referenced by ProcessNode().
49 {
50         std::vector<Vertex3> vertices;
51         std::vector<unsigned int> indices;
52         std::vector<Texture> textures;
53 
54         // process face data
55         for (unsigned int i = 0; i < mesh->mNumFaces; i++)
56         {
57                 Vertex3 vertex;
58                 glm::vec3 vertexPos;
59                 glm::vec4 colour;
60                 glm::vec3 normalCoord;
61                 glm::vec2 texCoord;
62                 glm::vec3 tangent;
63                 glm::vec3 biTangent;
64 
65                 aiFace face = mesh->mFaces[i];
66                 for (unsigned int j = 0; j < 3; j++)
67                 {
68                         // vertex positions
69                         auto const &v = mesh->mVertices[face.mIndices[j]];
70                         vertexPos.x = v.x; 
71                         vertexPos.y = v.y; 
72                         vertexPos.z = v.z;
73                         vertex.m_position = vertexPos;
74 
75                         // colours (randomised)
76                         colour = glm::vec4(((float)rand() / (RAND_MAX)), ((float)rand() / (RAND_MAX)), ((float)rand() / (RAND_MAX)), 1.0f);
77                         vertex.m_colour = colour;
78 
79                         // normals
80                         if (mesh->HasNormals())
81                         {
82                                 auto const &n = mesh->mNormals[face.mIndices[j]];
83                                 normalCoord.x = n.x;
84                                 normalCoord.y = n.y;
85                                 normalCoord.z = n.z;
86                                 vertex.m_normal = normalCoord;
87                         }
88                         else
89                                 vertex.m_normal = glm::vec3(0.0f, 0.0f, 0.0f);
90 
91                         // texture coordinates
92                         if (mesh->mTextureCoords[0])
93                         {
94                                 auto const &uv = mesh->mTextureCoords[0][face.mIndices[j]];
95                                 texCoord.x = uv.x;
96                                 texCoord.y = uv.y;
97                                 vertex.m_texCoords = texCoord;
98                         }
99                         else
100                                 vertex.m_texCoords = glm::vec2(0.0f, 0.0f);
101 
103                         //if (mesh->HasTangentsAndBitangents())
104                         //{
105                         //      auto const &t = mesh->mTangents[face.mIndices[j]];
106                         //      tangent.x = t.x;
107                         //      tangent.y = t.y;
108                         //      tangent.z = t.z;
109                         //      vertex.m_tangent = tangent;
110 
111                         //      auto const &bt = mesh->mBitangents[face.mIndices[j]];
112                         //      biTangent.x = bt.x;
113                         //      biTangent.y = bt.y;
114                         //      biTangent.z = bt.z;
115                         //      vertex.m_biTangent = biTangent;
116                         //}
117 
118                         vertices.push_back(vertex);
119                         indices.push_back(face.mIndices[j]);
120                 }
121         }
122         // process materials
123         aiMaterial* material = scene->mMaterials[mesh->mMaterialIndex];
124         // diffuse maps
125         std::vector<Texture> diffuseMaps = LoadMaterialTextures(material, aiTextureType_DIFFUSE, "texture_diffuse");
126         textures.insert(textures.end(), diffuseMaps.begin(), diffuseMaps.end());
127         // specular maps
128         std::vector<Texture> specularMaps = LoadMaterialTextures(material, aiTextureType_SPECULAR, "texture_specular");
129         textures.insert(textures.end(), specularMaps.begin(), specularMaps.end());
130         // normal maps
131         std::vector<Texture> normalMaps = LoadMaterialTextures(material, aiTextureType_HEIGHT, "texture_normal");
132         textures.insert(textures.end(), normalMaps.begin(), normalMaps.end());
133         // height maps
134         std::vector<Texture> heightMaps = LoadMaterialTextures(material, aiTextureType_AMBIENT, "texture_height");
135         textures.insert(textures.end(), heightMaps.begin(), heightMaps.end());
136 
137         return Mesh(vertices, indices, textures);
138 }
std::vector< Texture > Model::LoadMaterialTextures (aiMaterial * mat, aiTextureType type, std::string typeName)
Loads the material textures.
Reads in the materials of the aiMesh and stores them in a temporary Texture data structure that is then returned.
Parameters:
aiMaterial* mat
aiTextureType type
std::string typeName
Returns: std::vector<Texture>
Definition at line 140 of file Model.cpp.
Referenced by ProcessMesh().
141 {
142         std::vector<Texture> textures;
143         for (unsigned int i = 0; i < mat->GetTextureCount(type); i++)
144         {
145                 aiString str;
146                 mat->GetTexture(type, i, &str);
147                 // check if texture was loaded before and if so, continue to next iteration: skip loading a new texture
148                 bool skip = false;
149 
150                 if (std::strcmp(str.C_Str(), "$texture_dummy.bmp") == 0)
151                         skip = true;
152 
153                 for (unsigned int j = 0; j < m_texturesLoaded.size(); j++)
154                 {
155                         if (std::strcmp(m_texturesLoaded[j].m_path.data(), str.C_Str()) == 0)
156                         {
157                                 textures.push_back(m_texturesLoaded[j]);
158                                 skip = true; // a texture with the same filepath has already been loaded, continue to next one. (optimization)
159                                 break;
160                         }
161                 }
162                 if (!skip)
163                 {   // if texture hasn't been loaded already, load it
164                         Texture texture;
165                         texture.m_id = TextureFromFile(str.C_Str(), this->m_directory);
166                         texture.m_type = typeName;
167                         texture.m_path = str.C_Str();
168                         textures.push_back(texture);
169                         m_texturesLoaded.push_back(texture);  // store it as texture loaded for entire model, to ensure we won't unnecesery load duplicate textures.
170                 }
171         }
172         return textures;
173 }
void Model::Destroy ()
Destroys the model.
Deallocates any memory used by the model object.
Returns: void
Definition at line 175 of file Model.cpp.
Referenced by ~Model().
176 {
177         // Todo: implement destroy function of all meshes of the model
178         return void();
179 }
glm::vec3& Model::GetPosition () [inline]
Gets the models position.
Returns the position of the model as a glm::vec3.
Returns: glm::vec3&
Definition at line 120 of file Model.h.
Referenced by Player::GetPosition(), Player::MoveBackward(), Player::MoveForward(), and OpenGl::Render().
120 { return m_position; }
void Model::SetPosition (glm::vec3 position)
Sets the models position.
Sets the position of the model using the parameter given.
Parameters:
glm::vec3 position
Returns: void
Definition at line 182 of file Model.cpp.
Referenced by Player::MoveBackward(), Player::MoveForward(), Terrain::SetPosition(), and Player::SetPosition().
183 {
184         m_position = position;
185         for (size_t i = 0; i < m_meshBatch.size(); i++)
186         {
187                 m_meshBatch[i].SetPosition(position);
188         }
189 }
glm::vec3& Model::GetRotation () [inline]
Gets the models rotation.
Returns the rotation of the model as a glm::vec3.
Returns: glm::vec3&
Definition at line 139 of file Model.h.
Referenced by Player::GetRotation(), Player::MoveBackward(), Player::MoveForward(), OpenGl::Render(), Player::TurnAntiClock(), and Player::TurnClock().
139 { return m_rotation; }
void Model::SetRotation (glm::vec3 rotation)
Sets the models rotation.
Sets the rotation of the model using the parameter given.
Parameters:
glm::vec3 rotation
Returns: void
Definition at line 191 of file Model.cpp.
Referenced by Player::SetRotation(), Player::TurnAntiClock(), and Player::TurnClock().
192 {
193         m_rotation = rotation;
194         for (size_t i = 0; i < m_meshBatch.size(); i++)
195         {
196                 m_meshBatch[i].SetRotation(rotation);
197         }
198 }
glm::vec3& Model::GetScale () [inline]
Gets the models scale.
Returns the scale of the model as a glm::vec3.
Returns: glm::vec3&
Definition at line 158 of file Model.h.
Referenced by OpenGl::Render().
158 { return m_scale; }
void Model::SetScale (glm::vec3 scale)
Sets the models scale.
Sets the rotation of the model using the parameter given.
Parameters:
glm::vec3 scale
Returns: void
Definition at line 200 of file Model.cpp.
Referenced by Bruteforce::GenerateTerrain(), Model(), Terrain::SetScale(), and Player::SetScale().
201 {
202         m_scale = scale;
203         for (size_t i = 0; i < m_meshBatch.size(); i++)
204         {
205                 m_meshBatch[i].SetScale(scale);
206         }
207 }
Camera* Model::GetCamera () [inline]
Gets the camera object.
Returns a pointer to the camera object to access the view and projection matrices.
Returns: Camera*
Definition at line 177 of file Model.h.
Referenced by OpenGl::Render().
177 { return m_camera; }
const void Model::SetCamera (Camera * camera) [inline]
Sets the camera object.
Sets the camera object to the world camera object to retrieve the view and projection matrices.
Parameters:
Camera* camera
Returns: const void
Definition at line 188 of file Model.h.
Referenced by Terrain::SetCamera(), and Player::SetCamera().
188 { m_camera = camera; }
std::vector<Mesh>& Model::GetMeshBatch () [inline]
Gets the mesh batch.
Returns the vector of meshes of the model by reference.
Returns: std::vector<Mesh>&
Definition at line 197 of file Model.h.
Referenced by Bruteforce::GenerateTerrain(), OpenGl::Prepare(), and OpenGl::Render().
197 { return m_meshBatch; }
std::vector<Texture>& Model::GetTextures () [inline]
Gets the textures.
Returns the vector of textures of the model by reference.
Returns: std::vector<Texture>&
Definition at line 206 of file Model.h.
Referenced by Bruteforce::GenerateTerrain().
206 { return m_texturesLoaded; }
Shader* Model::GetShader () [inline]
Gets the shader.
Returns the shader object of the model.
Returns: Shader*
Definition at line 215 of file Model.h.
Referenced by OpenGl::Prepare(), and OpenGl::Render().
215 { return m_shader; }
void Model::SetShader (Shader * shader) [inline]
Sets the shader.
Sets the shader member variable to the parameter shader parsed in.
Parameters:
Shader* shader
Returns: void
Definition at line 225 of file Model.h.
225 { m_shader = shader; }
void Model::SetAI (ComputerAI * compAI) [inline]
Sets the AI of the model.
Sets the ComputerAI member variable of the model to tha parameter ComputerAI parsed in.
Parameters:
ComputerAI* compAI
Returns: void
Definition at line 236 of file Model.h.
236 { m_compAI = compAI; }
ComputerAI* Model::GetAI () [inline]
Gets the AI of the model.
Returns the ComputerAI member variable of the model as a pointer.
Returns: ComputerAI*
Definition at line 245 of file Model.h.
245 { return m_compAI; }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/AssetFactory/Model.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/AssetFactory/Model.cpp