btTriangleMesh Class Reference
#include <btTriangleMesh.h>
Public Member Functions
void addTriangle (const btVector3 &vertex0, const btVector3 &vertex1, const btVector3 &vertex2, bool removeDuplicateVertices=false)
void addTriangleIndices (int index1, int index2, int index3)
Add a triangle using its indices. Make sure the indices are pointing within the vertices array, so add the vertices first (and to be sure, avoid removal of duplicate vertices).
int findOrAddVertex (const btVector3 &vertex, bool removeDuplicateVertices)
findOrAddVertex is an internal method, use addTriangle instead
void addIndex (int index)
addIndex is an internal method, use addTriangle instead
Detailed Description
The btTriangleMesh class is a convenience class derived from btTriangleIndexVertexArray, that provides storage for a concave triangle mesh. It can be used as data for the btBvhTriangleMeshShape. It allows either 32bit or 16bit indices, and 4 (x-y-z-w) or 3 (x-y-z) component vertices. If you want to share triangle/index data between graphics mesh and collision mesh (btBvhTriangleMeshShape), you can directly use btTriangleIndexVertexArray or derive your own class from btStridingMeshInterface. Performance of btTriangleMesh and btTriangleIndexVertexArray used in a btBvhTriangleMeshShape is the same.
Definition at line 27 of file btTriangleMesh.h.
Member Function Documentation
void btTriangleMesh::addTriangle (const btVector3 & vertex0, const btVector3 & vertex1, const btVector3 & vertex2, bool removeDuplicateVertices = false)
By default addTriangle won't search for duplicate vertices, because the search is very slow for large triangle meshes. In general it is better to directly use btTriangleIndexVertexArray instead.
Definition at line 132 of file btTriangleMesh.cpp.
References addIndex(), and findOrAddVertex().
133 {
134         m_indexedMeshes[0].m_numTriangles++;
135         addIndex(findOrAddVertex(vertex0,removeDuplicateVertices));
136         addIndex(findOrAddVertex(vertex1,removeDuplicateVertices));
137         addIndex(findOrAddVertex(vertex2,removeDuplicateVertices));
138 }
int btTriangleMesh::findOrAddVertex (const btVector3 & vertex, bool removeDuplicateVertices)
findOrAddVertex is an internal method, use addTriangle instead
Todo : could use acceleration structure for this
Definition at line 86 of file btTriangleMesh.cpp.
References glm::length2(), btAlignedObjectArray< T >::push_back(), and btAlignedObjectArray< T >::size().
Referenced by addTriangle().
87 {
88         //return index of new/existing vertex
90         if (m_use4componentVertices)
91         {
92                 if (removeDuplicateVertices)
93                         {
94                         for (int i=0;i< m_4componentVertices.size();i++)
95                         {
96                                 if ((m_4componentVertices[i]-vertex).length2() <= m_weldingThreshold)
97                                 {
98                                         return i;
99                                 }
100                         }
101                 }
102                 m_indexedMeshes[0].m_numVertices++;
103                 m_4componentVertices.push_back(vertex);
104                 m_indexedMeshes[0].m_vertexBase = (unsigned char*)&m_4componentVertices[0];
105 
106                 return m_4componentVertices.size()-1;
107                 
108         } else
109         {
110                 
111                 if (removeDuplicateVertices)
112                 {
113                         for (int i=0;i< m_3componentVertices.size();i+=3)
114                         {
115                                 btVector3 vtx(m_3componentVertices[i],m_3componentVertices[i+1],m_3componentVertices[i+2]);
116                                 if ((vtx-vertex).length2() <= m_weldingThreshold)
117                                 {
118                                         return i/3;
119                                 }
120                         }
121                 }
122                 m_3componentVertices.push_back(vertex.getX());
123                 m_3componentVertices.push_back(vertex.getY());
124                 m_3componentVertices.push_back(vertex.getZ());
125                 m_indexedMeshes[0].m_numVertices++;
126                 m_indexedMeshes[0].m_vertexBase = (unsigned char*)&m_3componentVertices[0];
127                 return (m_3componentVertices.size()/3)-1;
128         }
129 
130 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/CollisionShapes/btTriangleMesh.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/CollisionShapes/btTriangleMesh.cpp