btSphereSphereCollisionAlgorithm Class Reference
#include <btSphereSphereCollisionAlgorithm.h>
Public Member Functions
virtual void processCollision (const btCollisionObjectWrapper *body0Wrap, const btCollisionObjectWrapper *body1Wrap, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
Detailed Description
btSphereSphereCollisionAlgorithm provides sphere-sphere collision detection. Other features are frame-coherency (persistent data) and collision response. Also provides the most basic sample for custom/user btCollisionAlgorithm
Definition at line 29 of file btSphereSphereCollisionAlgorithm.h.
Member Function Documentation
void btSphereSphereCollisionAlgorithm::processCollision (const btCollisionObjectWrapper * body0Wrap, const btCollisionObjectWrapper * body1Wrap, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
iff distance positive, don't generate a new contact
distance (negative means penetration)
point on A (worldspace) btVector3 pos0 = col0->getWorldTransform().getOrigin() - radius0 * normalOnSurfaceB; point on B (worldspace)
report a contact. internally this will be kept persistent, and contact reduction is done
Implements btCollisionAlgorithm.
Definition at line 44 of file btSphereSphereCollisionAlgorithm.cpp.
References btManifoldResult::addContactPoint(), btManifoldResult::m_closestPointDistanceThreshold, btManifoldResult::refreshContactPoints(), and btManifoldResult::setPersistentManifold().
45 {
46         (void)dispatchInfo;
47 
48         if (!m_manifoldPtr)
49                 return;
50 
51         resultOut->setPersistentManifold(m_manifoldPtr);
52 
53         btSphereShape* sphere0 = (btSphereShape*)col0Wrap->getCollisionShape();
54         btSphereShape* sphere1 = (btSphereShape*)col1Wrap->getCollisionShape();
55 
56         btVector3 diff = col0Wrap->getWorldTransform().getOrigin()-  col1Wrap->getWorldTransform().getOrigin();
57         btScalar len = diff.length();
58         btScalar radius0 = sphere0->getRadius();
59         btScalar radius1 = sphere1->getRadius();
60 
61 #ifdef CLEAR_MANIFOLD
62         m_manifoldPtr->clearManifold(); //don't do this, it disables warmstarting
63 #endif
64 
66         if ( len > (radius0+radius1+resultOut->m_closestPointDistanceThreshold))
67         {
68 #ifndef CLEAR_MANIFOLD
69                 resultOut->refreshContactPoints();
70 #endif //CLEAR_MANIFOLD
71                 return;
72         }
74         btScalar dist = len - (radius0+radius1);
75 
76         btVector3 normalOnSurfaceB(1,0,0);
77         if (len > SIMD_EPSILON)
78         {
79                 normalOnSurfaceB = diff / len;
80         }
81 
85         btVector3 pos1 = col1Wrap->getWorldTransform().getOrigin() + radius1* normalOnSurfaceB;
86 
88         
89         
90         resultOut->addContactPoint(normalOnSurfaceB,pos1,dist);
91 
92 #ifndef CLEAR_MANIFOLD
93         resultOut->refreshContactPoints();
94 #endif //CLEAR_MANIFOLD
95 
96 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp