btGImpactCollisionAlgorithm Class Reference
Collision Algorithm for GImpact Shapes.
#include <btGImpactCollisionAlgorithm.h>
void collide_gjk_triangles (const btCollisionObjectWrapper *body0Wrap, const btCollisionObjectWrapper *body1Wrap, const btGImpactMeshShapePart *shape0, const btGImpactMeshShapePart *shape1, const int *pairs, int pair_count)
void gimpact_vs_gimpact (const btCollisionObjectWrapper *body0Wrap, const btCollisionObjectWrapper *body1Wrap, const btGImpactShapeInterface *shape0, const btGImpactShapeInterface *shape1)
Collides two gimpact shapes.
void setFace0 (int value)
Accessor/Mutator pairs for Part and triangleID.
static void registerAlgorithm (btCollisionDispatcher *dispatcher)
Use this function for register the algorithm externally.
Protected Member Functions
SIMD_FORCE_INLINE btPersistentManifold * newContactManifold (const btCollisionObject *body0, const btCollisionObject *body1)
Creates a new contact point.
Detailed Description
Collision Algorithm for GImpact Shapes.
For register this algorithm in Bullet, proceed as following:
btCollisionDispatcher * dispatcher = static_cast<btCollisionDispatcher *>(m_dynamicsWorld ->getDispatcher());
btGImpactCollisionAlgorithm::registerAlgorithm(dispatcher);
Definition at line 54 of file btGImpactCollisionAlgorithm.h.
Member Function Documentation
void btGImpactCollisionAlgorithm::collide_gjk_triangles (const btCollisionObjectWrapper * body0Wrap, const btCollisionObjectWrapper * body1Wrap, const btGImpactMeshShapePart * shape0, const btGImpactMeshShapePart * shape1, const int * pairs, int pair_count) [protected]
Collision routines
Definition at line 349 of file btGImpactCollisionAlgorithm.cpp.
References btGImpactMeshShapePart::getBulletTriangle(), btGImpactMeshShapePart::lockChildShapes(), btTriangleShapeEx::overlap_test_conservative(), and btGImpactMeshShapePart::unlockChildShapes().
Referenced by gimpact_vs_gimpact().
354 {
355         btTriangleShapeEx tri0;
356         btTriangleShapeEx tri1;
357 
358         shape0->lockChildShapes();
359         shape1->lockChildShapes();
360 
361         const int * pair_pointer = pairs;
362 
363         while(pair_count--)
364         {
365 
366                 m_triface0 = *(pair_pointer);
367                 m_triface1 = *(pair_pointer+1);
368                 pair_pointer+=2;
369 
370 
371 
372                 shape0->getBulletTriangle(m_triface0,tri0);
373                 shape1->getBulletTriangle(m_triface1,tri1);
374 
375 
376                 //collide two convex shapes
377                 if(tri0.overlap_test_conservative(tri1))
378                 {
379                         convex_vs_convex_collision(body0Wrap,body1Wrap,&tri0,&tri1);
380                 }
381 
382         }
383 
384         shape0->unlockChildShapes();
385         shape1->unlockChildShapes();
386 }
void btGImpactCollisionAlgorithm::gimpact_vs_gimpact (const btCollisionObjectWrapper * body0Wrap, const btCollisionObjectWrapper * body1Wrap, const btGImpactShapeInterface * shape0, const btGImpactShapeInterface * shape1)
Collides two gimpact shapes.
Precondition: shape0 and shape1 couldn't be btGImpactMeshShape objects
Definition at line 461 of file btGImpactCollisionAlgorithm.cpp.
References btGImpactShapeInterface::childrenHasTransform(), collide_gjk_triangles(), GIM_ShapeRetriever::getChildShape(), btGImpactShapeInterface::getChildTransform(), btGImpactShapeInterface::getGImpactShapeType(), btGImpactMeshShape::getMeshPart(), btGImpactMeshShape::getMeshPartCount(), btGImpactShapeInterface::lockChildShapes(), GIM_PAIR::m_index1, GIM_PAIR::m_index2, btAlignedObjectArray< T >::size(), and btGImpactShapeInterface::unlockChildShapes().
466 {
467 
468         if(shape0->getGImpactShapeType()==CONST_GIMPACT_TRIMESH_SHAPE)
469         {
470                 const btGImpactMeshShape * meshshape0 = static_cast<const btGImpactMeshShape *>(shape0);
471                 m_part0 = meshshape0->getMeshPartCount();
472 
473                 while(m_part0--)
474                 {
475                         gimpact_vs_gimpact(body0Wrap,body1Wrap,meshshape0->getMeshPart(m_part0),shape1);
476                 }
477 
478                 return;
479         }
480 
481         if(shape1->getGImpactShapeType()==CONST_GIMPACT_TRIMESH_SHAPE)
482         {
483                 const btGImpactMeshShape * meshshape1 = static_cast<const btGImpactMeshShape *>(shape1);
484                 m_part1 = meshshape1->getMeshPartCount();
485 
486                 while(m_part1--)
487                 {
488 
489                         gimpact_vs_gimpact(body0Wrap,body1Wrap,shape0,meshshape1->getMeshPart(m_part1));
490 
491                 }
492 
493                 return;
494         }
495 
496 
497         btTransform orgtrans0 = body0Wrap->getWorldTransform();
498         btTransform orgtrans1 = body1Wrap->getWorldTransform();
499 
500         btPairSet pairset;
501 
502         gimpact_vs_gimpact_find_pairs(orgtrans0,orgtrans1,shape0,shape1,pairset);
503 
504         if(pairset.size()== 0) return;
505 
506         if(shape0->getGImpactShapeType() == CONST_GIMPACT_TRIMESH_SHAPE_PART &&
507                 shape1->getGImpactShapeType() == CONST_GIMPACT_TRIMESH_SHAPE_PART)
508         {
509                 const btGImpactMeshShapePart * shapepart0 = static_cast<const btGImpactMeshShapePart * >(shape0);
510                 const btGImpactMeshShapePart * shapepart1 = static_cast<const btGImpactMeshShapePart * >(shape1);
511                 //specialized function
512                 #ifdef BULLET_TRIANGLE_COLLISION
513                 collide_gjk_triangles(body0Wrap,body1Wrap,shapepart0,shapepart1,&pairset[0].m_index1,pairset.size());
514                 #else
515                 collide_sat_triangles(body0Wrap,body1Wrap,shapepart0,shapepart1,&pairset[0].m_index1,pairset.size());
516                 #endif
517 
518                 return;
519         }
520 
521         //general function
522 
523         shape0->lockChildShapes();
524         shape1->lockChildShapes();
525 
526         GIM_ShapeRetriever retriever0(shape0);
527         GIM_ShapeRetriever retriever1(shape1);
528 
529         bool child_has_transform0 = shape0->childrenHasTransform();
530         bool child_has_transform1 = shape1->childrenHasTransform();
531 
532         int i = pairset.size();
533         while(i--)
534         {
535                 GIM_PAIR * pair = &pairset[i];
536                 m_triface0 = pair->m_index1;
537                 m_triface1 = pair->m_index2;
538                 const btCollisionShape * colshape0 = retriever0.getChildShape(m_triface0);
539                 const btCollisionShape * colshape1 = retriever1.getChildShape(m_triface1);
540 
541                 btTransform tr0 = body0Wrap->getWorldTransform();
542                 btTransform tr1 = body1Wrap->getWorldTransform();
543 
544                 if(child_has_transform0)
545                 {
546                         tr0 = orgtrans0*shape0->getChildTransform(m_triface0);
547                 }
548 
549                 if(child_has_transform1)
550                 {
551                         tr1 = orgtrans1*shape1->getChildTransform(m_triface1);
552                 }
553 
554                 btCollisionObjectWrapper ob0(body0Wrap,colshape0,body0Wrap->getCollisionObject(),tr0,m_part0,m_triface0);
555                 btCollisionObjectWrapper ob1(body1Wrap,colshape1,body1Wrap->getCollisionObject(),tr1,m_part1,m_triface1);
556 
557                 //collide two convex shapes
558                 convex_vs_convex_collision(&ob0,&ob1,colshape0,colshape1);
559         }
560 
561         shape0->unlockChildShapes();
562         shape1->unlockChildShapes();
563 }
The documentation for this class was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp