C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/Gimpact/gim_basic_geometry_operations.h File Reference
#include `gim_linear_math.h`
Defines
#define TRIANGLE_PLANE(v1, v2, v3, plane)
plane is a vec4f
#define TRIANGLE_PLANE_FAST(v1, v2, v3, plane)
plane is a vec4f
#define EDGE_PLANE(e1, e2, n, plane)
Calc a plane from an edge an a normal. plane is a vec4f.
#define PLANE_MINOR_AXES(plane, i0, i1) VEC_MINOR_AXES(plane, i0, i1)
Finds the 2 smallest cartesian coordinates of a plane normal.
Functions
template<typename CLASS_POINT, typename CLASS_PLANE>
SIMD_FORCE_INLINE bool POINT_IN_HULL (const CLASS_POINT &point, const CLASS_PLANE *planes, GUINT plane_count)
Verifies if a point is in the plane hull.
template<typename CLASS_POINT, typename CLASS_PLANE>
SIMD_FORCE_INLINE eLINE_PLANE_INTERSECTION_TYPE PLANE_CLIP_SEGMENT2 (const CLASS_POINT &s1, const CLASS_POINT &s2, const CLASS_PLANE &plane, CLASS_POINT &clipped)
Confirms if the plane intersect the edge or nor.
template<typename CLASS_POINT, typename CLASS_PLANE>
SIMD_FORCE_INLINE eLINE_PLANE_INTERSECTION_TYPE PLANE_CLIP_SEGMENT_CLOSEST (const CLASS_POINT &s1, const CLASS_POINT &s2, const CLASS_PLANE &plane, CLASS_POINT &clipped1, CLASS_POINT &clipped2)
Confirms if the plane intersect the edge or not.
template<typename T, typename CLASS_POINT, typename CLASS_PLANE>
SIMD_FORCE_INLINE bool RAY_PLANE_COLLISION (const CLASS_PLANE &plane, const CLASS_POINT &vDir, const CLASS_POINT &vPoint, CLASS_POINT &pout, T &tparam)
Ray plane collision in one way.
template<typename T, typename CLASS_POINT, typename CLASS_PLANE>
SIMD_FORCE_INLINE GUINT LINE_PLANE_COLLISION (const CLASS_PLANE &plane, const CLASS_POINT &vDir, const CLASS_POINT &vPoint, CLASS_POINT &pout, T &tparam, T tmin, T tmax)
line collision
template<typename CLASS_POINT, typename CLASS_PLANE>
SIMD_FORCE_INLINE bool INTERSECT_PLANES (const CLASS_PLANE &p1, const CLASS_PLANE &p2, CLASS_POINT &p, CLASS_POINT &d)
Returns the Ray on which 2 planes intersect if they do. Written by Rodrigo Hernandez on ODE convex collision.
template<typename CLASS_POINT>
SIMD_FORCE_INLINE void CLOSEST_POINT_ON_SEGMENT (CLASS_POINT &cp, const CLASS_POINT &v, const CLASS_POINT &e1, const CLASS_POINT &e2)
template<typename T, typename CLASS_POINT>
SIMD_FORCE_INLINE bool LINE_INTERSECTION_PARAMS (const CLASS_POINT &dir1, CLASS_POINT &point1, const CLASS_POINT &dir2, CLASS_POINT &point2, T &t1, T &t2)
Finds the line params where these lines intersect.
template<typename CLASS_POINT>
SIMD_FORCE_INLINE void SEGMENT_COLLISION (const CLASS_POINT &vA1, const CLASS_POINT &vA2, const CLASS_POINT &vB1, const CLASS_POINT &vB2, CLASS_POINT &vPointA, CLASS_POINT &vPointB)
Find closest points on segments.
template<typename T>
SIMD_FORCE_INLINE bool BOX_AXIS_INTERSECT (T pos, T dir, T bmin, T bmax, T &tfirst, T &tlast)
Line box intersection in one dimension.
template<typename T>
SIMD_FORCE_INLINE void SORT_3_INDICES (const T *values, GUINT *order_indices)
Sorts 3 componets.
Detailed Description
Author: Francisco Leon Najera type independant geometry routines
Definition in file gim_basic_geometry_operations.h.
Function Documentation
template<typename T> SIMD_FORCE_INLINE bool BOX_AXIS_INTERSECT (T pos, T dir, T bmin, T bmax, T & tfirst, T & tlast) [inline]
Line box intersection in one dimension.
Parameters:
pos Position of the ray
dir Projection of the Direction of the ray
bmin Minimum bound of the box
bmax Maximum bound of the box
tfirst the minimum projection. Assign to 0 at first.
tlast the maximum projection. Assign to INFINITY at first.
Returns: true if there is an intersection.
Definition at line 501 of file gim_basic_geometry_operations.h.
References GIM_SWAP_NUMBERS.
502 {
503         if(GIM_IS_ZERO(dir))
504         {
505         return !(pos < bmin || pos > bmax);
506         }
507         GREAL a0 = (bmin - pos) / dir;
508         GREAL a1 = (bmax - pos) / dir;
509         if(a0 > a1)   GIM_SWAP_NUMBERS(a0, a1);
510         tfirst = GIM_MAX(a0, tfirst);
511         tlast = GIM_MIN(a1, tlast);
512         if (tlast < tfirst) return false;
513         return true;
514 }
template<typename CLASS_POINT> SIMD_FORCE_INLINE void CLOSEST_POINT_ON_SEGMENT (CLASS_POINT & cp, const CLASS_POINT & v, const CLASS_POINT & e1, const CLASS_POINT & e2) [inline]
Finds the closest point(cp) to (v) on a segment (e1,e2)
Definition at line 341 of file gim_basic_geometry_operations.h.
References VEC_COPY, VEC_DIFF, VEC_DOT, VEC_SCALE, and VEC_SUM.
Referenced by SEGMENT_COLLISION().
344 {
345     vec3f _n;
346     VEC_DIFF(_n,e2,e1);
347     VEC_DIFF(cp,v,e1);
348         GREAL _scalar = VEC_DOT(cp, _n);
349         _scalar/= VEC_DOT(_n, _n);
350         if(_scalar <0.0f)
351         {
352             VEC_COPY(cp,e1);
353         }
354         else if(_scalar >1.0f)
355         {
356             VEC_COPY(cp,e2);
357         }
358         else
359         {
360         VEC_SCALE(cp,_scalar,_n);
361         VEC_SUM(cp,cp,e1);
362         }
363 }
template<typename CLASS_POINT, typename CLASS_PLANE> SIMD_FORCE_INLINE bool INTERSECT_PLANES (const CLASS_PLANE & p1, const CLASS_PLANE & p2, CLASS_POINT & p, CLASS_POINT & d) [inline]
Returns the Ray on which 2 planes intersect if they do. Written by Rodrigo Hernandez on ODE convex collision.
Parameters:
p1 Plane 1
p2 Plane 2
p Contains the origin of the ray upon returning if planes intersect
d Contains the direction of the ray upon returning if planes intersect
Returns: true if the planes intersect, 0 if paralell.
Definition at line 316 of file gim_basic_geometry_operations.h.
References VEC_CROSS, and VEC_DOT.
321 {
322         VEC_CROSS(d,p1,p2);
323         GREAL denom = VEC_DOT(d, d);
324         if(GIM_IS_ZERO(denom)) return false;
325         vec3f _n;
326         _n[0]=p1[3]*p2[0] - p2[3]*p1[0];
327         _n[1]=p1[3]*p2[1] - p2[3]*p1[1];
328         _n[2]=p1[3]*p2[2] - p2[3]*p1[2];
329         VEC_CROSS(p,_n,d);
330         p[0]/=denom;
331         p[1]/=denom;
332         p[2]/=denom;
333         return true;
334 }
template<typename T, typename CLASS_POINT> SIMD_FORCE_INLINE bool LINE_INTERSECTION_PARAMS (const CLASS_POINT & dir1, CLASS_POINT & point1, const CLASS_POINT & dir2, CLASS_POINT & point2, T & t1, T & t2) [inline]
Finds the line params where these lines intersect.
Parameters:
dir1 Direction of line 1
point1 Point of line 1
dir2 Direction of line 2
point2 Point of line 2
t1 Result Parameter for line 1
t2 Result Parameter for line 2
dointersect 0 if the lines won't intersect, else 1
Definition at line 378 of file gim_basic_geometry_operations.h.
References VEC_DIFF, and VEC_DOT.
384 {
385     GREAL det;
386         GREAL e1e1 = VEC_DOT(dir1,dir1);
387         GREAL e1e2 = VEC_DOT(dir1,dir2);
388         GREAL e2e2 = VEC_DOT(dir2,dir2);
389         vec3f p1p2;
390     VEC_DIFF(p1p2,point1,point2);
391     GREAL p1p2e1 = VEC_DOT(p1p2,dir1);
392         GREAL p1p2e2 = VEC_DOT(p1p2,dir2);
393         det = e1e2*e1e2 - e1e1*e2e2;
394         if(GIM_IS_ZERO(det)) return false;
395         t1 = (e1e2*p1p2e2 - e2e2*p1p2e1)/det;
396         t2 = (e1e1*p1p2e2 - e1e2*p1p2e1)/det;
397         return true;
398 }
template<typename T, typename CLASS_POINT, typename CLASS_PLANE> SIMD_FORCE_INLINE GUINT LINE_PLANE_COLLISION (const CLASS_PLANE & plane, const CLASS_POINT & vDir, const CLASS_POINT & vPoint, CLASS_POINT & pout, T & tparam, T tmin, T tmax) [inline]
line collision
Returns: -0 if the ray never intersects -1 if the ray collides in front -2 if the ray collides in back
Definition at line 270 of file gim_basic_geometry_operations.h.
References VEC_DOT, VEC_SCALE, and VEC_SUM.
Referenced by GIM_TRIANGLE::ray_collision(), GIM_TRIANGLE::ray_collision_front_side(), and SEGMENT_COLLISION().
277 {
278         GREAL _dis,_dotdir;
279         _dotdir = VEC_DOT(plane,vDir);
280         if(btFabs(_dotdir)<PLANEDIREPSILON)
281         {
282                 tparam = tmax;
283             return 0;
284         }
285         _dis = DISTANCE_PLANE_POINT(plane,vPoint);
286         char returnvalue = _dis<0.0f?2:1;
287         tparam = -_dis/_dotdir;
288 
289         if(tparam<tmin)
290         {
291                 returnvalue = 0;
292                 tparam = tmin;
293         }
294         else if(tparam>tmax)
295         {
296                 returnvalue = 0;
297                 tparam = tmax;
298         }
299 
300         VEC_SCALE(pout,tparam,vDir);
301         VEC_SUM(pout,vPoint,pout);
302         return returnvalue;
303 }
template<typename CLASS_POINT, typename CLASS_PLANE> SIMD_FORCE_INLINE eLINE_PLANE_INTERSECTION_TYPE PLANE_CLIP_SEGMENT2 (const CLASS_POINT & s1, const CLASS_POINT & s2, const CLASS_PLANE & plane, CLASS_POINT & clipped) [inline]
Confirms if the plane intersect the edge or nor.
intersection type must have the following values
0 : Segment in front of plane, s1 closest
1 : Segment in front of plane, s2 closest
2 : Segment in back of plane, s1 closest
3 : Segment in back of plane, s2 closest
4 : Segment collides plane, s1 in back
5 : Segment collides plane, s2 in back
Definition at line 156 of file gim_basic_geometry_operations.h.
References VEC_DIFF, VEC_DOT, VEC_SCALE, and VEC_SUM.
Referenced by PLANE_CLIP_SEGMENT_CLOSEST().
160 {
161         GREAL _dis1 = DISTANCE_PLANE_POINT(plane,s1);
162         GREAL _dis2 = DISTANCE_PLANE_POINT(plane,s2);
163         if(_dis1 >-G_EPSILON && _dis2 >-G_EPSILON)
164         {
165             if(_dis1<_dis2) return G_FRONT_PLANE_S1;
166             return G_FRONT_PLANE_S2;
167         }
168         else if(_dis1 <G_EPSILON && _dis2 <G_EPSILON)
169         {
170             if(_dis1>_dis2) return G_BACK_PLANE_S1;
171             return G_BACK_PLANE_S2;
172         }
173 
174         VEC_DIFF(clipped,s2,s1);
175         _dis2 = VEC_DOT(clipped,plane);
176         VEC_SCALE(clipped,-_dis1/_dis2,clipped);
177         VEC_SUM(clipped,clipped,s1);
178         if(_dis1<_dis2) return G_COLLIDE_PLANE_S1;
179         return G_COLLIDE_PLANE_S2;
180 }
template<typename CLASS_POINT, typename CLASS_PLANE> SIMD_FORCE_INLINE eLINE_PLANE_INTERSECTION_TYPE PLANE_CLIP_SEGMENT_CLOSEST (const CLASS_POINT & s1, const CLASS_POINT & s2, const CLASS_PLANE & plane, CLASS_POINT & clipped1, CLASS_POINT & clipped2) [inline]
Confirms if the plane intersect the edge or not.
clipped1 and clipped2 are the vertices behind the plane. clipped1 is the closest
intersection_type must have the following values
0 : Segment in front of plane, s1 closest
1 : Segment in front of plane, s2 closest
2 : Segment in back of plane, s1 closest
3 : Segment in back of plane, s2 closest
4 : Segment collides plane, s1 in back
5 : Segment collides plane, s2 in back
Definition at line 198 of file gim_basic_geometry_operations.h.
References PLANE_CLIP_SEGMENT2(), and VEC_COPY.
203 {
204         eLINE_PLANE_INTERSECTION_TYPE intersection_type = PLANE_CLIP_SEGMENT2(s1,s2,plane,clipped1);
205         switch(intersection_type)
206         {
207         case G_FRONT_PLANE_S1:
208                 VEC_COPY(clipped1,s1);
209             VEC_COPY(clipped2,s2);
210                 break;
211         case G_FRONT_PLANE_S2:
212                 VEC_COPY(clipped1,s2);
213             VEC_COPY(clipped2,s1);
214                 break;
215         case G_BACK_PLANE_S1:
216                 VEC_COPY(clipped1,s1);
217             VEC_COPY(clipped2,s2);
218                 break;
219         case G_BACK_PLANE_S2:
220                 VEC_COPY(clipped1,s2);
221             VEC_COPY(clipped2,s1);
222                 break;
223         case G_COLLIDE_PLANE_S1:
224                 VEC_COPY(clipped2,s1);
225                 break;
226         case G_COLLIDE_PLANE_S2:
227                 VEC_COPY(clipped2,s2);
228                 break;
229         }
230         return intersection_type;
231 }
template<typename T, typename CLASS_POINT, typename CLASS_PLANE> SIMD_FORCE_INLINE bool RAY_PLANE_COLLISION (const CLASS_PLANE & plane, const CLASS_POINT & vDir, const CLASS_POINT & vPoint, CLASS_POINT & pout, T & tparam) [inline]
Ray plane collision in one way.
Intersects plane in one way only. The ray must face the plane (normals must be in opossite directions).
 It uses the PLANEDIREPSILON constant.
Definition at line 243 of file gim_basic_geometry_operations.h.
References VEC_DOT, VEC_SCALE, and VEC_SUM.
248 {
249         GREAL _dis,_dotdir;
250         _dotdir = VEC_DOT(plane,vDir);
251         if(_dotdir<PLANEDIREPSILON)
252         {
253             return false;
254         }
255         _dis = DISTANCE_PLANE_POINT(plane,vPoint);
256         tparam = -_dis/_dotdir;
257         VEC_SCALE(pout,tparam,vDir);
258         VEC_SUM(pout,vPoint,pout);
259         return true;
260 }