C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/BulletCollision/Gimpact/gim_radixsort.h File Reference
#include `gim_memory.h`
Classes
class less_comparator
class integer_comparator
Prototype for comparators.
class uint_key_func
Prototype for getting the integer representation of an object.
class copy_elements_func
Prototype for copying elements.
class memcopy_elements_func
Prototype for copying elements.
class GIM_RSORT_TOKEN_COMPARATOR
Prototype for comparators.
void gim_radix_sort_rtokens (GIM_RSORT_TOKEN *array, GIM_RSORT_TOKEN *sorted, GUINT element_count)
Radix sort for unsigned integer keys.
template<typename T, class GETKEY_CLASS>
void gim_radix_sort_array_tokens (T *array, GIM_RSORT_TOKEN *sorted_tokens, GUINT element_count, GETKEY_CLASS uintkey_macro)
Get the sorted tokens from an array. For generic use. Tokens are IRR_RSORT_TOKEN.
template<typename T, class GETKEY_CLASS, class COPY_CLASS>
void gim_radix_sort (T *array, GUINT element_count, GETKEY_CLASS get_uintkey_macro, COPY_CLASS copy_elements_macro)
Sorts array in place. For generic use.
template<class T, typename KEYCLASS, typename COMP_CLASS>
bool gim_binary_search_ex (const T *_array, GUINT _start_i, GUINT _end_i, GUINT &_result_index, const KEYCLASS &_search_key, COMP_CLASS _comp_macro)
Failsafe Iterative binary search,.
template<class T>
bool gim_binary_search (const T *_array, GUINT _start_i, GUINT _end_i, const T &_search_key, GUINT &_result_index)
Failsafe Iterative binary search,Template version.
template<typename T, typename COMP_CLASS>
void gim_down_heap (T *pArr, GUINT k, GUINT n, COMP_CLASS CompareFunc)
heap sort from http://www.csse.monash.edu.au/~lloyd/tildeAlgDS/Sort/Heap/
Detailed Description
Author: Francisco Leon Najera. Based on the work of Michael Herf : `fast floating-point radix sort` Avaliable on http://www.stereopsis.com/radix.html
Definition in file gim_radixsort.h.
Function Documentation
template<class T> bool gim_binary_search (const T * _array, GUINT _start_i, GUINT _end_i, const T & _search_key, GUINT & _result_index) [inline]
Failsafe Iterative binary search,Template version.
If the element is not found, it returns the nearest upper element position, may be the further position after the last element.
Parameters:
_array
_start_i the beginning of the array
_end_i the ending index of the array
_search_key Value to find
_result_index the index of the found element, or if not found then it will get the index of the closest bigger value
Returns: true if found, else false
Definition at line 318 of file gim_radixsort.h.
322 {
323         GUINT _i = _start_i;
324         GUINT _j = _end_i+1;
325         GUINT _k;
326         while(_i < _j)
327         {
328                 _k = (_j+_i-1)/2;
329                 if(_array[_k]==_search_key)
330                 {
331                         _result_index = _k;
332                         return true;
333                 }
334                 else if (_array[_k]<_search_key)
335                 {
336                         _i = _k+1;
337                 }
338                 else
339                 {
340                         _j = _k;
341                 }
342         }
343         _result_index = _i;
344         return false;
345 }
template<class T, typename KEYCLASS, typename COMP_CLASS> bool gim_binary_search_ex (const T * _array, GUINT _start_i, GUINT _end_i, GUINT & _result_index, const KEYCLASS & _search_key, COMP_CLASS _comp_macro) [inline]
Failsafe Iterative binary search,.
If the element is not found, it returns the nearest upper element position, may be the further position after the last element.
Parameters:
_array
_start_i the beginning of the array
_end_i the ending index of the array
_search_key Value to find
_comp_macro macro for comparing elements
_found If true the value has found. Boolean
_result_index the index of the found element, or if not found then it will get the index of the closest bigger value
Definition at line 273 of file gim_radixsort.h.
Referenced by gim_hash_table< T >::_insert_sorted(), and gim_hash_table< T >::find().
278 {
279         GUINT _k;
280         int _comp_result;
281         GUINT _i = _start_i;
282         GUINT _j = _end_i+1;
283         while (_i < _j)
284         {
285                 _k = (_j+_i-1)/2;
286                 _comp_result = _comp_macro(_array[_k], _search_key);
287                 if (_comp_result == 0)
288                 {
289                         _result_index = _k;
290                         return true;
291                 }
292                 else if (_comp_result < 0)
293                 {
294                         _i = _k+1;
295                 }
296                 else
297                 {
298                         _j = _k;
299                 }
300         }
301         _result_index = _i;
302         return false;
303 }
template<typename T, class GETKEY_CLASS, class COPY_CLASS> void gim_radix_sort (T * array, GUINT element_count, GETKEY_CLASS get_uintkey_macro, COPY_CLASS copy_elements_macro) [inline]
Sorts array in place. For generic use.
Parameters:
type Type of the array
array
element_count
get_uintkey_macro Macro for extract the Integer value of the element. Similar to SIMPLE_GET_UINTKEY
copy_elements_macro Macro for copy elements, similar to SIMPLE_COPY_ELEMENTS
Definition at line 245 of file gim_radixsort.h.
References gim_radix_sort_array_tokens().
248 {
249         GIM_RSORT_TOKEN * _sorted = (GIM_RSORT_TOKEN  *) gim_alloc(sizeof(GIM_RSORT_TOKEN)*element_count);
250     gim_radix_sort_array_tokens(array,_sorted,element_count,get_uintkey_macro);
251     T * _original_array = (T *) gim_alloc(sizeof(T)*element_count);
252     gim_simd_memcpy(_original_array,array,sizeof(T)*element_count);
253     for (GUINT _i=0;_i<element_count;++_i)
254     {
255         copy_elements_macro(array[_i],_original_array[_sorted[_i].m_value]);
256     }
257     gim_free(_original_array);
258     gim_free(_sorted);
259 }
template<typename T, class GETKEY_CLASS> void gim_radix_sort_array_tokens (T * array, GIM_RSORT_TOKEN * sorted_tokens, GUINT element_count, GETKEY_CLASS uintkey_macro) [inline]
Get the sorted tokens from an array. For generic use. Tokens are IRR_RSORT_TOKEN.
Parameters:
array Array of elements to sort
sorted_tokens Tokens of sorted elements
element_count element count
uintkey_macro Functor which retrieves the integer representation of an array element
Definition at line 220 of file gim_radixsort.h.
References gim_radix_sort_rtokens().
Referenced by gim_radix_sort().
224 {
225         GIM_RSORT_TOKEN * _unsorted = (GIM_RSORT_TOKEN *) gim_alloc(sizeof(GIM_RSORT_TOKEN)*element_count);
226     for (GUINT _i=0;_i<element_count;++_i)
227     {
228         _unsorted[_i].m_key = uintkey_macro(array[_i]);
229         _unsorted[_i].m_value = _i;
230     }
231     gim_radix_sort_rtokens(_unsorted,sorted_tokens,element_count);
232     gim_free(_unsorted);
233     gim_free(_unsorted);
234 }