GLM_GTX_fast_square_root
Sqrt optimisation based on Newton's method, www.gamedev.net/community/forums/topic.asp?topic id=139956.
Functions
template<typename genType>
GLM_FUNC_DECL genType glm::fastSqrt (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::fastInverseSqrt (genType const &x)
template<typename T, precision P, template< typename, precision > class vecType>
GLM_FUNC_DECL vecType< T, P > glm::fastInverseSqrt (vecType< T, P > const &x)
template<typename genType>
GLM_FUNC_DECL genType::value_type glm::fastLength (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType::value_type glm::fastDistance (genType const &x, genType const &y)
template<typename genType>
GLM_FUNC_DECL genType glm::fastNormalize (genType const &x)
Detailed Description
Fast but less accurate implementations of square root based functions.
Sqrt optimisation based on Newton's method, www.gamedev.net/community/forums/topic.asp?topic id=139956.
<glm/gtx/fast_square_root.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType> GLM_FUNC_QUALIFIER genType glm::fastDistance (genType const & x, genType const & y) [inline]
Faster than the common distance function but less accurate. From GLM_GTX_fast_square_root extension.
Definition at line 103 of file fast_square_root.inl.
References glm::fastLength().
107         {
108                 return fastLength(y - x);
109         }
template<typename T, precision P, template< typename, precision > class vecType> GLM_FUNC_QUALIFIER vecType< T, P > glm::fastInverseSqrt (vecType< T, P > const & x) [inline]
Faster than the common inversesqrt function but less accurate. From GLM_GTX_fast_square_root extension.
Definition at line 51 of file fast_square_root.inl.
54         {
55                 return detail::compute_inversesqrt<vecType, T, P>::call(x);
56         }
template<typename genType> GLM_FUNC_DECL genType glm::fastInverseSqrt (genType const & x) [inline]
Faster than the common inversesqrt function but less accurate. From GLM_GTX_fast_square_root extension.
Referenced by glm::fastNormalizeDot(), and glm::fastSqrt().
template<typename genType> GLM_FUNC_QUALIFIER genType glm::fastLength (genType const & x) [inline]
Faster than the common length function but less accurate. From GLM_GTX_fast_square_root extension.
Definition at line 63 of file fast_square_root.inl.
References glm::abs().
Referenced by glm::fastDistance().
66         {
67                 return abs(x);
68         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::fastNormalize (genType const & x) [inline]
Faster than the common normalize function but less accurate. From GLM_GTX_fast_square_root extension.
Definition at line 144 of file fast_square_root.inl.
147         {
148                 return x > genType(0) ? genType(1) : -genType(1);
149         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::fastSqrt (genType const & x) [inline]
Faster than the common sqrt function but less accurate. From GLM_GTX_fast_square_root extension.
Definition at line 15 of file fast_square_root.inl.
References glm::fastInverseSqrt().
18         {
19                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'fastSqrt' only accept floating-point input");
20 
21                 return genType(1) / fastInverseSqrt(x);
22         }