GLM_GTX_orthonormalize
Functions
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat3x3< T, P > glm::orthonormalize (const detail::tmat3x3< T, P > &m)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::orthonormalize (const detail::tvec3< T, P > &x, const detail::tvec3< T, P > &y)
Detailed Description
Orthonormalize matrices.
<glm/gtx/orthonormalize.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::orthonormalize (const detail::tvec3< T, P > & x, const detail::tvec3< T, P > & y) [inline]
Orthonormalizes x according y. From GLM_GTX_orthonormalize extension.
Definition at line 36 of file orthonormalize.inl.
References glm::dot(), and glm::normalize().
40         {
41                 return normalize(x - y * dot(y, x));
42         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat3x3< T, P > glm::orthonormalize (const detail::tmat3x3< T, P > & m) [inline]
Returns the orthonormalized matrix of m. From GLM_GTX_orthonormalize extension.
Definition at line 14 of file orthonormalize.inl.
References glm::dot(), and glm::normalize().
17         {
18                 detail::tmat3x3<T, P> r = m;
19 
20                 r[0] = normalize(r[0]);
21 
22                 float d0 = dot(r[0], r[1]);
23                 r[1] -= r[0] * d0;
24                 r[1] = normalize(r[1]);
25 
26                 float d1 = dot(r[1], r[2]);
27                 d0 = dot(r[0], r[2]);
28                 r[2] -= r[0] * d0 + r[1] * d1;
29                 r[2] = normalize(r[2]);
30 
31                 return r;
32         }