GLM_GTC_reciprocal
Functions
template<typename genType>
GLM_FUNC_DECL genType glm::sec (genType const &angle)
template<typename genType>
GLM_FUNC_DECL genType glm::csc (genType const &angle)
template<typename genType>
GLM_FUNC_DECL genType glm::cot (genType const &angle)
template<typename genType>
GLM_FUNC_DECL genType glm::asec (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::acsc (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::acot (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::sech (genType const &angle)
template<typename genType>
GLM_FUNC_DECL genType glm::csch (genType const &angle)
template<typename genType>
GLM_FUNC_DECL genType glm::coth (genType const &angle)
template<typename genType>
GLM_FUNC_DECL genType glm::asech (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::acsch (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::acoth (genType const &x)
Detailed Description
Define secant, cosecant and cotangent functions.
<glm/gtc/reciprocal.hpp> need to be included to use these features.
Function Documentation
template<typename genType> GLM_FUNC_QUALIFIER genType glm::acot (genType const & x) [inline]
Inverse cotangent function.
See also: GLM_GTC_reciprocal
Definition at line 107 of file reciprocal.inl.
References glm::atan().
110         {
111                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'acot' only accept floating-point values");
112 
113                 genType const pi_over_2 = genType(3.1415926535897932384626433832795 / 2.0);
114                 return pi_over_2 - atan(x);
115         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::acoth (genType const & x) [inline]
Inverse cotangent hyperbolic function.
See also: GLM_GTC_reciprocal
Definition at line 192 of file reciprocal.inl.
References glm::atanh().
195         {
196                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'acoth' only accept floating-point values");
197 
198                 return atanh(genType(1) / x);
199         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::acsc (genType const & x) [inline]
Inverse cosecant function.
See also: GLM_GTC_reciprocal
Definition at line 93 of file reciprocal.inl.
References glm::asin().
96         {
97                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'acsc' only accept floating-point values");
98 
99                 return asin(genType(1) / x);
100         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::acsch (genType const & x) [inline]
Inverse cosecant hyperbolic function.
See also: GLM_GTC_reciprocal
Definition at line 178 of file reciprocal.inl.
References glm::asinh().
181         {
182                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'acsch' only accept floating-point values");
183 
184                 return asinh(genType(1) / x);
185         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::asec (genType const & x) [inline]
Inverse secant function.
See also: GLM_GTC_reciprocal
Definition at line 79 of file reciprocal.inl.
References glm::acos().
82         {
83                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'asec' only accept floating-point values");
84         
85                 return acos(genType(1) / x);
86         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::asech (genType const & x) [inline]
Inverse secant hyperbolic function.
See also: GLM_GTC_reciprocal
Definition at line 164 of file reciprocal.inl.
References glm::acosh().
167         {
168                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'asech' only accept floating-point values");
169 
170                 return acosh(genType(1) / x);
171         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::cot (genType const & angle) [inline]
Cotangent function. adjacent / opposite or 1 / tan(x)
See also: GLM_GTC_reciprocal
Definition at line 65 of file reciprocal.inl.
References glm::tan().
68         {
69                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'cot' only accept floating-point values");
70 
71                 return genType(1) / glm::tan(angle);
72         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::coth (genType const & angle) [inline]
Cotangent hyperbolic function.
See also: GLM_GTC_reciprocal
Definition at line 150 of file reciprocal.inl.
References glm::cosh(), and glm::sinh().
153         {
154                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'coth' only accept floating-point values");
155 
156                 return glm::cosh(angle) / glm::sinh(angle);
157         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::csc (genType const & angle) [inline]
Cosecant function. hypotenuse / opposite or 1 / sin(x)
See also: GLM_GTC_reciprocal
Definition at line 51 of file reciprocal.inl.
References glm::sin().
54         {
55                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'csc' only accept floating-point values");
56 
57                 return genType(1) / glm::sin(angle);
58         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::csch (genType const & angle) [inline]
Cosecant hyperbolic function.
See also: GLM_GTC_reciprocal
Definition at line 136 of file reciprocal.inl.
References glm::sinh().
139         {
140                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'csch' only accept floating-point values");
141 
142                 return genType(1) / glm::sinh(angle);
143         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::sec (genType const & angle) [inline]
Secant function. hypotenuse / adjacent or 1 / cos(x)
See also: GLM_GTC_reciprocal
Definition at line 37 of file reciprocal.inl.
References glm::cos().
40         {
41                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'sec' only accept floating-point values");
42 
43                 return genType(1) / glm::cos(angle);
44         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::sech (genType const & angle) [inline]
Secant hyperbolic function.
See also: GLM_GTC_reciprocal
Definition at line 122 of file reciprocal.inl.
References glm::cosh().
125         {
126                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'sech' only accept floating-point values");
127 
128                 return genType(1) / glm::cosh(angle);
129         }