Exponential functions
Functions
template<typename genType>
GLM_FUNC_DECL genType glm::pow (genType const &base, genType const &exponent)
template<typename genType>
GLM_FUNC_DECL genType glm::exp (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::log (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::exp2 (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::log2 (genType x)
template<typename T, precision P, template< typename, precision > class vecType>
GLM_FUNC_DECL vecType< T, P > glm::sqrt (vecType< T, P > const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::inversesqrt (genType const &x)
Detailed Description
These all operate component-wise. The description is per component.
Function Documentation
template<typename genType> GLM_FUNC_QUALIFIER genType glm::exp (genType const & x) [inline]
Returns the natural exponentiation of x, i.e., e^x.
Parameters:
x exp function is defined for input values of x defined in the range (inf-, inf+) in the limit of the type precision.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL exp man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 100 of file func_exponential.inl.
References glm::exp().
Referenced by glm::fastPow(), and glm::intermediate().
103         {
104                 GLM_STATIC_ASSERT(
105                         std::numeric_limits<genType>::is_iec559,
106                         "'exp' only accept floating-point inputs");
107 
108                 return std::exp(x);
109         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::exp2 (genType const & x) [inline]
Returns 2 raised to the x power.
Parameters:
x exp2 function is defined for input values of x defined in the range (inf-, inf+) in the limit of the type precision.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL exp2 man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 131 of file func_exponential.inl.
References glm::exp().
132         {
133                 GLM_STATIC_ASSERT(
134                         std::numeric_limits<genType>::is_iec559,
135                         "'exp2' only accept floating-point inputs");
136 
137                 return std::exp(static_cast<genType>(0.69314718055994530941723212145818) * x);
138         }
template<typename genType> GLM_FUNC_DECL genType glm::inversesqrt (genType const & x) [inline]
Returns the reciprocal of the positive square root of x.
Parameters:
x inversesqrt function is defined for input values of x defined in the range [0, inf+) in the limit of the type precision.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL inversesqrt man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Referenced by glm::normalizeDot().
template<typename genType> GLM_FUNC_QUALIFIER genType glm::log (genType const & x) [inline]
Returns the natural logarithm of x, i.e., returns the value y which satisfies the equation x = e^y. Results are undefined if x <= 0.
Parameters:
x log function is defined for input values of x defined in the range (0, inf+) in the limit of the type precision.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL log man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 116 of file func_exponential.inl.
References glm::log().
Referenced by glm::acosh(), glm::asinh(), glm::atanh(), glm::fastPow(), glm::gaussRand(), glm::intermediate(), and glm::log().
119         {
120                 GLM_STATIC_ASSERT(
121                         std::numeric_limits<genType>::is_iec559,
122                         "'log' only accept floating-point inputs");
123 
124                 return std::log(x);
125         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::log2 (genType x) [inline]
Returns the base 2 log of x, i.e., returns the value y, which satisfies the equation x = 2 ^ y.
Parameters:
x log2 function is defined for input values of x defined in the range (0, inf+) in the limit of the type precision.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL log2 man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 144 of file func_exponential.inl.
145         {
146                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559 || std::numeric_limits<genType>::is_integer,
147                         "GLM core 'log2' only accept floating-point inputs. Include <glm/gtx/integer.hpp> for additional integer support.");
148 
149                 assert(x > genType(0)); // log2 is only defined on the range (0, inf]
150                 return detail::compute_log2<std::numeric_limits<genType>::is_iec559>()(x);
151         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::pow (genType const & base, genType const & exponent) [inline]
Returns 'base' raised to the power 'exponent'.
Parameters:
base Floating point value. pow function is defined for input values of x defined in the range (inf-, inf+) in the limit of the type precision.
exponent Floating point value representing the 'exponent'.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL pow man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 83 of file func_exponential.inl.
References glm::pow().
Referenced by glm::lxNorm().
87         {
88                 GLM_STATIC_ASSERT(
89                         std::numeric_limits<genType>::is_iec559,
90                         "'pow' only accept floating-point inputs");
91 
92                 return std::pow(x, y);
93         }
template<typename T, precision P, template< typename, precision > class vecType> GLM_FUNC_QUALIFIER vecType< T, P > glm::sqrt (vecType< T, P > const & x) [inline]
Returns the positive square root of x.
Parameters:
x sqrt function is defined for input values of x defined in the range [0, inf+) in the limit of the type precision.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL sqrt man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 219 of file func_exponential.inl.
Referenced by glm::acosh(), glm::asinh(), glm::axisAngle(), glm::dualquat_cast(), glm::extractRealComponent(), glm::gaussRand(), glm::intersectLineSphere(), glm::intersectRaySphere(), glm::length(), glm::log(), glm::polar(), glm::radialGradient(), glm::rotation(), glm::shortMix(), and glm::sphericalRand().
220         {
221                 GLM_STATIC_ASSERT(std::numeric_limits<T>::is_iec559, "'sqrt' only accept floating-point inputs");
222                 return detail::compute_sqrt<vecType, T, P>::call(x);
223         }