GLM_GTX_euler_angles
Functions
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::eulerAngleX (T const &angleX)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::eulerAngleY (T const &angleY)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::eulerAngleZ (T const &angleZ)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::eulerAngleXY (T const &angleX, T const &angleY)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::eulerAngleYX (T const &angleY, T const &angleX)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::eulerAngleXZ (T const &angleX, T const &angleZ)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::eulerAngleZX (T const &angle, T const &angleX)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::eulerAngleYZ (T const &angleY, T const &angleZ)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::eulerAngleZY (T const &angleZ, T const &angleY)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::eulerAngleYXZ (T const &yaw, T const &pitch, T const &roll)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::yawPitchRoll (T const &yaw, T const &pitch, T const &roll)
template<typename T>
GLM_FUNC_DECL detail::tmat2x2< T, defaultp > glm::orientate2 (T const &angle)
template<typename T>
GLM_FUNC_DECL detail::tmat3x3< T, defaultp > glm::orientate3 (T const &angle)
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat3x3< T, P > glm::orientate3 (detail::tvec3< T, P > const &angles)
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat4x4< T, P > glm::orientate4 (detail::tvec3< T, P > const &angles)
Detailed Description
Build matrices from Euler angles.
<glm/gtx/euler_angles.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::eulerAngleX (T const & angleX) [inline]
Creates a 3D 4 * 4 homogeneous rotation matrix from an euler angle X.
See also: GLM_GTX_euler_angles
Definition at line 14 of file euler_angles.inl.
References glm::cos(), and glm::sin().
Referenced by glm::eulerAngleXZ(), and glm::eulerAngleZX().
17         {
18                 T cosX = glm::cos(angleX);
19                 T sinX = glm::sin(angleX);
20         
21                 return detail::tmat4x4<T, defaultp>(
22                         T(1), T(0), T(0), T(0),
23                         T(0), cosX, sinX, T(0),
24                         T(0),-sinX, cosX, T(0),
25                         T(0), T(0), T(0), T(1));
26         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::eulerAngleXY (T const & angleX, T const & angleY) [inline]
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (X * Y).
See also: GLM_GTX_euler_angles
Definition at line 62 of file euler_angles.inl.
References glm::cos(), and glm::sin().
66         {
67                 T cosX = glm::cos(angleX);
68                 T sinX = glm::sin(angleX);
69                 T cosY = glm::cos(angleY);
70                 T sinY = glm::sin(angleY);
71 
72                 return detail::tmat4x4<T, defaultp>(
73                         cosY,   -sinX * -sinY,  cosX * -sinY,   T(0),
74                         T(0),   cosX,           sinX,           T(0),
75                         sinY,   -sinX * cosY,   cosX * cosY,    T(0),
76                         T(0),   T(0),           T(0),           T(1));
77         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::eulerAngleXZ (T const & angleX, T const & angleZ) [inline]
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (X * Z).
See also: GLM_GTX_euler_angles
Definition at line 100 of file euler_angles.inl.
References glm::eulerAngleX(), and glm::eulerAngleZ().
104         {
105                 return eulerAngleX(angleX) * eulerAngleZ(angleZ);
106         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::eulerAngleY (T const & angleY) [inline]
Creates a 3D 4 * 4 homogeneous rotation matrix from an euler angle Y.
See also: GLM_GTX_euler_angles
Definition at line 30 of file euler_angles.inl.
References glm::cos(), and glm::sin().
Referenced by glm::eulerAngleYZ(), and glm::eulerAngleZY().
33         {
34                 T cosY = glm::cos(angleY);
35                 T sinY = glm::sin(angleY);
36 
37                 return detail::tmat4x4<T, defaultp>(
38                         cosY,   T(0),   -sinY,  T(0),
39                         T(0),   T(1),   T(0),   T(0),
40                         sinY,   T(0),   cosY,   T(0),
41                         T(0),   T(0),   T(0),   T(1));
42         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::eulerAngleYX (T const & angleY, T const & angleX) [inline]
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * X).
See also: GLM_GTX_euler_angles
Definition at line 81 of file euler_angles.inl.
References glm::cos(), and glm::sin().
85         {
86                 T cosX = glm::cos(angleX);
87                 T sinX = glm::sin(angleX);
88                 T cosY = glm::cos(angleY);
89                 T sinY = glm::sin(angleY);
90 
91                 return detail::tmat4x4<T, defaultp>(
92                         cosY,          0,      -sinY,    T(0),
93                         sinY * sinX,  cosX, cosY * sinX, T(0),
94                         sinY * cosX, -sinX, cosY * cosX, T(0),
95                         T(0),         T(0),     T(0),    T(1));
96         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::eulerAngleYXZ (T const & yaw, T const & pitch, T const & roll) [inline]
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * X * Z).
See also: GLM_GTX_euler_angles
Definition at line 140 of file euler_angles.inl.
References glm::cos(), and glm::sin().
145         {
146                 T tmp_ch = glm::cos(yaw);
147                 T tmp_sh = glm::sin(yaw);
148                 T tmp_cp = glm::cos(pitch);
149                 T tmp_sp = glm::sin(pitch);
150                 T tmp_cb = glm::cos(roll);
151                 T tmp_sb = glm::sin(roll);
152 
153                 detail::tmat4x4<T, defaultp> Result;
154                 Result[0][0] = tmp_ch * tmp_cb + tmp_sh * tmp_sp * tmp_sb;
155                 Result[0][1] = tmp_sb * tmp_cp;
156                 Result[0][2] = -tmp_sh * tmp_cb + tmp_ch * tmp_sp * tmp_sb;
157                 Result[0][3] = static_cast<T>(0);
158                 Result[1][0] = -tmp_ch * tmp_sb + tmp_sh * tmp_sp * tmp_cb;
159                 Result[1][1] = tmp_cb * tmp_cp;
160                 Result[1][2] = tmp_sb * tmp_sh + tmp_ch * tmp_sp * tmp_cb;
161                 Result[1][3] = static_cast<T>(0);
162                 Result[2][0] = tmp_sh * tmp_cp;
163                 Result[2][1] = -tmp_sp;
164                 Result[2][2] = tmp_ch * tmp_cp;
165                 Result[2][3] = static_cast<T>(0);
166                 Result[3][0] = static_cast<T>(0);
167                 Result[3][1] = static_cast<T>(0);
168                 Result[3][2] = static_cast<T>(0);
169                 Result[3][3] = static_cast<T>(1);
170                 return Result;
171         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::eulerAngleYZ (T const & angleY, T const & angleZ) [inline]
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * Z).
See also: GLM_GTX_euler_angles
Definition at line 120 of file euler_angles.inl.
References glm::eulerAngleY(), and glm::eulerAngleZ().
124         {
125                 return eulerAngleY(angleY) * eulerAngleZ(angleZ);
126         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::eulerAngleZ (T const & angleZ) [inline]
Creates a 3D 4 * 4 homogeneous rotation matrix from an euler angle Z.
See also: GLM_GTX_euler_angles
Definition at line 46 of file euler_angles.inl.
References glm::cos(), and glm::sin().
Referenced by glm::eulerAngleXZ(), glm::eulerAngleYZ(), glm::eulerAngleZX(), and glm::eulerAngleZY().
49         {
50                 T cosZ = glm::cos(angleZ);
51                 T sinZ = glm::sin(angleZ);
52 
53                 return detail::tmat4x4<T, defaultp>(
54                         cosZ,   sinZ,   T(0), T(0),
55                         -sinZ,  cosZ,   T(0), T(0),
56                         T(0),   T(0),   T(1), T(0),
57                         T(0),   T(0),   T(0), T(1));
58         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::eulerAngleZX (T const & angle, T const & angleX) [inline]
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Z * X).
See also: GLM_GTX_euler_angles
Definition at line 110 of file euler_angles.inl.
References glm::eulerAngleX(), and glm::eulerAngleZ().
114         {
115                 return eulerAngleZ(angleZ) * eulerAngleX(angleX);
116         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::eulerAngleZY (T const & angleZ, T const & angleY) [inline]
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Z * Y).
See also: GLM_GTX_euler_angles
Definition at line 130 of file euler_angles.inl.
References glm::eulerAngleY(), and glm::eulerAngleZ().
134         {
135                 return eulerAngleZ(angleZ) * eulerAngleY(angleY);
136         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat2x2< T, defaultp > glm::orientate2 (T const & angle) [inline]
Creates a 2D 2 * 2 rotation matrix from an euler angle.
See also: GLM_GTX_euler_angles
Definition at line 210 of file euler_angles.inl.
References glm::cos(), and glm::sin().
213         {
214                 T c = glm::cos(angle);
215                 T s = glm::sin(angle);
216 
217                 detail::tmat2x2<T, defaultp> Result;
218                 Result[0][0] = c;
219                 Result[0][1] = s;
220                 Result[1][0] = -s;
221                 Result[1][1] = c;
222                 return Result;
223         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat3x3< T, P > glm::orientate3 (detail::tvec3< T, P > const & angles) [inline]
Creates a 3D 3 * 3 rotation matrix from euler angles (Y * X * Z).
See also: GLM_GTX_euler_angles
Definition at line 249 of file euler_angles.inl.
References glm::yawPitchRoll().
252         {
253                 return detail::tmat3x3<T, P>(yawPitchRoll(angles.z, angles.x, angles.y));
254         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat3x3< T, defaultp > glm::orientate3 (T const & angle) [inline]
Creates a 2D 4 * 4 homogeneous rotation matrix from an euler angle.
See also: GLM_GTX_euler_angles
Definition at line 227 of file euler_angles.inl.
References glm::cos(), and glm::sin().
230         {
231                 T c = glm::cos(angle);
232                 T s = glm::sin(angle);
233 
234                 detail::tmat3x3<T, defaultp> Result;
235                 Result[0][0] = c;
236                 Result[0][1] = s;
237                 Result[0][2] = 0.0f;
238                 Result[1][0] = -s;
239                 Result[1][1] = c;
240                 Result[1][2] = 0.0f;
241                 Result[2][0] = 0.0f;
242                 Result[2][1] = 0.0f;
243                 Result[2][2] = 1.0f;
244                 return Result;
245         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat4x4< T, P > glm::orientate4 (detail::tvec3< T, P > const & angles) [inline]
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * X * Z).
See also: GLM_GTX_euler_angles
Definition at line 258 of file euler_angles.inl.
References glm::yawPitchRoll().
261         {
262                 return yawPitchRoll(angles.z, angles.x, angles.y);
263         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::yawPitchRoll (T const & yaw, T const & pitch, T const & roll) [inline]
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * X * Z).
See also: GLM_GTX_euler_angles
Definition at line 175 of file euler_angles.inl.
References glm::cos(), and glm::sin().
Referenced by glm::orientate3(), and glm::orientate4().
180         {
181                 T tmp_ch = glm::cos(yaw);
182                 T tmp_sh = glm::sin(yaw);
183                 T tmp_cp = glm::cos(pitch);
184                 T tmp_sp = glm::sin(pitch);
185                 T tmp_cb = glm::cos(roll);
186                 T tmp_sb = glm::sin(roll);
187 
188                 detail::tmat4x4<T, defaultp> Result;
189                 Result[0][0] = tmp_ch * tmp_cb + tmp_sh * tmp_sp * tmp_sb;
190                 Result[0][1] = tmp_sb * tmp_cp;
191                 Result[0][2] = -tmp_sh * tmp_cb + tmp_ch * tmp_sp * tmp_sb;
192                 Result[0][3] = static_cast<T>(0);
193                 Result[1][0] = -tmp_ch * tmp_sb + tmp_sh * tmp_sp * tmp_cb;
194                 Result[1][1] = tmp_cb * tmp_cp;
195                 Result[1][2] = tmp_sb * tmp_sh + tmp_ch * tmp_sp * tmp_cb;
196                 Result[1][3] = static_cast<T>(0);
197                 Result[2][0] = tmp_sh * tmp_cp;
198                 Result[2][1] = -tmp_sp;
199                 Result[2][2] = tmp_ch * tmp_cp;
200                 Result[2][3] = static_cast<T>(0);
201                 Result[3][0] = static_cast<T>(0);
202                 Result[3][1] = static_cast<T>(0);
203                 Result[3][2] = static_cast<T>(0);
204                 Result[3][3] = static_cast<T>(1);
205                 return Result;
206         }