GLM_GTX_rotate_normalized_axis
Functions
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat4x4< T, P > glm::rotateNormalizedAxis (detail::tmat4x4< T, P > const &m, T const &angle, detail::tvec3< T, P > const &axis)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::rotateNormalizedAxis (detail::tquat< T, P > const &q, T const &angle, detail::tvec3< T, P > const &axis)
Detailed Description
Quaternions and matrices rotations around normalized axis.
<glm/gtx/rotate_normalized_axis.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::rotateNormalizedAxis (detail::tquat< T, P > const & q, T const & angle, detail::tvec3< T, P > const & axis) [inline]
Rotates a quaternion from a vector of 3 components normalized axis and an angle.
Parameters:
q Source orientation
angle Angle expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
axis Normalized axis of the rotation, must be normalized.
See also: GLM_GTX_rotate_normalized_axis
Definition at line 75 of file rotate_normalized_axis.inl.
References glm::cos(), glm::radians(), and glm::sin().
80         {
81                 detail::tvec3<T, P> Tmp = v;
82 
83 #ifdef GLM_FORCE_RADIANS
84                 T const AngleRad(angle);
85 #else
86 #               pragma message("GLM: rotateNormalizedAxis function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
87                 T const AngleRad = radians(angle);
88 #endif
89                 T const Sin = sin(AngleRad * T(0.5));
90 
91                 return q * detail::tquat<T, P>(cos(AngleRad * static_cast<T>(0.5)), Tmp.x * Sin, Tmp.y * Sin, Tmp.z * Sin);
92                 //return gtc::quaternion::cross(q, detail::tquat<T, P>(cos(AngleRad * T(0.5)), Tmp.x * fSin, Tmp.y * fSin, Tmp.z * fSin));
93         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat4x4< T, P > glm::rotateNormalizedAxis (detail::tmat4x4< T, P > const & m, T const & angle, detail::tvec3< T, P > const & axis) [inline]
Builds a rotation 4 * 4 matrix created from a normalized axis and an angle.
Parameters:
m Input matrix multiplied by this rotation matrix.
angle Rotation angle expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
axis Rotation axis, must be normalized.
Template Parameters:
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also: GLM_GTX_rotate_normalized_axis
- rotate(T angle, T x, T y, T z)
- rotate(detail::tmat4x4<T, P> const & m, T angle, T x, T y, T z)
- rotate(T angle, detail::tvec3<T, P> const & v)
Definition at line 33 of file rotate_normalized_axis.inl.
References glm::axis(), glm::cos(), glm::radians(), and glm::sin().
38         {
39 #ifdef GLM_FORCE_RADIANS
40                 T a = angle;
41 #else
42 #               pragma message("GLM: rotateNormalizedAxis function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
43                 T a = radians(angle);
44 #endif
45                 T c = cos(a);
46                 T s = sin(a);
47 
48                 detail::tvec3<T, P> axis = v;
49 
50                 detail::tvec3<T, P> temp = (T(1) - c) * axis;
51 
52                 detail::tmat4x4<T, P> Rotate(detail::tmat4x4<T, P>::_null);
53                 Rotate[0][0] = c + temp[0] * axis[0];
54                 Rotate[0][1] = 0 + temp[0] * axis[1] + s * axis[2];
55                 Rotate[0][2] = 0 + temp[0] * axis[2] - s * axis[1];
56 
57                 Rotate[1][0] = 0 + temp[1] * axis[0] - s * axis[2];
58                 Rotate[1][1] = c + temp[1] * axis[1];
59                 Rotate[1][2] = 0 + temp[1] * axis[2] + s * axis[0];
60 
61                 Rotate[2][0] = 0 + temp[2] * axis[0] + s * axis[1];
62                 Rotate[2][1] = 0 + temp[2] * axis[1] - s * axis[0];
63                 Rotate[2][2] = c + temp[2] * axis[2];
64 
65                 detail::tmat4x4<T, P> Result(detail::tmat4x4<T, P>::_null);
66                 Result[0] = m[0] * Rotate[0][0] + m[1] * Rotate[0][1] + m[2] * Rotate[0][2];
67                 Result[1] = m[0] * Rotate[1][0] + m[1] * Rotate[1][1] + m[2] * Rotate[1][2];
68                 Result[2] = m[0] * Rotate[2][0] + m[1] * Rotate[2][1] + m[2] * Rotate[2][2];
69                 Result[3] = m[3];
70                 return Result;
71         }