GLM_GTX_quaternion
Functions
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::cross (detail::tquat< T, P > const &q, detail::tvec3< T, P > const &v)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::cross (detail::tvec3< T, P > const &v, detail::tquat< T, P > const &q)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::squad (detail::tquat< T, P > const &q1, detail::tquat< T, P > const &q2, detail::tquat< T, P > const &s1, detail::tquat< T, P > const &s2, T const &h)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::intermediate (detail::tquat< T, P > const &prev, detail::tquat< T, P > const &curr, detail::tquat< T, P > const &next)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::exp (detail::tquat< T, P > const &q)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::log (detail::tquat< T, P > const &q)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::pow (detail::tquat< T, P > const &x, T const &y)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::rotate (detail::tquat< T, P > const &q, detail::tvec3< T, P > const &v)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec4< T, P > glm::rotate (detail::tquat< T, P > const &q, detail::tvec4< T, P > const &v)
template<typename T, precision P>
GLM_FUNC_DECL T glm::extractRealComponent (detail::tquat< T, P > const &q)
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat3x3< T, P > glm::toMat3 (detail::tquat< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat4x4< T, P > glm::toMat4 (detail::tquat< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::toQuat (detail::tmat3x3< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::toQuat (detail::tmat4x4< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::shortMix (detail::tquat< T, P > const &x, detail::tquat< T, P > const &y, T const &a)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::fastMix (detail::tquat< T, P > const &x, detail::tquat< T, P > const &y, T const &a)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::rotation (detail::tvec3< T, P > const &orig, detail::tvec3< T, P > const &dest)
template<typename T, precision P>
GLM_FUNC_DECL T glm::length2 (detail::tquat< T, P > const &q)
Detailed Description
Extented quaternion types and functions.
<glm/gtx/quaternion.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::cross (detail::tvec3< T, P > const & v, detail::tquat< T, P > const & q) [inline]
Compute a cross product between a vector and a quaternion.
See also: GLM_GTX_quaternion
Definition at line 17 of file quaternion.inl.
References glm::inverse().
Referenced by bt_edge_plane(), and btSoftBodyTriangleCallback::processTriangle().
21         {
22                 return inverse(q) * v;
23         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::cross (detail::tquat< T, P > const & q, detail::tvec3< T, P > const & v) [inline]
Compute a cross product between a quaternion and a vector.
See also: GLM_GTX_quaternion
Definition at line 27 of file quaternion.inl.
31         {
32                 return q * v;
33         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::exp (detail::tquat< T, P > const & q) [inline]
Returns a exp of a quaternion.
See also: GLM_GTX_quaternion
Definition at line 61 of file quaternion.inl.
References glm::cos(), glm::length(), and glm::sin().
Referenced by glm::exp(), and glm::exp2().
64         {
65                 detail::tvec3<T, P> u(q.x, q.y, q.z);
66                 T Angle = glm::length(u);
67                 if (Angle < epsilon<T>())
68                         return detail::tquat<T, P>();
69 
70                 detail::tvec3<T, P> v(u / Angle);
71                 return detail::tquat<T, P>(cos(Angle), sin(Angle) * v);
72         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::extractRealComponent (detail::tquat< T, P > const & q) [inline]
Extract the real component of a quaternion.
See also: GLM_GTX_quaternion
Definition at line 151 of file quaternion.inl.
References glm::sqrt().
154         {
155                 T w = static_cast<T>(1) - q.x * q.x - q.y * q.y - q.z * q.z;
156                 if(w < T(0))
157                         return T(0);
158                 else
159                         return -sqrt(w);
160         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::fastMix (detail::tquat< T, P > const & x, detail::tquat< T, P > const & y, T const & a) [inline]
Quaternion normalized linear interpolation.
See also: GLM_GTX_quaternion
Definition at line 215 of file quaternion.inl.
References glm::normalize().
220         {
221                 return glm::normalize(x * (static_cast<T>(1) - a) + (y * a));
222         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::intermediate (detail::tquat< T, P > const & prev, detail::tquat< T, P > const & curr, detail::tquat< T, P > const & next) [inline]
Returns an intermediate control point for squad interpolation.
See also: GLM_GTX_quaternion
Definition at line 49 of file quaternion.inl.
References glm::exp(), glm::inverse(), and glm::log().
54         {
55                 detail::tquat<T, P> invQuat = inverse(curr);
56                 return exp((log(next + invQuat) + log(prev + invQuat)) / static_cast<T>(-4)) * curr;
57         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::length2 (detail::tquat< T, P > const & q) [inline]
Returns the squared length of x.
See also: GLM_GTX_quaternion
Definition at line 164 of file quaternion.inl.
Referenced by btConvexConvexAlgorithm::calculateTimeOfImpact(), btConvex2dConvex2dAlgorithm::calculateTimeOfImpact(), btTriangleMesh::findOrAddVertex(), and btSoftBody::generateClusters().
167         {
168                 return q.x * q.x + q.y * q.y + q.z * q.z + q.w * q.w;
169         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::log (detail::tquat< T, P > const & q) [inline]
Returns a log of a quaternion.
See also: GLM_GTX_quaternion
Definition at line 76 of file quaternion.inl.
References glm::atan(), glm::length(), glm::log(), and glm::sqrt().
Referenced by glm::log().
79         {
80                 detail::tvec3<T, P> u(q.x, q.y, q.z);
81                 T Vec3Len = length(u);
82 
83                 if (Vec3Len < epsilon<T>())
84                 {
85                         if(q.w > static_cast<T>(0))
86                                 return detail::tquat<T, P>(log(q.w), static_cast<T>(0), static_cast<T>(0), static_cast<T>(0));
87                         else if(q.w < static_cast<T>(0))
88                                 return detail::tquat<T, P>(log(-q.w), pi<T>(), static_cast<T>(0), static_cast<T>(0));
89                         else
90                                 return detail::tquat<T, P>(std::numeric_limits<T>::infinity(), std::numeric_limits<T>::infinity(), std::numeric_limits<T>::infinity(), std::numeric_limits<T>::infinity());
91                 }
92                 else
93                 {
94                         T QuatLen = sqrt(Vec3Len * Vec3Len + q.w * q.w);
95                         T t = atan(Vec3Len, T(q.w)) / Vec3Len;
96                         return detail::tquat<T, P>(log(QuatLen), t * q.x, t * q.y, t * q.z);
97                 }
98         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::pow (detail::tquat< T, P > const & x, T const & y) [inline]
Returns x raised to the y power.
See also: GLM_GTX_quaternion
Definition at line 102 of file quaternion.inl.
References glm::abs(), glm::acos(), glm::cos(), and glm::sin().
Referenced by glm::pow().
106         {
107                 if(abs(x.w) > (static_cast<T>(1) - epsilon<T>()))
108                         return x;
109                 T Angle = acos(y);
110                 T NewAngle = Angle * y;
111                 T Div = sin(NewAngle) / sin(Angle);
112                 return detail::tquat<T, P>(
113                         cos(NewAngle),
114                         x.x * Div,
115                         x.y * Div,
116                         x.z * Div);
117         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec4< T, P > glm::rotate (detail::tquat< T, P > const & q, detail::tvec4< T, P > const & v) [inline]
Rotates a 4 components vector by a quaternion.
See also: GLM_GTX_quaternion
Definition at line 141 of file quaternion.inl.
145         {
146                 return q * v;
147         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::rotate (detail::tquat< T, P > const & q, detail::tvec3< T, P > const & v) [inline]
Returns quarternion square root.
See also: GLM_GTX_quaternion Rotates a 3 components vector by a quaternion.
GLM_GTX_quaternion
Definition at line 131 of file quaternion.inl.
135         {
136                 return q * v;
137         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::rotation (detail::tvec3< T, P > const & orig, detail::tvec3< T, P > const & dest) [inline]
Compute the rotation between two vectors. param orig vector, needs to be normalized param dest vector, needs to be normalized
See also: GLM_GTX_quaternion
Definition at line 226 of file quaternion.inl.
References glm::angleAxis(), glm::cross(), glm::dot(), glm::length2(), glm::normalize(), and glm::sqrt().
230         {
231                 T cosTheta = dot(orig, dest);
232                 detail::tvec3<T, P> rotationAxis;
233 
234                 if(cosTheta < static_cast<T>(-1) + epsilon<T>())
235                 {
236                         // special case when vectors in opposite directions :
237                         // there is no "ideal" rotation axis
238                         // So guess one; any will do as long as it's perpendicular to start
239                         // This implementation favors a rotation around the Up axis (Y),
240                         // since it's often what you want to do.
241                         rotationAxis = cross(detail::tvec3<T, P>(0, 0, 1), orig);
242                         if(length2(rotationAxis) < epsilon<T>()) // bad luck, they were parallel, try again!
243                                 rotationAxis = cross(detail::tvec3<T, P>(1, 0, 0), orig);
244 
245                         rotationAxis = normalize(rotationAxis);
246                         return angleAxis(pi<T>(), rotationAxis);
247                 }
248 
249                 // Implementation from Stan Melax's Game Programming Gems 1 article
250                 rotationAxis = cross(orig, dest);
251 
252                 T s = sqrt((T(1) + cosTheta) * static_cast<T>(2));
253                 T invs = static_cast<T>(1) / s;
254 
255                 return detail::tquat<T, P>(
256                         s * static_cast<T>(0.5f), 
257                         rotationAxis.x * invs,
258                         rotationAxis.y * invs,
259                         rotationAxis.z * invs);
260         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::shortMix (detail::tquat< T, P > const & x, detail::tquat< T, P > const & y, T const & a) [inline]
Quaternion interpolation using the rotation short path.
See also: GLM_GTX_quaternion
Definition at line 173 of file quaternion.inl.
References glm::atan(), glm::dot(), glm::sin(), and glm::sqrt().
178         {
179                 if(a <= static_cast<T>(0)) return x;
180                 if(a >= static_cast<T>(1)) return y;
181 
182                 T fCos = dot(x, y);
183                 detail::tquat<T, P> y2(y); //BUG!!! tquat<T> y2;
184                 if(fCos < static_cast<T>(0))
185                 {
186                         y2 = -y;
187                         fCos = -fCos;
188                 }
189 
190                 //if(fCos > 1.0f) // problem
191                 T k0, k1;
192                 if(fCos > (static_cast<T>(1) - epsilon<T>()))
193                 {
194                         k0 = static_cast<T>(1) - a;
195                         k1 = static_cast<T>(0) + a; //BUG!!! 1.0f + a;
196                 }
197                 else
198                 {
199                         T fSin = sqrt(T(1) - fCos * fCos);
200                         T fAngle = atan(fSin, fCos);
201                         T fOneOverSin = static_cast<T>(1) / fSin;
202                         k0 = sin((static_cast<T>(1) - a) * fAngle) * fOneOverSin;
203                         k1 = sin((static_cast<T>(0) + a) * fAngle) * fOneOverSin;
204                 }
205 
206                 return detail::tquat<T, P>(
207                         k0 * x.w + k1 * y2.w,
208                         k0 * x.x + k1 * y2.x,
209                         k0 * x.y + k1 * y2.y,
210                         k0 * x.z + k1 * y2.z);
211         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::squad (detail::tquat< T, P > const & q1, detail::tquat< T, P > const & q2, detail::tquat< T, P > const & s1, detail::tquat< T, P > const & s2, T const & h) [inline]
Compute a point on a path according squad equation. q1 and q2 are control points; s1 and s2 are intermediate control points.
See also: GLM_GTX_quaternion
Definition at line 37 of file quaternion.inl.
References glm::mix().
43         {
44                 return mix(mix(q1, q2, h), mix(s1, s2, h), static_cast<T>(2) * (static_cast<T>(1) - h) * h);
45         }
template<typename T, precision P> GLM_FUNC_DECL detail::tmat3x3<T, P> glm::toMat3 (detail::tquat< T, P > const & x) [inline]
Converts a quaternion to a 3 * 3 matrix.
See also: GLM_GTX_quaternion
Definition at line 150 of file quaternion.hpp.
References glm::mat3_cast().
151                                             {return mat3_cast(x);}
template<typename T, precision P> GLM_FUNC_DECL detail::tmat4x4<T, P> glm::toMat4 (detail::tquat< T, P > const & x) [inline]
Converts a quaternion to a 4 * 4 matrix.
See also: GLM_GTX_quaternion
Definition at line 157 of file quaternion.hpp.
References glm::mat4_cast().
158                                             {return mat4_cast(x);}
template<typename T, precision P> GLM_FUNC_DECL detail::tquat<T, P> glm::toQuat (detail::tmat4x4< T, P > const & x) [inline]
Converts a 4 * 4 matrix to a quaternion.
See also: GLM_GTX_quaternion
Definition at line 171 of file quaternion.hpp.
References glm::quat_cast().
172                                               {return quat_cast(x);}
template<typename T, precision P> GLM_FUNC_DECL detail::tquat<T, P> glm::toQuat (detail::tmat3x3< T, P > const & x) [inline]
Converts a 3 * 3 matrix to a quaternion.
See also: GLM_GTX_quaternion
Definition at line 164 of file quaternion.hpp.
References glm::quat_cast().
165                                               {return quat_cast(x);}