GLM_GTX_normalize_dot
Functions
template<typename genType>
GLM_FUNC_DECL genType::value_type glm::normalizeDot (genType const &x, genType const &y)
template<typename genType>
GLM_FUNC_DECL genType::value_type glm::fastNormalizeDot (genType const &x, genType const &y)
Detailed Description
Dot product of vectors that need to be normalize with a single square root.
<glm/gtx/normalized_dot.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType> GLM_FUNC_QUALIFIER genType glm::fastNormalizeDot (genType const & x, genType const & y) [inline]
Normalize parameters and returns the dot product of x and y. Faster that dot(fastNormalize(x), fastNormalize(y)). From GLM_GTX_normalize_dot extension.
Definition at line 66 of file normalize_dot.inl.
References glm::dot(), and glm::fastInverseSqrt().
70         {
71                 return 
72                         glm::dot(x, y) * 
73                         fastInverseSqrt(glm::dot(x, x) * 
74                         glm::dot(y, y));
75         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::normalizeDot (genType const & x, genType const & y) [inline]
Normalize parameters and returns the dot product of x and y. It's faster that dot(normalize(x), normalize(y)). From GLM_GTX_normalize_dot extension.
Definition at line 14 of file normalize_dot.inl.
References glm::dot(), and glm::inversesqrt().
18         {
19                 return 
20                         glm::dot(x, y) * 
21                         glm::inversesqrt(glm::dot(x, x) * 
22                         glm::dot(y, y));
23         }