Angle and Trigonometry Functions
Functions
template<typename genType>
GLM_FUNC_DECL genType glm::radians (genType const &degrees)
template<typename genType>
GLM_FUNC_DECL genType glm::degrees (genType const &radians)
template<typename genType>
GLM_FUNC_DECL genType glm::sin (genType const &angle)
template<typename genType>
GLM_FUNC_DECL genType glm::cos (genType const &angle)
template<typename genType>
GLM_FUNC_DECL genType glm::tan (genType const &angle)
template<typename genType>
GLM_FUNC_DECL genType glm::asin (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::acos (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::atan (genType const &y, genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::atan (genType const &y_over_x)
template<typename genType>
GLM_FUNC_DECL genType glm::sinh (genType const &angle)
template<typename genType>
GLM_FUNC_DECL genType glm::cosh (genType const &angle)
template<typename genType>
GLM_FUNC_DECL genType glm::tanh (genType const &angle)
template<typename genType>
GLM_FUNC_DECL genType glm::asinh (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::acosh (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::atanh (genType const &x)
Detailed Description
Function parameters specified as angle are assumed to be in units of radians. In no case will any of these functions result in a divide by zero error. If the divisor of a ratio is 0, then results will be undefined.
These all operate component-wise. The description is per component.
Function Documentation
template<typename genType> GLM_FUNC_QUALIFIER genType glm::acos (genType const & x) [inline]
Arc cosine. Returns an angle whose sine is x. The range of values returned by this function is [0, PI]. Results are undefined if |x| > 1.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL acos man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 119 of file func_trigonometric.inl.
Referenced by glm::angle(), glm::asec(), glm::axisAngle(), glm::mix(), glm::orientation(), glm::orientedAngle(), glm::pow(), and glm::slerp().
122         {
123                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'acos' only accept floating-point input");
124 
125                 return genType(::std::acos(x));
126         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::acosh (genType const & x) [inline]
Arc hyperbolic cosine; returns the non-negative inverse of cosh. Results are undefined if x < 1.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL acosh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 217 of file func_trigonometric.inl.
References glm::log(), and glm::sqrt().
Referenced by glm::asech().
220         {
221                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'acosh' only accept floating-point input");
222 
223                 if(x < genType(1))
224                         return genType(0);
225                 return log(x + sqrt(x * x - genType(1)));
226         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::asin (genType const & x) [inline]
Arc sine. Returns an angle whose sine is x. The range of values returned by this function is [-PI/2, PI/2]. Results are undefined if |x| > 1.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL asin man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 105 of file func_trigonometric.inl.
Referenced by glm::acsc(), and glm::yaw().
108         {
109                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'asin' only accept floating-point input");
110 
111                 return genType(::std::asin(x));
112         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::asinh (genType const & x) [inline]
Arc hyperbolic sine; returns the inverse of sinh.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL asinh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 203 of file func_trigonometric.inl.
References glm::abs(), glm::log(), and glm::sqrt().
Referenced by glm::acsch().
206         {
207                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'asinh' only accept floating-point input");
208                 
209                 return (x < genType(0) ? genType(-1) : (x > genType(0) ? genType(1) : genType(0))) * log(abs(x) + sqrt(genType(1) + x * x));
210         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::atan (genType const & y_over_x) [inline]
Arc tangent. Returns an angle whose tangent is y_over_x. The range of values returned by this function is [-PI/2, PI/2].
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL atan man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 147 of file func_trigonometric.inl.
Referenced by glm::pitch(), and glm::roll().
150         {
151                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'atan' only accept floating-point input");
152 
153                 return genType(::std::atan(x));
154         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::atan (genType const & y, genType const & x) [inline]
Arc tangent. Returns an angle whose tangent is y/x. The signs of x and y are used to determine what quadrant the angle is in. The range of values returned by this function is [-PI, PI]. Results are undefined if x and y are both 0.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL atan man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 133 of file func_trigonometric.inl.
References glm::atan2().
Referenced by glm::acot(), glm::atan2(), glm::log(), glm::polar(), and glm::shortMix().
137         {
138                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'atan' only accept floating-point input");
139 
140                 return genType(::std::atan2(y, x));
141         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::atanh (genType const & x) [inline]
Arc hyperbolic tangent; returns the inverse of tanh. Results are undefined if abs(x) >= 1.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL atanh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 233 of file func_trigonometric.inl.
References glm::abs(), and glm::log().
Referenced by glm::acoth().
236         {
237                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'atanh' only accept floating-point input");
238                 
239                 if(abs(x) >= genType(1))
240                         return 0;
241                 return genType(0.5) * log((genType(1) + x) / (genType(1) - x));
242         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::cos (genType const & angle) [inline]
The standard trigonometric cosine function. The values returned by this function will range from [-1, 1].
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL cos man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 79 of file func_trigonometric.inl.
Referenced by glm::angleAxis(), glm::axisAngleMatrix(), glm::circularRand(), glm::euclidean(), glm::eulerAngleX(), glm::eulerAngleXY(), glm::eulerAngleY(), glm::eulerAngleYX(), glm::eulerAngleYXZ(), glm::eulerAngleZ(), glm::exp(), Player::MoveBackward(), Player::MoveForward(), glm::orientate2(), glm::orientate3(), glm::perspectiveFov(), glm::pow(), glm::rotate(), glm::rotateNormalizedAxis(), glm::rotateX(), glm::rotateY(), glm::rotateZ(), glm::sec(), glm::sphericalRand(), and glm::yawPitchRoll().
80         {
81                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'cos' only accept floating-point input");
82 
83                 return genType(::std::cos(angle));
84         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::cosh (genType const & angle) [inline]
Returns the hyperbolic cosine function, (exp(x) + exp(-x)) / 2
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL cosh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 175 of file func_trigonometric.inl.
Referenced by glm::coth(), and glm::sech().
178         {
179                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'cosh' only accept floating-point input");
180 
181                 return genType(std::cosh(angle));
182         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::degrees (genType const & radians) [inline]
Converts radians to degrees and returns the result.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL degrees man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 52 of file func_trigonometric.inl.
Referenced by glm::angle(), Camera::GetRotationMatrix(), glm::orientation(), glm::orientedAngle(), glm::pitch(), glm::polar(), glm::roll(), and glm::yaw().
55         {
56                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'degrees' only accept floating-point input");
57 
58                 return radians * genType(57.295779513082320876798154814105);
59         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::radians (genType const & degrees) [inline]
Converts degrees to radians and returns the result.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL radians man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 38 of file func_trigonometric.inl.
Referenced by glm::angleAxis(), glm::euclidean(), glm::infinitePerspective(), glm::perspective(), glm::perspectiveFov(), glm::rotate(), glm::rotateNormalizedAxis(), glm::rotateX(), glm::rotateY(), glm::rotateZ(), and glm::tweakedInfinitePerspective().
41         {
42                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'radians' only accept floating-point input");
43 
44                 return degrees * genType(0.01745329251994329576923690768489);
45         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::sin (genType const & angle) [inline]
The standard trigonometric sine function. The values returned by this function will range from [-1, 1].
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL sin man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 66 of file func_trigonometric.inl.
Referenced by glm::angleAxis(), glm::axisAngleMatrix(), glm::circularRand(), glm::csc(), glm::euclidean(), glm::eulerAngleX(), glm::eulerAngleXY(), glm::eulerAngleY(), glm::eulerAngleYX(), glm::eulerAngleYXZ(), glm::eulerAngleZ(), glm::exp(), glm::mix(), Player::MoveBackward(), Player::MoveForward(), glm::orientate2(), glm::orientate3(), glm::perspectiveFov(), glm::pow(), glm::rotate(), glm::rotateNormalizedAxis(), glm::rotateX(), glm::rotateY(), glm::rotateZ(), glm::shortMix(), glm::slerp(), glm::sphericalRand(), and glm::yawPitchRoll().
69         {
70                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'sin' only accept floating-point input");
71 
72                 return genType(::std::sin(angle));
73         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::sinh (genType const & angle) [inline]
Returns the hyperbolic sine function, (exp(x) - exp(-x)) / 2
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL sinh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 161 of file func_trigonometric.inl.
Referenced by glm::coth(), and glm::csch().
164         {
165                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'sinh' only accept floating-point input");
166 
167                 return genType(std::sinh(angle));
168         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::tan (genType const & angle) [inline]
The standard trigonometric tangent function.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL tan man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 91 of file func_trigonometric.inl.
Referenced by glm::cot(), glm::infinitePerspective(), glm::perspective(), and glm::tweakedInfinitePerspective().
94         {
95                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'tan' only accept floating-point input");
96 
97                 return genType(::std::tan(angle));
98         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::tanh (genType const & angle) [inline]
Returns the hyperbolic tangent function, sinh(angle) / cosh(angle)
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL tanh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 189 of file func_trigonometric.inl.
192         {
193                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'tanh' only accept floating-point input");
194 
195                 return genType(std::tanh(angle));
196         }