GLM_GTX_integer
Typedefs
typedef signed int glm::sint
Functions
GLM_FUNC_DECL int glm::pow (int x, int y)
GLM_FUNC_DECL int glm::sqrt (int x)
template<typename genIUType>
GLM_FUNC_DECL genIUType glm::log2 (genIUType x)
GLM_FUNC_DECL unsigned int glm::floor_log2 (unsigned int x)
GLM_FUNC_DECL int glm::mod (int x, int y)
template<typename genType>
GLM_FUNC_DECL genType glm::factorial (genType const &x)
GLM_FUNC_DECL uint glm::pow (uint x, uint y)
GLM_FUNC_DECL uint glm::sqrt (uint x)
GLM_FUNC_DECL uint glm::mod (uint x, uint y)
GLM_FUNC_DECL uint glm::nlz (uint x)
Detailed Description
Add support for integer for core functions.
<glm/gtx/integer.hpp> need to be included to use these functionalities.
Typedef Documentation
typedef signed int glm::sint
32bit signed integer. From GLM_GTX_integer extension.
Definition at line 81 of file integer.hpp.
Function Documentation
template<typename genType> GLM_FUNC_QUALIFIER genType glm::factorial (genType const & x) [inline]
Return the factorial value of a number (!12 max, integer only) From GLM_GTX_integer extension.
Definition at line 93 of file integer.inl.
94         {
95                 genType Temp = x;
96                 genType Result;
97                 for(Result = 1; Temp > 1; --Temp)
98                         Result *= Temp;
99                 return Result;
100         }
GLM_FUNC_DECL unsigned int glm::floor_log2 (unsigned int x)
Returns the floor log2 of x. From GLM_GTX_integer extension.
template<typename genIUType> GLM_FUNC_DECL genIUType glm::log2 (genIUType x) [inline]
Returns the log2 of x. Can be reliably using to compute mipmap count from the texture size. From GLM_GTX_integer extension.
GLM_FUNC_QUALIFIER uint glm::mod (uint x, uint y)
Modulus. Returns x - y * floor(x / y) for each component in x using the floating point value y. From GLM_GTX_integer extension.
Definition at line 156 of file integer.inl.
157         {
158                 return x - y * (x / y);
159         }
GLM_FUNC_QUALIFIER int glm::mod (int x, int y)
Modulus. Returns x - y * floor(x / y) for each component in x using the floating point value y. From GLM_GTX_integer extension.
Definition at line 86 of file integer.inl.
87         {
88                 return x - y * (x / y);
89         }
GLM_FUNC_QUALIFIER unsigned int glm::nlz (uint x)
Returns the number of leading zeros. From GLM_GTX_integer extension.
Definition at line 171 of file integer.inl.
172         {
173                 int y, m, n;
174 
175                 y = -int(x >> 16);      // If left half of x is 0,
176                 m = (y >> 16) & 16;  // set n = 16.  If left half
177                 n = 16 - m;          // is nonzero, set n = 0 and
178                 x = x >> m;          // shift x right 16.
179                                                         // Now x is of the form 0000xxxx.
180                 y = x - 0x100;       // If positions 8-15 are 0,
181                 m = (y >> 16) & 8;   // add 8 to n and shift x left 8.
182                 n = n + m;
183                 x = x << m;
184 
185                 y = x - 0x1000;      // If positions 12-15 are 0,
186                 m = (y >> 16) & 4;   // add 4 to n and shift x left 4.
187                 n = n + m;
188                 x = x << m;
189 
190                 y = x - 0x4000;      // If positions 14-15 are 0,
191                 m = (y >> 16) & 2;   // add 2 to n and shift x left 2.
192                 n = n + m;
193                 x = x << m;
194 
195                 y = x >> 14;         // Set y = 0, 1, 2, or 3.
196                 m = y & ~(y >> 1);   // Set m = 0, 1, 2, or 2 resp.
197                 return unsigned(n + 2 - m);
198         }
GLM_FUNC_QUALIFIER uint glm::pow (uint x, uint y)
Returns x raised to the y power. From GLM_GTX_integer extension.
Definition at line 132 of file integer.inl.
133         {
134                 uint result = x;
135                 for(uint i = 1; i < y; ++i)
136                         result *= x;
137                 return result;
138         }
GLM_FUNC_QUALIFIER int glm::pow (int x, int y)
Returns x raised to the y power. From GLM_GTX_integer extension.
Definition at line 13 of file integer.inl.
14         {
15                 if(y == 0)
16                         return 1;
17                 int result = x;
18                 for(int i = 1; i < y; ++i)
19                         result *= x;
20                 return result;
21         }
GLM_FUNC_QUALIFIER uint glm::sqrt (uint x)
Returns the positive square root of x. From GLM_GTX_integer extension.
Definition at line 140 of file integer.inl.
Referenced by glm::axis(), Vector2::Distance(), glm::quat_cast(), and glm::refract().
141         {
142                 if(x <= 1) return x;
143 
144                 uint NextTrial = x >> 1;
145                 uint CurrentAnswer;
146 
147                 do
148                 {
149                         CurrentAnswer = NextTrial;
150                         NextTrial = (NextTrial + x / NextTrial) >> 1;
151                 } while(NextTrial < CurrentAnswer);
152 
153                 return CurrentAnswer;
154         }
GLM_FUNC_QUALIFIER int glm::sqrt (int x)
Returns the positive square root of x. From GLM_GTX_integer extension.
Definition at line 24 of file integer.inl.
25         {
26                 if(x <= 1) return x;
27 
28                 int NextTrial = x >> 1;
29                 int CurrentAnswer;
30 
31                 do
32                 {
33                         CurrentAnswer = NextTrial;
34                         NextTrial = (NextTrial + x / NextTrial) >> 1;
35                 } while(NextTrial < CurrentAnswer);
36 
37                 return CurrentAnswer;
38         }