GLM_GTX_bit
Functions
template<typename genIType>
GLM_FUNC_DECL genIType glm::mask (genIType const &count)
template<typename genType>
GLM_FUNC_DECL genType glm::highestBitValue (genType const &value)
template<typename genType>
GLM_FUNC_DECL bool glm::isPowerOfTwo (genType const &value)
template<typename genType>
GLM_FUNC_DECL genType glm::powerOfTwoAbove (genType const &value)
template<typename genType>
GLM_FUNC_DECL genType glm::powerOfTwoBelow (genType const &value)
template<typename genType>
GLM_FUNC_DECL genType glm::powerOfTwoNearest (genType const &value)
template<typename genType>
GLM_DEPRECATED GLM_FUNC_DECL genType glm::bitRevert (genType const &value)
template<typename genType>
GLM_FUNC_DECL genType glm::bitRotateRight (genType const &In, std::size_t Shift)
template<typename genType>
GLM_FUNC_DECL genType glm::bitRotateLeft (genType const &In, std::size_t Shift)
template<typename genIUType>
GLM_FUNC_DECL genIUType glm::fillBitfieldWithOne (genIUType const &Value, int const &FromBit, int const &ToBit)
template<typename genIUType>
GLM_FUNC_DECL genIUType glm::fillBitfieldWithZero (genIUType const &Value, int const &FromBit, int const &ToBit)
GLM_FUNC_DECL int16 glm::bitfieldInterleave (int8 x, int8 y)
GLM_FUNC_DECL uint16 glm::bitfieldInterleave (uint8 x, uint8 y)
GLM_FUNC_DECL int32 glm::bitfieldInterleave (int16 x, int16 y)
GLM_FUNC_DECL uint32 glm::bitfieldInterleave (uint16 x, uint16 y)
GLM_FUNC_DECL int64 glm::bitfieldInterleave (int32 x, int32 y)
GLM_FUNC_DECL uint64 glm::bitfieldInterleave (uint32 x, uint32 y)
GLM_FUNC_DECL int32 glm::bitfieldInterleave (int8 x, int8 y, int8 z)
GLM_FUNC_DECL uint32 glm::bitfieldInterleave (uint8 x, uint8 y, uint8 z)
GLM_FUNC_DECL int64 glm::bitfieldInterleave (int16 x, int16 y, int16 z)
GLM_FUNC_DECL uint64 glm::bitfieldInterleave (uint16 x, uint16 y, uint16 z)
GLM_FUNC_DECL int64 glm::bitfieldInterleave (int32 x, int32 y, int32 z)
GLM_FUNC_DECL uint64 glm::bitfieldInterleave (uint32 x, uint32 y, uint32 z)
GLM_FUNC_DECL int32 glm::bitfieldInterleave (int8 x, int8 y, int8 z, int8 w)
GLM_FUNC_DECL uint32 glm::bitfieldInterleave (uint8 x, uint8 y, uint8 z, uint8 w)
GLM_FUNC_DECL int64 glm::bitfieldInterleave (int16 x, int16 y, int16 z, int16 w)
GLM_FUNC_DECL uint64 glm::bitfieldInterleave (uint16 x, uint16 y, uint16 z, uint16 w)
Detailed Description
Allow to perform bit operations on integer values.
<glm/gtx/bit.hpp> need to be included to use these functionalities.
Function Documentation
GLM_FUNC_QUALIFIER uint64 glm::bitfieldInterleave (uint16 x, uint16 y, uint16 z, uint16 w) [inline]
Interleaves the bits of x, y, z and w. The first bit is the first bit of x followed by the first bit of y, the first bit of z and finally the first bit of w. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 777 of file bit.inl.
778         {
779                 return detail::bitfieldInterleave<uint16, uint64>(x, y, z, w);
780         }
GLM_FUNC_QUALIFIER int64 glm::bitfieldInterleave (int16 x, int16 y, int16 z, int16 w)
Interleaves the bits of x, y, z and w. The first bit is the first bit of x followed by the first bit of y, the first bit of z and finally the first bit of w. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 754 of file bit.inl.
References glm::bitfieldInterleave().
755         {
756                 union sign16
757                 {
758                         int16 i;
759                         uint16 u;
760                 } sign_x, sign_y, sign_z, sign_w;
761 
762                 union sign64
763                 {
764                         int64 i;
765                         uint64 u;
766                 } result;
767 
768                 sign_x.i = x;
769                 sign_y.i = y;
770                 sign_z.i = z;
771                 sign_w.i = w;
772                 result.u = bitfieldInterleave(sign_x.u, sign_y.u, sign_z.u, sign_w.u);
773 
774                 return result.i;
775         }
GLM_FUNC_QUALIFIER uint32 glm::bitfieldInterleave (uint8 x, uint8 y, uint8 z, uint8 w) [inline]
Interleaves the bits of x, y, z and w. The first bit is the first bit of x followed by the first bit of y, the first bit of z and finally the first bit of w. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 749 of file bit.inl.
750         {
751                 return detail::bitfieldInterleave<uint8, uint32>(x, y, z, w);
752         }
GLM_FUNC_QUALIFIER int32 glm::bitfieldInterleave (int8 x, int8 y, int8 z, int8 w)
Interleaves the bits of x, y, z and w. The first bit is the first bit of x followed by the first bit of y, the first bit of z and finally the first bit of w. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 726 of file bit.inl.
References glm::bitfieldInterleave().
727         {
728                 union sign8
729                 {
730                         int8 i;
731                         uint8 u;
732                 } sign_x, sign_y, sign_z, sign_w;
733 
734                 union sign32
735                 {
736                         int32 i;
737                         uint32 u;
738                 } result;
739 
740                 sign_x.i = x;
741                 sign_y.i = y;
742                 sign_z.i = z;
743                 sign_w.i = w;
744                 result.u = bitfieldInterleave(sign_x.u, sign_y.u, sign_z.u, sign_w.u);
745 
746                 return result.i;
747         }
GLM_FUNC_QUALIFIER uint64 glm::bitfieldInterleave (uint32 x, uint32 y, uint32 z) [inline]
Interleaves the bits of x, y and z. The first bit is the first bit of x followed by the first bit of y and the first bit of z. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 721 of file bit.inl.
722         {
723                 return detail::bitfieldInterleave<uint32, uint64>(x, y, z);
724         }
GLM_FUNC_QUALIFIER int64 glm::bitfieldInterleave (int32 x, int32 y, int32 z)
Interleaves the bits of x, y and z. The first bit is the first bit of x followed by the first bit of y and the first bit of z. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 699 of file bit.inl.
References glm::bitfieldInterleave().
700         {
701                 union sign16
702                 {
703                         int32 i;
704                         uint32 u;
705                 } sign_x, sign_y, sign_z;
706 
707                 union sign64
708                 {
709                         int64 i;
710                         uint64 u;
711                 } result;
712 
713                 sign_x.i = x;
714                 sign_y.i = y;
715                 sign_z.i = z;
716                 result.u = bitfieldInterleave(sign_x.u, sign_y.u, sign_z.u);
717 
718                 return result.i;
719         }
GLM_FUNC_QUALIFIER uint64 glm::bitfieldInterleave (uint16 x, uint16 y, uint16 z) [inline]
Interleaves the bits of x, y and z. The first bit is the first bit of x followed by the first bit of y and the first bit of z. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 694 of file bit.inl.
695         {
696                 return detail::bitfieldInterleave<uint32, uint64>(x, y, z);
697         }
GLM_FUNC_QUALIFIER int64 glm::bitfieldInterleave (int16 x, int16 y, int16 z)
Interleaves the bits of x, y and z. The first bit is the first bit of x followed by the first bit of y and the first bit of z. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 672 of file bit.inl.
References glm::bitfieldInterleave().
673         {
674                 union sign16
675                 {
676                         int16 i;
677                         uint16 u;
678                 } sign_x, sign_y, sign_z;
679 
680                 union sign64
681                 {
682                         int64 i;
683                         uint64 u;
684                 } result;
685 
686                 sign_x.i = x;
687                 sign_y.i = y;
688                 sign_z.i = z;
689                 result.u = bitfieldInterleave(sign_x.u, sign_y.u, sign_z.u);
690 
691                 return result.i;
692         }
GLM_FUNC_QUALIFIER uint32 glm::bitfieldInterleave (uint8 x, uint8 y, uint8 z) [inline]
Interleaves the bits of x, y and z. The first bit is the first bit of x followed by the first bit of y and the first bit of z. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 667 of file bit.inl.
668         {
669                 return detail::bitfieldInterleave<uint8, uint32>(x, y, z);
670         }
GLM_FUNC_QUALIFIER int32 glm::bitfieldInterleave (int8 x, int8 y, int8 z)
Interleaves the bits of x, y and z. The first bit is the first bit of x followed by the first bit of y and the first bit of z. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 645 of file bit.inl.
References glm::bitfieldInterleave().
646         {
647                 union sign8
648                 {
649                         int8 i;
650                         uint8 u;
651                 } sign_x, sign_y, sign_z;
652 
653                 union sign32
654                 {
655                         int32 i;
656                         uint32 u;
657                 } result;
658 
659                 sign_x.i = x;
660                 sign_y.i = y;
661                 sign_z.i = z;
662                 result.u = bitfieldInterleave(sign_x.u, sign_y.u, sign_z.u);
663 
664                 return result.i;
665         }
GLM_FUNC_QUALIFIER uint64 glm::bitfieldInterleave (uint32 x, uint32 y) [inline]
Interleaves the bits of x and y. The first bit is the first bit of x followed by the first bit of y. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 640 of file bit.inl.
641         {
642                 return detail::bitfieldInterleave<uint32, uint64>(x, y);
643         }
GLM_FUNC_QUALIFIER int64 glm::bitfieldInterleave (int32 x, int32 y)
Interleaves the bits of x and y. The first bit is the first bit of x followed by the first bit of y. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 619 of file bit.inl.
References glm::bitfieldInterleave().
620         {
621                 union sign32
622                 {
623                         int32 i;
624                         uint32 u;
625                 } sign_x, sign_y;
626 
627                 union sign64
628                 {
629                         int64 i;
630                         uint64 u;
631                 } result;
632 
633                 sign_x.i = x;
634                 sign_y.i = y;
635                 result.u = bitfieldInterleave(sign_x.u, sign_y.u);
636 
637                 return result.i;
638         }
GLM_FUNC_QUALIFIER uint32 glm::bitfieldInterleave (uint16 x, uint16 y) [inline]
Interleaves the bits of x and y. The first bit is the first bit of x followed by the first bit of y. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 614 of file bit.inl.
615         {
616                 return detail::bitfieldInterleave<uint16, uint32>(x, y);
617         }
GLM_FUNC_QUALIFIER int32 glm::bitfieldInterleave (int16 x, int16 y)
Interleaves the bits of x and y. The first bit is the first bit of x followed by the first bit of y. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 593 of file bit.inl.
References glm::bitfieldInterleave().
594         {
595                 union sign16
596                 {
597                         int16 i;
598                         uint16 u;
599                 } sign_x, sign_y;
600 
601                 union sign32
602                 {
603                         int32 i;
604                         uint32 u;
605                 } result;
606 
607                 sign_x.i = x;
608                 sign_y.i = y;
609                 result.u = bitfieldInterleave(sign_x.u, sign_y.u);
610 
611                 return result.i;
612         }
GLM_FUNC_QUALIFIER uint16 glm::bitfieldInterleave (uint8 x, uint8 y) [inline]
Interleaves the bits of x and y. The first bit is the first bit of x followed by the first bit of y. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 588 of file bit.inl.
589         {
590                 return detail::bitfieldInterleave<uint8, uint16>(x, y);
591         }
GLM_FUNC_QUALIFIER int16 glm::bitfieldInterleave (int8 x, int8 y)
Interleaves the bits of x and y. The first bit is the first bit of x followed by the first bit of y. The other bits are interleaved following the previous sequence.
See also: GLM_GTX_bit
Definition at line 567 of file bit.inl.
Referenced by glm::bitfieldInterleave().
568         {
569                 union sign8
570                 {
571                         int8 i;
572                         uint8 u;
573                 } sign_x, sign_y;
574 
575                 union sign16
576                 {
577                         int16 i;
578                         uint16 u;
579                 } result;
580 
581                 sign_x.i = x;
582                 sign_y.i = y;
583                 result.u = bitfieldInterleave(sign_x.u, sign_y.u);
584 
585                 return result.i;
586         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::bitRevert (genType const & value) [inline]
Revert all bits of any integer based type.
See also: GLM_GTX_bit
Definition at line 168 of file bit.inl.
169         {
170                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_integer, "'bitRevert' only accept integer values");
171 
172                 genType Out = 0;
173                 std::size_t BitSize = sizeof(genType) * 8;
174                 for(std::size_t i = 0; i < BitSize; ++i)
175                         if(In & (genType(1) << i))
176                                 Out |= genType(1) << (BitSize - 1 - i);
177                 return Out;
178         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::bitRotateLeft (genType const & In, std::size_t Shift) [inline]
Rotate all bits to the left.
See also: GLM_GTX_bit
Definition at line 231 of file bit.inl.
232         {
233                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_integer, "'bitRotateLeft' only accept integer values");
234 
235                 std::size_t BitSize = sizeof(genType) * 8;
236                 return (In >> Shift) | (In << (BitSize - Shift));
237         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::bitRotateRight (genType const & In, std::size_t Shift) [inline]
Rotate all bits to the right.
See also: GLM_GTX_bit
Definition at line 183 of file bit.inl.
184         {
185                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_integer, "'bitRotateRight' only accept integer values");
186 
187                 std::size_t BitSize = sizeof(genType) * 8;
188                 return (In << Shift) | (In >> (BitSize - Shift));
189         }
template<typename genIUType> GLM_FUNC_QUALIFIER genIUType glm::fillBitfieldWithOne (genIUType const & Value, int const & FromBit, int const & ToBit) [inline]
Set to 1 a range of bits.
See also: GLM_GTX_bit
Definition at line 280 of file bit.inl.
285         {
286                 assert(FromBit <= ToBit);
287                 assert(ToBit <= sizeof(genIUType) * std::size_t(8));
288 
289                 genIUType Result = Value;
290                 for(signed i = 0; i <= ToBit; ++i)
291                         Result |= (1 << i);
292                 return Result;
293         }
template<typename genIUType> GLM_FUNC_QUALIFIER genIUType glm::fillBitfieldWithZero (genIUType const & Value, int const & FromBit, int const & ToBit) [inline]
Set to 0 a range of bits.
See also: GLM_GTX_bit
Definition at line 297 of file bit.inl.
302         {
303                 assert(FromBit <= ToBit);
304                 assert(ToBit <= sizeof(genIUType) * std::size_t(8));
305 
306                 genIUType Result = Value;
307                 for(signed i = 0; i <= ToBit; ++i)
308                         Result &= ~(1 << i);
309                 return Result;
310         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::highestBitValue (genType const & value) [inline]
Find the highest bit set to 1 in a integer variable and return its value.
See also: GLM_GTX_bit
Definition at line 29 of file bit.inl.
Referenced by glm::powerOfTwoAbove(), glm::powerOfTwoBelow(), and glm::powerOfTwoNearest().
32         {
33                 genType tmp = value;
34                 genType result = genType(0);
35                 while(tmp)
36                 {
37                         result = (tmp & (~tmp + 1)); // grab lowest bit
38                         tmp &= ~result; // clear lowest bit
39                 }
40                 return result;
41         }
template<typename genType> GLM_FUNC_QUALIFIER bool glm::isPowerOfTwo (genType const & value) [inline]
Return true if the value is a power of two number.
See also: GLM_GTX_bit
Definition at line 81 of file bit.inl.
References glm::abs().
Referenced by glm::powerOfTwoAbove(), glm::powerOfTwoBelow(), and glm::powerOfTwoNearest().
82         {
83                 //detail::If<std::numeric_limits<genType>::is_signed>::apply(abs, Value);
84                 //return !(Value & (Value - 1));
85 
86                 // For old complier?
87                 genType Result = Value;
88                 if(std::numeric_limits<genType>::is_signed)
89                         Result = abs(Result);
90                 return !(Result & (Result - 1));
91         }
template<typename genIType> GLM_FUNC_QUALIFIER genIType glm::mask (genIType const & count) [inline]
Build a mask of 'count' bits
See also: GLM_GTX_bit
Definition at line 17 of file bit.inl.
20         {
21                 return ((genIType(1) << (count)) - genIType(1));
22         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::powerOfTwoAbove (genType const & value) [inline]
Return the power of two number which value is just higher the input value.
See also: GLM_GTX_bit
Definition at line 131 of file bit.inl.
References glm::highestBitValue(), and glm::isPowerOfTwo().
132         {
133                 return isPowerOfTwo(value) ? value : highestBitValue(value) << 1;
134         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::powerOfTwoBelow (genType const & value) [inline]
Return the power of two number which value is just lower the input value.
See also: GLM_GTX_bit
Definition at line 141 of file bit.inl.
References glm::highestBitValue(), and glm::isPowerOfTwo().
144         {
145                 return isPowerOfTwo(value) ? value : highestBitValue(value);
146         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::powerOfTwoNearest (genType const & value) [inline]
Return the power of two number which value is the closet to the input value.
See also: GLM_GTX_bit
Definition at line 153 of file bit.inl.
References glm::highestBitValue(), and glm::isPowerOfTwo().
156         {
157                 if(isPowerOfTwo(value))
158                         return value;
159 
160                 genType prev = highestBitValue(value);
161                 genType next = prev << 1;
162                 return (next - value) < (value - prev) ? next : prev;
163         }