GLM_GTX_optimum_pow
Functions
template<typename genType>
GLM_FUNC_DECL genType glm::gtx::pow2 (const genType &x)
template<typename genType>
GLM_FUNC_DECL genType glm::gtx::pow3 (const genType &x)
template<typename genType>
GLM_FUNC_DECL genType glm::gtx::pow4 (const genType &x)
GLM_FUNC_DECL bool glm::gtx::powOfTwo (int num)
template<precision P>
GLM_FUNC_DECL detail::tvec2< bool, P > glm::gtx::powOfTwo (detail::tvec2< int, P > const &x)
template<precision P>
GLM_FUNC_DECL detail::tvec3< bool, P > glm::gtx::powOfTwo (detail::tvec3< int, P > const &x)
template<precision P>
GLM_FUNC_DECL detail::tvec4< bool, P > glm::gtx::powOfTwo (detail::tvec4< int, P > const &x)
Detailed Description
Integer exponentiation of power functions.
<glm/gtx/optimum_pow.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType> GLM_FUNC_DECL genType glm::gtx::pow2 (const genType & x) [inline]
Returns x raised to the power of 2. From GLM_GTX_optimum_pow extension.
Definition at line 13 of file optimum_pow.inl.
Referenced by glm::catmullRom(), glm::hermite(), and glm::radialGradient().
14         {
15                 return x * x;
16         }
template<typename genType> GLM_FUNC_DECL genType glm::gtx::pow3 (const genType & x) [inline]
Returns x raised to the power of 3. From GLM_GTX_optimum_pow extension.
Definition at line 19 of file optimum_pow.inl.
Referenced by glm::catmullRom(), and glm::hermite().
20         {
21                 return x * x * x;
22         }
template<typename genType> GLM_FUNC_DECL genType glm::gtx::pow4 (const genType & x) [inline]
Returns x raised to the power of 4. From GLM_GTX_optimum_pow extension.
Definition at line 25 of file optimum_pow.inl.
26         {
27                 return (x * x) * (x * x);
28         }
template<precision P> GLM_FUNC_DECL detail::tvec4<bool, P> glm::gtx::powOfTwo (detail::tvec4< int, P > const & x) [inline]
Checks to determine if the parameter component are power of 2 numbers. From GLM_GTX_optimum_pow extension.
Definition at line 53 of file optimum_pow.inl.
References glm::powOfTwo().
54         {
55                 return detail::tvec4<bool, P>(
56                         powOfTwo(x.x),
57                         powOfTwo(x.y),
58                         powOfTwo(x.z),
59                         powOfTwo(x.w));
60         }
template<precision P> GLM_FUNC_DECL detail::tvec3<bool, P> glm::gtx::powOfTwo (detail::tvec3< int, P > const & x) [inline]
Checks to determine if the parameter component are power of 2 numbers. From GLM_GTX_optimum_pow extension.
Definition at line 44 of file optimum_pow.inl.
References glm::powOfTwo().
45         {
46                 return detail::tvec3<bool, P>(
47                         powOfTwo(x.x),
48                         powOfTwo(x.y),
49                         powOfTwo(x.z));
50         }
template<precision P> GLM_FUNC_DECL detail::tvec2<bool, P> glm::gtx::powOfTwo (detail::tvec2< int, P > const & x) [inline]
Checks to determine if the parameter component are power of 2 numbers. From GLM_GTX_optimum_pow extension.
Definition at line 36 of file optimum_pow.inl.
References glm::powOfTwo().
37         {
38                 return detail::tvec2<bool, P>(
39                         powOfTwo(x.x),
40                         powOfTwo(x.y));
41         }
GLM_FUNC_DECL bool glm::gtx::powOfTwo (int num)
Checks if the parameter is a power of 2 number. From GLM_GTX_optimum_pow extension.
Definition at line 30 of file optimum_pow.inl.
Referenced by glm::powOfTwo().
31         {
32                 return !(x & (x - 1));
33         }