Common functions
Functions
template<typename genType>
GLM_FUNC_DECL genType glm::abs (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::sign (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::floor (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::trunc (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::round (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::roundEven (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::ceil (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::fract (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::mod (genType const &x, genType const &y)
template<typename genType>
GLM_FUNC_DECL genType glm::mod (genType const &x, typename genType::value_type const &y)
template<typename genType>
GLM_FUNC_DECL genType glm::modf (genType const &x, genType &i)
template<typename genType>
GLM_FUNC_DECL genType glm::min (genType const &x, genType const &y)
template<typename genType>
GLM_FUNC_DECL genType glm::max (genType const &x, genType const &y)
template<typename genType>
GLM_FUNC_DECL genType glm::clamp (genType const &x, genType const &minVal, genType const &maxVal)
template<typename T, typename U, precision P, template< typename, precision > class vecType>
GLM_FUNC_DECL vecType< T, P > glm::mix (vecType< T, P > const &x, vecType< T, P > const &y, vecType< U, P > const &a)
template<typename genType>
GLM_FUNC_DECL genType glm::step (genType const &edge, genType const &x)
template<template< typename, precision > class vecType, typename T, precision P>
GLM_FUNC_DECL vecType< T, P > glm::step (T const &edge, vecType< T, P > const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::smoothstep (genType const &edge0, genType const &edge1, genType const &x)
template<typename genType>
GLM_FUNC_DECL genType::bool_type glm::isnan (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType::bool_type glm::isinf (genType const &x)
GLM_FUNC_DECL int glm::floatBitsToInt (float const &v)
template<template< typename, precision > class vecType, precision P>
GLM_FUNC_DECL vecType< int, P > glm::floatBitsToInt (vecType< float, P > const &v)
GLM_FUNC_DECL uint glm::floatBitsToUint (float const &v)
template<template< typename, precision > class vecType, precision P>
GLM_FUNC_DECL vecType< uint, P > glm::floatBitsToUint (vecType< float, P > const &v)
GLM_FUNC_DECL float glm::intBitsToFloat (int const &v)
template<template< typename, precision > class vecType, precision P>
GLM_FUNC_DECL vecType< float, P > glm::intBitsToFloat (vecType< int, P > const &v)
GLM_FUNC_DECL float glm::uintBitsToFloat (uint const &v)
template<template< typename, precision > class vecType, precision P>
GLM_FUNC_DECL vecType< float, P > glm::uintBitsToFloat (vecType< uint, P > const &v)
template<typename genType>
GLM_FUNC_DECL genType glm::fma (genType const &a, genType const &b, genType const &c)
template<typename genType, typename genIType>
GLM_FUNC_DECL genType glm::frexp (genType const &x, genIType &exp)
template<typename genType, typename genIType>
GLM_FUNC_DECL genType glm::ldexp (genType const &x, genIType const &exp)
Detailed Description
These all operate component-wise. The description is per component.
Function Documentation
template<typename genType> GLM_FUNC_DECL genType glm::abs (genType const & x) [inline]
Returns x if x >= 0; otherwise, it returns -x.
Template Parameters:
genType floating-point or signed integer; scalar or vector types.
See also: GLSL abs man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Referenced by glm::areOrthogonal(), glm::areOrthonormal(), glm::asinh(), glm::atanh(), glm::axisAngle(), glm::epsilonEqual(), glm::fastAtan(), glm::fastLength(), glm::isIdentity(), glm::isNormalized(), glm::isPowerOfTwo(), glm::l1Norm(), glm::length(), glm::pow(), and glm::rotate().
template<typename genType> GLM_FUNC_QUALIFIER genType glm::ceil (genType const & x) [inline]
Returns a value equal to the nearest integer that is greater than or equal to x.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL ceil man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 258 of file func_common.inl.
259         {
260                 GLM_STATIC_ASSERT(
261                         std::numeric_limits<genType>::is_iec559,
262                         "'ceil' only accept floating-point inputs");
263 
264                 return ::std::ceil(x);
265         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::clamp (genType const & x, genType const & minVal, genType const & maxVal) [inline]
Returns min(max(x, minVal), maxVal) for each component in x using the floating-point values minVal and maxVal.
Template Parameters:
genType Floating-point or integer; scalar or vector types.
See also: GLSL clamp man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 404 of file func_common.inl.
References glm::max(), and glm::min().
Referenced by glm::clamp(), glm::orientedAngle(), glm::packSnorm1x16(), glm::packSnorm1x8(), glm::packSnorm2x16(), glm::packSnorm2x8(), glm::packSnorm3x10_1x2(), glm::packSnorm4x16(), glm::packSnorm4x8(), glm::packUnorm1x16(), glm::packUnorm1x8(), glm::packUnorm2x16(), glm::packUnorm2x8(), glm::packUnorm3x10_1x2(), glm::packUnorm4x16(), glm::packUnorm4x8(), glm::saturate(), glm::smoothstep(), glm::unpackSnorm1x16(), glm::unpackSnorm1x8(), glm::unpackSnorm2x16(), glm::unpackSnorm2x8(), glm::unpackSnorm3x10_1x2(), and glm::unpackSnorm4x8().
409         {
410                 GLM_STATIC_ASSERT(
411                         std::numeric_limits<genType>::is_iec559 || std::numeric_limits<genType>::is_integer,
412                         "'clamp' only accept floating-point or integer inputs");
413                 
414                 return min(maxVal, max(minVal, x));
415         }
template<template< typename, precision > class vecType, precision P> GLM_FUNC_QUALIFIER vecType< int, P > glm::floatBitsToInt (vecType< float, P > const & v) [inline]
Returns a signed integer value representing the encoding of a floating-point value. The floatingpoint value's bit-level representation is preserved.
See also: GLSL floatBitsToInt man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 857 of file func_common.inl.
858         {
859                 return reinterpret_cast<vecType<int, P>&>(const_cast<vecType<float, P>&>(v));
860         }
GLM_FUNC_QUALIFIER int glm::floatBitsToInt (float const & v)
Returns a signed integer value representing the encoding of a floating-point value. The floating-point value's bit-level representation is preserved.
See also: GLSL floatBitsToInt man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 851 of file func_common.inl.
852         {
853                 return reinterpret_cast<int&>(const_cast<float&>(v));
854         }
template<template< typename, precision > class vecType, precision P> GLM_FUNC_QUALIFIER vecType< uint, P > glm::floatBitsToUint (vecType< float, P > const & v) [inline]
Returns a unsigned integer value representing the encoding of a floating-point value. The floatingpoint value's bit-level representation is preserved.
See also: GLSL floatBitsToUint man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 868 of file func_common.inl.
869         {
870                 return reinterpret_cast<vecType<uint, P>&>(const_cast<vecType<float, P>&>(v));
871         }
GLM_FUNC_QUALIFIER uint glm::floatBitsToUint (float const & v)
Returns a unsigned integer value representing the encoding of a floating-point value. The floatingpoint value's bit-level representation is preserved.
See also: GLSL floatBitsToUint man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 862 of file func_common.inl.
863         {
864                 return reinterpret_cast<uint&>(const_cast<float&>(v));
865         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::floor (genType const & x) [inline]
Returns a value equal to the nearest integer that is less then or equal to x.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL floor man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 170 of file func_common.inl.
Referenced by glm::fract(), glm::mirrorRepeat(), glm::mod(), glm::rgbColor(), and glm::trunc().
171         {
172                 GLM_STATIC_ASSERT(
173                         std::numeric_limits<genType>::is_iec559,
174                         "'floor' only accept floating-point inputs");
175 
176                 return ::std::floor(x);
177         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::fma (genType const & a, genType const & b, genType const & c) [inline]
Computes and returns a * b + c.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL fma man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 897 of file func_common.inl.
902         {
903                 return a * b + c;
904         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::fract (genType const & x) [inline]
Return x - floor(x).
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL fract man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 272 of file func_common.inl.
References glm::floor().
Referenced by glm::repeat(), and glm::roundEven().
275         {
276                 GLM_STATIC_ASSERT(
277                         std::numeric_limits<genType>::is_iec559,
278                         "'fract' only accept floating-point inputs");
279 
280                 return x - floor(x);
281         }
template<typename genType, typename genIType> GLM_FUNC_DECL genType glm::frexp (genType const & x, genIType & exp) [inline]
Splits x into a floating-point significand in the range [0.5, 1.0) and an integral exponent of two, such that: x = significand * exp(2, exponent)
The significand is returned by the function and the exponent is returned in the parameter exp. For a floating-point value of zero, the significant and exponent are both zero. For a floating-point value that is an infinity or is not a number, the results are undefined.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL frexp man page
GLSL 4.20.8 specification, section 8.3 Common Functions
template<template< typename, precision > class vecType, precision P> GLM_FUNC_QUALIFIER vecType< float, P > glm::intBitsToFloat (vecType< int, P > const & v) [inline]
Returns a floating-point value corresponding to a signed integer encoding of a floating-point value. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified. Otherwise, the bit-level representation is preserved.
See also: GLSL intBitsToFloat man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 879 of file func_common.inl.
880         {
881                 return reinterpret_cast<vecType<float, P>&>(const_cast<vecType<int, P>&>(v));
882         }
GLM_FUNC_QUALIFIER float glm::intBitsToFloat (int const & v)
Returns a floating-point value corresponding to a signed integer encoding of a floating-point value. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified. Otherwise, the bit-level representation is preserved.
See also: GLSL intBitsToFloat man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 873 of file func_common.inl.
874         {
875                 return reinterpret_cast<float&>(const_cast<int&>(v));
876         }
template<typename genType> GLM_FUNC_QUALIFIER bool glm::isinf (genType const & x) [inline]
Returns true if x holds a positive infinity or negative infinity representation in the underlying implementation's set of floating point representations. Returns false otherwise, including for implementations with no infinity representations.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL isinf man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 780 of file func_common.inl.
782         {
783                 GLM_STATIC_ASSERT(
784                         std::numeric_limits<genType>::is_iec559,
785                         "'isinf' only accept floating-point inputs");
786 
787 #               if(GLM_COMPILER & (GLM_COMPILER_INTEL | GLM_COMPILER_VC))
788                         return _fpclass(x) == _FPCLASS_NINF || _fpclass(x) == _FPCLASS_PINF;
789 #               elif(GLM_COMPILER & (GLM_COMPILER_GCC | GLM_COMPILER_CLANG))
790 #                       if(GLM_PLATFORM & GLM_PLATFORM_ANDROID && __cplusplus < 201103L)
791                                 return _isinf(x) != 0;
792 #                       else
793                                 return std::isinf(x);
794 #                       endif
795 #               elif(GLM_COMPILER & GLM_COMPILER_CUDA)
796                         // http://developer.download.nvidia.com/compute/cuda/4_2/rel/toolkit/docs/online/group__CUDA__MATH__DOUBLE_g13431dd2b40b51f9139cbb7f50c18fab.html#g13431dd2b40b51f9139cbb7f50c18fab
797                         return isinf(double(x)) != 0;
798 #               else
799                         return std::isinf(x);
800 #               endif
801         }
template<typename genType> GLM_FUNC_QUALIFIER bool glm::isnan (genType const & x) [inline]
Returns true if x holds a NaN (not a number) representation in the underlying implementation's set of floating point representations. Returns false otherwise, including for implementations with no NaN representations.
/!\ When using compiler fast math, this function may fail.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL isnan man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 710 of file func_common.inl.
711         {
712                 GLM_STATIC_ASSERT(
713                         std::numeric_limits<genType>::is_iec559,
714                         "'isnan' only accept floating-point inputs");
715 
716 #               if(GLM_COMPILER & (GLM_COMPILER_VC | GLM_COMPILER_INTEL))
717                         return _isnan(x) != 0;
718 #               elif(GLM_COMPILER & (GLM_COMPILER_GCC | GLM_COMPILER_CLANG))
719 #                       if(GLM_PLATFORM & GLM_PLATFORM_ANDROID && __cplusplus < 201103L)
720                                 return _isnan(x) != 0;
721 #                       else
722                                 return std::isnan(x);
723 #                       endif
724 #               elif(GLM_COMPILER & GLM_COMPILER_CUDA)
725                         return isnan(x) != 0;
726 #               else
727                         return std::isnan(x);
728 #               endif
729         }
template<typename genType, typename genIType> GLM_FUNC_DECL genType glm::ldexp (genType const & x, genIType const & exp) [inline]
Builds a floating-point number from x and the corresponding integral exponent of two in exp, returning: significand * exp(2, exponent)
If this product is too large to be represented in the floating-point type, the result is undefined.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL ldexp man page;
GLSL 4.20.8 specification, section 8.3 Common Functions
template<typename genType> GLM_FUNC_QUALIFIER genType glm::max (genType const & x, genType const & y) [inline]
Returns y if x < y; otherwise, it returns x.
Template Parameters:
genType Floating-point or integer; scalar or vector types.
See also: GLSL max man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 386 of file func_common.inl.
Referenced by glm::areOrthogonal(), glm::clamp(), glm::hsvColor(), and glm::max().
390         {
391                 GLM_STATIC_ASSERT(
392                         std::numeric_limits<genType>::is_iec559 || std::numeric_limits<genType>::is_integer,
393                         "'max' only accept floating-point or integer inputs");
394 
395                 return x > y ? x : y;
396         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::min (genType const & x, genType const & y) [inline]
Returns y if y < x; otherwise, it returns x.
Template Parameters:
genType Floating-point or integer; scalar or vector types.
See also: GLSL min man page
GLSL 4.20.8 specification, section 8.3 Common Functions<<<<<<< HEAD
Definition at line 368 of file func_common.inl.
Referenced by glm::clamp(), glm::hsvColor(), and glm::min().
372         {
373                 GLM_STATIC_ASSERT(
374                         std::numeric_limits<genType>::is_iec559 || std::numeric_limits<genType>::is_integer,
375                         "'min' only accept floating-point or integer inputs");
376 
377                 return x < y ? x : y;
378         }
template<typename T, typename U, precision P, template< typename, precision > class vecType> GLM_FUNC_QUALIFIER vecType< T, P > glm::mix (vecType< T, P > const & x, vecType< T, P > const & y, vecType< U, P > const & a) [inline]
If genTypeU is a floating scalar or vector: Returns x * (1.0 - a) + y * a, i.e., the linear blend of x and y using the floating-point value a. The value for a is not restricted to the range [0, 1].
If genTypeU is a boolean scalar or vector: Selects which vector each returned component comes from. For a component of that is false, the corresponding component of x is returned. For a component of a that is true, the corresponding component of y is returned. Components of x and y that are not selected are allowed to be invalid floating point values and will have no effect on the results. Thus, this provides different functionality than genType mix(genType x, genType y, genType(a)) where a is a Boolean vector.
See also: GLSL mix man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Parameters:
$\leftarrow$ x Value to interpolate.
$\leftarrow$ y Value to interpolate.
$\leftarrow$ a Interpolant.
Template Parameters:
genTypeT Floating point scalar or vector.
genTypeU Floating point or boolean scalar or vector. It can't be a vector if it is the length of genTypeT.
 #include <glm/glm.hpp>
 ...
 float a;
 bool b;
 glm::dvec3 e;
 glm::dvec3 f;
 glm::vec4 g;
 glm::vec4 h;
 ...
 glm::vec4 r = glm::mix(g, h, a); // Interpolate with a floating-point scalar two vectors. 
 glm::vec4 s = glm::mix(g, h, b); // Teturns g or h;
 glm::dvec3 t = glm::mix(e, f, a); // Types of the third parameter is not required to match with the first and the second.
 glm::vec4 u = glm::mix(g, h, r); // Interpolations can be perform per component with a vector for the last parameter.
Definition at line 527 of file func_common.inl.
Referenced by glm::lerp(), glm::squad(), and glm::step().
532         {
533                 return detail::compute_mix_vector<T, U, P, vecType>::call(x, y, a);
534         }
template<typename genType> GLM_FUNC_DECL genType glm::mod (genType const & x, typename genType::value_type const & y) [inline]
Modulus. Returns x - y * floor(x / y) for each component in x using the floating point value y.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL mod man page
GLSL 4.20.8 specification, section 8.3 Common Functions
template<typename genType> GLM_FUNC_QUALIFIER genType glm::mod (genType const & x, genType const & y) [inline]
Modulus. Returns x - y * floor(x / y) for each component in x using the floating point value y.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL mod man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 288 of file func_common.inl.
References glm::floor().
292         {
293                 GLM_STATIC_ASSERT(
294                         std::numeric_limits<genType>::is_iec559,
295                         "'mod' only accept floating-point inputs");
296 
297                 return x - y * floor(x / y);
298         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::modf (genType const & x, genType & i) [inline]
Returns the fractional part of x and sets i to the integer part (as a whole number floating point value). Both the return value and the output parameter will have the same sign as x.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL modf man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 306 of file func_common.inl.
310         {
311                 GLM_STATIC_ASSERT(
312                         std::numeric_limits<genType>::is_iec559,
313                         "'modf' only accept floating-point inputs");
314 
315                 return std::modf(x, &i);
316         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::round (genType const & x) [inline]
Returns a value equal to the nearest integer to x. The fraction 0.5 will round in a direction chosen by the implementation, presumably the direction that is fastest. This includes the possibility that round(x) returns the same value as roundEven(x) for all values of x.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL round man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 197 of file func_common.inl.
Referenced by glm::packSnorm1x16(), glm::packSnorm1x8(), glm::packSnorm2x16(), glm::packSnorm2x8(), glm::packSnorm3x10_1x2(), glm::packSnorm4x16(), glm::packSnorm4x8(), glm::packUnorm1x16(), glm::packUnorm1x8(), glm::packUnorm2x16(), glm::packUnorm2x8(), glm::packUnorm3x10_1x2(), glm::packUnorm4x16(), glm::packUnorm4x8(), and glm::roundEven().
198         {
199                 GLM_STATIC_ASSERT(
200                         std::numeric_limits<genType>::is_iec559,
201                         "'round' only accept floating-point inputs");
202 
203                 // TODO, add C++11 std::round
204                 return x < 0 ? genType(int(x - genType(0.5))) : genType(int(x + genType(0.5)));
205         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::roundEven (genType const & x) [inline]
Returns a value equal to the nearest integer to x. A fractional part of 0.5 will round toward the nearest even integer. (Both 3.5 and 4.5 for x will return 4.0.)
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL roundEven man page
GLSL 4.20.8 specification, section 8.3 Common Functions
New round to even technique
Definition at line 222 of file func_common.inl.
References glm::fract(), and glm::round().
223         {
224                 GLM_STATIC_ASSERT(
225                         std::numeric_limits<genType>::is_iec559,
226                         "'roundEven' only accept floating-point inputs");
227                 
228                 int Integer = static_cast<int>(x);
229                 genType IntegerPart = static_cast<genType>(Integer);
230                 genType FractionalPart = fract(x);
231 
232                 if(FractionalPart > static_cast<genType>(0.5) || FractionalPart < static_cast<genType>(0.5))
233                 {
234                         return round(x);
235                 }
236                 else if((Integer % 2) == 0)
237                 {
238                         return IntegerPart;
239                 }
240                 else if(x <= static_cast<genType>(0)) // Work around... 
241                 {
242                         return IntegerPart - static_cast<genType>(1);
243                 }
244                 else
245                 {
246                         return IntegerPart + static_cast<genType>(1);
247                 }
248                 //else // Bug on MinGW 4.5.2
249                 //{
250                 //      return mix(IntegerPart + genType(-1), IntegerPart + genType(1), x <= genType(0));
251                 //}
252         }
template<typename genType> GLM_FUNC_DECL genType glm::sign (genType const & x) [inline]
Returns 1.0 if x > 0, 0.0 if x == 0, or -1.0 if x < 0.
Template Parameters:
genType Floating-point or signed integer; scalar or vector types.
See also: GLSL sign man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Referenced by glm::fastAtan(), btQuaternion::slerp(), and b3Quaternion::slerp().
template<typename genType> GLM_FUNC_QUALIFIER genType glm::smoothstep (genType const & edge0, genType const & edge1, genType const & x) [inline]
Returns 0.0 if x <= edge0 and 1.0 if x >= edge1 and performs smooth Hermite interpolation between 0 and 1 when edge0 < x < edge1. This is useful in cases where you would want a threshold function with a smooth transition. This is equivalent to: genType t; t = clamp ((x - edge0) / (edge1 - edge0), 0, 1); return t * t * (3 - 2 * t); Results are undefined if edge0 >= edge1.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL smoothstep man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 586 of file func_common.inl.
References glm::clamp().
591         {
592                 GLM_STATIC_ASSERT(
593                         std::numeric_limits<genType>::is_iec559,
594                         "'smoothstep' only accept floating-point inputs");
595 
596                 genType tmp = clamp((x - edge0) / (edge1 - edge0), genType(0), genType(1));
597                 return tmp * tmp * (genType(3) - genType(2) * tmp);
598         }
template<template< typename, precision > class vecType, typename T, precision P> GLM_FUNC_QUALIFIER vecType< T, P > glm::step (T const & edge, vecType< T, P > const & x) [inline]
Returns 0.0 if x < edge, otherwise it returns 1.0.
See also: GLSL step man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 571 of file func_common.inl.
References glm::mix().
575         {
576                 GLM_STATIC_ASSERT(
577                         std::numeric_limits<T>::is_iec559,
578                         "'step' only accept floating-point inputs");
579 
580                 return mix(vecType<T, P>(1), vecType<T, P>(0), glm::lessThan(x, vecType<T, P>(edge)));
581         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::step (genType const & edge, genType const & x) [inline]
Returns 0.0 if x < edge, otherwise it returns 1.0 for each component of a genType.
See also: GLSL step man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 561 of file func_common.inl.
References glm::mix().
565         {
566                 return mix(genType(1), genType(0), glm::lessThan(x, edge));
567         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::trunc (genType const & x) [inline]
Returns a value equal to the nearest integer to x whose absolute value is not larger than the absolute value of x.
Template Parameters:
genType Floating-point scalar or vector types.
See also: GLSL trunc man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 183 of file func_common.inl.
References glm::floor().
184         {
185                 GLM_STATIC_ASSERT(
186                         std::numeric_limits<genType>::is_iec559,
187                         "'trunc' only accept floating-point inputs");
188 
189                 // TODO, add C++11 std::trunk
190                 return x < 0 ? -floor(-x) : floor(x);
191         }
template<template< typename, precision > class vecType, precision P> GLM_FUNC_QUALIFIER vecType< float, P > glm::uintBitsToFloat (vecType< uint, P > const & v) [inline]
Returns a floating-point value corresponding to a unsigned integer encoding of a floating-point value. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified. Otherwise, the bit-level representation is preserved.
See also: GLSL uintBitsToFloat man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 890 of file func_common.inl.
891         {
892                 return reinterpret_cast<vecType<float, P>&>(const_cast<vecType<uint, P>&>(v));
893         }
GLM_FUNC_QUALIFIER float glm::uintBitsToFloat (uint const & v)
Returns a floating-point value corresponding to a unsigned integer encoding of a floating-point value. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified. Otherwise, the bit-level representation is preserved.
See also: GLSL uintBitsToFloat man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 884 of file func_common.inl.
885         {
886                 return reinterpret_cast<float&>(const_cast<uint&>(v));
887         }