GLM_GTC_constants
Functions
template<typename genType>
GLM_FUNC_DECL genType glm::epsilon ()
template<typename genType>
GLM_FUNC_DECL genType glm::zero ()
template<typename genType>
GLM_FUNC_DECL genType glm::one ()
template<typename genType>
GLM_FUNC_DECL genType glm::pi ()
template<typename genType>
GLM_FUNC_DECL genType glm::root_pi ()
template<typename genType>
GLM_FUNC_DECL genType glm::half_pi ()
template<typename genType>
GLM_FUNC_DECL genType glm::quarter_pi ()
template<typename genType>
GLM_FUNC_DECL genType glm::one_over_pi ()
template<typename genType>
GLM_FUNC_DECL genType glm::two_over_pi ()
template<typename genType>
GLM_FUNC_DECL genType glm::two_over_root_pi ()
template<typename genType>
GLM_FUNC_DECL genType glm::one_over_root_two ()
template<typename genType>
GLM_FUNC_DECL genType glm::root_half_pi ()
template<typename genType>
GLM_FUNC_DECL genType glm::root_two_pi ()
template<typename genType>
GLM_FUNC_DECL genType glm::root_ln_four ()
template<typename genType>
GLM_FUNC_DECL genType glm::e ()
template<typename genType>
GLM_FUNC_DECL genType glm::euler ()
template<typename genType>
GLM_FUNC_DECL genType glm::root_two ()
template<typename genType>
GLM_FUNC_DECL genType glm::root_three ()
template<typename genType>
GLM_FUNC_DECL genType glm::root_five ()
template<typename genType>
GLM_FUNC_DECL genType glm::ln_two ()
template<typename genType>
GLM_FUNC_DECL genType glm::ln_ten ()
template<typename genType>
GLM_FUNC_DECL genType glm::ln_ln_two ()
template<typename genType>
GLM_FUNC_DECL genType glm::third ()
template<typename genType>
GLM_FUNC_DECL genType glm::two_thirds ()
template<typename genType>
GLM_FUNC_DECL genType glm::golden_ratio ()
Detailed Description
Provide a list of constants and precomputed useful values.
<glm/gtc/constants.hpp> need to be included to use these features.
Function Documentation
template<typename genType> GLM_FUNC_QUALIFIER genType glm::e () [inline]
Return e constant.
See also: GLM_GTC_constants
Definition at line 118 of file constants.inl.
Referenced by glm::unpackSnorm1x16(), glm::unpackSnorm2x16(), and glm::unpackUnorm2x16().
119         {
120                 return genType(2.71828182845904523536);
121         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::epsilon () [inline]
Return the epsilon constant for floating point types.
Todo Implement epsilon for half-precision floating point type.
See also: GLM_GTC_constants
Definition at line 34 of file constants.inl.
Referenced by glm::axisAngle(), btSubsimplexConvexCast::calcTimeOfImpact(), glm::intersectLineSphere(), glm::intersectLineTriangle(), glm::intersectRayPlane(), glm::intersectRaySphere(), and glm::intersectRayTriangle().
35         {
36                 return std::numeric_limits<genType>::epsilon();
37         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::euler () [inline]
Return Euler's constant.
See also: GLM_GTC_constants
Definition at line 124 of file constants.inl.
125         {
126                 return genType(0.577215664901532860606);
127         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::golden_ratio () [inline]
Return the golden ratio constant.
See also: GLM_GTC_constants
Definition at line 178 of file constants.inl.
179         {
180                 return genType(1.61803398874989484820458683436563811);
181         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::half_pi () [inline]
Return pi / 2.
See also: GLM_GTC_constants
Definition at line 64 of file constants.inl.
65         {
66                 return genType(1.57079632679489661923132169163975144);
67         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::ln_ln_two () [inline]
Return ln(ln(2)).
See also: GLM_GTC_constants
Definition at line 160 of file constants.inl.
161         {
162                 return genType(-0.3665129205816643);
163         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::ln_ten () [inline]
Return ln(10).
See also: GLM_GTC_constants
Definition at line 154 of file constants.inl.
155         {
156                 return genType(2.30258509299404568401799145468436421);
157         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::ln_two () [inline]
Return ln(2).
See also: GLM_GTC_constants
Definition at line 148 of file constants.inl.
149         {
150                 return genType(0.693147180559945309417232121458176568);
151         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::one () [inline]
Return 1.
See also: GLM_GTC_constants
Definition at line 46 of file constants.inl.
Referenced by glm::lerp().
47         {
48                 return genType(1);
49         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::one_over_pi () [inline]
Return 1 / pi.
See also: GLM_GTC_constants
Definition at line 76 of file constants.inl.
77         {
78                 return genType(0.318309886183790671537767526745028724);
79         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::one_over_root_two () [inline]
Return 1 / sqrt(2).
See also: GLM_GTC_constants
Definition at line 94 of file constants.inl.
95         {
96                 return genType(0.707106781186547524400844362104849039);
97         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::pi () [inline]
Return the pi constant.
See also: GLM_GTC_constants
Definition at line 52 of file constants.inl.
53         {
54                 return genType(3.14159265358979323846264338327950288);
55         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::quarter_pi () [inline]
Return pi / 4.
See also: GLM_GTC_constants
Definition at line 70 of file constants.inl.
71         {
72                 return genType(0.785398163397448309615660845819875721);
73         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::root_five () [inline]
Return sqrt(5).
See also: GLM_GTC_constants
Definition at line 142 of file constants.inl.
143         {
144                 return genType(2.23606797749978969640917366873127623);
145         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::root_half_pi () [inline]
Return sqrt(pi / 2).
See also: GLM_GTC_constants
Definition at line 100 of file constants.inl.
101         {
102                 return genType(1.253314137315500251);
103         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::root_ln_four () [inline]
Return sqrt(ln(4)).
See also: GLM_GTC_constants
Definition at line 112 of file constants.inl.
113         {
114                 return genType(1.17741002251547469);
115         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::root_pi () [inline]
Return square root of pi.
See also: GLM_GTC_constants
Definition at line 58 of file constants.inl.
59         {
60                 return genType(1.772453850905516027);
61         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::root_three () [inline]
Return sqrt(3).
See also: GLM_GTC_constants
Definition at line 136 of file constants.inl.
137         {
138                 return genType(1.73205080756887729352744634150587236);
139         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::root_two () [inline]
Return sqrt(2).
See also: GLM_GTC_constants
Definition at line 130 of file constants.inl.
131         {
132                 return genType(1.41421356237309504880168872420969808);
133         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::root_two_pi () [inline]
Return sqrt(2 * pi).
See also: GLM_GTC_constants
Definition at line 106 of file constants.inl.
107         {
108                 return genType(2.506628274631000502);
109         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::third () [inline]
Return 1 / 3.
See also: GLM_GTC_constants
Definition at line 166 of file constants.inl.
167         {
168                 return genType(0.3333333333333333333333333333333333333333);
169         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::two_over_pi () [inline]
Return 2 / pi.
See also: GLM_GTC_constants
Definition at line 82 of file constants.inl.
83         {
84                 return genType(0.636619772367581343075535053490057448);
85         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::two_over_root_pi () [inline]
Return 2 / sqrt(pi).
See also: GLM_GTC_constants
Definition at line 88 of file constants.inl.
89         {
90                 return genType(1.12837916709551257389615890312154517);
91         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::two_thirds () [inline]
Return 2 / 3.
See also: GLM_GTC_constants
Definition at line 172 of file constants.inl.
173         {
174                 return genType(0.666666666666666666666666666666666666667);
175         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::zero () [inline]
Return 0.
See also: GLM_GTC_constants
Definition at line 40 of file constants.inl.
41         {
42                 return genType(0);
43         }