GLM_GTX_polar_coordinates
Functions
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::polar (detail::tvec3< T, P > const &euclidean)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::euclidean (detail::tvec2< T, P > const &polar)
Detailed Description
Conversion from Euclidean space to polar space and revert.
<glm/gtx/polar_coordinates.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::euclidean (detail::tvec2< T, P > const & polar) [inline]
Convert Polar to Euclidean coordinates.
See also: GLM_GTX_polar_coordinates
Definition at line 38 of file polar_coordinates.inl.
References glm::cos(), glm::radians(), and glm::sin().
41         {
42 #ifdef GLM_FORCE_RADIANS
43                 T const latitude(polar.x);
44                 T const longitude(polar.y);
45 #else
46 #               pragma message("GLM: euclidean function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
47                 T const latitude(radians(polar.x));
48                 T const longitude(radians(polar.y));
49 #endif
50 
51                 return detail::tvec3<T, P>(
52                         cos(latitude) * sin(longitude),
53                         sin(latitude),
54                         cos(latitude) * cos(longitude));
55         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::polar (detail::tvec3< T, P > const & euclidean) [inline]
Convert Euclidean to Polar coordinates, x is the xz distance, y, the latitude and z the longitude.
See also: GLM_GTX_polar_coordinates
Definition at line 14 of file polar_coordinates.inl.
References glm::atan(), glm::degrees(), glm::length(), and glm::sqrt().
17         {
18                 T const Length(length(euclidean));
19                 detail::tvec3<T, P> const tmp(euclidean / Length);
20                 T const xz_dist(sqrt(tmp.x * tmp.x + tmp.z * tmp.z));
21 
22 #ifdef GLM_FORCE_RADIANS
23                 return detail::tvec3<T, P>(
24                         atan(xz_dist, tmp.y),   // latitude
25                         atan(tmp.x, tmp.z),             // longitude
26                         xz_dist);                               // xz distance
27 #else
28 #               pragma message("GLM: polar function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
29                 return detail::tvec3<T, P>(
30                         degrees(atan(xz_dist, tmp.y)),  // latitude
31                         degrees(atan(tmp.x, tmp.z)),    // longitude
32                         xz_dist);                                               // xz distance
33 #endif
34         }