GLM_GTX_vector_angle
Functions
template<typename vecType>
GLM_FUNC_DECL vecType::value_type glm::angle (vecType const &x, vecType const &y)
template<typename T, precision P>
GLM_FUNC_DECL T glm::orientedAngle (detail::tvec2< T, P > const &x, detail::tvec2< T, P > const &y)
template<typename T, precision P>
GLM_FUNC_DECL T glm::orientedAngle (detail::tvec3< T, P > const &x, detail::tvec3< T, P > const &y, detail::tvec3< T, P > const &ref)
Detailed Description
Compute angle between vectors.
<glm/gtx/vector_angle.hpp> need to be included to use these functionalities.
Function Documentation
template<typename vecType> GLM_FUNC_DECL vecType::value_type glm::angle (vecType const & x, vecType const & y) [inline]
Returns the absolute angle between two vectors Parameters need to be normalized.
See also: GLM_GTX_vector_angle extension
Referenced by glm::mix(), and glm::slerp().
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::orientedAngle (detail::tvec3< T, P > const & x, detail::tvec3< T, P > const & y, detail::tvec3< T, P > const & ref) [inline]
Returns the oriented angle between two 3d vectors based from a reference axis. Parameters need to be normalized.
See also: GLM_GTX_vector_angle extension.
Definition at line 77 of file vector_angle.inl.
References glm::acos(), glm::clamp(), glm::cross(), glm::degrees(), and glm::dot().
82         {
83                 GLM_STATIC_ASSERT(std::numeric_limits<T>::is_iec559, "'orientedAngle' only accept floating-point inputs");
84 
85                 T const Dot = clamp(dot(x, y), T(-1), T(1));
86 
87 #ifdef GLM_FORCE_RADIANS
88                 T const Angle(acos(Dot));
89 #else
90 #               pragma message("GLM: orientedAngle function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
91                 T const Angle(degrees(acos(Dot)));
92 #endif
93 
94                 if(dot(ref, cross(x, y)) < T(0))
95                         return -Angle;
96                 else
97                         return Angle;
98         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::orientedAngle (detail::tvec2< T, P > const & x, detail::tvec2< T, P > const & y) [inline]
Returns the oriented angle between two 2d vectors Parameters need to be normalized.
See also: GLM_GTX_vector_angle extension.
Todo epsilon is hard coded to 0.01
Definition at line 53 of file vector_angle.inl.
References glm::acos(), glm::all(), glm::clamp(), glm::degrees(), glm::dot(), glm::epsilonEqual(), and glm::rotate().
57         {
58                 GLM_STATIC_ASSERT(std::numeric_limits<T>::is_iec559, "'orientedAngle' only accept floating-point inputs");
59 
60                 T const Dot = clamp(dot(x, y), T(-1), T(1));
61 
62 #ifdef GLM_FORCE_RADIANS
63                 T const Angle(acos(Dot));
64 #else
65 #               pragma message("GLM: orientedAngle function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
66                 T const Angle(degrees(acos(Dot)));
67 #endif
68                 detail::tvec2<T, P> const TransformedVector(glm::rotate(x, Angle));
69                 if(all(epsilonEqual(y, TransformedVector, T(0.01))))
70                         return Angle;
71                 else
72                         return -Angle;
73         }