GLM_GTC_type_ptr
Functions
template<typename genType>
GLM_FUNC_DECL genType::value_type const * glm::value_ptr (genType const &vec)
template<typename T>
GLM_FUNC_DECL detail::tvec2< T, defaultp > glm::make_vec2 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tvec3< T, defaultp > glm::make_vec3 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tvec4< T, defaultp > glm::make_vec4 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tmat2x2< T, defaultp > glm::make_mat2x2 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tmat2x3< T, defaultp > glm::make_mat2x3 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tmat2x4< T, defaultp > glm::make_mat2x4 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tmat3x2< T, defaultp > glm::make_mat3x2 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tmat3x3< T, defaultp > glm::make_mat3x3 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tmat3x4< T, defaultp > glm::make_mat3x4 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tmat4x2< T, defaultp > glm::make_mat4x2 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tmat4x3< T, defaultp > glm::make_mat4x3 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::make_mat4x4 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tmat2x2< T, defaultp > glm::make_mat2 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tmat3x3< T, defaultp > glm::make_mat3 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::make_mat4 (T const *const ptr)
template<typename T>
GLM_FUNC_DECL detail::tquat< T, defaultp > glm::make_quat (T const *const ptr)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tvec2< T, P > const &vec)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tvec2< T, P > &vec)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tvec3< T, P > const &vec)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tvec3< T, P > &vec)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tvec4< T, P > const &vec)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tvec4< T, P > &vec)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat2x2< T, P > const &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat2x2< T, P > &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat3x3< T, P > const &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat3x3< T, P > &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat4x4< T, P > const &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat4x4< T, P > &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat2x3< T, P > const &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat2x3< T, P > &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat3x2< T, P > const &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat3x2< T, P > &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat2x4< T, P > const &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat2x4< T, P > &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat4x2< T, P > const &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat4x2< T, P > &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat3x4< T, P > const &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat3x4< T, P > &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat4x3< T, P > const &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat4x3< T, P > &mat)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tquat< T, P > const &q)
template<typename T, precision P>
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tquat< T, P > &q)
Detailed Description
Handles the interaction between pointers and vector, matrix types.
This extension defines an overloaded function, glm::value_ptr, which takes any of the core template types. It returns a pointer to the memory layout of the object. Matrix types store their values in column-major order.
This is useful for uploading data to matrices or copying data to buffer objects.
Example:
 #include <glm/glm.hpp>
 #include <glm/gtc/type_ptr.hpp>
 
 glm::vec3 aVector(3);
 glm::mat4 someMatrix(1.0);
 
 glUniform3fv(uniformLoc, 1, glm::value_ptr(aVector));
 glUniformMatrix4fv(uniformMatrixLoc, 1, GL_FALSE, glm::value_ptr(someMatrix));
<glm/gtc/type_ptr.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T> GLM_FUNC_QUALIFIER detail::tmat2x2< T, defaultp > glm::make_mat2 (T const *const ptr) [inline]
Build a matrix from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 442 of file type_ptr.inl.
References glm::make_mat2x2().
443         {
444                 return make_mat2x2(ptr);
445         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat2x2< T, defaultp > glm::make_mat2x2 (T const *const ptr) [inline]
Build a matrix from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 352 of file type_ptr.inl.
References glm::value_ptr().
Referenced by glm::make_mat2().
353         {
354                 detail::tmat2x2<T, defaultp> Result;
355                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat2x2<T, defaultp>));
356                 return Result;
357         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat2x3< T, defaultp > glm::make_mat2x3 (T const *const ptr) [inline]
Build a matrix from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 362 of file type_ptr.inl.
References glm::value_ptr().
363         {
364                 detail::tmat2x3<T, defaultp> Result;
365                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat2x3<T, defaultp>));
366                 return Result;
367         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat2x4< T, defaultp > glm::make_mat2x4 (T const *const ptr) [inline]
Build a matrix from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 372 of file type_ptr.inl.
References glm::value_ptr().
373         {
374                 detail::tmat2x4<T, defaultp> Result;
375                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat2x4<T, defaultp>));
376                 return Result;
377         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat3x3< T, defaultp > glm::make_mat3 (T const *const ptr) [inline]
Build a matrix from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 450 of file type_ptr.inl.
References glm::make_mat3x3().
451         {
452                 return make_mat3x3(ptr);
453         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat3x2< T, defaultp > glm::make_mat3x2 (T const *const ptr) [inline]
Build a matrix from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 382 of file type_ptr.inl.
References glm::value_ptr().
383         {
384                 detail::tmat3x2<T, defaultp> Result;
385                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat3x2<T, defaultp>));
386                 return Result;
387         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat3x3< T, defaultp > glm::make_mat3x3 (T const *const ptr) [inline]
Build a matrix from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 392 of file type_ptr.inl.
References glm::value_ptr().
Referenced by glm::make_mat3().
393         {
394                 detail::tmat3x3<T, defaultp> Result;
395                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat3x3<T, defaultp>));
396                 return Result;
397         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat3x4< T, defaultp > glm::make_mat3x4 (T const *const ptr) [inline]
Build a matrix from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 402 of file type_ptr.inl.
References glm::value_ptr().
403         {
404                 detail::tmat3x4<T, defaultp> Result;
405                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat3x4<T, defaultp>));
406                 return Result;
407         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::make_mat4 (T const *const ptr) [inline]
Build a matrix from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 458 of file type_ptr.inl.
References glm::make_mat4x4().
459         {
460                 return make_mat4x4(ptr);
461         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x2< T, defaultp > glm::make_mat4x2 (T const *const ptr) [inline]
Build a matrix from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 412 of file type_ptr.inl.
References glm::value_ptr().
413         {
414                 detail::tmat4x2<T, defaultp> Result;
415                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat4x2<T, defaultp>));
416                 return Result;
417         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x3< T, defaultp > glm::make_mat4x3 (T const *const ptr) [inline]
Build a matrix from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 422 of file type_ptr.inl.
References glm::value_ptr().
423         {
424                 detail::tmat4x3<T, defaultp> Result;
425                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat4x3<T, defaultp>));
426                 return Result;
427         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::make_mat4x4 (T const *const ptr) [inline]
Build a matrix from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 432 of file type_ptr.inl.
References glm::value_ptr().
Referenced by glm::make_mat4().
433         {
434                 detail::tmat4x4<T, defaultp> Result;
435                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat4x4<T, defaultp>));
436                 return Result;
437         }
template<typename T> GLM_FUNC_QUALIFIER detail::tquat< T, defaultp > glm::make_quat (T const *const ptr) [inline]
Build a quaternion from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 466 of file type_ptr.inl.
References glm::value_ptr().
467         {
468                 detail::tquat<T, defaultp> Result;
469                 memcpy(value_ptr(Result), ptr, sizeof(detail::tquat<T, defaultp>));
470                 return Result;
471         }
template<typename T> GLM_FUNC_QUALIFIER detail::tvec2< T, defaultp > glm::make_vec2 (T const *const ptr) [inline]
Build a vector from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 322 of file type_ptr.inl.
References glm::value_ptr().
323         {
324                 detail::tvec2<T, defaultp> Result;
325                 memcpy(value_ptr(Result), ptr, sizeof(detail::tvec2<T, defaultp>));
326                 return Result;
327         }
template<typename T> GLM_FUNC_QUALIFIER detail::tvec3< T, defaultp > glm::make_vec3 (T const *const ptr) [inline]
Build a vector from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 332 of file type_ptr.inl.
References glm::value_ptr().
333         {
334                 detail::tvec3<T, defaultp> Result;
335                 memcpy(value_ptr(Result), ptr, sizeof(detail::tvec3<T, defaultp>));
336                 return Result;
337         }
template<typename T> GLM_FUNC_QUALIFIER detail::tvec4< T, defaultp > glm::make_vec4 (T const *const ptr) [inline]
Build a vector from a pointer.
See also: GLM_GTC_type_ptr
Definition at line 342 of file type_ptr.inl.
References glm::value_ptr().
343         {
344                 detail::tvec4<T, defaultp> Result;
345                 memcpy(value_ptr(Result), ptr, sizeof(detail::tvec4<T, defaultp>));
346                 return Result;
347         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tquat< T, P > & q) [inline]
Return the address to the data of the quaternion input.
See also: GLM_GTC_type_ptr
Definition at line 312 of file type_ptr.inl.
315         {
316                 return &(q[0]);
317         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tquat< T, P > const & q) [inline]
Return the constant address to the data of the input parameter.
See also: GLM_GTC_type_ptr
Definition at line 301 of file type_ptr.inl.
304         {
305                 return &(q[0]);
306         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat4x3< T, P > & mat) [inline]
Return the address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 292 of file type_ptr.inl.
293         {
294                 return &(mat[0].x);
295         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat4x3< T, P > const & mat) [inline]
Return the constant address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 282 of file type_ptr.inl.
285         {
286                 return &(mat[0].x);
287         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat3x4< T, P > & mat) [inline]
Return the address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 271 of file type_ptr.inl.
274         {
275                 return &(mat[0].x);
276         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat3x4< T, P > const & mat) [inline]
Return the constant address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 260 of file type_ptr.inl.
263         {
264                 return &(mat[0].x);
265         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat4x2< T, P > & mat) [inline]
Return the address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 249 of file type_ptr.inl.
252         {
253                 return &(mat[0].x);
254         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat4x2< T, P > const & mat) [inline]
Return the constant address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 238 of file type_ptr.inl.
241         {
242                 return &(mat[0].x);
243         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat2x4< T, P > & mat) [inline]
Return the address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 227 of file type_ptr.inl.
230         {
231                 return &(mat[0].x);
232         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat2x4< T, P > const & mat) [inline]
Return the constant address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 216 of file type_ptr.inl.
219         {
220                 return &(mat[0].x);
221         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat3x2< T, P > & mat) [inline]
Return the address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 205 of file type_ptr.inl.
208         {
209                 return &(mat[0].x);
210         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat3x2< T, P > const & mat) [inline]
Return the constant address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 194 of file type_ptr.inl.
197         {
198                 return &(mat[0].x);
199         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat2x3< T, P > & mat) [inline]
Return the address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 183 of file type_ptr.inl.
186         {
187                 return &(mat[0].x);
188         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat2x3< T, P > const & mat) [inline]
Return the constant address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 172 of file type_ptr.inl.
175         {
176                 return &(mat[0].x);
177         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat4x4< T, P > & mat) [inline]
Return the address to the data of the matrix input. From GLM_GTC_type_ptr extension.
Definition at line 161 of file type_ptr.inl.
164         {
165                 return &(mat[0].x);
166         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat4x4< T, P > const & mat) [inline]
Return the constant address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 150 of file type_ptr.inl.
153         {
154                 return &(mat[0].x);
155         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat3x3< T, P > & mat) [inline]
Return the address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 139 of file type_ptr.inl.
142         {
143                 return &(mat[0].x);
144         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat3x3< T, P > const & mat) [inline]
Return the constant address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 128 of file type_ptr.inl.
131         {
132                 return &(mat[0].x);
133         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat2x2< T, P > & mat) [inline]
Return the address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 117 of file type_ptr.inl.
120         {
121                 return &(mat[0].x);
122         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat2x2< T, P > const & mat) [inline]
Return the constant address to the data of the matrix input.
See also: GLM_GTC_type_ptr
Definition at line 106 of file type_ptr.inl.
109         {
110                 return &(mat[0].x);
111         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tvec4< T, P > & vec) [inline]
Return the address to the data of the vector input. From GLM_GTC_type_ptr extension.
Definition at line 95 of file type_ptr.inl.
98         {
99                 return &(vec.x);
100         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tvec4< T, P > const & vec) [inline]
Return the constant address to the data of the vector input.
See also: GLM_GTC_type_ptr
Definition at line 84 of file type_ptr.inl.
87         {
88                 return &(vec.x);
89         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tvec3< T, P > & vec) [inline]
Return the address to the data of the vector input.
See also: GLM_GTC_type_ptr
Definition at line 73 of file type_ptr.inl.
76         {
77                 return &(vec.x);
78         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tvec3< T, P > const & vec) [inline]
Return the constant address to the data of the vector input.
See also: GLM_GTC_type_ptr
Definition at line 62 of file type_ptr.inl.
65         {
66                 return &(vec.x);
67         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tvec2< T, P > & vec) [inline]
Return the address to the data of the vector input.
See also: GLM_GTC_type_ptr
Definition at line 51 of file type_ptr.inl.
54         {
55                 return &(vec.x);
56         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tvec2< T, P > const & vec) [inline]
Return the constant address to the data of the vector input.
See also: GLM_GTC_type_ptr
Definition at line 40 of file type_ptr.inl.
43         {
44                 return &(vec.x);
45         }
template<typename genType> GLM_FUNC_DECL genType::value_type const* glm::value_ptr (genType const & vec) [inline]
Return the constant address to the data of the input parameter.
See also: GLM_GTC_type_ptr
Referenced by glm::make_mat2x2(), glm::make_mat2x3(), glm::make_mat2x4(), glm::make_mat3x2(), glm::make_mat3x3(), glm::make_mat3x4(), glm::make_mat4x2(), glm::make_mat4x3(), glm::make_mat4x4(), glm::make_quat(), glm::make_vec2(), glm::make_vec3(), and glm::make_vec4().