GLM_GTX_vector_query
Functions
template<typename T, precision P, template< typename, precision > class vecType>
GLM_FUNC_DECL bool glm::areCollinear (vecType< T, P > const &v0, vecType< T, P > const &v1, T const &epsilon)
template<typename T, precision P, template< typename, precision > class vecType>
GLM_FUNC_DECL bool glm::areOrthogonal (vecType< T, P > const &v0, vecType< T, P > const &v1, T const &epsilon)
template<typename T, precision P, template< typename, precision > class vecType>
GLM_FUNC_DECL bool glm::isNormalized (vecType< T, P > const &v, T const &epsilon)
template<typename T, precision P, template< typename, precision > class vecType>
GLM_FUNC_DECL bool glm::isNull (vecType< T, P > const &v, T const &epsilon)
template<typename T, precision P, template< typename, precision > class vecType>
GLM_FUNC_DECL vecType< bool, P > glm::isCompNull (vecType< T, P > const &v, T const &epsilon)
template<typename T, precision P, template< typename, precision > class vecType>
GLM_FUNC_DECL bool glm::areOrthonormal (vecType< T, P > const &v0, vecType< T, P > const &v1, T const &epsilon)
Detailed Description
Query informations of vector types.
<glm/gtx/vector_query.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T, precision P, template< typename, precision > class vecType> GLM_FUNC_QUALIFIER bool glm::areCollinear (vecType< T, P > const & v0, vecType< T, P > const & v1, T const & epsilon) [inline]
Check whether two vectors are collinears.
See also: GLM_GTX_vector_query extensions.
Definition at line 91 of file vector_query.inl.
96         {
97                 GLM_STATIC_ASSERT(std::numeric_limits<T>::is_iec559, "'areCollinear' only accept floating-point inputs");
98 
99                 return detail::compute_areCollinear<T, P, vecType>::call(v0, v1, epsilon);
100         }
template<typename T, precision P, template< typename, precision > class vecType> GLM_FUNC_QUALIFIER bool glm::areOrthogonal (vecType< T, P > const & v0, vecType< T, P > const & v1, T const & epsilon) [inline]
Check whether two vectors are orthogonals.
See also: GLM_GTX_vector_query extensions.
Definition at line 104 of file vector_query.inl.
References glm::abs(), glm::dot(), glm::length(), and glm::max().
Referenced by glm::isOrthogonal().
109         {
110                 GLM_STATIC_ASSERT(std::numeric_limits<T>::is_iec559, "'areOrthogonal' only accept floating-point inputs");
111 
112                 return abs(dot(v0, v1)) <= max(
113                         static_cast<T>(1),
114                         length(v0)) * max(static_cast<T>(1), length(v1)) * epsilon;
115         }
template<typename T, precision P, template< typename, precision > class vecType> GLM_FUNC_QUALIFIER bool glm::areOrthonormal (vecType< T, P > const & v0, vecType< T, P > const & v1, T const & epsilon) [inline]
Check whether two vectors are orthonormal.
See also: GLM_GTX_vector_query extensions.
Definition at line 193 of file vector_query.inl.
References glm::abs(), glm::dot(), and glm::isNormalized().
198         {
199                 return isNormalized(v0, epsilon) && isNormalized(v1, epsilon) && (abs(dot(v0, v1)) <= epsilon);
200         }
template<typename T, precision P, template< typename, precision > class vecType> GLM_FUNC_QUALIFIER vecType< bool, P > glm::isCompNull (vecType< T, P > const & v, T const & epsilon) [inline]
Check whether a each component of a vector is null.
See also: GLM_GTX_vector_query extensions.
Definition at line 143 of file vector_query.inl.
147         {
148                 GLM_STATIC_ASSERT(std::numeric_limits<T>::is_iec559, "'isCompNull' only accept floating-point inputs");
149 
150                 return detail::compute_isCompNull<T, P, vecType>::call(v, epsilon);
151         }
template<typename T, precision P, template< typename, precision > class vecType> GLM_FUNC_QUALIFIER bool glm::isNormalized (vecType< T, P > const & v, T const & epsilon) [inline]
Check whether a vector is normalized.
See also: GLM_GTX_vector_query extensions.
Definition at line 119 of file vector_query.inl.
References glm::abs(), and glm::length().
123         {
124                 GLM_STATIC_ASSERT(std::numeric_limits<T>::is_iec559, "'isNormalized' only accept floating-point inputs");
125 
126                 return abs(length(v) - static_cast<T>(1)) <= static_cast<T>(2) * epsilon;
127         }
template<typename T, precision P, template< typename, precision > class vecType> GLM_FUNC_QUALIFIER bool glm::isNull (vecType< T, P > const & v, T const & epsilon) [inline]
Check whether a vector is null.
See also: GLM_GTX_vector_query extensions.
Definition at line 131 of file vector_query.inl.
References glm::length().
135         {
136                 GLM_STATIC_ASSERT(std::numeric_limits<T>::is_iec559, "'isNull' only accept floating-point inputs");
137 
138                 return length(v) <= epsilon;
139         }