GLM_GTX_rotate_vector
Functions
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec2< T, P > glm::rotate (detail::tvec2< T, P > const &v, T const &angle)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::rotate (detail::tvec3< T, P > const &v, T const &angle, detail::tvec3< T, P > const &normal)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec4< T, P > glm::rotate (detail::tvec4< T, P > const &v, T const &angle, detail::tvec3< T, P > const &normal)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::rotateX (detail::tvec3< T, P > const &v, T const &angle)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::rotateY (detail::tvec3< T, P > const &v, T const &angle)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::rotateZ (detail::tvec3< T, P > const &v, T const &angle)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec4< T, P > glm::rotateX (detail::tvec4< T, P > const &v, T const &angle)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec4< T, P > glm::rotateY (detail::tvec4< T, P > const &v, T const &angle)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec4< T, P > glm::rotateZ (detail::tvec4< T, P > const &v, T const &angle)
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat4x4< T, P > glm::orientation (detail::tvec3< T, P > const &Normal, detail::tvec3< T, P > const &Up)
Detailed Description
Function to directly rotate a vector.
<glm/gtx/rotate_vector.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat4x4< T, P > glm::orientation (detail::tvec3< T, P > const & Normal, detail::tvec3< T, P > const & Up) [inline]
Build a rotation matrix from a normal and a up vector. From GLM_GTX_rotate_vector extension.
Definition at line 206 of file rotate_vector.inl.
References glm::acos(), glm::all(), glm::cross(), glm::degrees(), glm::dot(), and glm::rotate().
210         {
211                 if(all(equal(Normal, Up)))
212                         return detail::tmat4x4<T, P>(T(1));
213 
214                 detail::tvec3<T, P> RotationAxis = cross(Up, Normal);
215 #               ifdef GLM_FORCE_RADIANS
216                         T Angle = acos(dot(Normal, Up));
217 #               else
218 #                       pragma message("GLM: rotateZ function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
219                         T Angle = degrees(acos(dot(Normal, Up)));
220 #               endif
221                 return rotate(Angle, RotationAxis);
222         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec4< T, P > glm::rotate (detail::tvec4< T, P > const & v, T const & angle, detail::tvec3< T, P > const & normal) [inline]
Rotate a four dimensional vector around an axis. From GLM_GTX_rotate_vector extension.
Definition at line 57 of file rotate_vector.inl.
References glm::rotate().
62         {
63                 return rotate(angle, normal) * v;
64         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::rotate (detail::tvec3< T, P > const & v, T const & angle, detail::tvec3< T, P > const & normal) [inline]
Rotate a three dimensional vector around an axis. From GLM_GTX_rotate_vector extension.
Definition at line 35 of file rotate_vector.inl.
References glm::rotate().
40         {
41                 return detail::tmat3x3<T, P>(glm::rotate(angle, normal)) * v;
42         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec2< T, P > glm::rotate (detail::tvec2< T, P > const & v, T const & angle) [inline]
Rotate a two dimensional vector. From GLM_GTX_rotate_vector extension.
Definition at line 14 of file rotate_vector.inl.
References glm::cos(), glm::radians(), and glm::sin().
18         {
19                 detail::tvec2<T, P> Result;
20 #ifdef GLM_FORCE_RADIANS
21                 T const Cos(cos(angle));
22                 T const Sin(sin(angle));
23 #else
24 #               pragma message("GLM: rotate function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
25                 T const Cos = cos(radians(angle));
26                 T const Sin = sin(radians(angle));
27 #endif
28                 Result.x = v.x * Cos - v.y * Sin;
29                 Result.y = v.x * Sin + v.y * Cos;
30                 return Result;
31         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec4< T, P > glm::rotateX (detail::tvec4< T, P > const & v, T const & angle) [inline]
Rotate a four dimentionnals vector around the X axis. From GLM_GTX_rotate_vector extension.
Definition at line 137 of file rotate_vector.inl.
References glm::cos(), glm::radians(), and glm::sin().
141         {
142                 detail::tvec4<T, P> Result = v;
143 
144 #ifdef GLM_FORCE_RADIANS
145                 T const Cos(cos(angle));
146                 T const Sin(sin(angle));
147 #else
148 #               pragma message("GLM: rotateX function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
149                 T const Cos(cos(radians(angle)));
150                 T const Sin(sin(radians(angle)));
151 #endif
152 
153                 Result.y = v.y * Cos - v.z * Sin;
154                 Result.z = v.y * Sin + v.z * Cos;
155                 return Result;
156         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::rotateX (detail::tvec3< T, P > const & v, T const & angle) [inline]
Rotate a three dimensional vector around the X axis. From GLM_GTX_rotate_vector extension.
Definition at line 68 of file rotate_vector.inl.
References glm::cos(), glm::radians(), and glm::sin().
72         {
73                 detail::tvec3<T, P> Result(v);
74 
75 #ifdef GLM_FORCE_RADIANS
76                 T const Cos(cos(angle));
77                 T const Sin(sin(angle));
78 #else
79 #               pragma message("GLM: rotateX function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
80                 T const Cos = cos(radians(angle));
81                 T const Sin = sin(radians(angle));
82 #endif
83 
84                 Result.y = v.y * Cos - v.z * Sin;
85                 Result.z = v.y * Sin + v.z * Cos;
86                 return Result;
87         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec4< T, P > glm::rotateY (detail::tvec4< T, P > const & v, T const & angle) [inline]
Rotate a four dimensional vector around the X axis. From GLM_GTX_rotate_vector extension.
Definition at line 160 of file rotate_vector.inl.
References glm::cos(), glm::radians(), and glm::sin().
164         {
165                 detail::tvec4<T, P> Result = v;
166 
167 #ifdef GLM_FORCE_RADIANS
168                 T const Cos(cos(angle));
169                 T const Sin(sin(angle));
170 #else
171 #               pragma message("GLM: rotateX function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
172                 T const Cos(cos(radians(angle)));
173                 T const Sin(sin(radians(angle)));
174 #endif
175 
176                 Result.x =  v.x * Cos + v.z * Sin;
177                 Result.z = -v.x * Sin + v.z * Cos;
178                 return Result;
179         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::rotateY (detail::tvec3< T, P > const & v, T const & angle) [inline]
Rotate a three dimensional vector around the Y axis. From GLM_GTX_rotate_vector extension.
Definition at line 91 of file rotate_vector.inl.
References glm::cos(), glm::radians(), and glm::sin().
95         {
96                 detail::tvec3<T, P> Result = v;
97 
98 #ifdef GLM_FORCE_RADIANS
99                 T const Cos(cos(angle));
100                 T const Sin(sin(angle));
101 #else
102 #               pragma message("GLM: rotateY function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
103                 T const Cos(cos(radians(angle)));
104                 T const Sin(sin(radians(angle)));
105 #endif
106 
107                 Result.x =  v.x * Cos + v.z * Sin;
108                 Result.z = -v.x * Sin + v.z * Cos;
109                 return Result;
110         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec4< T, P > glm::rotateZ (detail::tvec4< T, P > const & v, T const & angle) [inline]
Rotate a four dimensional vector around the X axis. From GLM_GTX_rotate_vector extension.
Definition at line 183 of file rotate_vector.inl.
References glm::cos(), glm::radians(), and glm::sin().
187         {
188                 detail::tvec4<T, P> Result = v;
189 
190 #ifdef GLM_FORCE_RADIANS
191                 T const Cos(cos(angle));
192                 T const Sin(sin(angle));
193 #else
194 #               pragma message("GLM: rotateZ function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
195                 T const Cos(cos(radians(angle)));
196                 T const Sin(sin(radians(angle)));
197 #endif
198 
199                 Result.x = v.x * Cos - v.y * Sin;
200                 Result.y = v.x * Sin + v.y * Cos;
201                 return Result;
202         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::rotateZ (detail::tvec3< T, P > const & v, T const & angle) [inline]
Rotate a three dimensional vector around the Z axis. From GLM_GTX_rotate_vector extension.
Definition at line 114 of file rotate_vector.inl.
References glm::cos(), glm::radians(), and glm::sin().
118         {
119                 detail::tvec3<T, P> Result = v;
120 
121 #ifdef GLM_FORCE_RADIANS
122                 T const Cos(cos(angle));
123                 T const Sin(sin(angle));
124 #else
125 #               pragma message("GLM: rotateZ function taking degrees as parameters is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
126                 T const Cos(cos(radians(angle)));
127                 T const Sin(sin(radians(angle)));
128 #endif
129 
130                 Result.x = v.x * Cos - v.y * Sin;
131                 Result.y = v.x * Sin + v.y * Cos;
132                 return Result;
133         }