GLM_GTX_extented_min_max
Functions
template<typename T>
GLM_FUNC_DECL T glm::min (T const &x, T const &y, T const &z)
template<typename T, template< typename > class C>
GLM_FUNC_DECL C< T > glm::min (C< T > const &x, typename C< T >::T const &y, typename C< T >::T const &z)
template<typename T, template< typename > class C>
GLM_FUNC_DECL C< T > glm::min (C< T > const &x, C< T > const &y, C< T > const &z)
template<typename T>
GLM_FUNC_DECL T glm::min (T const &x, T const &y, T const &z, T const &w)
template<typename T, template< typename > class C>
GLM_FUNC_DECL C< T > glm::min (C< T > const &x, typename C< T >::T const &y, typename C< T >::T const &z, typename C< T >::T const &w)
template<typename T, template< typename > class C>
GLM_FUNC_DECL C< T > glm::min (C< T > const &x, C< T > const &y, C< T > const &z, C< T > const &w)
template<typename T>
GLM_FUNC_DECL T glm::max (T const &x, T const &y, T const &z)
template<typename T, template< typename > class C>
GLM_FUNC_DECL C< T > glm::max (C< T > const &x, typename C< T >::T const &y, typename C< T >::T const &z)
template<typename T, template< typename > class C>
GLM_FUNC_DECL C< T > glm::max (C< T > const &x, C< T > const &y, C< T > const &z)
template<typename T>
GLM_FUNC_DECL T glm::max (T const &x, T const &y, T const &z, T const &w)
template<typename T, template< typename > class C>
GLM_FUNC_DECL C< T > glm::max (C< T > const &x, typename C< T >::T const &y, typename C< T >::T const &z, typename C< T >::T const &w)
template<typename T, template< typename > class C>
GLM_FUNC_DECL C< T > glm::max (C< T > const &x, C< T > const &y, C< T > const &z, C< T > const &w)
Detailed Description
Min and max functions for 3 to 4 parameters.
<glm/gtx/extented_min_max.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T, template< typename > class C> GLM_FUNC_QUALIFIER C< T > glm::max (C< T > const & x, C< T > const & y, C< T > const & z, C< T > const & w) [inline]
Return the maximum component-wise values of 4 inputs
See also: GLM_GTX_extented_min_max
Definition at line 136 of file extented_min_max.inl.
References glm::max().
142         {
143                 return glm::max(glm::max(x, y), glm::max(z, w));
144         }
template<typename T, template< typename > class C> GLM_FUNC_QUALIFIER C< T > glm::max (C< T > const & x, typename C< T >::T const & y, typename C< T >::T const & z, typename C< T >::T const & w) [inline]
Return the maximum component-wise values of 4 inputs
See also: GLM_GTX_extented_min_max
Definition at line 124 of file extented_min_max.inl.
References glm::max().
130         {
131                 return glm::max(glm::max(x, y), glm::max(z, w));
132         }
template<typename T> GLM_FUNC_QUALIFIER T glm::max (T const & x, T const & y, T const & z, T const & w) [inline]
Return the maximum component-wise values of 4 inputs
See also: GLM_GTX_extented_min_max
Definition at line 112 of file extented_min_max.inl.
References glm::max().
118         {
119                 return glm::max(glm::max(x, y), glm::max(z, w));
120         }
template<typename T, template< typename > class C> GLM_FUNC_QUALIFIER C< T > glm::max (C< T > const & x, C< T > const & y, C< T > const & z) [inline]
Return the maximum component-wise values of 3 inputs
See also: GLM_GTX_extented_min_max
Definition at line 101 of file extented_min_max.inl.
References glm::max().
106         {
107                 return glm::max(glm::max(x, y), z);
108         }
template<typename T, template< typename > class C> GLM_FUNC_QUALIFIER C< T > glm::max (C< T > const & x, typename C< T >::T const & y, typename C< T >::T const & z) [inline]
Return the maximum component-wise values of 3 inputs
See also: GLM_GTX_extented_min_max
Definition at line 90 of file extented_min_max.inl.
References glm::max().
95         {
96                 return glm::max(glm::max(x, y), z);
97         }
template<typename T> GLM_FUNC_QUALIFIER T glm::max (T const & x, T const & y, T const & z) [inline]
Return the maximum component-wise values of 3 inputs
See also: GLM_GTX_extented_min_max
Definition at line 80 of file extented_min_max.inl.
References glm::max().
84         {
85                 return glm::max(glm::max(x, y), z);
86         }
template<typename T, template< typename > class C> GLM_FUNC_QUALIFIER C< T > glm::min (C< T > const & x, C< T > const & y, C< T > const & z, C< T > const & w) [inline]
Return the minimum component-wise values of 4 inputs
See also: GLM_GTX_extented_min_max
Definition at line 69 of file extented_min_max.inl.
References glm::min().
Referenced by btInverseDynamics::MultiBodyTree::addBody().
75         {
76                 return glm::min(glm::min(x, y), glm::min(z, w));
77         }
template<typename T, template< typename > class C> GLM_FUNC_QUALIFIER C< T > glm::min (C< T > const & x, typename C< T >::T const & y, typename C< T >::T const & z, typename C< T >::T const & w) [inline]
Return the minimum component-wise values of 4 inputs
See also: GLM_GTX_extented_min_max
Definition at line 57 of file extented_min_max.inl.
References glm::min().
63         {
64                 return glm::min(glm::min(x, y), glm::min(z, w));
65         }
template<typename T> GLM_FUNC_QUALIFIER T glm::min (T const & x, T const & y, T const & z, T const & w) [inline]
Return the minimum component-wise values of 4 inputs
See also: GLM_GTX_extented_min_max
Definition at line 45 of file extented_min_max.inl.
References glm::min().
51         {
52                 return glm::min(glm::min(x, y), glm::min(z, w));
53         }
template<typename T, template< typename > class C> GLM_FUNC_QUALIFIER C< T > glm::min (C< T > const & x, C< T > const & y, C< T > const & z) [inline]
Return the minimum component-wise values of 3 inputs
See also: GLM_GTX_extented_min_max
Definition at line 34 of file extented_min_max.inl.
References glm::min().
39         {
40                 return glm::min(glm::min(x, y), z);
41         }
template<typename T, template< typename > class C> GLM_FUNC_QUALIFIER C< T > glm::min (C< T > const & x, typename C< T >::T const & y, typename C< T >::T const & z) [inline]
Return the minimum component-wise values of 3 inputs
See also: GLM_GTX_extented_min_max
Definition at line 23 of file extented_min_max.inl.
References glm::min().
28         {
29                 return glm::min(glm::min(x, y), z);
30         }
template<typename T> GLM_FUNC_QUALIFIER T glm::min (T const & x, T const & y, T const & z) [inline]
Return the minimum component-wise values of 3 inputs
See also: GLM_GTX_extented_min_max
Definition at line 13 of file extented_min_max.inl.
References glm::min().
17         {
18                 return glm::min(glm::min(x, y), z);
19         }