GLM_GTC_matrix_transform
Functions
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat4x4< T, P > glm::translate (detail::tmat4x4< T, P > const &m, detail::tvec3< T, P > const &v)
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat4x4< T, P > glm::rotate (detail::tmat4x4< T, P > const &m, T const &angle, detail::tvec3< T, P > const &axis)
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat4x4< T, P > glm::scale (detail::tmat4x4< T, P > const &m, detail::tvec3< T, P > const &v)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::ortho (T const &left, T const &right, T const &bottom, T const &top, T const &zNear, T const &zFar)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::ortho (T const &left, T const &right, T const &bottom, T const &top)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::frustum (T const &left, T const &right, T const &bottom, T const &top, T const &near, T const &far)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::perspective (T const &fovy, T const &aspect, T const &near, T const &far)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::perspectiveFov (T const &fov, T const &width, T const &height, T const &near, T const &far)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::infinitePerspective (T fovy, T aspect, T near)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::tweakedInfinitePerspective (T fovy, T aspect, T near)
template<typename T>
GLM_FUNC_DECL detail::tmat4x4< T, defaultp > glm::tweakedInfinitePerspective (T fovy, T aspect, T near, T ep)
template<typename T, typename U, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::project (detail::tvec3< T, P > const &obj, detail::tmat4x4< T, P > const &model, detail::tmat4x4< T, P > const &proj, detail::tvec4< U, P > const &viewport)
template<typename T, typename U, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::unProject (detail::tvec3< T, P > const &win, detail::tmat4x4< T, P > const &model, detail::tmat4x4< T, P > const &proj, detail::tvec4< U, P > const &viewport)
template<typename T, precision P, typename U>
GLM_FUNC_DECL detail::tmat4x4< T, P > glm::pickMatrix (detail::tvec2< T, P > const &center, detail::tvec2< T, P > const &delta, detail::tvec4< U, P > const &viewport)
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat4x4< T, P > glm::lookAt (detail::tvec3< T, P > const &eye, detail::tvec3< T, P > const &center, detail::tvec3< T, P > const &up)
Detailed Description
Defines functions that generate common transformation matrices.
The matrices generated by this extension use standard OpenGL fixed-function conventions. For example, the lookAt function generates a transform from world space into the specific eye space that the projective matrix functions (perspective, ortho, etc) are designed to expect. The OpenGL compatibility specifications defines the particular layout of this eye space.
<glm/gtc/matrix_transform.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::frustum (T const & left, T const & right, T const & bottom, T const & top, T const & near, T const & far) [inline]
Creates a frustum matrix.
Parameters:
left
right
bottom
top
near
far
Template Parameters:
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also: GLM_GTC_matrix_transform
Definition at line 197 of file matrix_transform.inl.
205         {
206                 detail::tmat4x4<T, defaultp> Result(0);
207                 Result[0][0] = (static_cast<T>(2) * nearVal) / (right - left);
208                 Result[1][1] = (static_cast<T>(2) * nearVal) / (top - bottom);
209                 Result[2][0] = (right + left) / (right - left);
210                 Result[2][1] = (top + bottom) / (top - bottom);
211                 Result[2][2] = -(farVal + nearVal) / (farVal - nearVal);
212                 Result[2][3] = static_cast<T>(-1);
213                 Result[3][2] = -(static_cast<T>(2) * farVal * nearVal) / (farVal - nearVal);
214                 return Result;
215         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::infinitePerspective (T fovy, T aspect, T near) [inline]
Creates a matrix for a symmetric perspective-view frustum with far plane at infinite.
Parameters:
fovy Expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
aspect
near
Template Parameters:
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also: GLM_GTC_matrix_transform
Definition at line 281 of file matrix_transform.inl.
References glm::radians(), and glm::tan().
286         {
287 #ifdef GLM_FORCE_RADIANS
288                 T const range = tan(fovy / T(2)) * zNear;       
289 #else
290 #               pragma message("GLM: infinitePerspective function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
291                 T const range = tan(radians(fovy / T(2))) * zNear;      
292 #endif
293                 T left = -range * aspect;
294                 T right = range * aspect;
295                 T bottom = -range;
296                 T top = range;
297 
298                 detail::tmat4x4<T, defaultp> Result(T(0));
299                 Result[0][0] = (T(2) * zNear) / (right - left);
300                 Result[1][1] = (T(2) * zNear) / (top - bottom);
301                 Result[2][2] = - T(1);
302                 Result[2][3] = - T(1);
303                 Result[3][2] = - T(2) * zNear;
304                 return Result;
305         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat4x4< T, P > glm::lookAt (detail::tvec3< T, P > const & eye, detail::tvec3< T, P > const & center, detail::tvec3< T, P > const & up) [inline]
Build a look at view matrix.
Parameters:
eye Position of the camera
center Position where the camera is looking at
up Normalized up vector, how the camera is oriented. Typically (0, 0, 1)
See also: GLM_GTC_matrix_transform
- frustum(T const & left, T const & right, T const & bottom, T const & top, T const & nearVal, T const & farVal) frustum(T const & left, T const & right, T const & bottom, T const & top, T const & nearVal, T const & farVal)
Definition at line 417 of file matrix_transform.inl.
References glm::cross(), glm::dot(), and glm::normalize().
422         {
423                 detail::tvec3<T, P> f(normalize(center - eye));
424                 detail::tvec3<T, P> s(normalize(cross(f, up)));
425                 detail::tvec3<T, P> u(cross(s, f));
426 
427                 detail::tmat4x4<T, P> Result(1);
428                 Result[0][0] = s.x;
429                 Result[1][0] = s.y;
430                 Result[2][0] = s.z;
431                 Result[0][1] = u.x;
432                 Result[1][1] = u.y;
433                 Result[2][1] = u.z;
434                 Result[0][2] =-f.x;
435                 Result[1][2] =-f.y;
436                 Result[2][2] =-f.z;
437                 Result[3][0] =-dot(s, eye);
438                 Result[3][1] =-dot(u, eye);
439                 Result[3][2] = dot(f, eye);
440                 return Result;
441         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::ortho (T const & left, T const & right, T const & bottom, T const & top) [inline]
Creates a matrix for projecting two-dimensional coordinates onto the screen.
Parameters:
left
right
bottom
top
Template Parameters:
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also: GLM_GTC_matrix_transform
- glm::ortho(T const & left, T const & right, T const & bottom, T const & top, T const & zNear, T const & zFar)
Definition at line 179 of file matrix_transform.inl.
185         {
186                 detail::tmat4x4<T, defaultp> Result(1);
187                 Result[0][0] = static_cast<T>(2) / (right - left);
188                 Result[1][1] = static_cast<T>(2) / (top - bottom);
189                 Result[2][2] = - T(1);
190                 Result[3][0] = - (right + left) / (right - left);
191                 Result[3][1] = - (top + bottom) / (top - bottom);
192                 return Result;
193         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::ortho (T const & left, T const & right, T const & bottom, T const & top, T const & zNear, T const & zFar) [inline]
Creates a matrix for an orthographic parallel viewing volume.
Parameters:
left
right
bottom
top
zNear
zFar
Template Parameters:
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also: GLM_GTC_matrix_transform
- glm::ortho(T const & left, T const & right, T const & bottom, T const & top)
Definition at line 158 of file matrix_transform.inl.
166         {
167                 detail::tmat4x4<T, defaultp> Result(1);
168                 Result[0][0] = static_cast<T>(2) / (right - left);
169                 Result[1][1] = static_cast<T>(2) / (top - bottom);
170                 Result[2][2] = - T(2) / (zFar - zNear);
171                 Result[3][0] = - (right + left) / (right - left);
172                 Result[3][1] = - (top + bottom) / (top - bottom);
173                 Result[3][2] = - (zFar + zNear) / (zFar - zNear);
174                 return Result;
175         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::perspective (T const & fovy, T const & aspect, T const & near, T const & far) [inline]
Creates a matrix for a symetric perspective-view frustum.
Parameters:
fovy Expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
aspect
near
far
Template Parameters:
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also: GLM_GTC_matrix_transform
Definition at line 219 of file matrix_transform.inl.
References glm::radians(), and glm::tan().
Referenced by Camera::SetPerspective().
225         {
226                 assert(aspect != static_cast<T>(0));
227                 assert(zFar != zNear);
228 
229 #ifdef GLM_FORCE_RADIANS
230                 T const rad = fovy;
231 #else
232 #               pragma message("GLM: perspective function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
233                 T const rad = glm::radians(fovy);
234 #endif
235 
236                 T tanHalfFovy = tan(rad / static_cast<T>(2));
237 
238                 detail::tmat4x4<T, defaultp> Result(static_cast<T>(0));
239                 Result[0][0] = static_cast<T>(1) / (aspect * tanHalfFovy);
240                 Result[1][1] = static_cast<T>(1) / (tanHalfFovy);
241                 Result[2][2] = - (zFar + zNear) / (zFar - zNear);
242                 Result[2][3] = - static_cast<T>(1);
243                 Result[3][2] = - (static_cast<T>(2) * zFar * zNear) / (zFar - zNear);
244                 return Result;
245         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::perspectiveFov (T const & fov, T const & width, T const & height, T const & near, T const & far) [inline]
Builds a perspective projection matrix based on a field of view.
Parameters:
fov Expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
width
height
near
far
Template Parameters:
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also: GLM_GTC_matrix_transform
todo max(width , Height) / min(width , Height)?
Definition at line 249 of file matrix_transform.inl.
References glm::cos(), glm::radians(), and glm::sin().
256         {
257                 assert(width > static_cast<T>(0));
258                 assert(height > static_cast<T>(0));
259                 assert(fov > static_cast<T>(0));
260         
261 #ifdef GLM_FORCE_RADIANS
262                 T rad = fov;
263 #else
264 #               pragma message("GLM: perspectiveFov function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
265                 T rad = glm::radians(fov);
266 #endif
267                 T h = glm::cos(static_cast<T>(0.5) * rad) / glm::sin(static_cast<T>(0.5) * rad);
268                 T w = h * height / width; 
269 
270                 detail::tmat4x4<T, defaultp> Result(static_cast<T>(0));
271                 Result[0][0] = w;
272                 Result[1][1] = h;
273                 Result[2][2] = - (zFar + zNear) / (zFar - zNear);
274                 Result[2][3] = - static_cast<T>(1);
275                 Result[3][2] = - (static_cast<T>(2) * zFar * zNear) / (zFar - zNear);
276                 return Result;
277         }
template<typename T, precision P, typename U> GLM_FUNC_QUALIFIER detail::tmat4x4< T, P > glm::pickMatrix (detail::tvec2< T, P > const & center, detail::tvec2< T, P > const & delta, detail::tvec4< U, P > const & viewport) [inline]
Define a picking region
Parameters:
center
delta
viewport
Template Parameters:
T Native type used for the computation. Currently supported: half (not recommanded), float or double.
U Currently supported: Floating-point types and integer types.
See also: GLM_GTC_matrix_transform
Definition at line 393 of file matrix_transform.inl.
References glm::scale(), and glm::translate().
398         {
399                 assert(delta.x > T(0) && delta.y > T(0));
400                 detail::tmat4x4<T, P> Result(1.0f);
401 
402                 if(!(delta.x > T(0) && delta.y > T(0)))
403                         return Result; // Error
404 
405                 detail::tvec3<T, P> Temp(
406                         (T(viewport[2]) - T(2) * (center.x - T(viewport[0]))) / delta.x,
407                         (T(viewport[3]) - T(2) * (center.y - T(viewport[1]))) / delta.y,
408                         T(0));
409 
410                 // Translate and scale the picked region to the entire window
411                 Result = translate(Result, Temp);
412                 return scale(Result, detail::tvec3<T, P>(T(viewport[2]) / delta.x, T(viewport[3]) / delta.y, T(1)));
413         }
template<typename T, typename U, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::project (detail::tvec3< T, P > const & obj, detail::tmat4x4< T, P > const & model, detail::tmat4x4< T, P > const & proj, detail::tvec4< U, P > const & viewport) [inline]
Map the specified object coordinates (obj.x, obj.y, obj.z) into window coordinates.
Parameters:
obj
model
proj
viewport
Template Parameters:
T Native type used for the computation. Currently supported: half (not recommanded), float or double.
U Currently supported: Floating-point types and integer types.
See also: GLM_GTC_matrix_transform
Definition at line 350 of file matrix_transform.inl.
356         {
357                 detail::tvec4<T, P> tmp = detail::tvec4<T, P>(obj, T(1));
358                 tmp = model * tmp;
359                 tmp = proj * tmp;
360 
361                 tmp /= tmp.w;
362                 tmp = tmp * T(0.5) + T(0.5);
363                 tmp[0] = tmp[0] * T(viewport[2]) + T(viewport[0]);
364                 tmp[1] = tmp[1] * T(viewport[3]) + T(viewport[1]);
365 
366                 return detail::tvec3<T, P>(tmp);
367         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat4x4< T, P > glm::rotate (detail::tmat4x4< T, P > const & m, T const & angle, detail::tvec3< T, P > const & axis) [inline]
Builds a rotation 4 * 4 matrix created from an axis vector and an angle.
Parameters:
m Input matrix multiplied by this rotation matrix.
angle Rotation angle expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
axis Rotation axis, recommanded to be normalized.
Template Parameters:
T Value type used to build the matrix. Supported: half, float or double.
See also: GLM_GTC_matrix_transform
GLM_GTX_transform
- rotate(T angle, T x, T y, T z)
- rotate(detail::tmat4x4<T, P> const & m, T angle, T x, T y, T z)
- rotate(T angle, detail::tvec3<T, P> const & v)
Definition at line 49 of file matrix_transform.inl.
References glm::axis(), glm::cos(), glm::normalize(), glm::radians(), and glm::sin().
Referenced by Camera::GetRotationMatrix(), glm::orientation(), glm::orientedAngle(), and glm::rotate().
54         {
55 #ifdef GLM_FORCE_RADIANS
56                 T a = angle;
57 #else
58 #               pragma message("GLM: rotate function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
59                 T a = radians(angle);
60 #endif
61                 T c = cos(a);
62                 T s = sin(a);
63 
64                 detail::tvec3<T, P> axis(normalize(v));
65                 detail::tvec3<T, P> temp((T(1) - c) * axis);
66 
67                 detail::tmat4x4<T, P> Rotate(detail::tmat4x4<T, P>::_null);
68                 Rotate[0][0] = c + temp[0] * axis[0];
69                 Rotate[0][1] = 0 + temp[0] * axis[1] + s * axis[2];
70                 Rotate[0][2] = 0 + temp[0] * axis[2] - s * axis[1];
71 
72                 Rotate[1][0] = 0 + temp[1] * axis[0] - s * axis[2];
73                 Rotate[1][1] = c + temp[1] * axis[1];
74                 Rotate[1][2] = 0 + temp[1] * axis[2] + s * axis[0];
75 
76                 Rotate[2][0] = 0 + temp[2] * axis[0] + s * axis[1];
77                 Rotate[2][1] = 0 + temp[2] * axis[1] - s * axis[0];
78                 Rotate[2][2] = c + temp[2] * axis[2];
79 
80                 detail::tmat4x4<T, P> Result(detail::tmat4x4<T, P>::_null);
81                 Result[0] = m[0] * Rotate[0][0] + m[1] * Rotate[0][1] + m[2] * Rotate[0][2];
82                 Result[1] = m[0] * Rotate[1][0] + m[1] * Rotate[1][1] + m[2] * Rotate[1][2];
83                 Result[2] = m[0] * Rotate[2][0] + m[1] * Rotate[2][1] + m[2] * Rotate[2][2];
84                 Result[3] = m[3];
85                 return Result;
86         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat4x4< T, P > glm::scale (detail::tmat4x4< T, P > const & m, detail::tvec3< T, P > const & v) [inline]
Builds a scale 4 * 4 matrix created from 3 scalars.
Parameters:
m Input matrix multiplied by this scale matrix.
v Ratio of scaling for each axis.
Template Parameters:
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also: GLM_GTC_matrix_transform
GLM_GTX_transform
- scale(T x, T y, T z) scale(T const & x, T const & y, T const & z)
- scale(detail::tmat4x4<T, P> const & m, T x, T y, T z)
- scale(detail::tvec3<T, P> const & v)
Definition at line 129 of file matrix_transform.inl.
Referenced by glm::pickMatrix(), and glm::scale().
133         {
134                 detail::tmat4x4<T, P> Result(detail::tmat4x4<T, P>::_null);
135                 Result[0] = m[0] * v[0];
136                 Result[1] = m[1] * v[1];
137                 Result[2] = m[2] * v[2];
138                 Result[3] = m[3];
139                 return Result;
140         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat4x4< T, P > glm::translate (detail::tmat4x4< T, P > const & m, detail::tvec3< T, P > const & v) [inline]
Builds a translation 4 * 4 matrix created from a vector of 3 components.
Parameters:
m Input matrix multiplied by this translation matrix.
v Coordinates of a translation vector.
Template Parameters:
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
 #include <glm/glm.hpp>
 #include <glm/gtc/matrix_transform.hpp>
 ...
 glm::mat4 m = glm::translate(glm::mat4(1.0f), glm::vec3(1.0f));
 // m[0][0] == 1.0f, m[0][1] == 0.0f, m[0][2] == 0.0f, m[0][3] == 0.0f
 // m[1][0] == 0.0f, m[1][1] == 1.0f, m[1][2] == 0.0f, m[1][3] == 0.0f
 // m[2][0] == 0.0f, m[2][1] == 0.0f, m[2][2] == 1.0f, m[2][3] == 0.0f
 // m[3][0] == 1.0f, m[3][1] == 1.0f, m[3][2] == 1.0f, m[3][3] == 1.0f
See also: GLM_GTC_matrix_transform
GLM_GTX_transform
- translate(T x, T y, T z)
- translate(detail::tmat4x4<T, P> const & m, T x, T y, T z)
- translate(detail::tvec3<T, P> const & v)
Definition at line 37 of file matrix_transform.inl.
Referenced by Camera::GetViewMatrix(), glm::pickMatrix(), and glm::translate().
41         {
42                 detail::tmat4x4<T, P> Result(m);
43                 Result[3] = m[0] * v[0] + m[1] * v[1] + m[2] * v[2] + m[3];
44                 return Result;
45         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::tweakedInfinitePerspective (T fovy, T aspect, T near, T ep) [inline]
Creates a matrix for a symmetric perspective-view frustum with far plane at infinite for graphics hardware that doesn't support depth clamping.
Parameters:
fovy Expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
aspect
near
Template Parameters:
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also: GLM_GTC_matrix_transform
Definition at line 310 of file matrix_transform.inl.
References glm::radians(), and glm::tan().
316         {
317 #ifdef GLM_FORCE_RADIANS
318                 T range = tan(fovy / T(2)) * zNear;     
319 #else
320 #               pragma message("GLM: tweakedInfinitePerspective function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
321                 T range = tan(radians(fovy / T(2))) * zNear;    
322 #endif
323                 T left = -range * aspect;
324                 T right = range * aspect;
325                 T bottom = -range;
326                 T top = range;
327 
328                 detail::tmat4x4<T, defaultp> Result(T(0));
329                 Result[0][0] = (static_cast<T>(2) * zNear) / (right - left);
330                 Result[1][1] = (static_cast<T>(2) * zNear) / (top - bottom);
331                 Result[2][2] = ep - static_cast<T>(1);
332                 Result[2][3] = static_cast<T>(-1);
333                 Result[3][2] = (ep - static_cast<T>(2)) * zNear;
334                 return Result;
335         }
template<typename T> GLM_FUNC_QUALIFIER detail::tmat4x4< T, defaultp > glm::tweakedInfinitePerspective (T fovy, T aspect, T near) [inline]
Creates a matrix for a symmetric perspective-view frustum with far plane at infinite for graphics hardware that doesn't support depth clamping.
Parameters:
fovy Expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
aspect
near
Template Parameters:
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also: GLM_GTC_matrix_transform
Definition at line 339 of file matrix_transform.inl.
344         {
345                 return tweakedInfinitePerspective(fovy, aspect, zNear, epsilon<T>());
346         }
template<typename T, typename U, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::unProject (detail::tvec3< T, P > const & win, detail::tmat4x4< T, P > const & model, detail::tmat4x4< T, P > const & proj, detail::tvec4< U, P > const & viewport) [inline]
Map the specified window coordinates (win.x, win.y, win.z) into object coordinates.
Parameters:
win
model
proj
viewport
Template Parameters:
T Native type used for the computation. Currently supported: half (not recommanded), float or double.
U Currently supported: Floating-point types and integer types.
See also: GLM_GTC_matrix_transform
Definition at line 371 of file matrix_transform.inl.
References glm::inverse().
377         {
378                 detail::tmat4x4<T, P> Inverse = inverse(proj * model);
379 
380                 detail::tvec4<T, P> tmp = detail::tvec4<T, P>(win, T(1));
381                 tmp.x = (tmp.x - T(viewport[0])) / T(viewport[2]);
382                 tmp.y = (tmp.y - T(viewport[1])) / T(viewport[3]);
383                 tmp = tmp * T(2) - T(1);
384 
385                 detail::tvec4<T, P> obj = Inverse * tmp;
386                 obj /= obj.w;
387 
388                 return detail::tvec3<T, P>(obj);
389         }