Geometric functions
Functions
template<typename genType>
GLM_FUNC_DECL genType::value_type glm::length (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType::value_type glm::distance (genType const &p0, genType const &p1)
template<typename T, precision P, template< typename, precision > class vecType>
GLM_FUNC_DECL T glm::dot (vecType< T, P > const &x, vecType< T, P > const &y)
template<typename genType>
GLM_FUNC_DECL genType glm::dot (genType const &x, genType const &y)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::cross (detail::tvec3< T, P > const &x, detail::tvec3< T, P > const &y)
template<typename genType>
GLM_FUNC_DECL genType glm::normalize (genType const &x)
template<typename genType>
GLM_FUNC_DECL genType glm::faceforward (genType const &N, genType const &I, genType const &Nref)
template<typename genType>
GLM_FUNC_DECL genType glm::reflect (genType const &I, genType const &N)
template<typename T, precision P, template< typename, precision > class vecType>
GLM_FUNC_DECL vecType< T, P > glm::refract (vecType< T, P > const &I, vecType< T, P > const &N, T const &eta)
Detailed Description
These operate on vectors as vectors, not component-wise.
Function Documentation
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::cross (detail::tvec3< T, P > const & x, detail::tvec3< T, P > const & y) [inline]
Returns the cross product of x and y.
Template Parameters:
valType Floating-point scalar types.
See also: GLSL cross man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 217 of file func_geometric.inl.
Referenced by glm::intersectLineTriangle(), glm::intersectRayTriangle(), glm::leftHanded(), glm::lookAt(), glm::mixedProduct(), glm::orientation(), glm::orientedAngle(), glm::rightHanded(), glm::rotation(), and glm::triangleNormal().
221         {
222                 GLM_STATIC_ASSERT(std::numeric_limits<T>::is_iec559, "'cross' only accept floating-point inputs");
223 
224                 return detail::tvec3<T, P>(
225                         x.y * y.z - y.y * x.z,
226                         x.z * y.x - y.z * x.x,
227                         x.x * y.y - y.x * x.y);
228         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::distance (genType const & p0, genType const & p1) [inline]
Returns the distance betwwen p0 and p1, i.e., length(p0 - p1).
Template Parameters:
genType Floating-point vector types.
See also: GLSL distance man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 128 of file func_geometric.inl.
References glm::length().
Referenced by glm::closestPointOnLine(), btConvexPlaneCollisionAlgorithm::collideSingleContact(), btGjkPairDetector::getClosestPointsNonVirtual(), glm::intersectRaySphere(), and btConvexPlaneCollisionAlgorithm::processCollision().
132         {
133                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'distance' only accept floating-point inputs");
134 
135                 return length(p1 - p0);
136         }
template<typename genType> GLM_FUNC_DECL genType glm::dot (genType const & x, genType const & y) [inline]
Returns the dot product of x and y, i.e., result = x * y.
Template Parameters:
genType Floating-point vector types.
See also: GLSL dot man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
template<typename T, precision P, template< typename, precision > class vecType> GLM_FUNC_QUALIFIER T glm::dot (vecType< T, P > const & x, vecType< T, P > const & y) [inline]
Returns the dot product of x and y, i.e., result = x * y.
Template Parameters:
genType Floating-point vector types.
See also: GLSL dot man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 188 of file func_geometric.inl.
Referenced by glm::areOrthogonal(), glm::areOrthonormal(), glm::closestPointOnLine(), glm::faceforward(), glm::fastNormalizeDot(), glm::intersectLineSphere(), glm::intersectLineTriangle(), glm::intersectRayPlane(), glm::intersectRaySphere(), glm::intersectRayTriangle(), glm::inverse(), glm::leftHanded(), glm::lerp(), glm::linearGradient(), glm::lookAt(), glm::luminosity(), glm::mixedProduct(), glm::normalizeDot(), glm::orientation(), glm::orientedAngle(), glm::orthonormalize(), glm::proj(), glm::reflect(), glm::refract(), glm::rightHanded(), glm::rotation(), and glm::shortMix().
192         {
193                 GLM_STATIC_ASSERT(std::numeric_limits<T>::is_iec559, "'dot' only accept floating-point inputs");
194                 return detail::compute_dot<vecType, T, P>::call(x, y);
195         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::faceforward (genType const & N, genType const & I, genType const & Nref) [inline]
If dot(Nref, I) < 0.0, return N, otherwise, return -N.
Template Parameters:
genType Floating-point vector types.
See also: GLSL faceforward man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 282 of file func_geometric.inl.
References glm::dot().
287         {
288                 return dot(Nref, I) < 0 ? N : -N;
289         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::length (genType const & x) [inline]
Returns the length of x, i.e., sqrt(x * x).
Template Parameters:
genType Floating-point vector types.
See also: GLSL length man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 89 of file func_geometric.inl.
References glm::abs().
Referenced by glm::areOrthogonal(), glm::ballRand(), glm::diskRand(), glm::distance(), glm::exp(), glm::isNormalized(), glm::isNull(), glm::l2Norm(), glm::log(), glm::normalize(), glm::polar(), glm::rotate(), and glm::row().
92         {
93                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'length' only accept floating-point inputs");
94 
95                 return abs(x);
96         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::normalize (genType const & x) [inline]
Returns a vector in the same direction as x but with length of 1.
See also: GLSL normalize man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 233 of file func_geometric.inl.
Referenced by glm::axisAngleMatrix(), glm::fastMix(), glm::intersectLineSphere(), glm::lookAt(), glm::orthonormalize(), glm::rotate(), glm::rotation(), and glm::triangleNormal().
236         {
237                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'normalize' only accept floating-point inputs");
238 
239                 return x < genType(0) ? genType(-1) : genType(1);
240         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::reflect (genType const & I, genType const & N) [inline]
For the incident vector I and surface orientation N, returns the reflection direction : result = I - 2.0 * dot(N, I) * N.
Template Parameters:
genType Floating-point vector types.
See also: GLSL reflect man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 294 of file func_geometric.inl.
References glm::dot().
298         {
299                 return I - N * dot(N, I) * genType(2);
300         }
template<typename T, precision P, template< typename, precision > class vecType> GLM_FUNC_QUALIFIER vecType< T, P > glm::refract (vecType< T, P > const & I, vecType< T, P > const & N, T const & eta) [inline]
For the incident vector I and surface normal N, and the ratio of indices of refraction eta, return the refraction vector.
Template Parameters:
genType Floating-point vector types.
See also: GLSL refract man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 323 of file func_geometric.inl.
References glm::dot(), and glm::sqrt().
328         {
329                 GLM_STATIC_ASSERT(std::numeric_limits<T>::is_iec559, "'refract' only accept floating-point inputs");
330 
331                 T dotValue = dot(N, I);
332                 T k = T(1) - eta * eta * (T(1) - dotValue * dotValue);
333                 if(k < T(0))
334                         return vecType<T, P>(0);
335                 else
336                         return eta * I - (eta * dotValue + std::sqrt(k)) * N;
337         }