GLM_GTC_random
Functions
template<typename genType>
GLM_FUNC_DECL genType glm::linearRand (genType const &Min, genType const &Max)
template<typename genType>
GLM_FUNC_DECL genType glm::gaussRand (genType const &Mean, genType const &Deviation)
template<typename T>
GLM_FUNC_DECL detail::tvec2< T, defaultp > glm::circularRand (T const &Radius)
template<typename T>
GLM_FUNC_DECL detail::tvec3< T, defaultp > glm::sphericalRand (T const &Radius)
template<typename T>
GLM_FUNC_DECL detail::tvec2< T, defaultp > glm::diskRand (T const &Radius)
template<typename T>
GLM_FUNC_DECL detail::tvec3< T, defaultp > glm::ballRand (T const &Radius)
Detailed Description
Generate random number from various distribution methods.
<glm/gtc/random.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T> GLM_FUNC_QUALIFIER detail::tvec3< T, defaultp > glm::ballRand (T const & Radius) [inline]
Generate a random 3D vector which coordinates are regulary distributed within the volume of a ball of a given radius
Parameters:
Radius
See also: GLM_GTC_random
Definition at line 126 of file random.inl.
References glm::length(), and glm::linearRand().
129         {               
130                 detail::tvec3<T, defaultp> Result(T(0));
131                 T LenRadius(T(0));
132                 
133                 do
134                 {
135                         Result = linearRand(
136                                 detail::tvec3<T, defaultp>(-Radius),
137                                 detail::tvec3<T, defaultp>(Radius));
138                         LenRadius = length(Result);
139                 }
140                 while(LenRadius > Radius);
141                 
142                 return Result;
143         }
template<typename T> GLM_FUNC_QUALIFIER detail::tvec2< T, defaultp > glm::circularRand (T const & Radius) [inline]
Generate a random 2D vector which coordinates are regulary distributed on a circle of a given radius
Parameters:
Radius
See also: GLM_GTC_random
Definition at line 147 of file random.inl.
References glm::cos(), glm::linearRand(), and glm::sin().
150         {
151                 T a = linearRand(T(0), T(6.283185307179586476925286766559f));
152                 return detail::tvec2<T, defaultp>(cos(a), sin(a)) * Radius;             
153         }
template<typename T> GLM_FUNC_QUALIFIER detail::tvec2< T, defaultp > glm::diskRand (T const & Radius) [inline]
Generate a random 2D vector which coordinates are regulary distributed within the area of a disk of a given radius
Parameters:
Radius
See also: GLM_GTC_random
Definition at line 105 of file random.inl.
References glm::length(), and glm::linearRand().
108         {               
109                 detail::tvec2<T, defaultp> Result(T(0));
110                 T LenRadius(T(0));
111                 
112                 do
113                 {
114                         Result = linearRand(
115                                 detail::tvec2<T, defaultp>(-Radius),
116                                 detail::tvec2<T, defaultp>(Radius));
117                         LenRadius = length(Result);
118                 }
119                 while(LenRadius > Radius);
120                 
121                 return Result;
122         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::gaussRand (genType const & Mean, genType const & Deviation) [inline]
Generate random numbers in the interval [Min, Max], according a gaussian distribution
Parameters:
Mean
Deviation
See also: GLM_GTC_random
Definition at line 83 of file random.inl.
References glm::linearRand(), glm::log(), and glm::sqrt().
87         {
88                 genType w, x1, x2;
89         
90                 do
91                 {
92                         x1 = linearRand(genType(-1), genType(1));
93                         x2 = linearRand(genType(-1), genType(1));
94                 
95                         w = x1 * x1 + x2 * x2;
96                 } while(w > genType(1));
97         
98                 return x2 * Deviation * Deviation * sqrt((genType(-2) * log(w)) / w) + Mean;
99         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::linearRand (genType const & Min, genType const & Max) [inline]
Generate random numbers in the interval [Min, Max], according a linear distribution
Parameters:
Min
Max
Template Parameters:
genType Value type. Currently supported: half (not recommanded), float or double scalars and vectors.
See also: GLM_GTC_random
Definition at line 71 of file random.inl.
Referenced by glm::ballRand(), glm::circularRand(), glm::diskRand(), glm::gaussRand(), and glm::sphericalRand().
75         {
76                 return detail::compute_linearRand()(Min, Max);
77         }
template<typename T> GLM_FUNC_QUALIFIER detail::tvec3< T, defaultp > glm::sphericalRand (T const & Radius) [inline]
Generate a random 3D vector which coordinates are regulary distributed on a sphere of a given radius
Parameters:
Radius
See also: GLM_GTC_random
Definition at line 157 of file random.inl.
References glm::cos(), glm::linearRand(), glm::sin(), and glm::sqrt().
160         {
161                 T z = linearRand(T(-1), T(1));
162                 T a = linearRand(T(0), T(6.283185307179586476925286766559f));
163         
164                 T r = sqrt(T(1) - z * z);
165         
166                 T x = r * cos(a);
167                 T y = r * sin(a);
168         
169                 return detail::tvec3<T, defaultp>(x, y, z) * Radius;    
170         }