GLM_GTX_spline
Functions
template<typename genType>
GLM_FUNC_DECL genType glm::catmullRom (genType const &v1, genType const &v2, genType const &v3, genType const &v4, typename genType::value_type const &s)
template<typename genType>
GLM_FUNC_DECL genType glm::hermite (genType const &v1, genType const &t1, genType const &v2, genType const &t2, typename genType::value_type const &s)
template<typename genType>
GLM_FUNC_DECL genType glm::cubic (genType const &v1, genType const &v2, genType const &v3, genType const &v4, typename genType::value_type const &s)
Detailed Description
Spline functions.
<glm/gtx/spline.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType> GLM_FUNC_QUALIFIER genType glm::catmullRom (genType const & v1, genType const & v2, genType const & v3, genType const & v4, typename genType::value_type const & s) [inline]
Return a point from a catmull rom curve.
See also: GLM_GTX_spline extension.
Definition at line 14 of file spline.inl.
References glm::pow2(), and glm::pow3().
21 {
22         typename genType::value_type s1 = s;
23         typename genType::value_type s2 = pow2(s);
24         typename genType::value_type s3 = pow3(s);
25 
26         typename genType::value_type f1 = -s3 + typename genType::value_type(2) * s2 - s;
27         typename genType::value_type f2 = typename genType::value_type(3) * s3 - typename genType::value_type(5) * s2 + typename genType::value_type(2);
28         typename genType::value_type f3 = typename genType::value_type(-3) * s3 + typename genType::value_type(4) * s2 + s;
29         typename genType::value_type f4 = s3 - s2;
30 
31         return (f1 * v1 + f2 * v2 + f3 * v3 + f4 * v4) / typename genType::value_type(2);
32 
33 }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::cubic (genType const & v1, genType const & v2, genType const & v3, genType const & v4, typename genType::value_type const & s) [inline]
Return a point from a cubic curve.
See also: GLM_GTX_spline extension.
Definition at line 59 of file spline.inl.
66 {
67         return ((v1 * s + v2) * s + v3) * s + v4;
68 }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::hermite (genType const & v1, genType const & t1, genType const & v2, genType const & t2, typename genType::value_type const & s) [inline]
Return a point from a hermite curve.
See also: GLM_GTX_spline extension.
Definition at line 37 of file spline.inl.
References glm::pow2(), and glm::pow3().
44 {
45         typename genType::value_type s1 = s;
46         typename genType::value_type s2 = pow2(s);
47         typename genType::value_type s3 = pow3(s);
48 
49         typename genType::value_type f1 = typename genType::value_type(2) * s3 - typename genType::value_type(3) * s2 + typename genType::value_type(1);
50         typename genType::value_type f2 = typename genType::value_type(-2) * s3 + typename genType::value_type(3) * s2;
51         typename genType::value_type f3 = s3 - typename genType::value_type(2) * s2 + s;
52         typename genType::value_type f4 = s3 - s2;
53 
54         return f1 * v1 + f2 * v2 + f3 * t1 + f4 * t2;
55 }