GLM_GTX_fast_trigonometry
Functions
template<typename T>
GLM_FUNC_DECL T glm::fastSin (const T &angle)
template<typename T>
GLM_FUNC_DECL T glm::fastCos (const T &angle)
template<typename T>
GLM_FUNC_DECL T glm::fastTan (const T &angle)
template<typename T>
GLM_FUNC_DECL T glm::fastAsin (const T &angle)
template<typename T>
GLM_FUNC_DECL T glm::fastAcos (const T &angle)
template<typename T>
GLM_FUNC_DECL T glm::fastAtan (const T &y, const T &x)
template<typename T>
GLM_FUNC_DECL T glm::fastAtan (const T &angle)
Detailed Description
Fast but less accurate implementations of trigonometric functions.
<glm/gtx/fast_trigonometry.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T> GLM_FUNC_QUALIFIER T glm::fastAcos (const T & angle) [inline]
Faster than the common acos function but less accurate. Defined between -2pi and 2pi. From GLM_GTX_fast_trigonometry extension.
Definition at line 50 of file fast_trigonometry.inl.
References glm::fastAsin().
51         {
52                 return T(1.5707963267948966192313216916398) - fastAsin(x); //(PI / 2)
53         }
template<typename T> GLM_FUNC_QUALIFIER T glm::fastAsin (const T & angle) [inline]
Faster than the common asin function but less accurate. Defined between -2pi and 2pi. From GLM_GTX_fast_trigonometry extension.
Definition at line 41 of file fast_trigonometry.inl.
Referenced by glm::fastAcos().
42         {
43                 return x + (x * x * x * T(0.166666667)) + (x * x * x * x * x * T(0.075)) + (x * x * x * x * x * x * x * T(0.0446428571)) + (x * x * x * x * x * x * x * x * x * T(0.0303819444));// + (x * x * x * x * x * x * x * x * x * x * x * T(0.022372159));
44         }
template<typename T> GLM_FUNC_QUALIFIER T glm::fastAtan (const T & angle) [inline]
Faster than the common atan function but less accurate. Defined between -2pi and 2pi. From GLM_GTX_fast_trigonometry extension.
Definition at line 68 of file fast_trigonometry.inl.
69         {
70                 return x - (x * x * x * T(0.333333333333)) + (x * x * x * x * x * T(0.2)) - (x * x * x * x * x * x * x * T(0.1428571429)) + (x * x * x * x * x * x * x * x * x * T(0.111111111111)) - (x * x * x * x * x * x * x * x * x * x * x * T(0.0909090909));
71         }
template<typename T> GLM_FUNC_QUALIFIER T glm::fastAtan (const T & y, const T & x) [inline]
Faster than the common atan function but less accurate. Defined between -2pi and 2pi. From GLM_GTX_fast_trigonometry extension.
Definition at line 59 of file fast_trigonometry.inl.
References glm::abs(), and glm::sign().
60         {
61                 T sgn = sign(y) * sign(x);
62                 return abs(fastAtan(y / x)) * sgn;
63         }
template<typename T> GLM_FUNC_QUALIFIER T glm::fastCos (const T & angle) [inline]
Faster than the common cos function but less accurate. Defined between -2pi and 2pi. From GLM_GTX_fast_trigonometry extension.
Definition at line 23 of file fast_trigonometry.inl.
24         {
25                 return T(1) - (x * x * T(0.5)) + (x * x * x * x * T(0.041666666666)) - (x * x * x * x * x * x * T(0.00138888888888));
26         }
template<typename T> GLM_FUNC_QUALIFIER T glm::fastSin (const T & angle) [inline]
Faster than the common sin function but less accurate. Defined between -2pi and 2pi. From GLM_GTX_fast_trigonometry extension.
Definition at line 14 of file fast_trigonometry.inl.
15         {
16                 return x - ((x * x * x) / T(6)) + ((x * x * x * x * x) / T(120)) - ((x * x * x * x * x * x * x) / T(5040));
17         }
template<typename T> GLM_FUNC_QUALIFIER T glm::fastTan (const T & angle) [inline]
Faster than the common tan function but less accurate. Defined between -2pi and 2pi. From GLM_GTX_fast_trigonometry extension.
Definition at line 32 of file fast_trigonometry.inl.
33         {
34                 return x + (x * x * x * T(0.3333333333)) + (x * x * x * x * x * T(0.1333333333333)) + (x * x * x * x * x * x * x * T(0.0539682539));
35         }