GLM_GTX_norm
Functions
template<typename T>
GLM_FUNC_DECL T glm::length2 (T const &x)
template<typename genType>
GLM_FUNC_DECL genType::value_type glm::length2 (genType const &x)
template<typename T>
GLM_FUNC_DECL T glm::distance2 (T const &p0, T const &p1)
template<typename genType>
GLM_FUNC_DECL genType::value_type glm::distance2 (genType const &p0, genType const &p1)
template<typename T, precision P>
GLM_FUNC_DECL T glm::l1Norm (detail::tvec3< T, P > const &x, detail::tvec3< T, P > const &y)
template<typename T, precision P>
GLM_FUNC_DECL T glm::l1Norm (detail::tvec3< T, P > const &v)
template<typename T, precision P>
GLM_FUNC_DECL T glm::l2Norm (detail::tvec3< T, P > const &x, detail::tvec3< T, P > const &y)
template<typename T, precision P>
GLM_FUNC_DECL T glm::l2Norm (detail::tvec3< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL T glm::lxNorm (detail::tvec3< T, P > const &x, detail::tvec3< T, P > const &y, unsigned int Depth)
template<typename T, precision P>
GLM_FUNC_DECL T glm::lxNorm (detail::tvec3< T, P > const &x, unsigned int Depth)
Detailed Description
Various ways to compute vector norms.
<glm/gtx/norm.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType> GLM_FUNC_DECL genType::value_type glm::distance2 (genType const & p0, genType const & p1) [inline]
Returns the squared distance between p0 and p1, i.e., length(p0 - p1). From GLM_GTX_norm extension.
Referenced by btGjkPairDetector::getClosestPointsNonVirtual().
template<typename T> GLM_FUNC_QUALIFIER T glm::distance2 (T const & p0, T const & p1) [inline]
Returns the squared distance between p0 and p1, i.e., length(p0 - p1). From GLM_GTX_norm extension.
Definition at line 50 of file norm.inl.
References glm::length2().
54         {
55                 return length2(p1 - p0);
56         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::l1Norm (detail::tvec3< T, P > const & v) [inline]
Returns the L1 norm of v. From GLM_GTX_norm extension.
Definition at line 100 of file norm.inl.
References glm::abs().
103         {
104                 return abs(v.x) + abs(v.y) + abs(v.z);
105         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::l1Norm (detail::tvec3< T, P > const & x, detail::tvec3< T, P > const & y) [inline]
Returns the L1 norm between x and y. From GLM_GTX_norm extension.
Definition at line 90 of file norm.inl.
References glm::abs().
94         {
95                 return abs(b.x - a.x) + abs(b.y - a.y) + abs(b.z - a.z);
96         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::l2Norm (detail::tvec3< T, P > const & x) [inline]
Returns the L2 norm of v. From GLM_GTX_norm extension.
Definition at line 119 of file norm.inl.
References glm::length().
122         {
123                 return length(v);
124         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::l2Norm (detail::tvec3< T, P > const & x, detail::tvec3< T, P > const & y) [inline]
Returns the L2 norm between x and y. From GLM_GTX_norm extension.
Definition at line 109 of file norm.inl.
References glm::length().
113         {
114                 return length(b - a);
115         }
template<typename genType> GLM_FUNC_DECL genType::value_type glm::length2 (genType const & x) [inline]
Returns the squared length of x. From GLM_GTX_norm extension.
template<typename T> GLM_FUNC_QUALIFIER T glm::length2 (T const & x) [inline]
Returns the squared length of x. From GLM_GTX_norm extension.
Definition at line 14 of file norm.inl.
Referenced by glm::distance2(), glm::mat3x4_cast(), and glm::rotation().
17         {
18                 return x * x;
19         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::lxNorm (detail::tvec3< T, P > const & x, unsigned int Depth) [inline]
Returns the L norm of v. From GLM_GTX_norm extension.
Definition at line 139 of file norm.inl.
References glm::pow().
143         {
144                 return pow(pow(v.x, T(Depth)) + pow(v.y, T(Depth)) + pow(v.z, T(Depth)), T(1) / T(Depth));
145         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::lxNorm (detail::tvec3< T, P > const & x, detail::tvec3< T, P > const & y, unsigned int Depth) [inline]
Returns the L norm between x and y. From GLM_GTX_norm extension.
Definition at line 128 of file norm.inl.
References glm::pow().
133         {
134                 return pow(pow(y.x - x.x, T(Depth)) + pow(y.y - x.y, T(Depth)) + pow(y.z - x.z, T(Depth)), T(1) / T(Depth));
135         }