GLM_GTX_gradient_paint
Functions
template<typename T, precision P>
GLM_FUNC_DECL T glm::radialGradient (detail::tvec2< T, P > const &Center, T const &Radius, detail::tvec2< T, P > const &Focal, detail::tvec2< T, P > const &Position)
template<typename T, precision P>
GLM_FUNC_DECL T glm::linearGradient (detail::tvec2< T, P > const &Point0, detail::tvec2< T, P > const &Point1, detail::tvec2< T, P > const &Position)
Detailed Description
Functions that return the color of procedural gradient for specific coordinates. <glm/gtx/gradient_paint.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::linearGradient (detail::tvec2< T, P > const & Point0, detail::tvec2< T, P > const & Point1, detail::tvec2< T, P > const & Position) [inline]
Return a color from a linear gradient.
See also: - GLM_GTX_gradient_paint
Definition at line 34 of file gradient_paint.inl.
References glm::dot().
39         {
40                 detail::tvec2<T, P> Dist = Point1 - Point0;
41                 return (Dist.x * (Position.x - Point0.x) + Dist.y * (Position.y - Point0.y)) / glm::dot(Dist, Dist);
42         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::radialGradient (detail::tvec2< T, P > const & Center, T const & Radius, detail::tvec2< T, P > const & Focal, detail::tvec2< T, P > const & Position) [inline]
Return a color from a radial gradient.
See also: - GLM_GTX_gradient_paint
Definition at line 14 of file gradient_paint.inl.
References glm::pow2(), and glm::sqrt().
20         {
21                 detail::tvec2<T, P> F = Focal - Center;
22                 detail::tvec2<T, P> D = Position - Focal;
23                 T Radius2 = pow2(Radius);
24                 T Fx2 = pow2(F.x);
25                 T Fy2 = pow2(F.y);
26 
27                 T Numerator = (D.x * F.x + D.y * F.y) + sqrt(Radius2 * (pow2(D.x) + pow2(D.y)) - pow2(D.x * F.y - D.y * F.x));
28                 T Denominator = Radius2 - (Fx2 + Fy2);
29                 return Numerator / Denominator;
30         }