GLM_GTX_wrap
Functions
template<typename genType>
GLM_FUNC_DECL genType glm::clamp (genType const &Texcoord)
template<typename genType>
GLM_FUNC_DECL genType glm::repeat (genType const &Texcoord)
template<typename genType>
GLM_FUNC_DECL genType glm::mirrorRepeat (genType const &Texcoord)
Detailed Description
Wrapping mode of texture coordinates.
<glm/gtx/wrap.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType> GLM_FUNC_QUALIFIER genType glm::clamp (genType const & Texcoord) [inline]
Simulate GL_CLAMP OpenGL wrap mode
See also: GLM_GTX_wrap extension.
Definition at line 17 of file wrap.inl.
References glm::clamp().
20         {
21                 return glm::clamp(Texcoord, genType(0), genType(1));
22         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::mirrorRepeat (genType const & Texcoord) [inline]
Simulate GL_MIRROR_REPEAT OpenGL wrap mode
See also: GLM_GTX_wrap extension.
Definition at line 113 of file wrap.inl.
References glm::floor().
116         {
117                 genType const Clamp = genType(int(glm::floor(Texcoord)) % 2);
118                 genType const Floor = glm::floor(Texcoord);
119                 genType const Rest = Texcoord - Floor;
120                 genType const Mirror = Clamp + Rest;
121 
122                 genType Out;
123                 if(Mirror >= genType(1))
124                         Out = genType(1) - Rest;
125                 else
126                         Out = Rest;
127                 return Out;
128         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::repeat (genType const & Texcoord) [inline]
Simulate GL_REPEAT OpenGL wrap mode
See also: GLM_GTX_wrap extension.
Definition at line 65 of file wrap.inl.
References glm::fract().
68         {
69                 return glm::fract(Texcoord);
70         }