GLM_GTX_intersect
Functions
template<typename genType>
GLM_FUNC_DECL bool glm::intersectRayPlane (genType const &orig, genType const &dir, genType const &planeOrig, genType const &planeNormal, typename genType::value_type &intersectionDistance)
template<typename genType>
GLM_FUNC_DECL bool glm::intersectRayTriangle (genType const &orig, genType const &dir, genType const &vert0, genType const &vert1, genType const &vert2, genType &baryPosition)
template<typename genType>
GLM_FUNC_DECL bool glm::intersectLineTriangle (genType const &orig, genType const &dir, genType const &vert0, genType const &vert1, genType const &vert2, genType &position)
template<typename genType>
GLM_FUNC_DECL bool glm::intersectRaySphere (genType const &rayStarting, genType const &rayNormalizedDirection, genType const &sphereCenter, typename genType::value_type const sphereRadiusSquered, typename genType::value_type &intersectionDistance)
template<typename genType>
GLM_FUNC_DECL bool glm::intersectRaySphere (genType const &rayStarting, genType const &rayNormalizedDirection, genType const &sphereCenter, const typename genType::value_type sphereRadius, genType &intersectionPosition, genType &intersectionNormal)
template<typename genType>
GLM_FUNC_DECL bool glm::intersectLineSphere (genType const &point0, genType const &point1, genType const &sphereCenter, typename genType::value_type sphereRadius, genType &intersectionPosition1, genType &intersectionNormal1, genType &intersectionPosition2=genType(), genType &intersectionNormal2=genType())
Detailed Description
Add intersection functions.
<glm/gtx/intersect.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType> GLM_FUNC_QUALIFIER bool glm::intersectLineSphere (genType const & point0, genType const & point1, genType const & sphereCenter, typename genType::value_type sphereRadius, genType & intersectionPosition1, genType & intersectionNormal1, genType & intersectionPosition2 = genType(), genType & intersectionNormal2 = genType()) [inline]
Compute the intersection of a line and a sphere. From GLM_GTX_intersect extension
Definition at line 192 of file intersect.inl.
References glm::dot(), glm::epsilon(), glm::normalize(), and glm::sqrt().
198         {
199                 typename genType::value_type Epsilon = std::numeric_limits<typename genType::value_type>::epsilon();
200                 genType dir = normalize(point1 - point0);
201                 genType diff = sphereCenter - point0;
202                 typename genType::value_type t0 = dot(diff, dir);
203                 typename genType::value_type dSquared = dot(diff, diff) - t0 * t0;
204                 if( dSquared > sphereRadius * sphereRadius )
205                 {
206                         return false;
207                 }
208                 typename genType::value_type t1 = sqrt( sphereRadius * sphereRadius - dSquared );
209                 if( t0 < t1 + Epsilon )
210                         t1 = -t1;
211                 intersectionPoint1 = point0 + dir * (t0 - t1);
212                 intersectionNormal1 = (intersectionPoint1 - sphereCenter) / sphereRadius;
213                 intersectionPoint2 = point0 + dir * (t0 + t1);
214                 intersectionNormal2 = (intersectionPoint2 - sphereCenter) / sphereRadius;
215                 return true;
216         }
template<typename genType> GLM_FUNC_QUALIFIER bool glm::intersectLineTriangle (genType const & orig, genType const & dir, genType const & vert0, genType const & vert1, genType const & vert2, genType & position) [inline]
Compute the intersection of a line and a triangle. From GLM_GTX_intersect extension.
Definition at line 115 of file intersect.inl.
References glm::cross(), glm::dot(), and glm::epsilon().
120         {
121                 typename genType::value_type Epsilon = std::numeric_limits<typename genType::value_type>::epsilon();
122 
123                 genType edge1 = vert1 - vert0;
124                 genType edge2 = vert2 - vert0;
125 
126                 genType pvec = cross(dir, edge2);
127 
128                 float det = dot(edge1, pvec);
129 
130                 if (det > -Epsilon && det < Epsilon)
131                         return false;
132                 float inv_det = typename genType::value_type(1) / det;
133 
134                 genType tvec = orig - vert0;
135 
136                 position.y = dot(tvec, pvec) * inv_det;
137                 if (position.y < typename genType::value_type(0) || position.y > typename genType::value_type(1))
138                         return false;
139 
140                 genType qvec = cross(tvec, edge1);
141 
142                 position.z = dot(dir, qvec) * inv_det;
143                 if (position.z < typename genType::value_type(0) || position.y + position.z > typename genType::value_type(1))
144                         return false;
145 
146                 position.x = dot(edge2, qvec) * inv_det;
147 
148                 return true;
149         }
template<typename genType> GLM_FUNC_QUALIFIER bool glm::intersectRayPlane (genType const & orig, genType const & dir, genType const & planeOrig, genType const & planeNormal, typename genType::value_type & intersectionDistance) [inline]
Compute the intersection of a ray and a triangle. Ray direction and plane normal must be unit length. From GLM_GTX_intersect extension.
Definition at line 18 of file intersect.inl.
References glm::dot(), and glm::epsilon().
23         {
24                 typename genType::value_type d = glm::dot(dir, planeNormal);
25                 typename genType::value_type Epsilon = std::numeric_limits<typename genType::value_type>::epsilon();
26 
27                 if(d < Epsilon)
28                 {
29                         intersectionDistance = glm::dot(planeOrig - orig, planeNormal) / d;
30                         return true;
31                 }
32 
33                 return false;
34         }
template<typename genType> GLM_FUNC_QUALIFIER bool glm::intersectRaySphere (genType const & rayStarting, genType const & rayNormalizedDirection, genType const & sphereCenter, const typename genType::value_type sphereRadius, genType & intersectionPosition, genType & intersectionNormal) [inline]
Compute the intersection of a ray and a sphere. From GLM_GTX_intersect extension.
Definition at line 174 of file intersect.inl.
References glm::distance(), and glm::intersectRaySphere().
179         {
180                 typename genType::value_type distance;
181                 if( intersectRaySphere( rayStarting, rayNormalizedDirection, sphereCenter, sphereRadius * sphereRadius, distance ) )
182                 {
183                         intersectionPosition = rayStarting + rayNormalizedDirection * distance;
184                         intersectionNormal = (intersectionPosition - sphereCenter) / sphereRadius;
185                         return true;
186                 }
187                 return false;
188         }
template<typename genType> GLM_FUNC_QUALIFIER bool glm::intersectRaySphere (genType const & rayStarting, genType const & rayNormalizedDirection, genType const & sphereCenter, typename genType::value_type const sphereRadiusSquered, typename genType::value_type & intersectionDistance) [inline]
Compute the intersection distance of a ray and a sphere. The ray direction vector is unit length. From GLM_GTX_intersect extension.
Definition at line 153 of file intersect.inl.
References glm::dot(), glm::epsilon(), and glm::sqrt().
Referenced by glm::intersectRaySphere().
158         {
159                 typename genType::value_type Epsilon = std::numeric_limits<typename genType::value_type>::epsilon();
160                 genType diff = sphereCenter - rayStarting;
161                 typename genType::value_type t0 = dot(diff, rayNormalizedDirection);
162                 typename genType::value_type dSquared = dot(diff, diff) - t0 * t0;
163                 if( dSquared > sphereRadiusSquered )
164                 {
165                         return false;
166                 }
167                 typename genType::value_type t1 = sqrt( sphereRadiusSquered - dSquared );
168                 intersectionDistance = t0 > t1 + Epsilon ? t0 - t1 : t0 + t1;
169                 return intersectionDistance > Epsilon;
170         }
template<typename genType> GLM_FUNC_QUALIFIER bool glm::intersectRayTriangle (genType const & orig, genType const & dir, genType const & vert0, genType const & vert1, genType const & vert2, genType & baryPosition) [inline]
Compute the intersection of a ray and a triangle. From GLM_GTX_intersect extension.
Definition at line 38 of file intersect.inl.
References glm::cross(), glm::dot(), and glm::epsilon().
43         {
44                 genType e1 = v1 - v0;
45                 genType e2 = v2 - v0;
46 
47                 genType p = glm::cross(dir, e2);
48 
49                 typename genType::value_type a = glm::dot(e1, p);
50 
51                 typename genType::value_type Epsilon = std::numeric_limits<typename genType::value_type>::epsilon();
52                 if(a < Epsilon)
53                         return false;
54 
55                 typename genType::value_type f = typename genType::value_type(1.0f) / a;
56 
57                 genType s = orig - v0;
58                 baryPosition.x = f * glm::dot(s, p);
59                 if(baryPosition.x < typename genType::value_type(0.0f))
60                         return false;
61                 if(baryPosition.x > typename genType::value_type(1.0f))
62                         return false;
63 
64                 genType q = glm::cross(s, e1);
65                 baryPosition.y = f * glm::dot(dir, q);
66                 if(baryPosition.y < typename genType::value_type(0.0f))
67                         return false;
68                 if(baryPosition.y + baryPosition.x > typename genType::value_type(1.0f))
69                         return false;
70 
71                 baryPosition.z = f * glm::dot(e2, q);
72 
73                 return baryPosition.z >= typename genType::value_type(0.0f);
74         }