GLM_GTC_quaternion
Functions
template<typename T, precision P>
GLM_FUNC_DECL T glm::length (detail::tquat< T, P > const &q)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::normalize (detail::tquat< T, P > const &q)
template<typename T, precision P, template< typename, precision > class quatType>
GLM_FUNC_DECL T glm::dot (quatType< T, P > const &x, quatType< T, P > const &y)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::mix (detail::tquat< T, P > const &x, detail::tquat< T, P > const &y, T const &a)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::lerp (detail::tquat< T, P > const &x, detail::tquat< T, P > const &y, T const &a)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::slerp (detail::tquat< T, P > const &x, detail::tquat< T, P > const &y, T const &a)
Returns the slurp interpolation between two quaternions.
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::conjugate (detail::tquat< T, P > const &q)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::inverse (detail::tquat< T, P > const &q)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::rotate (detail::tquat< T, P > const &q, T const &angle, detail::tvec3< T, P > const &axis)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::eulerAngles (detail::tquat< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL T glm::roll (detail::tquat< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL T glm::pitch (detail::tquat< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL T glm::yaw (detail::tquat< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat3x3< T, P > glm::mat3_cast (detail::tquat< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat4x4< T, P > glm::mat4_cast (detail::tquat< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::quat_cast (detail::tmat3x3< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::quat_cast (detail::tmat4x4< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL T glm::angle (detail::tquat< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec3< T, P > glm::axis (detail::tquat< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL detail::tquat< T, P > glm::angleAxis (T const &angle, detail::tvec3< T, P > const &axis)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec4< bool, P > glm::lessThan (detail::tquat< T, P > const &x, detail::tquat< T, P > const &y)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec4< bool, P > glm::lessThanEqual (detail::tquat< T, P > const &x, detail::tquat< T, P > const &y)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec4< bool, P > glm::greaterThan (detail::tquat< T, P > const &x, detail::tquat< T, P > const &y)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec4< bool, P > glm::greaterThanEqual (detail::tquat< T, P > const &x, detail::tquat< T, P > const &y)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec4< bool, P > glm::equal (detail::tquat< T, P > const &x, detail::tquat< T, P > const &y)
template<typename T, precision P>
GLM_FUNC_DECL detail::tvec4< bool, P > glm::notEqual (detail::tquat< T, P > const &x, detail::tquat< T, P > const &y)
Detailed Description
Defines a templated quaternion type and several quaternion operations.
<glm/gtc/quaternion.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::angle (detail::tquat< T, P > const & x) [inline]
Returns the quaternion rotation angle.
See also: GLM_GTC_quaternion
Definition at line 799 of file quaternion.inl.
References glm::acos(), and glm::degrees().
802         {
803 #ifdef GLM_FORCE_RADIANS
804                 return acos(x.w) * T(2);
805 #else
806 #               pragma message("GLM: angle function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
807                 return glm::degrees(acos(x.w) * T(2));
808 #endif
809         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::angleAxis (T const & angle, detail::tvec3< T, P > const & axis) [inline]
Build a quaternion from an angle and a normalized axis.
Parameters:
angle Angle expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
axis Axis of the quaternion, must be normalized.
See also: GLM_GTC_quaternion
Definition at line 826 of file quaternion.inl.
References glm::cos(), glm::radians(), and glm::sin().
Referenced by glm::rotation().
830         {
831                 detail::tquat<T, P> result;
832 
833 #ifdef GLM_FORCE_RADIANS
834                 T const a(angle);
835 #else
836 #               pragma message("GLM: angleAxis function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
837                 T const a(glm::radians(angle));
838 #endif
839                 T s = glm::sin(a * T(0.5));
840 
841                 result.w = glm::cos(a * T(0.5));
842                 result.x = v.x * s;
843                 result.y = v.y * s;
844                 result.z = v.z * s;
845                 return result;
846         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::axis (detail::tquat< T, P > const & x) [inline]
Returns the q rotation axis.
See also: GLM_GTC_quaternion
Definition at line 813 of file quaternion.inl.
References glm::sqrt().
Referenced by btGearConstraint::getParam(), glm::rotate(), and glm::rotateNormalizedAxis().
816         {
817                 T tmp1 = static_cast<T>(1) - x.w * x.w;
818                 if(tmp1 <= static_cast<T>(0))
819                         return detail::tvec3<T, P>(0, 0, 1);
820                 T tmp2 = static_cast<T>(1) / sqrt(tmp1);
821                 return detail::tvec3<T, P>(x.x * tmp2, x.y * tmp2, x.z * tmp2);
822         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::conjugate (detail::tquat< T, P > const & q) [inline]
Returns the q conjugate.
See also: GLM_GTC_quaternion
Definition at line 177 of file quaternion.inl.
Referenced by glm::inverse().
180         {
181                 return detail::tquat<T, P>(q.w, -q.x, -q.y, -q.z);
182         }
template<typename T, precision P, template< typename, precision > class quatType> GLM_FUNC_DECL T glm::dot (quatType< T, P > const & x, quatType< T, P > const & y) [inline]
Returns dot product of q1 and q2, i.e., q1[0] * q2[0] + q1[1] * q2[1] + ...
See also: GLM_GTC_quaternion
Referenced by btGjkPairDetector::getClosestPointsNonVirtual(), glm::inverse(), glm::length(), glm::mix(), and glm::slerp().
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec4< bool, P > glm::equal (detail::tquat< T, P > const & x, detail::tquat< T, P > const & y) [inline]
Returns the component-wise comparison of result x == y.
Template Parameters:
quatType Floating-point quaternion types.
See also: GLM_GTC_quaternion
Definition at line 902 of file quaternion.inl.
906         {
907                 detail::tvec4<bool, P> Result;
908                 for(length_t i = 0; i < x.length(); ++i)
909                         Result[i] = x[i] == y[i];
910                 return Result;
911         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec3< T, P > glm::eulerAngles (detail::tquat< T, P > const & x) [inline]
Returns euler angles, yitch as x, yaw as y, roll as z. The result is expressed in radians if GLM_FORCE_RADIANS is defined or degrees otherwise.
See also: GLM_GTC_quaternion
Definition at line 632 of file quaternion.inl.
References glm::pitch(), glm::roll(), and glm::yaw().
635         {
636                 return detail::tvec3<T, P>(pitch(x), yaw(x), roll(x));
637         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec4< bool, P > glm::greaterThan (detail::tquat< T, P > const & x, detail::tquat< T, P > const & y) [inline]
Returns the component-wise comparison of result x > y.
Template Parameters:
quatType Floating-point quaternion types.
See also: GLM_GTC_quaternion
Definition at line 876 of file quaternion.inl.
880         {
881                 detail::tvec4<bool, P> Result;
882                 for(length_t i = 0; i < x.length(); ++i)
883                         Result[i] = x[i] > y[i];
884                 return Result;
885         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec4< bool, P > glm::greaterThanEqual (detail::tquat< T, P > const & x, detail::tquat< T, P > const & y) [inline]
Returns the component-wise comparison of result x >= y.
Template Parameters:
quatType Floating-point quaternion types.
See also: GLM_GTC_quaternion
Definition at line 889 of file quaternion.inl.
893         {
894                 detail::tvec4<bool, P> Result;
895                 for(length_t i = 0; i < x.length(); ++i)
896                         Result[i] = x[i] >= y[i];
897                 return Result;
898         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::inverse (detail::tquat< T, P > const & q) [inline]
Returns the q inverse.
See also: GLM_GTC_quaternion
Definition at line 186 of file quaternion.inl.
References glm::conjugate(), and glm::dot().
189         {
190                 return conjugate(q) / dot(q, q);
191         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::length (detail::tquat< T, P > const & q) [inline]
Returns the length of the quaternion.
See also: GLM_GTC_quaternion
Definition at line 402 of file quaternion.inl.
References glm::dot(), and glm::sqrt().
Referenced by btInverseDynamics::MultiBodyTree::addBody(), btContinuousConvexCollision::calcTimeOfImpact(), PhysicsEngine::CreateHeightfieldTerrainShape(), btGjkPairDetector::getClosestPointsNonVirtual(), Bruteforce::LoadHeightfield(), glm::normalize(), and Vector2::Normalized().
405         {
406                 return glm::sqrt(dot(q, q));
407         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::lerp (detail::tquat< T, P > const & x, detail::tquat< T, P > const & y, T const & a) [inline]
Linear interpolation of two quaternions. The interpolation is oriented.
Parameters:
x A quaternion
y A quaternion
a Interpolation factor. The interpolation is defined in the range [0, 1].
Template Parameters:
T Value type used to build the quaternion. Supported: half, float or double.
See also: GLM_GTC_quaternion
Definition at line 547 of file quaternion.inl.
552         {
553                 // Lerp is only defined in [0, 1]
554                 assert(a >= static_cast<T>(0));
555                 assert(a <= static_cast<T>(1));
556 
557                 return x * (T(1) - a) + (y * a);
558         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec4< bool, P > glm::lessThan (detail::tquat< T, P > const & x, detail::tquat< T, P > const & y) [inline]
Returns the component-wise comparison result of x < y.
Template Parameters:
quatType Floating-point quaternion types.
See also: GLM_GTC_quaternion
Definition at line 850 of file quaternion.inl.
854         {
855                 detail::tvec4<bool, P> Result;
856                 for(length_t i = 0; i < x.length(); ++i)
857                         Result[i] = x[i] < y[i];
858                 return Result;
859         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec4< bool, P > glm::lessThanEqual (detail::tquat< T, P > const & x, detail::tquat< T, P > const & y) [inline]
Returns the component-wise comparison of result x <= y.
Template Parameters:
quatType Floating-point quaternion types.
See also: GLM_GTC_quaternion
Definition at line 863 of file quaternion.inl.
867         {
868                 detail::tvec4<bool, P> Result;
869                 for(length_t i = 0; i < x.length(); ++i)
870                         Result[i] = x[i] <= y[i];
871                 return Result;
872         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat3x3< T, P > glm::mat3_cast (detail::tquat< T, P > const & x) [inline]
Converts a quaternion to a 3 * 3 matrix.
See also: GLM_GTC_quaternion
Definition at line 683 of file quaternion.inl.
Referenced by glm::mat4_cast(), and glm::toMat3().
686         {
687                 detail::tmat3x3<T, P> Result(T(1));
688                 T qxx(q.x * q.x);
689                 T qyy(q.y * q.y);
690                 T qzz(q.z * q.z);
691                 T qxz(q.x * q.z);
692                 T qxy(q.x * q.y);
693                 T qyz(q.y * q.z);
694                 T qwx(q.w * q.x);
695                 T qwy(q.w * q.y);
696                 T qwz(q.w * q.z);
697 
698                 Result[0][0] = 1 - 2 * (qyy +  qzz);
699                 Result[0][1] = 2 * (qxy + qwz);
700                 Result[0][2] = 2 * (qxz - qwy);
701 
702                 Result[1][0] = 2 * (qxy - qwz);
703                 Result[1][1] = 1 - 2 * (qxx +  qzz);
704                 Result[1][2] = 2 * (qyz + qwx);
705 
706                 Result[2][0] = 2 * (qxz + qwy);
707                 Result[2][1] = 2 * (qyz - qwx);
708                 Result[2][2] = 1 - 2 * (qxx +  qyy);
709                 return Result;
710         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat4x4< T, P > glm::mat4_cast (detail::tquat< T, P > const & x) [inline]
Converts a quaternion to a 4 * 4 matrix.
See also: GLM_GTC_quaternion
Definition at line 714 of file quaternion.inl.
References glm::mat3_cast().
Referenced by glm::toMat4().
717         {
718                 return detail::tmat4x4<T, P>(mat3_cast(q));
719         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::mix (detail::tquat< T, P > const & x, detail::tquat< T, P > const & y, T const & a) [inline]
Spherical linear interpolation of two quaternions. The interpolation is oriented and the rotation is performed at constant speed. For short path spherical linear interpolation, use the slerp function.
Parameters:
x A quaternion
y A quaternion
a Interpolation factor. The interpolation is defined beyond the range [0, 1].
Template Parameters:
T Value type used to build the quaternion. Supported: half, float or double.
See also: GLM_GTC_quaternion
- slerp(detail::tquat<T, P> const & x, detail::tquat<T, P> const & y, T const & a)
Definition at line 519 of file quaternion.inl.
References glm::acos(), glm::angle(), glm::dot(), and glm::sin().
Referenced by glm::slerp().
524         {
525                 T cosTheta = dot(x, y);
526 
527                 // Perform a linear interpolation when cosTheta is close to 1 to avoid side effect of sin(angle) becoming a zero denominator
528                 if(cosTheta > T(1) - epsilon<T>())
529                 {
530                         // Linear interpolation
531                         return detail::tquat<T, P>(
532                                 mix(x.w, y.w, a),
533                                 mix(x.x, y.x, a),
534                                 mix(x.y, y.y, a),
535                                 mix(x.z, y.z, a));
536                 }
537                 else
538                 {
539                         // Essential Mathematics, page 467
540                         T angle = acos(cosTheta);
541                         return (sin((T(1) - a) * angle) * x + sin(a * angle) * y) / sin(angle);
542                 }
543         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::normalize (detail::tquat< T, P > const & q) [inline]
Returns the normalized quaternion.
See also: GLM_GTC_quaternion
Definition at line 411 of file quaternion.inl.
References glm::length().
414         {
415                 T len = length(q);
416                 if(len <= T(0)) // Problem
417                         return detail::tquat<T, P>(1, 0, 0, 0);
418                 T oneOverLen = T(1) / len;
419                 return detail::tquat<T, P>(q.w * oneOverLen, q.x * oneOverLen, q.y * oneOverLen, q.z * oneOverLen);
420         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tvec4< bool, P > glm::notEqual (detail::tquat< T, P > const & x, detail::tquat< T, P > const & y) [inline]
Returns the component-wise comparison of result x != y.
Template Parameters:
quatType Floating-point quaternion types.
See also: GLM_GTC_quaternion
Definition at line 915 of file quaternion.inl.
919         {
920                 detail::tvec4<bool, P> Result;
921                 for(length_t i = 0; i < x.length(); ++i)
922                         Result[i] = x[i] != y[i];
923                 return Result;
924         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::pitch (detail::tquat< T, P > const & x) [inline]
Returns pitch value of euler angles expressed in radians if GLM_FORCE_RADIANS is defined or degrees otherwise.
See also: GLM_GTX_quaternion
Definition at line 655 of file quaternion.inl.
References glm::atan(), and glm::degrees().
Referenced by glm::eulerAngles().
658         {
659 #ifdef GLM_FORCE_RADIANS
660                 return T(atan(T(2) * (q.y * q.z + q.w * q.x), q.w * q.w - q.x * q.x - q.y * q.y + q.z * q.z));
661 #else
662 #               pragma message("GLM: pitch function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
663                 return glm::degrees(atan(T(2) * (q.y * q.z + q.w * q.x), q.w * q.w - q.x * q.x - q.y * q.y + q.z * q.z));
664 #endif
665         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::quat_cast (detail::tmat4x4< T, P > const & x) [inline]
Converts a 4 * 4 matrix to a quaternion.
See also: GLM_GTC_quaternion
Definition at line 790 of file quaternion.inl.
793         {
794                 return quat_cast(detail::tmat3x3<T, P>(m4));
795         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::quat_cast (detail::tmat3x3< T, P > const & x) [inline]
Converts a 3 * 3 matrix to a quaternion.
See also: GLM_GTC_quaternion
Definition at line 723 of file quaternion.inl.
References glm::sqrt().
Referenced by glm::toQuat().
726         {
727                 T fourXSquaredMinus1 = m[0][0] - m[1][1] - m[2][2];
728                 T fourYSquaredMinus1 = m[1][1] - m[0][0] - m[2][2];
729                 T fourZSquaredMinus1 = m[2][2] - m[0][0] - m[1][1];
730                 T fourWSquaredMinus1 = m[0][0] + m[1][1] + m[2][2];
731 
732                 int biggestIndex = 0;
733                 T fourBiggestSquaredMinus1 = fourWSquaredMinus1;
734                 if(fourXSquaredMinus1 > fourBiggestSquaredMinus1)
735                 {
736                         fourBiggestSquaredMinus1 = fourXSquaredMinus1;
737                         biggestIndex = 1;
738                 }
739                 if(fourYSquaredMinus1 > fourBiggestSquaredMinus1)
740                 {
741                         fourBiggestSquaredMinus1 = fourYSquaredMinus1;
742                         biggestIndex = 2;
743                 }
744                 if(fourZSquaredMinus1 > fourBiggestSquaredMinus1)
745                 {
746                         fourBiggestSquaredMinus1 = fourZSquaredMinus1;
747                         biggestIndex = 3;
748                 }
749 
750                 T biggestVal = sqrt(fourBiggestSquaredMinus1 + T(1)) * T(0.5);
751                 T mult = static_cast<T>(0.25) / biggestVal;
752 
753                 detail::tquat<T, P> Result;
754                 switch(biggestIndex)
755                 {
756                 case 0:
757                         Result.w = biggestVal;
758                         Result.x = (m[1][2] - m[2][1]) * mult;
759                         Result.y = (m[2][0] - m[0][2]) * mult;
760                         Result.z = (m[0][1] - m[1][0]) * mult;
761                         break;
762                 case 1:
763                         Result.w = (m[1][2] - m[2][1]) * mult;
764                         Result.x = biggestVal;
765                         Result.y = (m[0][1] + m[1][0]) * mult;
766                         Result.z = (m[2][0] + m[0][2]) * mult;
767                         break;
768                 case 2:
769                         Result.w = (m[2][0] - m[0][2]) * mult;
770                         Result.x = (m[0][1] + m[1][0]) * mult;
771                         Result.y = biggestVal;
772                         Result.z = (m[1][2] + m[2][1]) * mult;
773                         break;
774                 case 3:
775                         Result.w = (m[0][1] - m[1][0]) * mult;
776                         Result.x = (m[2][0] + m[0][2]) * mult;
777                         Result.y = (m[1][2] + m[2][1]) * mult;
778                         Result.z = biggestVal;
779                         break;
780                         
781                 default:                                        // Silence a -Wswitch-default warning in GCC. Should never actually get here. Assert is just for sanity.
782                         assert(false);
783                         break;
784                 }
785                 return Result;
786         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::roll (detail::tquat< T, P > const & x) [inline]
Returns roll value of euler angles expressed in radians if GLM_FORCE_RADIANS is defined or degrees otherwise.
See also: GLM_GTX_quaternion
Definition at line 641 of file quaternion.inl.
References glm::atan(), and glm::degrees().
Referenced by glm::eulerAngles().
644         {
645 #ifdef GLM_FORCE_RADIANS
646                 return T(atan(T(2) * (q.x * q.y + q.w * q.z), q.w * q.w + q.x * q.x - q.y * q.y - q.z * q.z));
647 #else
648 #               pragma message("GLM: roll function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
649                 return glm::degrees(atan(T(2) * (q.x * q.y + q.w * q.z), q.w * q.w + q.x * q.x - q.y * q.y - q.z * q.z));
650 #endif
651         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tquat< T, P > glm::rotate (detail::tquat< T, P > const & q, T const & angle, detail::tvec3< T, P > const & axis) [inline]
Rotates a quaternion from a vector of 3 components axis and an angle.
Parameters:
q Source orientation
angle Angle expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
axis Axis of the rotation
See also: GLM_GTC_quaternion
Definition at line 600 of file quaternion.inl.
References glm::abs(), glm::cos(), glm::length(), glm::radians(), and glm::sin().
605         {
606                 detail::tvec3<T, P> Tmp = v;
607 
608                 // Axis of rotation must be normalised
609                 T len = glm::length(Tmp);
610                 if(abs(len - T(1)) > T(0.001))
611                 {
612                         T oneOverLen = static_cast<T>(1) / len;
613                         Tmp.x *= oneOverLen;
614                         Tmp.y *= oneOverLen;
615                         Tmp.z *= oneOverLen;
616                 }
617 
618 #ifdef GLM_FORCE_RADIANS
619                 T const AngleRad(angle);
620 #else
621 #               pragma message("GLM: rotate function taking degrees as a parameter is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
622                 T const AngleRad = radians(angle);
623 #endif
624                 T const Sin = sin(AngleRad * T(0.5));
625 
626                 return q * detail::tquat<T, P>(cos(AngleRad * T(0.5)), Tmp.x * Sin, Tmp.y * Sin, Tmp.z * Sin);
627                 //return gtc::quaternion::cross(q, detail::tquat<T, P>(cos(AngleRad * T(0.5)), Tmp.x * fSin, Tmp.y * fSin, Tmp.z * fSin));
628         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::slerp (detail::tquat< T, P > const & x, detail::tquat< T, P > const & y, T const & a) [inline]
Returns the slurp interpolation between two quaternions.
Spherical linear interpolation of two quaternions. The interpolation always take the short path and the rotation is performed at constant speed.
Parameters:
x A quaternion
y A quaternion
a Interpolation factor. The interpolation is defined beyond the range [0, 1].
Template Parameters:
T Value type used to build the quaternion. Supported: half, float or double.
See also: GLM_GTC_quaternion
Definition at line 562 of file quaternion.inl.
References glm::acos(), glm::angle(), glm::dot(), glm::mix(), and glm::sin().
567         {
568                 detail::tquat<T, P> z = y;
569 
570                 T cosTheta = dot(x, y);
571 
572                 // If cosTheta < 0, the interpolation will take the long way around the sphere. 
573                 // To fix this, one quat must be negated.
574                 if (cosTheta < T(0))
575                 {
576                         z        = -y;
577                         cosTheta = -cosTheta;
578                 }
579 
580                 // Perform a linear interpolation when cosTheta is close to 1 to avoid side effect of sin(angle) becoming a zero denominator
581                 if(cosTheta > T(1) - epsilon<T>())
582                 {
583                         // Linear interpolation
584                         return detail::tquat<T, P>(
585                                 mix(x.w, z.w, a),
586                                 mix(x.x, z.x, a),
587                                 mix(x.y, z.y, a),
588                                 mix(x.z, z.z, a));
589                 }
590                 else
591                 {
592                         // Essential Mathematics, page 467
593                         T angle = acos(cosTheta);
594                         return (sin((T(1) - a) * angle) * x + sin(a * angle) * z) / sin(angle);
595                 }
596         }
template<typename T, precision P> GLM_FUNC_QUALIFIER T glm::yaw (detail::tquat< T, P > const & x) [inline]
Returns yaw value of euler angles expressed in radians if GLM_FORCE_RADIANS is defined or degrees otherwise.
See also: GLM_GTX_quaternion
Definition at line 669 of file quaternion.inl.
References glm::asin(), and glm::degrees().
Referenced by glm::eulerAngles().
672         {
673 #ifdef GLM_FORCE_RADIANS
674                 return asin(T(-2) * (q.x * q.z - q.w * q.y));
675 #else
676 #               pragma message("GLM: yaw function returning degrees is deprecated. #define GLM_FORCE_RADIANS before including GLM headers to remove this message.")
677                 return glm::degrees(asin(T(-2) * (q.x * q.z - q.w * q.y)));
678 #endif
679         }