GLM_GTC_packing
Functions
GLM_FUNC_DECL uint8 glm::packUnorm1x8 (float v)
GLM_FUNC_DECL float glm::unpackUnorm1x8 (uint8 p)
GLM_FUNC_DECL uint16 glm::packUnorm2x8 (vec2 const &v)
GLM_FUNC_DECL vec2 glm::unpackUnorm2x8 (uint16 p)
GLM_FUNC_DECL uint8 glm::packSnorm1x8 (float s)
GLM_FUNC_DECL float glm::unpackSnorm1x8 (uint8 p)
GLM_FUNC_DECL uint16 glm::packSnorm2x8 (vec2 const &v)
GLM_FUNC_DECL vec2 glm::unpackSnorm2x8 (uint16 p)
GLM_FUNC_DECL uint16 glm::packUnorm1x16 (float v)
GLM_FUNC_DECL float glm::unpackUnorm1x16 (uint16 p)
GLM_FUNC_DECL uint64 glm::packUnorm4x16 (vec4 const &v)
GLM_FUNC_DECL vec4 glm::unpackUnorm4x16 (uint64 p)
GLM_FUNC_DECL uint16 glm::packSnorm1x16 (float v)
GLM_FUNC_DECL float glm::unpackSnorm1x16 (uint16 p)
GLM_FUNC_DECL uint64 glm::packSnorm4x16 (vec4 const &v)
GLM_FUNC_DECL vec4 glm::unpackSnorm4x16 (uint64 const &p)
GLM_FUNC_DECL uint16 glm::packHalf1x16 (float v)
GLM_FUNC_DECL float glm::unpackHalf1x16 (uint16 v)
GLM_FUNC_DECL uint64 glm::packHalf4x16 (vec4 const &v)
GLM_FUNC_DECL vec4 glm::unpackHalf4x16 (uint64 p)
GLM_FUNC_DECL uint32 glm::packI3x10_1x2 (ivec4 const &v)
GLM_FUNC_DECL ivec4 glm::unpackI3x10_1x2 (uint32 p)
GLM_FUNC_DECL uint32 glm::packU3x10_1x2 (uvec4 const &v)
GLM_FUNC_DECL uvec4 glm::unpackU3x10_1x2 (uint32 p)
GLM_FUNC_DECL uint32 glm::packSnorm3x10_1x2 (vec4 const &v)
GLM_FUNC_DECL vec4 glm::unpackSnorm3x10_1x2 (uint32 p)
GLM_FUNC_DECL uint32 glm::packUnorm3x10_1x2 (vec4 const &v)
GLM_FUNC_DECL vec4 glm::unpackUnorm3x10_1x2 (uint32 p)
GLM_FUNC_DECL uint32 glm::packF2x11_1x10 (vec3 const &v)
GLM_FUNC_DECL vec3 glm::unpackF2x11_1x10 (uint32 p)
Detailed Description
This extension provides a set of function to convert vertors to packed formats.
<glm/gtc/packing.hpp> need to be included to use these features.
Function Documentation
GLM_FUNC_QUALIFIER uint32 glm::packF2x11_1x10 (vec3 const & v)
First, converts the first two components of the normalized floating-point value v into 11-bit signless floating-point values. Then, converts the third component of the normalized floating-point value v into a 10-bit signless floating-point value. Then, the results are packed into the returned 32-bit unsigned integer.
The first vector component specifies the 11 least-significant bits of the result; the last component specifies the 10 most-significant bits.
See also: GLM_GTC_packing
vec3 unpackF2x11_1x10(uint32 const & p)
Definition at line 480 of file packing.inl.
481         {
482                 return 
483                         ((detail::floatTo11bit(v.x) & ((1 << 11) - 1)) <<  0) |
484                         ((detail::floatTo11bit(v.y) & ((1 << 11) - 1)) << 11) |
485                         ((detail::floatTo10bit(v.z) & ((1 << 10) - 1)) << 22);
486         }
GLM_FUNC_QUALIFIER uint16 glm::packHalf1x16 (float v)
Returns an unsigned integer obtained by converting the components of a floating-point scalar to the 16-bit floating-point representation found in the OpenGL Specification, and then packing this 16-bit value into a 16-bit unsigned integer.
See also: GLM_GTC_packing
uint32 packHalf2x16(vec2 const & v)
uint64 packHalf4x16(vec4 const & v)
GLSL packHalf2x16 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 357 of file packing.inl.
358         {
359                 int16 Topack = detail::toFloat16(v);
360                 uint16* Packed = reinterpret_cast<uint16*>(&Topack);
361                 return *Packed;
362         }
GLM_FUNC_QUALIFIER uint64 glm::packHalf4x16 (glm::vec4 const & v)
Returns an unsigned integer obtained by converting the components of a four-component floating-point vector to the 16-bit floating-point representation found in the OpenGL Specification, and then packing these four 16-bit values into a 64-bit unsigned integer. The first vector component specifies the 16 least-significant bits of the result; the forth component specifies the 16 most-significant bits.
See also: GLM_GTC_packing
uint16 packHalf1x16(float const & v)
uint32 packHalf2x16(vec2 const & v)
GLSL packHalf2x16 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 370 of file packing.inl.
371         {
372                 i16vec4 Unpack(
373                         detail::toFloat16(v.x),
374                         detail::toFloat16(v.y),
375                         detail::toFloat16(v.z),
376                         detail::toFloat16(v.w));
377 
378                 uint64* Packed = reinterpret_cast<uint64*>(&Unpack);
379                 return *Packed;
380         }
GLM_FUNC_QUALIFIER uint32 glm::packI3x10_1x2 (ivec4 const & v)
Returns an unsigned integer obtained by converting the components of a four-component signed integer vector to the 10-10-10-2-bit signed integer representation found in the OpenGL Specification, and then packing these four values into a 32-bit unsigned integer. The first vector component specifies the 10 least-significant bits of the result; the forth component specifies the 2 most-significant bits.
See also: GLM_GTC_packing
uint32 packI3x10_1x2(uvec4 const & v)
uint32 packSnorm3x10_1x2(vec4 const & v)
uint32 packUnorm3x10_1x2(vec4 const & v)
ivec4 unpackI3x10_1x2(uint32 const & p)
Definition at line 394 of file packing.inl.
395         {
396                 detail::i10i10i10i2 Result;
397                 Result.data.x = v.x;
398                 Result.data.y = v.y;
399                 Result.data.z = v.z;
400                 Result.data.w = v.w;
401                 return Result.pack; 
402         }
GLM_FUNC_QUALIFIER uint16 glm::packSnorm1x16 (float v)
First, converts the normalized floating-point value v into 16-bit integer value. Then, the results are packed into the returned 16-bit unsigned integer.
The conversion to fixed point is done as follows: packSnorm1x8: round(clamp(s, -1, +1) * 32767.0)
See also: GLM_GTC_packing
uint32 packSnorm2x16(vec2 const & v)
uint64 packSnorm4x16(vec4 const & v)
GLSL packSnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 327 of file packing.inl.
References glm::clamp(), and glm::round().
328         {
329                 int16 Topack = static_cast<int16>(round(clamp(v ,-1.0f, 1.0f) * 32767.0f));
330                 uint16* Packed = reinterpret_cast<uint16*>(&Topack);
331                 return *Packed;
332         }
GLM_FUNC_QUALIFIER uint8 glm::packSnorm1x8 (float s)
First, converts the normalized floating-point value v into 8-bit integer value. Then, the results are packed into the returned 8-bit unsigned integer.
The conversion to fixed point is done as follows: packSnorm1x8: round(clamp(s, -1, +1) * 127.0)
See also: GLM_GTC_packing
uint16 packSnorm2x8(vec2 const & v)
uint32 packSnorm4x8(vec4 const & v)
GLSL packSnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 273 of file packing.inl.
References glm::clamp(), and glm::round().
274         {
275                 int8 Topack(static_cast<int8>(round(clamp(v ,-1.0f, 1.0f) * 127.0f)));
276                 uint8* Packed = reinterpret_cast<uint8*>(&Topack);
277                 return *Packed;
278         }
GLM_FUNC_QUALIFIER uint16 glm::packSnorm2x8 (vec2 const & v)
First, converts each component of the normalized floating-point value v into 8-bit integer values. Then, the results are packed into the returned 16-bit unsigned integer.
The conversion for component c of v to fixed point is done as follows: packSnorm2x8: round(clamp(c, -1, +1) * 127.0)
The first component of the vector will be written to the least significant bits of the output; the last component will be written to the most significant bits.
See also: GLM_GTC_packing
uint8 packSnorm1x8(float const & v)
uint32 packSnorm4x8(vec4 const & v)
GLSL packSnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 288 of file packing.inl.
References glm::clamp(), and glm::round().
289         {
290                 i8vec2 Topack(round(clamp(v ,-1.0f, 1.0f) * 127.0f));
291                 uint16* Packed = reinterpret_cast<uint16*>(&Topack);
292                 return *Packed;
293         }
GLM_FUNC_QUALIFIER uint32 glm::packSnorm3x10_1x2 (vec4 const & v)
First, converts the first three components of the normalized floating-point value v into 10-bit signed integer values. Then, converts the forth component of the normalized floating-point value v into 2-bit signed integer values. Then, the results are packed into the returned 32-bit unsigned integer.
The conversion for component c of v to fixed point is done as follows: packSnorm3x10_1x2(xyz): round(clamp(c, -1, +1) * 511.0) packSnorm3x10_1x2(w): round(clamp(c, -1, +1) * 1.0)
The first vector component specifies the 10 least-significant bits of the result; the forth component specifies the 2 most-significant bits.
See also: GLM_GTC_packing
vec4 unpackSnorm3x10_1x2(uint32 const & p)
uint32 packUnorm3x10_1x2(vec4 const & v)
uint32 packU3x10_1x2(uvec4 const & v)
uint32 packI3x10_1x2(ivec4 const & v)
Definition at line 436 of file packing.inl.
References glm::clamp(), and glm::round().
437         {
438                 detail::i10i10i10i2 Result;
439                 Result.data.x = int(round(clamp(v.x,-1.0f, 1.0f) * 511.f));
440                 Result.data.y = int(round(clamp(v.y,-1.0f, 1.0f) * 511.f));
441                 Result.data.z = int(round(clamp(v.z,-1.0f, 1.0f) * 511.f));
442                 Result.data.w = int(round(clamp(v.w,-1.0f, 1.0f) *   1.f));
443                 return Result.pack;
444         }
GLM_FUNC_QUALIFIER uint64 glm::packSnorm4x16 (vec4 const & v)
First, converts each component of the normalized floating-point value v into 16-bit integer values. Then, the results are packed into the returned 64-bit unsigned integer.
The conversion for component c of v to fixed point is done as follows: packSnorm2x8: round(clamp(c, -1, +1) * 32767.0)
The first component of the vector will be written to the least significant bits of the output; the last component will be written to the most significant bits.
See also: GLM_GTC_packing
uint16 packSnorm1x16(float const & v)
uint32 packSnorm2x16(vec2 const & v)
GLSL packSnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 342 of file packing.inl.
References glm::clamp(), and glm::round().
343         {
344                 i16vec4 Topack = static_cast<i16vec4>(round(clamp(v ,-1.0f, 1.0f) * 32767.0f));
345                 uint64* Packed = reinterpret_cast<uint64*>(&Topack);
346                 return *Packed;
347         }
GLM_FUNC_QUALIFIER uint32 glm::packU3x10_1x2 (uvec4 const & v)
Returns an unsigned integer obtained by converting the components of a four-component unsigned integer vector to the 10-10-10-2-bit unsigned integer representation found in the OpenGL Specification, and then packing these four values into a 32-bit unsigned integer. The first vector component specifies the 10 least-significant bits of the result; the forth component specifies the 2 most-significant bits.
See also: GLM_GTC_packing
uint32 packI3x10_1x2(ivec4 const & v)
uint32 packSnorm3x10_1x2(vec4 const & v)
uint32 packUnorm3x10_1x2(vec4 const & v)
ivec4 unpackU3x10_1x2(uint32 const & p)
Definition at line 415 of file packing.inl.
416         {
417                 detail::u10u10u10u2 Result;
418                 Result.data.x = v.x;
419                 Result.data.y = v.y;
420                 Result.data.z = v.z;
421                 Result.data.w = v.w;
422                 return Result.pack; 
423         }
GLM_FUNC_QUALIFIER uint16 glm::packUnorm1x16 (float v)
First, converts the normalized floating-point value v into a 16-bit integer value. Then, the results are packed into the returned 16-bit unsigned integer.
The conversion for component c of v to fixed point is done as follows: packUnorm1x16: round(clamp(c, 0, +1) * 65535.0)
See also: GLM_GTC_packing
uint16 packSnorm1x16(float const & v)
uint64 packSnorm4x16(vec4 const & v)
GLSL packUnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 303 of file packing.inl.
References glm::clamp(), and glm::round().
304         {
305                 return static_cast<uint16>(round(clamp(s, 0.0f, 1.0f) * 65535.0f));
306         }
GLM_FUNC_QUALIFIER uint8 glm::packUnorm1x8 (float v)
First, converts the normalized floating-point value v into a 8-bit integer value. Then, the results are packed into the returned 8-bit unsigned integer.
The conversion for component c of v to fixed point is done as follows: packUnorm1x8: round(clamp(c, 0, +1) * 255.0)
See also: GLM_GTC_packing
uint16 packUnorm2x8(vec2 const & v)
uint32 packUnorm4x8(vec4 const & v)
GLSL packUnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 249 of file packing.inl.
References glm::clamp(), and glm::round().
250         {
251                 return static_cast<uint8>(round(clamp(v, 0.0f, 1.0f) * 255.0f));
252         }
GLM_FUNC_QUALIFIER uint16 glm::packUnorm2x8 (vec2 const & v)
First, converts each component of the normalized floating-point value v into 8-bit integer values. Then, the results are packed into the returned 16-bit unsigned integer.
The conversion for component c of v to fixed point is done as follows: packUnorm2x8: round(clamp(c, 0, +1) * 255.0)
The first component of the vector will be written to the least significant bits of the output; the last component will be written to the most significant bits.
See also: GLM_GTC_packing
uint8 packUnorm1x8(float const & v)
uint32 packUnorm4x8(vec4 const & v)
GLSL packUnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 260 of file packing.inl.
References glm::clamp(), and glm::round().
261         {
262                 u8vec2 Topack(round(clamp(v, 0.0f, 1.0f) * 255.0f));
263                 uint16* Packed = reinterpret_cast<uint16*>(&Topack);
264                 return *Packed;
265         }
GLM_FUNC_QUALIFIER uint32 glm::packUnorm3x10_1x2 (vec4 const & v)
First, converts the first three components of the normalized floating-point value v into 10-bit unsigned integer values. Then, converts the forth component of the normalized floating-point value v into 2-bit signed uninteger values. Then, the results are packed into the returned 32-bit unsigned integer.
The conversion for component c of v to fixed point is done as follows: packUnorm3x10_1x2(xyz): round(clamp(c, 0, +1) * 1023.0) packUnorm3x10_1x2(w): round(clamp(c, 0, +1) * 3.0)
The first vector component specifies the 10 least-significant bits of the result; the forth component specifies the 2 most-significant bits.
See also: GLM_GTC_packing
vec4 unpackUnorm3x10_1x2(uint32 const & p)
uint32 packUnorm3x10_1x2(vec4 const & v)
uint32 packU3x10_1x2(uvec4 const & v)
uint32 packI3x10_1x2(ivec4 const & v)
Definition at line 458 of file packing.inl.
References glm::clamp(), and glm::round().
459         {
460                 detail::i10i10i10i2 Result;
461                 Result.data.x = int(round(clamp(v.x, 0.0f, 1.0f) * 1023.f));
462                 Result.data.y = int(round(clamp(v.y, 0.0f, 1.0f) * 1023.f));
463                 Result.data.z = int(round(clamp(v.z, 0.0f, 1.0f) * 1023.f));
464                 Result.data.w = int(round(clamp(v.w, 0.0f, 1.0f) *    3.f));
465                 return Result.pack;
466         }
GLM_FUNC_QUALIFIER uint64 glm::packUnorm4x16 (vec4 const & v)
First, converts each component of the normalized floating-point value v into 16-bit integer values. Then, the results are packed into the returned 64-bit unsigned integer.
The conversion for component c of v to fixed point is done as follows: packUnorm4x16: round(clamp(c, 0, +1) * 65535.0)
The first component of the vector will be written to the least significant bits of the output; the last component will be written to the most significant bits.
See also: GLM_GTC_packing
uint16 packUnorm1x16(float const & v)
uint32 packUnorm2x16(vec2 const & v)
GLSL packUnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 314 of file packing.inl.
References glm::clamp(), and glm::round().
315         {
316                 u16vec4 Topack(round(clamp(v , 0.0f, 1.0f) * 65535.0f));
317                 uint64* Packed = reinterpret_cast<uint64*>(&Topack);
318                 return *Packed;
319         }
GLM_FUNC_QUALIFIER vec3 glm::unpackF2x11_1x10 (uint32 p)
First, unpacks a single 32-bit unsigned integer p into two 11-bit signless floating-point values and one 10-bit signless floating-point value . Then, each component is converted to a normalized floating-point value to generate the returned three-component vector.
The first component of the returned vector will be extracted from the least significant bits of the input; the last component will be extracted from the most significant bits.
See also: GLM_GTC_packing
uint32 packF2x11_1x10(vec3 const & v)
Definition at line 488 of file packing.inl.
489         {
490                 return vec3(
491                         detail::packed11bitToFloat(v >> 0), 
492                         detail::packed11bitToFloat(v >> 11), 
493                         detail::packed10bitToFloat(v >> 22));
494         }
GLM_FUNC_QUALIFIER float glm::unpackHalf1x16 (uint16 v)
Returns a floating-point scalar with components obtained by unpacking a 16-bit unsigned integer into a 16-bit value, interpreted as a 16-bit floating-point number according to the OpenGL Specification, and converting it to 32-bit floating-point values.
See also: GLM_GTC_packing
vec2 unpackHalf2x16(uint32 const & v)
vec4 unpackHalf4x16(uint64 const & v)
GLSL unpackHalf2x16 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 364 of file packing.inl.
365         {
366                 int16* Unpack = reinterpret_cast<int16*>(const_cast<uint16*>(&v));
367                 return detail::toFloat32(*Unpack);
368         }
GLM_FUNC_QUALIFIER glm::vec4 glm::unpackHalf4x16 (uint64 p)
Returns a four-component floating-point vector with components obtained by unpacking a 64-bit unsigned integer into four 16-bit values, interpreting those values as 16-bit floating-point numbers according to the OpenGL Specification, and converting them to 32-bit floating-point values. The first component of the vector is obtained from the 16 least-significant bits of v; the forth component is obtained from the 16 most-significant bits of v.
See also: GLM_GTC_packing
float unpackHalf1x16(uint16 const & v)
vec2 unpackHalf2x16(uint32 const & v)
GLSL unpackHalf2x16 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 382 of file packing.inl.
383         {
384                 i16vec4* p = reinterpret_cast<i16vec4*>(const_cast<uint64*>(&v));
385                 i16vec4 Unpack(*p);
386         
387                 return vec4(
388                         detail::toFloat32(Unpack.x), 
389                         detail::toFloat32(Unpack.y), 
390                         detail::toFloat32(Unpack.z), 
391                         detail::toFloat32(Unpack.w));
392         }
GLM_FUNC_QUALIFIER ivec4 glm::unpackI3x10_1x2 (uint32 p)
Unpacks a single 32-bit unsigned integer p into three 10-bit and one 2-bit signed integers.
The first component of the returned vector will be extracted from the least significant bits of the input; the last component will be extracted from the most significant bits.
See also: GLM_GTC_packing
uint32 packU3x10_1x2(uvec4 const & v)
vec4 unpackSnorm3x10_1x2(uint32 const & p);
uvec4 unpackI3x10_1x2(uint32 const & p);
Definition at line 404 of file packing.inl.
405         {
406                 detail::i10i10i10i2 Unpack;
407                 Unpack.pack = v;
408                 return ivec4(
409                         Unpack.data.x,
410                         Unpack.data.y,
411                         Unpack.data.z,
412                         Unpack.data.w);
413         }
GLM_FUNC_QUALIFIER float glm::unpackSnorm1x16 (uint16 p)
First, unpacks a single 16-bit unsigned integer p into a single 16-bit signed integers. Then, each component is converted to a normalized floating-point value to generate the returned scalar.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackSnorm1x16: clamp(f / 32767.0, -1, +1)
See also: GLM_GTC_packing
vec2 unpackSnorm2x16(uint32 p)
vec4 unpackSnorm4x16(uint64 p)
GLSL unpackSnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 334 of file packing.inl.
References glm::clamp(), and glm::e().
335         {
336                 float Unpack = static_cast<float>(*const_cast<uint16*>(&p));
337                 return clamp(
338                         Unpack * 3.0518509475997192297128208258309e-5f, //1.0f / 32767.0f, 
339                         -1.0f, 1.0f);
340         }
GLM_FUNC_QUALIFIER float glm::unpackSnorm1x8 (uint8 p)
First, unpacks a single 8-bit unsigned integer p into a single 8-bit signed integers. Then, the value is converted to a normalized floating-point value to generate the returned scalar.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackSnorm1x8: clamp(f / 127.0, -1, +1)
See also: GLM_GTC_packing
vec2 unpackSnorm2x8(uint16 p)
vec4 unpackSnorm4x8(uint32 p)
GLSL unpackSnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 280 of file packing.inl.
References glm::clamp().
281         {
282                 float Unpack(static_cast<float>(*const_cast<uint8*>(&p)));
283                 return clamp(
284                         Unpack * 0.00787401574803149606299212598425f, // 1.0f / 127.0f
285                         -1.0f, 1.0f);
286         }
GLM_FUNC_QUALIFIER vec2 glm::unpackSnorm2x8 (uint16 p)
First, unpacks a single 16-bit unsigned integer p into a pair of 8-bit signed integers. Then, each component is converted to a normalized floating-point value to generate the returned two-component vector.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackSnorm2x8: clamp(f / 127.0, -1, +1)
The first component of the returned vector will be extracted from the least significant bits of the input; the last component will be extracted from the most significant bits.
See also: GLM_GTC_packing
float unpackSnorm1x8(uint8 p)
vec4 unpackSnorm4x8(uint32 p)
GLSL unpackSnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 295 of file packing.inl.
References glm::clamp().
296         {
297                 i8vec2* Unpack = reinterpret_cast<i8vec2*>(const_cast<uint16*>(&p));
298                 return clamp(
299                         vec2(*Unpack) * 0.00787401574803149606299212598425f, // 1.0f / 127.0f
300                         -1.0f, 1.0f);
301         }
GLM_FUNC_QUALIFIER vec4 glm::unpackSnorm3x10_1x2 (uint32 p)
First, unpacks a single 32-bit unsigned integer p into four 16-bit signed integers. Then, each component is converted to a normalized floating-point value to generate the returned four-component vector.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackSnorm3x10_1x2(xyz): clamp(f / 511.0, -1, +1) unpackSnorm3x10_1x2(w): clamp(f / 511.0, -1, +1)
The first component of the returned vector will be extracted from the least significant bits of the input; the last component will be extracted from the most significant bits.
See also: GLM_GTC_packing
uint32 packSnorm3x10_1x2(vec4 const & v)
vec4 unpackUnorm3x10_1x2(uint32 const & p))
uvec4 unpackI3x10_1x2(uint32 const & p)
uvec4 unpackU3x10_1x2(uint32 const & p)
Definition at line 446 of file packing.inl.
References glm::clamp().
447         {
448                 detail::i10i10i10i2 Unpack;
449                 Unpack.pack = v;
450                 vec4 Result;
451                 Result.x = clamp(float(Unpack.data.x) / 511.f, -1.0f, 1.0f);
452                 Result.y = clamp(float(Unpack.data.y) / 511.f, -1.0f, 1.0f);
453                 Result.z = clamp(float(Unpack.data.z) / 511.f, -1.0f, 1.0f);
454                 Result.w = clamp(float(Unpack.data.w) /   1.f, -1.0f, 1.0f);
455                 return Result;
456         }
GLM_FUNC_DECL vec4 glm::unpackSnorm4x16 (uint64 const & p)
First, unpacks a single 64-bit unsigned integer p into four 16-bit signed integers. Then, each component is converted to a normalized floating-point value to generate the returned four-component vector.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackSnorm4x16: clamp(f / 32767.0, -1, +1)
The first component of the returned vector will be extracted from the least significant bits of the input; the last component will be extracted from the most significant bits.
See also: GLM_GTC_packing
float unpackSnorm1x16(uint16 p)
vec2 unpackSnorm2x16(uint32 p)
GLSL unpackSnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
GLM_FUNC_QUALIFIER uvec4 glm::unpackU3x10_1x2 (uint32 p)
Unpacks a single 32-bit unsigned integer p into three 10-bit and one 2-bit unsigned integers.
The first component of the returned vector will be extracted from the least significant bits of the input; the last component will be extracted from the most significant bits.
See also: GLM_GTC_packing
uint32 packU3x10_1x2(uvec4 const & v)
vec4 unpackSnorm3x10_1x2(uint32 const & p);
uvec4 unpackI3x10_1x2(uint32 const & p);
Definition at line 425 of file packing.inl.
426         {
427                 detail::u10u10u10u2 Unpack;
428                 Unpack.pack = v;
429                 return uvec4(
430                         Unpack.data.x,
431                         Unpack.data.y,
432                         Unpack.data.z,
433                         Unpack.data.w);
434         }
GLM_FUNC_QUALIFIER float glm::unpackUnorm1x16 (uint16 p)
First, unpacks a single 16-bit unsigned integer p into a of 16-bit unsigned integers. Then, the value is converted to a normalized floating-point value to generate the returned scalar.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackUnorm1x16: f / 65535.0
See also: GLM_GTC_packing
vec2 unpackUnorm2x16(uint32 p)
vec4 unpackUnorm4x16(uint64 p)
GLSL unpackUnorm2x16 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 308 of file packing.inl.
309         {
310                 float Unpack = static_cast<float>(*const_cast<uint16*>(&p));
311                 return Unpack * 1.5259021896696421759365224689097e-5f; // 1.0 / 65535.0
312         }
GLM_FUNC_QUALIFIER float glm::unpackUnorm1x8 (uint8 p)
Convert a single 8-bit integer to a normalized floating-point value.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackUnorm4x8: f / 255.0
See also: GLM_GTC_packing
vec2 unpackUnorm2x8(uint16 p)
vec4 unpackUnorm4x8(uint32 p)
GLSL unpackUnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 254 of file packing.inl.
255         {
256                 float Unpack(static_cast<float>(p));
257                 return Unpack * static_cast<float>(0.0039215686274509803921568627451); // 1 / 255
258         }
GLM_FUNC_QUALIFIER vec2 glm::unpackUnorm2x8 (uint16 p)
First, unpacks a single 16-bit unsigned integer p into a pair of 8-bit unsigned integers. Then, each component is converted to a normalized floating-point value to generate the returned two-component vector.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackUnorm4x8: f / 255.0
The first component of the returned vector will be extracted from the least significant bits of the input; the last component will be extracted from the most significant bits.
See also: GLM_GTC_packing
float unpackUnorm1x8(uint8 v)
vec4 unpackUnorm4x8(uint32 p)
GLSL unpackUnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 267 of file packing.inl.
268         {
269                 u8vec2* Unpacked = reinterpret_cast<u8vec2*>(const_cast<uint16*>(&p));
270                 return vec2(*Unpacked) * float(0.0039215686274509803921568627451); // 1 / 255
271         }
GLM_FUNC_QUALIFIER vec4 glm::unpackUnorm3x10_1x2 (uint32 p)
First, unpacks a single 32-bit unsigned integer p into four 16-bit signed integers. Then, each component is converted to a normalized floating-point value to generate the returned four-component vector.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackSnorm3x10_1x2(xyz): clamp(f / 1023.0, 0, +1) unpackSnorm3x10_1x2(w): clamp(f / 3.0, 0, +1)
The first component of the returned vector will be extracted from the least significant bits of the input; the last component will be extracted from the most significant bits.
See also: GLM_GTC_packing
uint32 packSnorm3x10_1x2(vec4 const & v)
vec4 unpackInorm3x10_1x2(uint32 const & p))
uvec4 unpackI3x10_1x2(uint32 const & p)
uvec4 unpackU3x10_1x2(uint32 const & p)
Definition at line 468 of file packing.inl.
469         {
470                 detail::i10i10i10i2 Unpack;
471                 Unpack.pack = v;
472                 vec4 Result;
473                 Result.x = float(Unpack.data.x) / 1023.f;
474                 Result.y = float(Unpack.data.y) / 1023.f;
475                 Result.z = float(Unpack.data.z) / 1023.f;
476                 Result.w = float(Unpack.data.w) /   3.f;
477                 return Result;
478         }
GLM_FUNC_QUALIFIER vec4 glm::unpackUnorm4x16 (uint64 p)
First, unpacks a single 64-bit unsigned integer p into four 16-bit unsigned integers. Then, each component is converted to a normalized floating-point value to generate the returned four-component vector.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackUnormx4x16: f / 65535.0
The first component of the returned vector will be extracted from the least significant bits of the input; the last component will be extracted from the most significant bits.
See also: GLM_GTC_packing
float unpackUnorm1x16(uint16 p)
vec2 unpackUnorm2x16(uint32 p)
GLSL unpackUnorm2x16 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 321 of file packing.inl.
322         {
323                 u16vec4* Unpack = reinterpret_cast<u16vec4*>(const_cast<uint64*>(&p));
324                 return vec4(*Unpack) * 1.5259021896696421759365224689097e-5f; // 1.0 / 65535.0
325         }