GLM_GTX_matrix_transform_2d
Functions
template<typename T, precision P>
GLM_FUNC_QUALIFIER detail::tmat3x3< T, P > glm::translate (detail::tmat3x3< T, P > const &m, detail::tvec2< T, P > const &v)
template<typename T, precision P>
GLM_FUNC_QUALIFIER detail::tmat3x3< T, P > glm::rotate (detail::tmat3x3< T, P > const &m, T const &angle)
template<typename T, precision P>
GLM_FUNC_QUALIFIER detail::tmat3x3< T, P > glm::scale (detail::tmat3x3< T, P > const &m, detail::tvec2< T, P > const &v)
template<typename T, precision P>
GLM_FUNC_QUALIFIER detail::tmat3x3< T, P > glm::shearX (detail::tmat3x3< T, P > const &m, T const &y)
template<typename T, precision P>
GLM_FUNC_QUALIFIER detail::tmat3x3< T, P > glm::shearY (detail::tmat3x3< T, P > const &m, T const &x)
Detailed Description
Defines functions that generate common 2d transformation matrices.
<glm/gtx/matrix_transform_2d.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat3x3< T, P > glm::rotate (detail::tmat3x3< T, P > const & m, T const & angle) [inline]
Builds a rotation 3 * 3 matrix created from an angle.
Parameters:
m Input matrix multiplied by this translation matrix.
angle Rotation angle expressed in radians if GLM_FORCE_RADIANS is defined or degrees otherwise.
Definition at line 46 of file matrix_transform_2d.inl.
References glm::cos(), glm::radians(), and glm::sin().
49         {
50         #ifdef GLM_FORCE_RADIANS
51                 T a = angle;
52         #else
53                 T a = radians(angle);           
54         #endif
55                 T c = cos(a);
56                 T s = sin(a);
57 
58                 detail::tmat3x3<T, P> Result(detail::tmat3x3<T, P>::_null);
59                 Result[0] = m[0] * c + m[1] * s;
60                 Result[1] = m[0] * -s + m[1] * c;
61                 Result[2] = m[2];
62                 return Result;
63         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat3x3< T, P > glm::scale (detail::tmat3x3< T, P > const & m, detail::tvec2< T, P > const & v) [inline]
Builds a scale 3 * 3 matrix created from a vector of 2 components.
Parameters:
m Input matrix multiplied by this translation matrix.
v Coordinates of a scale vector.
Definition at line 66 of file matrix_transform_2d.inl.
69         {
70                 detail::tmat3x3<T, P> Result(detail::tmat3x3<T, P>::_null);
71                 Result[0] = m[0] * v[0];
72                 Result[1] = m[1] * v[1];
73                 Result[2] = m[2];
74                 return Result;
75         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat3x3< T, P > glm::shearX (detail::tmat3x3< T, P > const & m, T const & y) [inline]
Builds an horizontal (parallel to the x axis) shear 3 * 3 matrix.
Parameters:
m Input matrix multiplied by this translation matrix.
y Shear factor.
Definition at line 78 of file matrix_transform_2d.inl.
81         {
82                 detail::tmat3x3<T, P> Result();
83                 Result[0][1] = y;
84                 return m * Result;
85         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat3x3< T, P > glm::shearY (detail::tmat3x3< T, P > const & m, T const & x) [inline]
Builds a vertical (parallel to the y axis) shear 3 * 3 matrix.
Parameters:
m Input matrix multiplied by this translation matrix.
x Shear factor.
Definition at line 88 of file matrix_transform_2d.inl.
91         {
92                 detail::tmat3x3<T, P> Result();
93                 Result[1][0] = x;
94                 return m * Result;
95         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat3x3< T, P > glm::translate (detail::tmat3x3< T, P > const & m, detail::tvec2< T, P > const & v) [inline]
Builds a translation 3 * 3 matrix created from a vector of 2 components.
Parameters:
m Input matrix multiplied by this translation matrix.
v Coordinates of a translation vector.
Definition at line 35 of file matrix_transform_2d.inl.
38         {
39                 detail::tmat3x3<T, P> Result(m);
40                 Result[2] = m[0] * v[0] + m[1] * v[1] + m[2];
41                 return Result;
42         }