GLM_GTC_matrix_access
Functions
template<typename genType>
GLM_FUNC_DECL genType::row_type glm::row (genType const &m, length_t const &index)
template<typename genType>
GLM_FUNC_DECL genType glm::row (genType const &m, length_t const &index, typename genType::row_type const &x)
template<typename genType>
GLM_FUNC_DECL genType::col_type glm::column (genType const &m, length_t const &index)
template<typename genType>
GLM_FUNC_DECL genType glm::column (genType const &m, length_t const &index, typename genType::col_type const &x)
Detailed Description
Defines functions to access rows or columns of a matrix easily. <glm/gtc/matrix_access.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType> GLM_FUNC_QUALIFIER genType glm::column (genType const & m, length_t const & index, typename genType::col_type const & x) [inline]
Set a specific column to a matrix.
See also: GLM_GTC_matrix_access
Definition at line 64 of file matrix_access.inl.
69         {
70                 assert(index >= 0 && index < m.length());
71 
72                 genType Result = m;
73                 Result[index] = x;
74                 return Result;
75         }
template<typename genType> GLM_FUNC_QUALIFIER genType::col_type glm::column (genType const & m, length_t const & index) [inline]
Get a specific column of a matrix.
See also: GLM_GTC_matrix_access
Definition at line 79 of file matrix_access.inl.
83         {
84                 assert(index >= 0 && index < m.length());
85 
86                 return m[index];
87         }
template<typename genType> GLM_FUNC_QUALIFIER genType glm::row (genType const & m, length_t const & index, typename genType::row_type const & x) [inline]
Set a specific row to a matrix.
See also: GLM_GTC_matrix_access
Definition at line 33 of file matrix_access.inl.
References glm::length().
Referenced by btInverseDynamics::MultiBodyTree::MultiBodyImpl::calculateMassMatrix(), and btMLCPSolver::createMLCPFast().
38         {
39                 assert(index >= 0 && index < m[0].length());
40 
41                 genType Result = m;
42                 for(length_t i = 0; i < m.length(); ++i)
43                         Result[i][index] = x[i];
44                 return Result;
45         }
template<typename genType> GLM_FUNC_QUALIFIER genType::row_type glm::row (genType const & m, length_t const & index) [inline]
Get a specific row of a matrix.
See also: GLM_GTC_matrix_access
Definition at line 49 of file matrix_access.inl.
References glm::length().
53         {
54                 assert(index >= 0 && index < m[0].length());
55 
56                 typename genType::row_type Result;
57                 for(length_t i = 0; i < m.length(); ++i)
58                         Result[i] = m[i][index];
59                 return Result;
60         }