GLM_GTX_dual_quaternion
Typedefs
typedef detail::tdualquat< float, lowp > glm::lowp_dualquat
typedef detail::tdualquat< float, mediump > glm::mediump_dualquat
typedef detail::tdualquat< float, highp > glm::highp_dualquat
typedef detail::tdualquat< float, lowp > glm::lowp_fdualquat
typedef detail::tdualquat< float, mediump > glm::mediump_fdualquat
typedef detail::tdualquat< float, highp > glm::highp_fdualquat
typedef detail::tdualquat< double, lowp > glm::lowp_ddualquat
typedef detail::tdualquat< double, mediump > glm::mediump_ddualquat
typedef detail::tdualquat< double, highp > glm::highp_ddualquat
typedef highp_fdualquat glm::dualquat
typedef highp_fdualquat glm::fdualquat
typedef highp_ddualquat glm::ddualquat
Functions
template<typename T, precision P>
GLM_FUNC_DECL detail::tdualquat< T, P > glm::normalize (detail::tdualquat< T, P > const &q)
template<typename T, precision P>
GLM_FUNC_DECL detail::tdualquat< T, P > glm::lerp (detail::tdualquat< T, P > const &x, detail::tdualquat< T, P > const &y, T const &a)
template<typename T, precision P>
GLM_FUNC_DECL detail::tdualquat< T, P > glm::inverse (detail::tdualquat< T, P > const &q)
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat2x4< T, P > glm::mat2x4_cast (detail::tdualquat< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL detail::tmat3x4< T, P > glm::mat3x4_cast (detail::tdualquat< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL detail::tdualquat< T, P > glm::dualquat_cast (detail::tmat2x4< T, P > const &x)
template<typename T, precision P>
GLM_FUNC_DECL detail::tdualquat< T, P > glm::dualquat_cast (detail::tmat3x4< T, P > const &x)
Detailed Description
Defines a templated dual-quaternion type and several dual-quaternion operations.
<glm/gtx/dual_quaternion.hpp> need to be included to use these functionalities.
Typedef Documentation
typedef highp_ddualquat glm::ddualquat
Dual-quaternion of default double-precision floating-point numbers.
See also: GLM_GTX_dual_quaternion
Definition at line 279 of file dual_quaternion.hpp.
typedef highp_fdualquat glm::dualquat
Dual-quaternion of floating-point numbers.
See also: GLM_GTX_dual_quaternion
Definition at line 255 of file dual_quaternion.hpp.
typedef highp_fdualquat glm::fdualquat
Dual-quaternion of single-precision floating-point numbers.
See also: GLM_GTX_dual_quaternion
Definition at line 260 of file dual_quaternion.hpp.
typedef detail::tdualquat<double, highp> glm::highp_ddualquat
Dual-quaternion of high double-precision floating-point numbers.
See also: GLM_GTX_dual_quaternion
Definition at line 248 of file dual_quaternion.hpp.
typedef detail::tdualquat<float, highp> glm::highp_dualquat
Dual-quaternion of high single-precision floating-point numbers.
See also: GLM_GTX_dual_quaternion
Definition at line 216 of file dual_quaternion.hpp.
typedef detail::tdualquat<float, highp> glm::highp_fdualquat
Dual-quaternion of high single-precision floating-point numbers.
See also: GLM_GTX_dual_quaternion
Definition at line 232 of file dual_quaternion.hpp.
typedef detail::tdualquat<double, lowp> glm::lowp_ddualquat
Dual-quaternion of low double-precision floating-point numbers.
See also: GLM_GTX_dual_quaternion
Definition at line 238 of file dual_quaternion.hpp.
typedef detail::tdualquat<float, lowp> glm::lowp_dualquat
Dual-quaternion of low single-precision floating-point numbers.
See also: GLM_GTX_dual_quaternion
Definition at line 206 of file dual_quaternion.hpp.
typedef detail::tdualquat<float, lowp> glm::lowp_fdualquat
Dual-quaternion of low single-precision floating-point numbers.
See also: GLM_GTX_dual_quaternion
Definition at line 222 of file dual_quaternion.hpp.
typedef detail::tdualquat<double, mediump> glm::mediump_ddualquat
Dual-quaternion of medium double-precision floating-point numbers.
See also: GLM_GTX_dual_quaternion
Definition at line 243 of file dual_quaternion.hpp.
typedef detail::tdualquat<float, mediump> glm::mediump_dualquat
Dual-quaternion of medium single-precision floating-point numbers.
See also: GLM_GTX_dual_quaternion
Definition at line 211 of file dual_quaternion.hpp.
typedef detail::tdualquat<float, mediump> glm::mediump_fdualquat
Dual-quaternion of medium single-precision floating-point numbers.
See also: GLM_GTX_dual_quaternion
Definition at line 227 of file dual_quaternion.hpp.
Function Documentation
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tdualquat< T, P > glm::dualquat_cast (detail::tmat3x4< T, P > const & x) [inline]
Converts a 3 * 4 matrix (augmented matrix rotation + translation) to a quaternion.
See also: GLM_GTX_dual_quaternion
Definition at line 369 of file dual_quaternion.inl.
References glm::sqrt().
372         {
373                 detail::tquat<T, P> real;
374                 
375                 T const trace = x[0].x + x[1].y + x[2].z;
376                 if(trace > T(0))
377                 {
378                         T const r = sqrt(T(1) + trace);
379                         T const invr = static_cast<T>(0.5) / r;
380                         real.w = static_cast<T>(0.5) * r;
381                         real.x = (x[2].y - x[1].z) * invr;
382                         real.y = (x[0].z - x[2].x) * invr;
383                         real.z = (x[1].x - x[0].y) * invr;
384                 }
385                 else if(x[0].x > x[1].y && x[0].x > x[2].z)
386                 {
387                         T const r = sqrt(T(1) + x[0].x - x[1].y - x[2].z);
388                         T const invr = static_cast<T>(0.5) / r;
389                         real.x = static_cast<T>(0.5)*r;
390                         real.y = (x[1].x + x[0].y) * invr;
391                         real.z = (x[0].z + x[2].x) * invr;
392                         real.w = (x[2].y - x[1].z) * invr;
393                 }
394                 else if(x[1].y > x[2].z)
395                 {
396                         T const r = sqrt(T(1) + x[1].y - x[0].x - x[2].z);
397                         T const invr = static_cast<T>(0.5) / r;
398                         real.x = (x[1].x + x[0].y) * invr;
399                         real.y = static_cast<T>(0.5) * r;
400                         real.z = (x[2].y + x[1].z) * invr;
401                         real.w = (x[0].z - x[2].x) * invr;
402                 }
403                 else
404                 {
405                         T const r = sqrt(T(1) + x[2].z - x[0].x - x[1].y);
406                         T const invr = static_cast<T>(0.5) / r;
407                         real.x = (x[0].z + x[2].x) * invr;
408                         real.y = (x[2].y + x[1].z) * invr;
409                         real.z = static_cast<T>(0.5) * r;
410                         real.w = (x[1].x - x[0].y) * invr;
411                 }
412                 
413                 detail::tquat<T, P> dual;
414                 dual.x =  T(0.5) * ( x[0].w * real.w + x[1].w * real.z - x[2].w * real.y);
415                 dual.y =  T(0.5) * (-x[0].w * real.z + x[1].w * real.w + x[2].w * real.x);
416                 dual.z =  T(0.5) * ( x[0].w * real.y - x[1].w * real.x + x[2].w * real.w);
417                 dual.w = -T(0.5) * ( x[0].w * real.x + x[1].w * real.y + x[2].w * real.z);
418                 return detail::tdualquat<T, P>(real, dual);
419         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tdualquat< T, P > glm::dualquat_cast (detail::tmat2x4< T, P > const & x) [inline]
Converts a 2 * 4 matrix (matrix which holds real and dual parts) to a quaternion.
See also: GLM_GTX_dual_quaternion
Definition at line 358 of file dual_quaternion.inl.
361         {
362                 return detail::tdualquat<T, P>(
363                         detail::tquat<T, P>( x[0].w, x[0].x, x[0].y, x[0].z ),
364                         detail::tquat<T, P>( x[1].w, x[1].x, x[1].y, x[1].z ));
365         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tdualquat< T, P > glm::inverse (detail::tdualquat< T, P > const & q) [inline]
Returns the q inverse.
See also: GLM_GTX_dual_quaternion
Definition at line 299 of file dual_quaternion.inl.
References glm::conjugate(), and glm::dot().
302         {
303                 const glm::detail::tquat<T, P> real = conjugate(q.real);
304                 const glm::detail::tquat<T, P> dual = conjugate(q.dual);
305                 return detail::tdualquat<T, P>(real, dual + (real * (-2.0f * dot(real,dual))));
306         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tdualquat< T, P > glm::lerp (detail::tdualquat< T, P > const & x, detail::tdualquat< T, P > const & y, T const & a) [inline]
Returns the linear interpolation of two dual quaternion.
See also: GLM_GTX_dual_quaternion
Definition at line 282 of file dual_quaternion.inl.
References glm::dot(), and glm::one().
287         {
288                 // Dual Quaternion Linear blend aka DLB:
289                 // Lerp is only defined in [0, 1]
290                 assert(a >= static_cast<T>(0));
291                 assert(a <= static_cast<T>(1));
292                 T const k = dot(x.real,y.real) < static_cast<T>(0) ? -a : a;
293                 T const one(1);
294                 return detail::tdualquat<T, P>(x * (one - a) + y * k);
295         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat2x4< T, P > glm::mat2x4_cast (detail::tdualquat< T, P > const & x) [inline]
Converts a quaternion to a 2 * 4 matrix.
See also: GLM_GTX_dual_quaternion
Definition at line 310 of file dual_quaternion.inl.
313         {
314                 return detail::tmat2x4<T, P>( x[0].x, x[0].y, x[0].z, x[0].w, x[1].x, x[1].y, x[1].z, x[1].w );
315         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tmat3x4< T, P > glm::mat3x4_cast (detail::tdualquat< T, P > const & x) [inline]
Converts a quaternion to a 3 * 4 matrix.
See also: GLM_GTX_dual_quaternion
Definition at line 319 of file dual_quaternion.inl.
References glm::length2().
322         {
323                 detail::tquat<T, P> r = x.real / length2(x.real);
324                 
325                 detail::tquat<T, P> const rr(r.w * x.real.w, r.x * x.real.x, r.y * x.real.y, r.z * x.real.z);
326                 r *= static_cast<T>(2);
327                 
328                 T const xy = r.x * x.real.y;
329                 T const xz = r.x * x.real.z;
330                 T const yz = r.y * x.real.z;
331                 T const wx = r.w * x.real.x;
332                 T const wy = r.w * x.real.y;
333                 T const wz = r.w * x.real.z;
334                 
335                 detail::tvec4<T, P> const a(
336                         rr.w + rr.x - rr.y - rr.z,
337                         xy - wz,
338                         xz + wy,
339                         -(x.dual.w * r.x - x.dual.x * r.w + x.dual.y * r.z - x.dual.z * r.y));
340                 
341                 detail::tvec4<T, P> const b(
342                         xy + wz,
343                         rr.w + rr.y - rr.x - rr.z,
344                         yz - wx,
345                         -(x.dual.w * r.y - x.dual.x * r.z - x.dual.y * r.w + x.dual.z * r.x));
346                 
347                 detail::tvec4<T, P> const c(
348                         xz - wy,
349                         yz + wx,
350                         rr.w + rr.z - rr.x - rr.y,
351                         -(x.dual.w * r.z + x.dual.x * r.y - x.dual.y * r.x - x.dual.z * r.w));
352                 
353                 return detail::tmat3x4<T, P>(a, b, c);
354         }
template<typename T, precision P> GLM_FUNC_QUALIFIER detail::tdualquat< T, P > glm::normalize (detail::tdualquat< T, P > const & q) [inline]
Returns the normalized quaternion.
See also: GLM_GTX_dual_quaternion
Definition at line 273 of file dual_quaternion.inl.
References glm::length().
276         {
277                 return q / length(q.real);
278         }