Vector2 Struct Reference
#include <Structs.h>
Public Member Functions
Vector2 (float x, float z)
A contructor to define a 3D vector.
Vector2 ()
A default constructor to set the vector's variables to 0.
Vector2 (float num)
A constructor to set all variables to the parameter's value.
Vector2 operator= (const Vector2 original)
Overloads the equality operator to copy vectors.
float operator[] (const int index) const
An overlaoded array access operator to get one of the vector's values.
void Set (int index, float value)
Changes one of the variables of this vector.
Vector2 operator/ (const float copy)
Divides this vector by a scalar.
Vector2 Normalized () const
Calculates a normalized version of the vector.
Static Public Member Functions
static float Dot (Vector2 one, Vector2 two)
Returns the dot product of two vectors.
static Vector2 Normal (Vector2 a, Vector2 b, Vector2 c)
The normal vector of a face.
static Vector2 Cross (const Vector2 first, const Vector2 second)
The cross product of two vectors.
static float Distance (const Vector2 first, const Vector2 second)
Calculates the distance between to 3D points.
Friends
std::ostream & operator<< (std::ostream &os, const Vector2 &vector)
Uses IO to display one vector.
Detailed Description
Contains all the operations required by Vector2 variables Taken from old assignment TODO: Fix comments
Definition at line 44 of file Structs.h.
Constructor & Destructor Documentation
Vector2::Vector2 (float x, float z) [inline]
A contructor to define a 3D vector.
Parameters:
x - x-axis value
y - y-axis value
z - z-axis value
Definition at line 58 of file Structs.h.
58                                   {
59                 Vector2::x = x;
60                 Vector2::z = z;
61         };
Vector2::Vector2 (float num) [inline]
A constructor to set all variables to the parameter's value.
Parameters:
num - the number to be set to.
Definition at line 73 of file Structs.h.
73                            {
74                 x = num;
75                 z = num;
76         }
Member Function Documentation
Vector2 Vector2::operator= (const Vector2 original) [inline]
Overloads the equality operator to copy vectors.
Parameters:
A vector to be copied from.
Returns: a bew vector
Definition at line 83 of file Structs.h.
References Vector2(), x, and z.
83                                                     {
84                 x = original.x;
85                 z = original.z;
86                 return Vector2(x, z);
87         };
static float Vector2::Dot (Vector2 one, Vector2 two) [inline, static]
Returns the dot product of two vectors.
Parameters:
one - the first vector
two - the second vector
Returns: a scalar value
Definition at line 95 of file Structs.h.
References x, and z.
95                                                    {
96                 return one.x*two.x + one.z *two.z;
97         }
static Vector2 Vector2::Normal (Vector2 a, Vector2 b, Vector2 c) [inline, static]
The normal vector of a face.
Parameters:
a - the first point
b - the second point
c - the third point
Returns: Normal vector
Definition at line 116 of file Structs.h.
References Cross().
116                                                                {
117                 return Cross(a - b, c - b);
118         }
static Vector2 Vector2::Cross (const Vector2 first, const Vector2 second) [inline, static]
The cross product of two vectors.
Parameters:
first - the first vector
second - the second vector
Returns: the cross product
Definition at line 126 of file Structs.h.
References Vector2(), x, and z.
Referenced by Normal().
126                                                                         {
127                 return Vector2(first.x * second.z + first.z * second.x);
128         }
static float Vector2::Distance (const Vector2 first, const Vector2 second) [inline, static]
Calculates the distance between to 3D points.
Parameters:
first - the first point
second - the second point
Returns: the distance between the points.
Definition at line 136 of file Structs.h.
References glm::sqrt(), x, and z.
136                                                                          {
137                 return sqrt((second.x - first.x)*(second.x - first.x) +
138                         (second.z - first.z)*(second.z - first.z));
139         }
]float Vector2::operator[] (const int index) const [inline]
An overlaoded array access operator to get one of the vector's values.
Parameters:
index - 0 - x value, 1 - y value, 2 - z value
Returns: the value of a particular variable or -1000000
Definition at line 179 of file Structs.h.
179                                                  {
180                 if (index == 0)
181                         return x;
182                 else if (index == 1)
183                         return z;
184                 else
185                         return -10000000;
186         }
void Vector2::Set (int index, float value) [inline]
Changes one of the variables of this vector.
Parameters:
index - 0 - x value, 1 - y value, 2 - z value
value - a new value to be assigned
Definition at line 193 of file Structs.h.
193                                          {
194                 if (index == 0)
195                         x = value;
196                 else if (index == 1)
197                         z = value;
198         }
Vector2 Vector2::operator/ (const float copy) [inline]
Divides this vector by a scalar.
Parameters:
a float to be divided by
Returns: the result of division
Definition at line 206 of file Structs.h.
References Vector2().
206                                               {
207                 x /= copy;
208                 z /= copy;
209                 return Vector2(x, z);
210         }
Vector2 Vector2::Normalized () const [inline]
Calculates a normalized version of the vector.
Returns: the normalized vector.
Definition at line 224 of file Structs.h.
References glm::length(), and Vector2().
224                                    {
225                 float length = Vector2(x, z).Length();
226                 if (length == 0)
227                         return Vector2(0);
228                 else {
229                         return Vector2(x / length, z / length);
230                 }
231         }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Vector2 & vector) [friend]
Uses IO to display one vector.
Parameters:
os - reference to an output stream
vector - a vector to be displayed.
Definition at line 104 of file Structs.h.
104                                                                                  {
105                 os << vector.x << "  " << vector.z;
106                 return os;
107         }
The documentation for this struct was generated from the following file:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/CarreGameEngine/headers/Structs.h