b3DynamicBvhBroadphase Struct Reference
#include <b3DynamicBvhBroadphase.h>
Public Member Functions
virtual void resetPool (b3Dispatcher *dispatcher)
reset broadphase internal structures, to ensure determinism/reproducability
void setAabbForceUpdate (b3BroadphaseProxy *absproxy, const b3Vector3 &aabbMin, const b3Vector3 &aabbMax, b3Dispatcher *)
Detailed Description
The b3DynamicBvhBroadphase implements a broadphase using two dynamic AABB bounding volume hierarchies/trees (see b3DynamicBvh). One tree is used for static/non-moving objects, and another tree is used for dynamic objects. Objects can move from one tree to the other. This is a very fast broadphase, especially for very dynamic worlds where many objects are moving. Its insert/add and remove of objects is generally faster than the sweep and prune broadphases b3AxisSweep3 and b332BitAxisSweep3.
Definition at line 120 of file b3DynamicBvhBroadphase.h.
Member Function Documentation
void b3DynamicBvhBroadphase::setAabbForceUpdate (b3BroadphaseProxy * absproxy, const b3Vector3 & aabbMin, const b3Vector3 & aabbMax, b3Dispatcher *)
this setAabbForceUpdate is similar to setAabb but always forces the aabb update. it is not part of the b3BroadphaseInterface but specific to b3DynamicBvhBroadphase. it bypasses certain optimizations that prevent aabb updates (when the aabb shrinks), see http://code.google.com/p/bullet/issues/detail?id=223
Definition at line 361 of file b3DynamicBvhBroadphase.cpp.
References b3DynamicBvh::collideTTpersistentStack(), b3DynamicBvh::insert(), b3DynamicBvh::remove(), and b3DynamicBvh::update().
365 {
366         b3DbvtProxy*                                            proxy=(b3DbvtProxy*)absproxy;
367         B3_ATTRIBUTE_ALIGNED16(b3DbvtVolume)    aabb=b3DbvtVolume::FromMM(aabbMin,aabbMax);
368         bool    docollide=false;
369         if(proxy->stage==STAGECOUNT)
370         {/* fixed -> dynamic set        */ 
371                 m_sets[1].remove(proxy->leaf);
372                 proxy->leaf=m_sets[0].insert(aabb,proxy);
373                 docollide=true;
374         }
375         else
376         {/* dynamic set                         */ 
377                 ++m_updates_call;
378                 /* Teleporting                  */ 
379                 m_sets[0].update(proxy->leaf,aabb);
380                 ++m_updates_done;
381                 docollide=true;
382         }
383         b3ListRemove(proxy,m_stageRoots[proxy->stage]);
384         proxy->m_aabbMin = aabbMin;
385         proxy->m_aabbMax = aabbMax;
386         proxy->stage    =       m_stageCurrent;
387         b3ListAppend(proxy,m_stageRoots[m_stageCurrent]);
388         if(docollide)
389         {
390                 m_needcleanup=true;
391                 if(!m_deferedcollide)
392                 {
393                         b3DbvtTreeCollider      collider(this);
394                         m_sets[1].collideTTpersistentStack(m_sets[1].m_root,proxy->leaf,collider);
395                         m_sets[0].collideTTpersistentStack(m_sets[0].m_root,proxy->leaf,collider);
396                 }
397         }       
398 }
The documentation for this struct was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.cpp