b3DynamicBvh Struct Reference
#include <b3DynamicBvh.h>
Public Member Functions
B3_DBVT_PREFIX void rayTestInternal (const b3DbvtNode *root, const b3Vector3 &rayFrom, const b3Vector3 &rayTo, const b3Vector3 &rayDirectionInverse, unsigned int signs[3], b3Scalar lambda_max, const b3Vector3 &aabbMin, const b3Vector3 &aabbMax, B3_DBVT_IPOLICY) const
Static Public Member Functions
static B3_DBVT_PREFIX void rayTest (const b3DbvtNode *root, const b3Vector3 &rayFrom, const b3Vector3 &rayTo, B3_DBVT_IPOLICY)
Detailed Description
The b3DynamicBvh class implements a fast dynamic bounding volume tree based on axis aligned bounding boxes (aabb tree). This b3DynamicBvh is used for soft body collision detection and for the b3DynamicBvhBroadphase. It has a fast insert, remove and update of nodes. Unlike the b3QuantizedBvh, nodes can be dynamically moved around, which allows for change in topology of the underlying data structure.
Definition at line 194 of file b3DynamicBvh.h.
Member Function Documentation
B3_DBVT_PREFIX void b3DynamicBvh::rayTest (const b3DbvtNode * root, const b3Vector3 & rayFrom, const b3Vector3 & rayTo, B3_DBVT_IPOLICY) [inline, static]
rayTest is a re-entrant ray test, and can be called in parallel as long as the b3AlignedAlloc is thread-safe (uses locking etc) rayTest is slower than rayTestInternal, because it builds a local stack, using memory allocations, and it recomputes signs/rayDirectionInverses each time
what about division by zero? --> just set rayDirection[i] to INF/B3_LARGE_FLOAT
Definition at line 1005 of file b3DynamicBvh.h.
References b3AlignedObjectArray< T >::resize(), and b3AlignedObjectArray< T >::size().
1009 {
1010         B3_DBVT_CHECKTYPE
1011                 if(root)
1012                 {
1013                         b3Vector3 rayDir = (rayTo-rayFrom);
1014                         rayDir.normalize ();
1015 
1017                         b3Vector3 rayDirectionInverse;
1018                         rayDirectionInverse[0] = rayDir[0] == b3Scalar(0.0) ? b3Scalar(B3_LARGE_FLOAT) : b3Scalar(1.0) / rayDir[0];
1019                         rayDirectionInverse[1] = rayDir[1] == b3Scalar(0.0) ? b3Scalar(B3_LARGE_FLOAT) : b3Scalar(1.0) / rayDir[1];
1020                         rayDirectionInverse[2] = rayDir[2] == b3Scalar(0.0) ? b3Scalar(B3_LARGE_FLOAT) : b3Scalar(1.0) / rayDir[2];
1021                         unsigned int signs[3] = { rayDirectionInverse[0] < 0.0, rayDirectionInverse[1] < 0.0, rayDirectionInverse[2] < 0.0};
1022 
1023                         b3Scalar lambda_max = rayDir.dot(rayTo-rayFrom);
1024 #ifdef COMPARE_BTRAY_AABB2
1025                         b3Vector3 resultNormal;
1026 #endif//COMPARE_BTRAY_AABB2
1027                         
1028                         b3AlignedObjectArray<const b3DbvtNode*> stack;
1029 
1030                         int                                                             depth=1;
1031                         int                                                             treshold=B3_DOUBLE_STACKSIZE-2;
1032 
1033                         stack.resize(B3_DOUBLE_STACKSIZE);
1034                         stack[0]=root;
1035                         b3Vector3 bounds[2];
1036                         do      {
1037                                 const b3DbvtNode*       node=stack[--depth];
1038 
1039                                 bounds[0] = node->volume.Mins();
1040                                 bounds[1] = node->volume.Maxs();
1041                                 
1042                                 b3Scalar tmin=1.f,lambda_min=0.f;
1043                                 unsigned int result1 = b3RayAabb2(rayFrom,rayDirectionInverse,signs,bounds,tmin,lambda_min,lambda_max);
1044 
1045 #ifdef COMPARE_BTRAY_AABB2
1046                                 b3Scalar param=1.f;
1047                                 bool result2 = b3RayAabb(rayFrom,rayTo,node->volume.Mins(),node->volume.Maxs(),param,resultNormal);
1048                                 b3Assert(result1 == result2);
1049 #endif //TEST_BTRAY_AABB2
1050 
1051                                 if(result1)
1052                                 {
1053                                         if(node->isinternal())
1054                                         {
1055                                                 if(depth>treshold)
1056                                                 {
1057                                                         stack.resize(stack.size()*2);
1058                                                         treshold=stack.size()-2;
1059                                                 }
1060                                                 stack[depth++]=node->childs[0];
1061                                                 stack[depth++]=node->childs[1];
1062                                         }
1063                                         else
1064                                         {
1065                                                 policy.Process(node);
1066                                         }
1067                                 }
1068                         } while(depth);
1069 
1070                 }
1071 }
B3_DBVT_PREFIX void b3DynamicBvh::rayTestInternal (const b3DbvtNode * root, const b3Vector3 & rayFrom, const b3Vector3 & rayTo, const b3Vector3 & rayDirectionInverse, unsigned int signs[3], b3Scalar lambda_max, const b3Vector3 & aabbMin, const b3Vector3 & aabbMax, B3_DBVT_IPOLICY) const [inline]
rayTestInternal is faster than rayTest, because it uses a persistent stack (to reduce dynamic memory allocations to a minimum) and it uses precomputed signs/rayInverseDirections rayTestInternal is used by b3DynamicBvhBroadphase to accelerate world ray casts
Definition at line 954 of file b3DynamicBvh.h.
References b3AlignedObjectArray< T >::resize(), and b3AlignedObjectArray< T >::size().
963 {
964         (void) rayTo;
965         B3_DBVT_CHECKTYPE
966         if(root)
967         {
968                 int                                                             depth=1;
969                 int                                                             treshold=B3_DOUBLE_STACKSIZE-2;
970                 b3AlignedObjectArray<const b3DbvtNode*>&        stack = m_rayTestStack;
971                 stack.resize(B3_DOUBLE_STACKSIZE);
972                 stack[0]=root;
973                 b3Vector3 bounds[2];
974                 do      
975                 {
976                         const b3DbvtNode*       node=stack[--depth];
977                         bounds[0] = node->volume.Mins()-aabbMax;
978                         bounds[1] = node->volume.Maxs()-aabbMin;
979                         b3Scalar tmin=1.f,lambda_min=0.f;
980                         unsigned int result1=false;
981                         result1 = b3RayAabb2(rayFrom,rayDirectionInverse,signs,bounds,tmin,lambda_min,lambda_max);
982                         if(result1)
983                         {
984                                 if(node->isinternal())
985                                 {
986                                         if(depth>treshold)
987                                         {
988                                                 stack.resize(stack.size()*2);
989                                                 treshold=stack.size()-2;
990                                         }
991                                         stack[depth++]=node->childs[0];
992                                         stack[depth++]=node->childs[1];
993                                 }
994                                 else
995                                 {
996                                         policy.Process(node);
997                                 }
998                         }
999                 } while(depth);
1000         }
1001 }
The documentation for this struct was generated from the following files:
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.h
C:/Users/New/Documents/Games_Technology/Year4_Semester1/ICT397/~My Work/Assignment2/ICT397Carre/CarreGameEngine/Dependencies/BulletPhysicsEngine/include/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.cpp